### ISSUE TITLE
tabel组件滚动条Bug任然存在的问题

### ISSUE THREAD

**Issue by zhaoyang141414** [rsuite/rsuite#1011]
今天更新rsuite-table到了最新的3.12.1版本，上次出现的关于修复滚动条问题的 onDataUpdated={(_nextData, scrollTo) => {
            scrollTo({ y: 0, x: 0 });
 }}
还是有问题，通过onScroll获取滚动条位置并存储，点击编辑更新数据 ，onDataUpdated指定滚动的位置，但是 第一次还是会回到顶部，然后顶部有空白，再次setstate之后才滚动到指定位置；其次，如果使用滚动加载，判断滚动条到底部，增加新数据，setstate之后还是会回到顶部，onDataUpdated不生效；

**Comment by simonguo** [comment]
Table 的每一次 data 更新都会重置滚动条位置，如果你不希望滚动条被重置，可以设置：
```tsx
<Table shouldUpdateScroll={false} /> 
```
关闭自动重置滚动条后，如果需要手动更新可以通过  onDataUpdated 回调中进行处理：
```tsx
<Table 
  shouldUpdateScroll={false} 
  onDataUpdated={(_nextData, scrollTo)=>{
     scrollTo({ y: 0, x: 0 });
}}/> 
```
