### ISSUE TITLE
is possible adjust the width according to the table headers?

### ISSUE THREAD

**Issue by cocodrino** [rsuite/rsuite#1013]
### What problem does this feature solve?

Hi, good day, I've some really long headers that must be displayed completely, right now I was adjusting the width manually trying to calculate the pixels width according to the length of the headers but I think that must be exist a better approach, through I can't found in the api. I know that exist flex grow but this approach is a bit manual too and my columns are dinamics, so according to some parameters they are displayed

Also would work for me if I could include tooltips in the header, so when mouse over the header this will show the full text (actually I think that this approach would be better for me)

**Comment by simonguo** [comment]
Automatic column width based on content is not supported.

But you can expand in your business and dynamically generate columns. Set the column width according to the number of words in the title text.

Another solution is to customize the column and add Tooltip components to the column.
