### ISSUE TITLE
<Table.Column> colSpan and rowSpan 

### ISSUE THREAD

**Issue by VirgoArt** [rsuite/rsuite#1015]
I find **<Table.Column>** props of colSpan , why not rowSpan ?

**Comment by simonguo** [comment]
@VirgoArt 
`rowSpan` is relatively troublesome to deal with, and no good solution has yet been thought of.
If you have good suggestions, please discuss and PR.

**Comment by VirgoArt** [comment]
I think the reason why it is difficult to deal with is that RSuiteTable does not support Row, and all rendering is handled by cells

**Comment by VirgoArt** [comment]
@simonguo 
I think the reason why it is difficult to deal with is that RSuiteTable does not support Row, and all rendering is handled by cells
