### ISSUE TITLE
Tabel onRowClick问题

### ISSUE THREAD

**Issue by zhaoyang141414** [rsuite/rsuite#1018]
tabel  组件提供了onRowClick  函数，但是点击了Tabel的该行，从用户的角度上来说，这应该属于一个select 的行为，但是没有对应点击的改变，只有Hover 才有颜色效果，很不直观。建议在对应行点击之后，对应tabel 颜色 变深，而不只是Hover改变颜色，让用户对select的行元素一目了然，同时增加selectedKey属性，对设置了selectedKey的行元素颜色变深。

**Comment by SevenOutman** [comment]
在 RSuite 的中，Table 并没有“选中行”的概念，这一点也体现在 table row 在 hover 时 cursor 并非 pointer，表明 row 并非一个“选项”。`onRowClick` 更多地像是 `<div onClick>`，只是提供一个点击事件的回调。

如果你需要引入选中的操作，可以在行首添加一个 Checkbox 列来实现。

**Comment by VirgoArt** [comment]
![image](https://user-images.githubusercontent.com/41778222/80678100-d5acad80-8aec-11ea-8596-0bf61f5b9c1b.png)
可以自定义实现，而不是提供功能

**Comment by simonguo** [comment]
如果需要选中的行可以参考 @SevenOutman  与 @VirgoArt  的建议，通过 Checkbox 实现。


另外以下代码可以为指定行设置为自定义背景颜色：

```jsx
const [activeRow, setActiveRow] = React.useState();

<Table
  rowClassName={rowData => (rowData.id === activeRow ? 'active-row' : '')}
  onRowClick={rowData => {
    setActiveRow(rowData.id);
  }}
/>;
```
 CSS:
```css
.active-row .rs-table-cell {
  background: #f1f1f1;
}
```
