### ISSUE TITLE
Carousel 报错

### ISSUE THREAD

**Issue by Link-Kou** [rsuite/rsuite#1023]
| package  | version |
| -------- | ------- |
| `rsuite` | `4.3.4` |

Carousel

![image](https://user-images.githubusercontent.com/22113151/80856439-aa58c880-8c7c-11ea-9482-eefb21ac612f.png)

![image](https://user-images.githubusercontent.com/22113151/80856503-2bb05b00-8c7d-11ea-91d5-84fcff6088bf.png)

**Comment by simonguo** [comment]
Carousel 的 children 出现了 undefined.  你可以通过以下方式处理：
```jsx
rowData?.images?.filter((k)=>k.type===1).map((k)=><img />)
```
