### ISSUE TITLE
Table 套 Table的时候 RowHeight 计算有误

### ISSUE THREAD

**Issue by Link-Kou** [rsuite/rsuite#1024]
设置了autoHeight的同时，又对rowHeight进行function定义返回自定义行高。
calculateTableContextHeight方法中

https://github.com/rsuite/rsuite-table/blob/5da0b90ebe5365f192f496233094703135d991aa/src/Table.tsx#L865

个人认为应该取rowHeight的值计算高度了，而不是在去查询所有row的dom计算高度了。否者表格套表格，row计算就有错误了。

![image](https://user-images.githubusercontent.com/22113151/80951305-3e1bc780-8e2a-11ea-83d8-6dcdced8924d.png)

![image](https://user-images.githubusercontent.com/22113151/80949126-fc891d80-8e25-11ea-8c72-dfcafe784ff7.png)

**Comment by simonguo** [comment]
目前获取 contentHeight 的高度，最合适的方式就是直接 DOM 元素的高度。  主要还是要考虑在 `virtualized` 的情况下，遍历数据再获取 rowHeight 会非常耗时。

另外，我们的表格不支持嵌套，希望可以从设计上进行调整。

**Comment by Link-Kou** [comment]
@simonguo  从个人角度我也不喜欢表格套表格，

电商的环境中有很多辅助的场景。迫于无奈,只能用表格套表格来解决。当是表格的高度计算，导致表格套表格的时候，出现高度问题

![image](https://user-images.githubusercontent.com/22113151/81169948-5297c580-8fcc-11ea-8a36-27be7c4f3523.png)

能否dom获取的时候,限制一下层级。

**Comment by Link-Kou** [comment]
解决这个问题，目前已经有一个low的解决办法，就是在表格外面套一个div，然后自己在计算高度。

![image](https://user-images.githubusercontent.com/22113151/84719049-dae68e80-afac-11ea-8bf6-f74c359b28e4.png)

这样子就可以解决掉，表格套表格的高度问题。

**Comment by simonguo** [comment]
> @simonguo 从个人角度我也不喜欢表格套表格，
> 
> 电商的环境中有很多辅助的场景。迫于无奈,只能用表格套表格来解决。当是表格的高度计算，导致表格套表格的时候，出现高度问题
> 
> ![image](https://user-images.githubusercontent.com/22113151/81169948-5297c580-8fcc-11ea-8a36-27be7c4f3523.png)
> 
> 能否dom获取的时候,限制一下层级。

你示例中的表格设计截图，如果不需要锁定行，列，不需要排序，不需要 virtualized，或许通过 HTML table 改改样式，实现成本会更低一些。
