### ISSUE TITLE
add ref support to FormControl

### ISSUE THREAD

**Issue by iwan-uschka** [rsuite/rsuite#1025]
### What problem does this feature solve?

It would help a lot to be able to reference a form control element directly.

### What does the proposed API look like?

Adding a `ref` property to the `FormControl` component would be sufficient.

**Comment by simonguo** [comment]
Do you want to get the form control through `ref`?  You can customize an inputRef property and then set it on FormControl.

```tsx
const CustomInput = ({ innerRef, ...rest }) => <Input ref={innerRef} {...rest} />;
const inputRef = React.createRef();
const App = () => <FormControl accepter={CustomInput} innerRef={inputRef} />;
```

**Comment by iwan-uschka** [comment]
Hi, thanks for getting back on this one.

I need to get the reference of the FormControl wrapper (`.rs-form-control-wrapper`). I tell you why:

```
<RsFormControl
  data={someData}
  block
  placeholder="Select"
  name={name}
  accepter={RsInputPicker}
  container={() => {
    const formElement = document.querySelector(`[name="${name}"]`);

    return formElement && formElement.parentNode.parentNode;
  }}
  renderExtraFooter={() => someDataSource.loading > 0 && <RsLoader backdrop />}
/>
```
The input picker uses a popover and i want to set the container of the popover's whisper component. Right now i need to know the name of the form field to search the DOM which is not a great solution. Instead it would be cool to get the form control wrapper reference and set it as the container of the whisper component directly.

Btw: it's not guaranteed that a form control accepter component has a `ref` property.

**Comment by simonguo** [comment]
What `FormControl` gets through` ref` is not its DOM, but its instance.  Recommended method:
```tsx
const containerRef = React.createRef();
const App = () => (
  <div ref={containerRef}>
    <FormControl accepter={InputPicker} container={() => containerRef.current} />
  </div>
);
```

**Comment by iwan-uschka** [comment]
> What `FormControl` gets through `ref` is not its DOM, but its instance

I know :)

I'll go with the workaround you suggested.

Nevertheless i need to be a little stubborn on this one because i think it's not a good idea to add a `<div>` for non layout technical reasons. If it's easy to implement without breaking other concepts it would be cool to have the chance to get the reference directly somehow (without adding a `<div>`).

I never contributed to any project hosted on github but if you think that it could help if i make a proposal i could try.

I could think of adding a property `wrapperRef` directly to the component or `wrapperElement` to the form control instance (which can be fetched via `ref`).

**Comment by simonguo** [comment]
I don't know why you set the Picker's container on FormControl. This is not the way we recommend. FormControl is not a layout component, its main function is to associate the value of the form.

**Comment by iwan-uschka** [comment]
I am using a modal which contains a form. This form contains various picker elements and i need to set the picker's (popover) container anyway because of the modal. Otherwise the popovers won't scroll along the modal. Agree?

The form in the modal can be pre-filled by selecting an option from another picker aside/outside the form (but in the same modal). For the sake of the UI flow (if i can name it like this) this picker is not visible the entire time so it's not seen as part of the form but as a tool to manipulate the form (like you showed in https://rsuitejs.com/en/components/table/ > Advanced > Custom Cell => action cell with action menu popover). So i/we decided (after a week of discussion and trial and error) to use a button which shows a popover containing a picker. Let me sum this up: a modal contains a popover which contains a picker using a popover. Sounds crazy but it works pretty well. 

<img width="411" alt="Bildschirmfoto 2020-05-06 um 10 54 00" src="https://user-images.githubusercontent.com/2256579/81158080-e8f5c800-8f87-11ea-815e-5e6ee83af0ef.png">

But i had problems with non working `z-index`. The picker's popover wasn't visible because it was below the parent popover. After setting the form control wrapper (of all pickers) as the popover container it worked.

**Comment by iwan-uschka** [comment]
Don't wanna bother you but just want to know if i was able to convince you :) Or do you still have doubts?

**Comment by simonguo** [comment]
I understand your application scenario. All Picker components provide `container` attribute, the purpose is really to solve the problem of overlay can be scrolled within a specified range. In fact, this complex hierarchical design is not fully considered in our example.

Patching FormControl is not a good solution. The question I am thinking about is how to design a reasonable way to manage the overlay hierarchy.Currently you still want you to implement it through custom HTML elements as containers.

**Comment by iwan-uschka** [comment]
I think rsuite is doing a really good job so far when it comes to combining components hierarchically. The beauty of it all is the modularity. Every component works on its own and provides an API (props) to interact with.

I am saying this because i think that it should not be the job of this library to provide a way for handling these kinds of hierarchies mentioned above explicitly, like handling a modal containing popover containing popover containing whatever.

I know i tend to be kind of dogmatic now and then in some cases, this could be one of them :) but i think as long as a component creates a DOM element (which `FormControl` is actually doing) it could/should provide a way to access this DOM element directly like rsuite is doing _in some way_ for instance with tables (`bodyRef`) or popovers (`triggerRef`). But this is only my way of understanding. You could also say that this would blow up the APIs :)

Gonna shut up for now. Please let me know, if i can do anything here.

**Comment by iwan-uschka** [comment]
And again: thx for taking the time on this one.

**Comment by SevenOutman** [comment]
Hi @iwan-uschka, I'm closing this issue as it seems to have been resolved. Feel free to re-open if it's actually not.
