### ISSUE TITLE
add onOpen/onOpened and onClose/onClosed to components

### ISSUE THREAD

**Issue by iwan-uschka** [rsuite/rsuite#1026]
### What problem does this feature solve?

At the moment some components provide `onOpen` and `onClose` callbacks which are fired after animation has finished. It would be very helpful to be able to track both events of an animation: start and end.

### What does the proposed API look like?

Next to component properties `onOpen` and `onClose` it would be nice to have two more properties: `onOpened` and `onClosed`.

**Comment by simonguo** [comment]
In fact, these components have callback functions for the animation life cycle. Missing documentation description.
```ts
onEnter
onEntering
onEntered
onExit
onExiting
onExited
```

**Comment by iwan-uschka** [comment]
Ahhhh right. I knew I'd seen something like this before. So cool.

👍 👍 👍 

Feel free to update the docs :)

Thx..
