### ISSUE TITLE
Month title in Calendar

### ISSUE THREAD

**Issue by StrangersSoftware** [rsuite/rsuite#1034]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `6.13.1` |
| `rsuite` | `4.3.4` |

!!!! Thanks for Rsuite! Excellent job! :) !!!!

Calendar Month does not changes according to the local language and stays in English.
![1](https://user-images.githubusercontent.com/15338501/81229935-4f66fe80-8ff9-11ea-8fe3-1b075e8ce8d9.jpg)

**Comment by simonguo** [comment]
The month in the current component is formatted using the `format` function provided by date-fns.
We provide a solution to add a new `formatDate` method to the` <IntlProvider> `component for formatting dates.

```tsx
import format from 'date-fns/format';
import ru from 'date-fns/locale/ru';

function formatDate(data, formatStr) {
  return format(data, formatStr, {
    locale: ru
  });
}
```

```tsx
function App() {
  reutrn(
    <IntlProvider formatDate={formatDate}>
      {children}
    </IntlProvider>
  );
}
```

**Comment by StrangersSoftware** [comment]
Yes, I use the `<IntlProvider>` and the screenshot above is exactly the result of implementation of it in a code by this way:

```
import ru_RU from 'rsuite/lib/IntlProvider/locales/ru_RU';
const app = (
  <BrowserRouter>
    <React.StrictMode>
      <IntlProvider locale={ru_RU}>
        <App />
      </IntlProvider>
    </React.StrictMode>
  </BrowserRouter>
)
```

But if I add a code you've suggest, I recieve this:
![2](https://user-images.githubusercontent.com/15338501/81328840-3c5e3800-90a6-11ea-83a9-36d7effb2aa1.jpg)

Here is the code:

```
import format from 'date-fns/format';
import ru from 'date-fns/locale/ru';

function formatDate(data, formatStr) {
  return format(data, formatStr, {
    locale: ru
  });
}        

const app = (
  <BrowserRouter>
    <React.StrictMode>
      <IntlProvider formatDate={formatDate}>
        <App />
      </IntlProvider>
    </React.StrictMode>
  </BrowserRouter>
)

```
Do I use code in wrong way?

**Comment by simonguo** [comment]
@StrangersSoftware 
https://github.com/rsuite/rsuite/pull/1036 `formatDate` is an unreleased new feature. It is still in the testing and verification stage, if there is no problem, it will be released in the near future.

**Comment by StrangersSoftware** [comment]
Yes, sure! Not a critical problem for me - just mentioned this bug for you, not for immediate fix at all. Thanks for Rsuite again - it is quite simple tool to use! I enjoy using of it! 👍
