### ISSUE TITLE
When the virtual table is scrolled vertically to the end, the cell font will be blurred in the chrome browser

### ISSUE THREAD

**Issue by VirgoArt** [rsuite/rsuite#1038]
### Versions

| package  | version |
| -------- | ------- |
 "react": "^16.8.3",
 "react-dom": "^16.8.3",
 "rsuite-table": "3.11.3",
![image](https://user-images.githubusercontent.com/41778222/81364130-816e8280-9117-11ea-89b3-344b3aa12355.png)
![image](https://user-images.githubusercontent.com/41778222/81364145-8b908100-9117-11ea-855f-eae53519c714.png)

**Comment by simonguo** [comment]
You try to set the `translate3d` property of Table to `false`, which should improve the blur of the font.
```tsx
<Table translate3d={false} >
```

**Comment by VirgoArt** [comment]
@simonguo Thanks, its fine
