### ISSUE TITLE
Table update single item cell value problem

### ISSUE THREAD

**Issue by JoToe** [rsuite/rsuite#1041]
### Versions
| package  | version |
| -------- | ------- |
| `react`  | `16.12.0` |
| `rsuite` | `4.5.0` |

### What is the expected behavior?
Update a single item property should only update the single cell. No matter where I have scrolled to in the table.

### What is the current behavior?
Having scrolled to the bottom of a table and update a single property of an item leads to scrolling to top. And when having the virtualized flag set it will not show anything after having changed the property. Only when scrolling again it will re-render. But also from the top.

### What are the steps to reproduce?
1. Scroll to the bottom
2. Change a single item property

[Here](https://codesandbox.io/s/react-table-update-item-problem-ft15y) is the link to the code sandbox example where you can test it. ( Scroll down - Click update Peters age button and see the issue. After that you can add virtualized flag and test it again.)

**Comment by simonguo** [comment]
By default, data update will cause the scroll bar to reset. You can prevent the scroll bar from resetting by setting `shouldUpdateScroll` to` false`.
```tsx 
<Table shouldUpdateScroll={false} >
```

**Comment by JoToe** [comment]
very good :) Thanks a lot!
