### ISSUE TITLE
DateRangePicker change format of dates shown

### ISSUE THREAD

**Issue by thellimist** [rsuite/rsuite#1043]
### What problem does this feature solve?

![image](https://user-images.githubusercontent.com/6690196/81491414-021cb280-92c1-11ea-899c-c169bdd4daaf.png)

I want the red values customizable. Hopefully, they can shown the green values or custom format like "10 May" etc.

### What does the proposed API look like?

This is combined of three requests
1) Allow pre-set date range names to be shown as date value
2) Customize date value in a different ISO 8601 format like 'YYYY-mm' etc.
3) Customize the `~` character for date ranges

Three two attributes would handle all these cases

```
<DateRangePicker 
   showPresetDateName // boolean "true" as default
   dateFormat=(date1, date2) => {
      return date1.format('YYYY-MM-DD') + ' ~ ' + date2.format('YYYY-MM-DD')
   }
>
```

This solution would work for single dates rather than date ranges as well. `dateFormat` would return only a single date like `(date) => { }`

**Comment by simonguo** [comment]
All Pickers provide a `renderValue` props. You can customize the values ​​displayed in the rendering.

```jsx
import format from 'date-fns/format';

return (
  <DateRangePicker
    renderValue={(value) => {
      return format(value[0], 'MMM,YYYY') + ' ~ ' + format(value[1], 'MMM,YYYY');
    }}
  />
)
```

**Comment by thellimist** [comment]
Thanks. This handles 2nd and 3rd issues. How can we achieve 1st item `Allow pre-set date range names to be shown as date value`?

**Comment by simonguo** [comment]
`defaultValue` is used to preset default values.


```jsx
import format from 'date-fns/format';
import addWeeks from 'date-fns/addWeeks';

return (
  <DateRangePicker
    defaultValue={[new Date('2020/01/01'), addWeeks(new Date('2020/02/01'), 2)]}
    renderValue={value => {
      return format(value[0], 'MMM,YYYY') + ' ~ ' + format(value[1], 'MMM,YYYY');
    }}
  />
);

```

**Comment by thellimist** [comment]
@simonguo  I think you misunderstood the question.

![image](https://user-images.githubusercontent.com/6690196/81491414-021cb280-92c1-11ea-899c-c169bdd4daaf.png)

When the green buttons are clicked, I want to see the green button text rather than the date in `renderValue` field. 

An option like 

```
<DateRangePicker 
   ...
   showPresetDateName
>

would be amazing, but is there an easier way to achieve this without calculating the text again in `renderValue`?

**Comment by simonguo** [comment]
I understand your question now. Currently, it can only be customized through `renderValue`. In `renderValue`, it is judged whether it is consistent with the preset value. If they are the same, the preset value is displayed.

It may be an improvement in the future.

**Comment by thellimist** [comment]
for anyone looking at it I'm using moment and the following works like a charm

```
renderValue={(value) => {
                for (const range of ranges) {
                  if (moment(range.value[0]).isSame(moment(value[0])) && moment(range.value[1]).isSame(moment(value[1]))) {
                    return range.label;
                  }
                }
               return moment(new Date(value[0])).format('MMM DD') + ' / ' + moment(new Date(value[1])).format('MMM DD');
}}
```
