### ISSUE TITLE
table组件virtualized为true时，使用scrollTop方法滚动到指定位置时，可视区域外的行空白

### ISSUE THREAD

**Issue by zhaofengping** [rsuite/rsuite#1044]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `16.12.0` |
| `rsuite` | `4.5.0` |

### What is the expected behavior?
1、滚动到指定位置，当前显示行正常展示
2、通过rowClassName指定的类名设置background无效

### What is the current behavior?
1、可视区域外的行空白，需操作滚动条后才能正常显示
2、通过rowClassName指定的类名可设置background（当前的默认白色背景是在rs-table-cell类上，能否指定到rs-table-row上，rs-table-cell继承它的background）

### example
https://codesandbox.io/s/rsuite-table-demo-weumm?file=/package.json:237-242

**Comment by simonguo** [comment]
@zhaofengping  这确实存在更新问题，一个临时的解决办法：
```js
table.scrollTop(500);
table.forceUpdate(); // 强制更新 Table
```

该问题我们近期会修复。

**Comment by zhaofengping** [comment]
通过rowClassName指定的类名可设置background无效的问题会解决吗

**Comment by simonguo** [comment]
row 不能覆盖 cell 的背景颜色，你需要改变 cell 的背景颜色。
一个类似的问题 https://github.com/rsuite/rsuite/issues/1012

**Comment by zhaofengping** [comment]
好的，那我只能按照如上继承的方式组件样式实现了。
建议：项目大部分选型都是antd，一个api的变更对于大项目都需要统一排查，所以希望能参考一些它的api，降低项目的切换成本，这样才能有更多用户愿意尝试
