### ISSUE TITLE
Pick multiple dates at once

### ISSUE THREAD

**Issue by ruihildt** [rsuite/rsuite#1049]
### What problem does this feature solve?

I'm building a meeting app where a user can pick multiple dates for a possible meeting.
Right now it's only possible to select a [single date](https://rsuitejs.com/en/components/date-picker/) or a [range](https://rsuitejs.com/en/components/date-range-picker/) of consequent dates.

I would like to be able to pick multiple dates by clicking on dates. Selected dates would have a blue background.

### What does the proposed API look like?
The input values would be an array of dates instead of a single value.

**Comment by simonguo** [comment]
rsuite provides an extension component `@rsuite/multi-date-picker`, which can meet the features you want.
- https://rsuite.github.io/multi-date-picker/
- https://github.com/rsuite/multi-date-picker

![image](https://user-images.githubusercontent.com/1203827/81762868-48ac2000-9500-11ea-82ba-b3b85768e6d9.png)

More extension components: https://rsuitejs.com/en/extensions

**Comment by ruihildt** [comment]
Thanks, I still have suggestion for improvement, but I will create an issue in the multi-date-picker repo.

**Comment by ruihildt** [comment]
@simonguo Here is the new [issue](https://github.com/rsuite/multi-date-picker/issues/5).
