### ISSUE TITLE
Issue with the new prop formatDate

### ISSUE THREAD

**Issue by juan-manuel-alberro** [rsuite/rsuite#1057]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `16.13.1` |
| `rsuite` | `4.6.0` |
| `date-fns` | `2.13.0` |

### What is the expected behavior?

To format the dates properly.

### What is the current behavior?

RangeError: Use `yyyy` instead of `YYYY` for formatting years; see: https://git.io/fxCyr
throwProtectedError

```jsx
node_modules/date-fns/esm/_lib/protectedTokens/index.js:11
   8 | }
   9 | export function throwProtectedError(token) {
  10 |   if (token === 'YYYY') {
> 11 |     throw new RangeError('Use `yyyy` instead of `YYYY` for formatting years; see: https://git.io/fxCyr');
  12 |   } else if (token === 'YY') {
  13 |     throw new RangeError('Use `yy` instead of `YY` for formatting years; see: https://git.io/fxCyr');
  14 |   } else if (token === 'D') {
```

### What are the steps to reproduce?

```jsx
import React from 'react';
import format from 'date-fns/format';
import es from 'date-fns/locale/es';
import { IntlProvider } from 'rsuite';

import { Router } from './Router';

function formatDate(data, formatStr) {
  return format(data, formatStr, { locale: es });
}

function App() {
  return (
    <IntlProvider
      formatDate={formatDate}
    >
      <Router />
    </IntlProvider>
  );
}

export default App;
```

### Any additional comments? (optional)

Example from here: https://rsuitejs.com/en/guide/intl/

Popular mistakes: https://github.com/date-fns/date-fns/blob/master/docs/unicodeTokens.md#popular-mistakes

**Comment by simonguo** [comment]
Please use `date-fns@1.30.1`. The date-fns v2 version API has compatibility issues.

**Comment by juan-manuel-alberro** [comment]
Yeap, that was the issue, should I close this ticket or you want to keep it to migrate the API to the 2.x?

**Comment by simonguo** [comment]
The date-fns upgrade to v2 is already in our development plan.
