### ISSUE TITLE
with-electron can't work

### ISSUE THREAD

**Issue by 986244073** [rsuite/rsuite#1060]
我clone 最新的代码 然后run star  不能运行

**Comment by begoat** [comment]
@986244073  这个example确实存在问题，是package.json遗漏了`babel`相关的包
在运行start命令的时候可以通过 localhost: 9000 去查看 webpack构建过程产生的日志

你可以先手动install `babel`相关的包
```sh
npm install --save-dev @babel/core @babel/preset-env @babel/preset-react babel-loader
```

稍后我们会提交修复这个问题，并补充相关文档

**Comment by begoat** [comment]
@986244073  麻烦pull下最新代码在重新运行下

如果还有问题麻烦提供node版本、平台信息以及相关的错误日志方便debug

> ps: dev模式访问localhost:9000查看webpack编译报错

**Comment by 986244073** [comment]
可以用了 谢谢

**Comment by begoat** [comment]
编码愉快
