### ISSUE TITLE
selectPicker的下拉框展开时位置调整的问题

### ISSUE THREAD

**Issue by ESCEBT** [rsuite/rsuite#1073]
### Versions
| package  | version |
| `rsuite` | `4.5.1-beta` |

### What is the current behavior?
selectPicker组件设置属性autoVerticalEnd，下拉框展开后位置变动会有闪一下的效果，原因在于展开后宽度改变重新计算下拉框的位置

### What is the expected behavior?
展开下拉框时下拉框位置不会改变。

### Detail description
这里希望的效果是：在下拉框宽度改变后，能固定上面和右边的位置不动，整个下拉框往左侧延伸开。
而现在其实是以左上方为固定点的，宽度向右变宽，然后再重新计算位置整个框左移。
![image](https://user-images.githubusercontent.com/20390748/82779122-ec44eb00-9e85-11ea-8d2f-d4ab5d381b08.png)

**Comment by simonguo** [comment]
Fixed in [rsuite v5](https://next.rsuitejs.com/).

```
npm i rsuite@next
```
