### ISSUE TITLE
docs目录下面 npm run dev 跑起来很慢 且组件没有加载。 控制台报错如下

### ISSUE THREAD

**Issue by fubd** [rsuite/rsuite#1074]
![image](https://user-images.githubusercontent.com/29155847/82782558-29fa4180-9e8f-11ea-82ba-9ca8c239430c.png)
![image](https://user-images.githubusercontent.com/29155847/82782992-23b89500-9e90-11ea-9584-6ef71f3635d9.png)

Environment | Info
-- | --
rsuite | 4.7.0
React | 16.12.0
System | Mac OS
Browser | 版本 81.0.4044.138（正式版本） （64 位）
node | 10.5.0
npm | 6.1.0

**Comment by simonguo** [comment]
## npm run dev  开发环境慢的问题

这个是依赖于 next.js 的的编译速度，希望 webpack 5 的发布能够解决这个问题 https://github.com/zeit/next.js/issues/4844#issuecomment-614483722。

## 控制台报错如下的问题

感觉像是对 babel 的依赖有问题，我无法重现这个问题。你是按照 [UI 驱动开发](https://github.com/rsuite/rsuite#ui-driven-development)文档说明进行操作的吗？

**Comment by fubd** [comment]
@simonguo 是的。根据 https://github.com/simonguo/react-code-view/issues/3#issuecomment-498988955 修复了这个问题。

很惊讶 这个issue是19年提出的，今天尝试 run rsuite 的时候这个问题依然存在。
