### ISSUE TITLE
Tree table - refresh table after data setState

### ISSUE THREAD

**Issue by Shenwa** [rsuite/rsuite#1076]
Hi everyone,

I'm facing an issue with the Table component. I've got a virtualized tree table component with a search input for each column. When I update my data state after an onChange, the table doesn't refresh : 

![2020-05-25 16_16_10-Window](https://user-images.githubusercontent.com/22005418/82820815-2a043c80-9ea3-11ea-8887-61e40ecfc2b1.png)

In my onChange of my columns inputs :

![2020-05-25 16_18_02-Window](https://user-images.githubusercontent.com/22005418/82820910-5cae3500-9ea3-11ea-89cc-33c8d6774f67.png)

Is there a method which allow to reload the Table component ? I didn't find it in the documentation.
Thanks !

**Comment by simonguo** [comment]
How does your code in `onChange` update data?

**Comment by Shenwa** [comment]
In my onChange, I create a copy of my actual state, then I use a filter function in my array in all of my childrens. Then, with my new array, I update the state.

![2020-05-26 09_08_12-vepsi-front – VirtualizedTable_index js IntelliJ IDEA](https://user-images.githubusercontent.com/22005418/82870570-78135180-9f30-11ea-9314-571072cb0946.png)

**Comment by simonguo** [comment]
```js
site.children = site.children.filter(...)
```
In your code,  actually modifies data directly. Because javascript objects are reference types.

**Comment by Shenwa** [comment]
Yeah indeed, I did that because when I do 
```
let var = site.children.filter(...)
site.children = var;
```
My IDE says this : 

![2020-05-26 09_42_01-vepsi-front – VirtualizedTable_index js IntelliJ IDEA](https://user-images.githubusercontent.com/22005418/82873732-38029d80-9f35-11ea-8cce-b3e972daa893.png)

But in all cases, my data is well filtered, my state is modified, but the tree table doesn't refresh :/

**Comment by simonguo** [comment]
In Table, it will compare whether the values ​​of `props.data` and` prevProps.data` are consistent. If they are not consistent, the table will be updated.

If you directly modify data before `this.setState`, the values ​​of` props.data` and `prevProps.data` will be the same, and the table will not be updated.

The data should be immutable. A simple solution is to make a clone before modifying the data.

```js
const nextData = _.cloneDeep(this.state.data);

this.setState({
  data: nextData.map(...)
})
```
But this may cause performance problems. You can try other solutions to keep the data immutable. 

In addition, you can update the Table `key` to achieve table re-rendering.

**Comment by Shenwa** [comment]
The cloneDeep() method works effectively ! I didn't notice performance issue with it in my large dataset.
I'll look to update the Table `key`. Thank you for your explanation 👍
