### ISSUE TITLE
Web site down?

### ISSUE THREAD

**Issue by mrfambo** [rsuite/rsuite#1077]
Seems like rsuite website is not working. Can you please check it?

**Comment by simonguo** [comment]
The current website visit is normal.

https://vercel-status.com/
Can you visit this website?

**Comment by mrfambo** [comment]
<img width="959" alt="Screenshot 2020-05-26 at 9 45 40 AM" src="https://user-images.githubusercontent.com/16781300/82861307-ac3d4100-9f35-11ea-9a4f-3eebb5fc006f.png">

I still see this error Message !! Maybe something is wrong with my own network !!!

**Comment by mrfambo** [comment]
<img width="534" alt="Screenshot 2020-05-26 at 9 53 48 AM" src="https://user-images.githubusercontent.com/16781300/82861645-cdeaf800-9f36-11ea-8960-f828d95133af.png">
I see the same for other Vercel websites. Just the vercel website (https://vercel.com) seems to be working fine though !!!
Weird issue.

**Comment by mrfambo** [comment]
I opened the latest Commit.

https://github.com/rsuite/rsuite/commit/c8bfd645159fe25503818d1fb0873b4cf9fa4112#commitcomment-39434982

Got this URL working finally !!! 

https://rsuite-ip0x8umao.now.sh/

**Comment by simonguo** [comment]
If you have been unable to access, you can try to visit https://rsuite.now.sh/
