### ISSUE TITLE
PopUp on navbar item

### ISSUE THREAD

**Issue by StrangersSoftware** [rsuite/rsuite#1084]
package | version
-- | --
react | 6.13.1
rsuite | 4.7.0

!!!! Thanks for Rsuite! Excellent job! :) !!!!

In case if element of menu is a `<Dropdown>`, the popup is not shown.
![1](https://user-images.githubusercontent.com/15338501/83079835-64c5ca80-a085-11ea-8aab-4c5f1b844d99.jpg)
![2](https://user-images.githubusercontent.com/15338501/83079837-655e6100-a085-11ea-8e61-378f39eafbc8.jpg)

**Comment by simonguo** [comment]
This is indeed a problem of inconsistent design. We will fix it, but it will bring a problem, Tooltip and Dropdown will overlap.
![image](https://user-images.githubusercontent.com/1203827/83125181-bd3eab80-a109-11ea-8ba9-c5fc506226b4.png)

**Comment by StrangersSoftware** [comment]
Oh, I see. But maybe you can make popup switchable? Any way - it is just a request for feature, not a problem for me. You can close this request if you wish to. 

Again - thanks for your job!

**Comment by simonguo** [comment]
![image](https://user-images.githubusercontent.com/1203827/84978434-74ee3880-b15f-11ea-87a6-9e84cec1f7eb.png)
We will add a header to Dropdown in order to solve this user experience problem

**Comment by StrangersSoftware** [comment]
Great! I am already done something like that with disabled dropdown item. 👍

**Comment by simonguo** [comment]
You don't need to disable dropdown item, just upgrade to the latest version `rsuite@4.7.5`
