### ISSUE TITLE
wordWrap: true not working at all with in virtualized table

### ISSUE THREAD

**Issue by shuozhang2016** [rsuite/rsuite#1086]
![image](https://user-images.githubusercontent.com/17228552/83106797-a68b5b00-a0ef-11ea-91c9-aac316194f67.png)

**Comment by shuozhang2016** [comment]
@simonguo  请问 有没有什么好的思路既想用无限滚动又可以设置动态的行高？ 很喜欢用你们的这一套UI

**Comment by simonguo** [comment]
`virtualized` 的实现前提就是要预先知道表格所有行所占用的行高，`wordWrap` 是在渲染后得到实际的行高再重绘，所以逻辑上是行不通的。

有一个折中的方式，就是你可以通过 `rowData` 自己判断，并设置行高。

```tsx
<Table
  virtualized
  rowHeight={rowData => {
    // 这里只是一个简单的判断，应该以你实际的业务为准
    if (rowData.username.length > 40) {
      return 92;
    }
    return 46;
  }}
/>;
```
rsuite Table 中会判断，如果 rowHeight 属性是一个函数，则会在渲染前遍历所有的数据，并计算出总高度。这样处理所带来的问题就是当数据量达到一定程度会导致性能问题。 所以，我还是推荐在使用 `virtualized` 的情况下就选择固定行高。
