### ISSUE TITLE
Who's using React Suite?

### ISSUE THREAD

**Issue by SevenOutman** [rsuite/rsuite#11]
Drop your company name, SVG logo, and a link to your website. Links to any public repos using React Router are welcome, too!

**Comment by MrSaints** [comment]
FYI (slightly off-topic), the website is _incredibly slow_ to load (takes over a minute) for visitors outside of China (at least that is what I am assuming).

**Comment by SevenOutman** [comment]
@MrSaints Thanks for your feedback!

FYI this issue is specially for collecting projects using RSUITE. I would appreciate it if you can open a separate issue for your question and allow me to delete your comment within 24 hours. We'll keep track on your new issue then.

**Comment by MrSaints** [comment]
Appreciate it :) @SevenOutman

**Comment by windgaucho** [comment]
Hello, congratulations for this great suit of ui react components, it looks great !!
I wanted to know if there are some design or project examples from which I can start using rsuite.

**Comment by simonguo** [comment]
@windgaucho ,
https://github.com/rsuite/rsuite-management-system
Please pay attention to this library, which is an example project that will be open source in the near future.

**Comment by windgaucho** [comment]
Thank you very much, I will start using this framework!! it is look awesome!!

**Comment by gdx945** [comment]
import React, { Component } from 'react';
import { Navbar, Nav, Icon, Dropdown } from 'rsuite';
import 'rsuite/dist/styles/rsuite.min.css';

class Header extends Component {
  render() {
    return (
      <Navbar>
        <Navbar.Header>
          <a href="#" className="navbar-brand logo">RSUITE</a>
        </Navbar.Header>
        <Navbar.Body>
          <Nav>
            <Nav.Item icon={<Icon icon="home" />} >Home</Nav.Item>
            <Nav.Item>News</Nav.Item>
            <Nav.Item>Products</Nav.Item>
            <Dropdown title="About">
              <Dropdown.Item>Company</Dropdown.Item>
              <Dropdown.Item>Team</Dropdown.Item>
              <Dropdown.Item>Contact</Dropdown.Item>
            </Dropdown>
          </Nav>
          <Nav pullRight>
            <Nav.Item icon={<Icon icon="cog" />} >Settings</Nav.Item>
          </Nav>
        </Navbar.Body>
      </Navbar>
    );
  }
这样使用时，页面没有在示例页面中#body .navbar-brand的样式，请问这些样式是从哪加载的？

**Comment by simonguo** [comment]
@gdx945  https://github.com/rsuite/rsuite.github.io/blob/master/src/less/main.less#L715

**Comment by ChristianReifberger** [comment]
Been using it in 4 Projects now and I love it. If you need any contributors dont bother to hit me up!

**Comment by 15607306950** [comment]
Why does the code not run properly after being pulled down, following the steps given by the author

**Comment by 15607306950** [comment]
Could you please tell me that you used less in this project, and the path to node_models is the path to node_models in the path to the path to the path of node_models file.
@ import '~ rsuite - table/lib/less/index. The less';What if I'm using the current project, which is a SCSS compilation, and I'm using a gulp package, and I want to introduce a change plug-in library

**Comment by SevenOutman** [comment]
@gdx945 @15607306950 This issue is not the right place to ask questions. Please [open a new issue](https://github.com/rsuite/rsuite/issues/new) or [join our Discord group](https://discordapp.com/invite/R8mnjwh) for support. Your comments will be deleted within 24 hours, or you can delete them your self.

**Comment by 15607306950** [comment]
ddd

**Comment by fannaoshaoxiang** [comment]
我们公司目前就使用了此框架来做中后台。
![4.0.png](https://uploads.codesandbox.io/uploads/user/54d06f4d-17b5-465c-83df-cb94c7484cde/WgTH-2019-01-10_17-04-14.png)
![5.0.png](https://uploads.codesandbox.io/uploads/user/54d06f4d-17b5-465c-83df-cb94c7484cde/kuLF-2019-01-10_17-05-19.png)

**Comment by shiyachuang** [comment]
Thanks for developing this component is great, especially the virtual components.  👍👍👍

**Comment by pengshaomin** [comment]
有admin后台模板吗？

**Comment by bennihoss** [comment]
just started my first application with this framework, i was searching a nice looking framework for b2b applications, without the playfulness like in material-ui as example. First i wanted to use semantic, but then i saw your framework i have to say, it's awesome. Really nice looking and easy to understand. I really love that Pickers with Searching etc, perfect for my usecase, and the combination of the ripple-buttons and normal input components is really good fitting. 
Really good work, will definitely recommend it!

**Comment by Ericnr** [comment]
Just found out about the lib and it seems amazing. Seriously considering using it. The only thing that threw me off a little was the fact there is no prop you can pass to disable the buttons ripple effect. Think I would have to roll out my own button component.

**Comment by simonguo** [comment]
@Ericnr 

Disable ripple effect：
```less
@import '~rsuite/src/styles/index';
@button-ripple: false;
```

A detailed description of the custom theme. https://rsuitejs.com/en/guide/themes

**Comment by Ericnr** [comment]
oke thats perfect thank you

**Comment by webtrend55** [comment]
Hi everyone,

I have some problems in implementing rsuite table components.

![image](https://user-images.githubusercontent.com/57599786/73425661-95ddfa80-4332-11ea-94f7-4212c230d3d9.png)

As you can see, horizontal scroll bar always does not work properly at the first time.
If I resize browser several time, it does work well.

Please help me to handle this problem.

**Comment by pabloiea1995** [comment]
Great work guys! This library makes it so easy and fast to develop a very well contructed and professional UI. I have used it for my first freelance project and the result has been amazing... Got the result o 100 working hours in just 30.
I have a few ideas to contribute, i wil try to develop them by my self and contribute!
