### ISSUE TITLE
TS7016 implicitly has an 'any' type

### ISSUE THREAD

**Issue by aromanp** [rsuite/rsuite#1102]
| package  | version |
| -------- | ------- |
| `react`  | `16.13.1` |
| `rsuite` | `^4.7.1` |

I just found rsuite and set out to try it, add to my project, so I followed the steps they put into "https://github.com/rsuite/rsuite" Installation & Usage, but when I run it throws the error of the attached image

![image](https://user-images.githubusercontent.com/55712537/83718969-b4634380-a5fb-11ea-96cc-b52ca1d790ec.png)

**Comment by simonguo** [comment]
Through the error message, it is a bit like the warning thrown by ts-loader, we fix it, you can refer to this typescript example project first.

https://github.com/rsuite/rsuite/tree/master/examples/with-typescript

**Comment by aromanp** [comment]
the button or any other element no problem, it marks me that the error is in the node_module to be precise in the DateRangePicker.d.ts
"Could not find a declaration file for module ''../constants"

**Comment by simonguo** [comment]
Try to upgrade to the latest version
```
npm i rsuite@latest
```

**Comment by aromanp** [comment]
It was perfect thanks
