### ISSUE TITLE
Labels within the components

### ISSUE THREAD

**Issue by aromanp** [rsuite/rsuite#1105]
Hello currently components like Input, InputNumber, AutoComplete, InputPicker, TagPicker, SelectPicker, CheckPicker, etc ...
To be able to distinguish which field is the one that I am filling we depend on putting something like this "<ControlLabel> Username </ControlLabel>". 
![image](https://user-images.githubusercontent.com/55712537/83773502-37ab8600-a64a-11ea-8146-ca9f5029a994.png)

 I suggest you can do something like the image below
![image](https://user-images.githubusercontent.com/55712537/83773883-b274a100-a64a-11ea-83bc-d56599029b7d.png)

Being able to call the label type in a way like:

<FormControl 
     name="name" 
     label="our label" 
     labelType="Standard||filled||outlined"/>

<Input 
      style={{ width: 300 }} 
     placeholder="Default Input" 
     label="our label" 
     labelType="Standard||filled||outlined"/>

<SelectPicker
      data={data}
      appearance="default"
      placeholder="Default"
      style={{ width: 224 }}
      label="our label"
       labelType="Standard||filled||outlined"
    />

**Comment by simonguo** [comment]
There are not many types of labels in our [design system](https://rsuitejs.com/design/default/#artboard46), and I am not sure whether they will be considered in the future.

In addition, you can meet the business use through the combination of components.

```jsx

function TextField({ name, label, accepter, ...rest }) {
  return (
    <FormGroup>
      <ControlLabel>{label} </ControlLabel>
      <FormControl name={name} accepter={accepter} {...rest} />
    </FormGroup>
  );
}

return (
  <Form>
    <TextField
      label="label"
      data={data}
      accepter={InputPicker}
      appearance="default"
      style={{ width: 224 }}
    />
  </Form>
);
```
