### ISSUE TITLE
Components not using dark theme with babel preset

### ISSUE THREAD

**Issue by dan-dr** [rsuite/rsuite#1114]
### Versions
| package  | version |
| -------- | ------- |
| `react`  | `16.3.1` |
| `rsuite` | `4.6.0` |

### What is the expected behavior?
When I use `babel-preset-rsuite` with `{ style: true, theme: dark}`, when I `import { Input } from 'rsuite'` it should have a dark background.

### What is the current behavior?
The input has white background.

### What are the steps to reproduce?
1. use `less-loader` with `javascriptEnabled: true`
2. use `babel-preset-rsuite` with `{ style: true, theme: dark}`
3. `import { Input } from 'rsuite'`

https://codesandbox.io/s/cranky-goldwasser-89hjj

Simply use the babel preset as mentioned above, with webpack `less-loader` and only import individual components without importing any other style files.

### Any additional comments? (optional)
It seems like every file needs to load the dark-theme constants by himself, because you are loading separate `less` files, they don't share variables.

**Comment by simonguo** [comment]
The problems with `codesandbox` have been fixed, please use the latest version `4.7.3`. We are still investigating problems with the Dark theme.

**Comment by dan-dr** [comment]
example:
https://codesandbox.io/s/cranky-goldwasser-89hjj

**Comment by simonguo** [comment]
stale
