### ISSUE TITLE
<Dropdown /> How to set the width of dropdown always as long as the max one among the items?

### ISSUE THREAD

**Issue by Shawn1224** [rsuite/rsuite#1119]
### What problem does this feature solve?
I encounter a problem when I use the `Dropdown` component, which is how can I set the width of one currently shown to always align with the max one among the items?

### What does the proposed API look like?
As the picture is shown below, I  want the first `Dropdown`'s width always as long as the second one(max one among the items) no matter what I select.

![image](https://user-images.githubusercontent.com/21187889/84228019-780e7680-ab18-11ea-8770-03de2cea739d.png)

The above picture's code: [https://codesandbox.io/s/rsuite-dropdown-default-width-issue-ehcr6](https://codesandbox.io/s/rsuite-dropdown-default-width-issue-ehcr6?file=/src/App.js)

**Comment by simonguo** [comment]
The container is set to line-block, and the dropdown is set to block. The width of dropdown will be displayed according to the maximum width of the container.

```jsx
<div className="dropdown-group">
  <Dropdown />
  <Dropdown />
</div>
```
```css
.dropdown-group {
  display: inline-block;
}

.rs-dropdown,
.rs-dropdown-toggle {
  display: block !important;
}

```
https://codesandbox.io/s/rsuite-dropdown-default-width-issue-sirzz

**Comment by Shawn1224** [comment]
It's so good. Thanks a lot.
