### ISSUE TITLE
DateRangePicker 支持显示时分秒，希望开放显示。

### ISSUE THREAD

**Issue by Link-Kou** [rsuite/rsuite#1123]
官方 DateRangePicker 时间区域目前只有支持 YYYY-MM-DD显示

我看完源代码发现 DateRangePicker 与 DatePicker 使用的是同一个Header组件
而DateRangePicker默认情况下不开放。

![image](https://user-images.githubusercontent.com/22113151/84592971-f0a86680-ae7b-11ea-9f43-7e066afe0a71.png)

左边为DateRangePicker        右边为DatePicker
![image](https://user-images.githubusercontent.com/22113151/84593002-21889b80-ae7c-11ea-8dda-70ed1b6c7871.png)

**Comment by hiyangguo** [comment]
你可以试试[使用 DatePicker 选择范围](https://rsuitejs.com/components/date-picker#%E9%80%89%E6%8B%A9%E8%8C%83%E5%9B%B4)

**Comment by Link-Kou** [comment]
@hiyangguo  提供的方案是一个选择，不过从两者的体验来看。明显DateRangePicker的体验更好。
而且我有点疑问，为什么不能将DateRangePicker的时分秒放开。我尝试修改了一下。发现没有什么特别有影响的地方？
