### ISSUE TITLE
rsuite table 3.13.1 上下滚动时候左右也跟着动，反之一样。 

### ISSUE THREAD

**Issue by qiuhuiyang** [rsuite/rsuite#1126]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `X.Y.Z` |
| `rsuite` | `X.Y.Z` |

**Comment by simonguo** [comment]
我无法复现你说的问题，可以提供更详细的复现说明吗？
或者通过 https://codesandbox.io/s/5vq6zo2z5l 复现你使用场景。

**Comment by qiuhuiyang** [comment]
当表格 右侧 有fixed的时候， 内容较长， 横向滚动， 当横向滚动条在初始位置时候不会有问题， 当横向滑动后，然后 mac 触摸板滑动，因为手指肯定有可能不一定是直上直下的滑动， 整个列表就会随着手指竖向滑动，不同程度的左右滑动，大概率左滑，等滑动到底了，横向滚动条也基本回到初始了。  window 或者鼠标当时试了一下应该没有这个问题。

**Comment by simonguo** [comment]
你手指有`不同程度的左右滑动`，滚动条就应该触发横向滚动的事件。
