### ISSUE TITLE
add 'none' as trigger option to Whisper component

### ISSUE THREAD

**Issue by iwan-uschka** [rsuite/rsuite#1131]
### What problem does this feature solve?

It would be cool to be able to fully control how a `<Popover>` can be opened and closed. Right now you can check different events/trigger states: `click`, `hover`, `focus`, `active`.

I would like to control the visibility of a popover by simply and only calling the methods `show` and `hide` of the `<Whisper>`s `triggerRef`. Right now the events/trigger states `click`, `hover`, `focus`, `active` do interfere here.

### What does the proposed API look like?

Add `none` as a `trigger` option to the `<Whisper>` component.

**Comment by simonguo** [comment]
We will consider your use case. You can use `pointerEvents` to solve current problems,
```tsx
<Whisper>
  <span style={{ pointerEvents: 'none' }}>Popover</span>
</Whisper>
```

**Comment by iwan-uschka** [comment]
I forgot to mention that the `<Whisper>` should work as a trigger element nevertheless. So `pointerEvents: none' won't work here. Or i am not getting the idea behind your suggestion. But thx anyway!!

To be more precisely about my use case: i've put a form into a `<Popover>`, the form can contain `<...Picker>` elements. If a `<...Picker>` has been opened it shouldn't be possible to close the `<Popover>` but only the `<...Picker>` being opened. If no `<...Picker>` is open the `<Popover>` should be able to be closed.

**Comment by iwan-uschka** [comment]
And not to forget the option to close a `<Popover>` by hitting the ESC key. I need to suppress this as well. Like it's possible for the `<Modal>` component via the `keyboard` property.

**Comment by iwan-uschka** [comment]
🎉 Works great! Thanks!
