### ISSUE TITLE
Dropdown is not following the scroll when implemented in drawer

### ISSUE THREAD

**Issue by Torvaldi** [rsuite/rsuite#1134]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `16.13.1` |
| `rsuite` | `4.7.5` |

### What is the expected behavior?

When I try to sroll up or down when dropdow is open, the dropdown values should move with the page.

![image](https://user-images.githubusercontent.com/7703951/85123384-78012b80-b228-11ea-88a2-63fa05142d9c.png)

### What is the current behavior?

When I try to create a dropdown (or any associated element) in a Drawer element and it has a scroll, the dropdown remains static on the page and does not go down or up according to the user movement.

![image](https://user-images.githubusercontent.com/7703951/85123325-5d2eb700-b228-11ea-9d05-31730b78ce45.png)

### What are the steps to reproduce?

1. Create a scrollable drawer
2. Add a dropdown into the drawer
3. Open the dropdown
4. Try to scroll the drawer

**Comment by simonguo** [comment]
Change the container of the picker component so that the menu is rendered inside the drawer.
```jsx
const mountRef = React.createRef();

return (
  <div ref={mountRef}>
    <SelectPicker container={() => mountRef.current} />
  </div>
);
```

**Comment by Torvaldi** [comment]
Okay, that solved my problem! Maybe this should be in the doc? Anyway, thank you very much for the tip!
