### ISSUE TITLE
add option to open/close Picker components programmatically

### ISSUE THREAD

**Issue by iwan-uschka** [rsuite/rsuite#1144]
### What problem does this feature solve?

Would be helpful to be able to open/close `<Picker>` components programmatically, similar to `<Whisper>`/`<Popover>` components where you can call `trigger.hide` or `trigger.show`.

### What does the proposed API look like?

A new property would be necessary here which provides the methods `open` and `close`.

Like i pointed out in https://github.com/rsuite/rsuite/issues/1025 it would be cool to be able to access the root DOM element of a component via `ref` (not only `FormControl` like addressed in this ticket but in general) so these two things probably interfere and need to be handled separately. I could think of a `<componentName>Ref` property containing the API methods and another child property like `ref` referencing the root DOM element.

**Comment by iwan-uschka** [comment]
Just a suggestion :)

**Comment by simonguo** [comment]
@iwan-uschka  
All Pickers currently provide `open` and `close` methods.  Regarding the DOM element obtained by `ref`, we will solve it through `React.forwardRef` in the next version.
```tsx
const pickerRef = React.createRef();
const open = () => pickerRef.current.open();
const close = () => pickerRef.current.close();

return (
  <>
    <CheckPicker data={data} ref={pickerRef} />
    <button onClick={open}>click</button>
    <button onClick={close}>close</button>
  </>
);
```

**Comment by iwan-uschka** [comment]
Thx for pointing that out!
