### ISSUE TITLE
add option to update position of a Picker

### ISSUE THREAD

**Issue by iwan-uschka** [rsuite/rsuite#1145]
### What problem does this feature solve?

I added a `<DateRangePicker>` to the top right corner of my application using `placement="bottomEnd"`.

<img width="814" alt="date-range-picker" src="https://user-images.githubusercontent.com/2256579/85947169-5bac6f80-b949-11ea-919f-342103744ac5.png">

If i now resize the window while the `<DateRangePicker>` stays opened the dropdown doesn't get replaced correctly.

<img width="975" alt="date-range-picker-2" src="https://user-images.githubusercontent.com/2256579/85947234-9c0bed80-b949-11ea-8c27-b7022c32a8fd.png">

After closing and reopening the picker everything looks good again and the dropdown's position is correct.

Workaround:

```
  const [dateRangePickerPlacement, setDateRangePickerPlacement] = useState(
    'bottomEnd',
  );

  const onResize = useCallback(() => {
    setDateRangePickerPlacement('bottomStart');
    setTimeout(setDateRangePickerPlacement('bottomEnd'));
  }, []);
```

Using `useState` here rerenders the whole component just for updating the position of the dropdown. That's why I need to put `<DateRangePicker>` into another component just for handling the repositioning in an encapsulated way.

### What does the proposed API look like?

I don't know if it's a good idea to implement a repositioning mechanism depending on window resizing (only). There are probably other dependencies like parent container resizing. So maybe a method like `updatePlacement` could be added to a component reference property.

**Comment by iwan-uschka** [comment]
Cool. Works great. Thx @simonguo !

For the record, if someone runs into the same issue as i did. @simonguo provided the following code snippet in https://github.com/rsuite/rsuite/pull/1148:

```
const positionRef = React.createRef();

window.addEventListener('resize', () => {
  positionRef.current?.updatePosition?.();
});

return (
  <DateRangePicker positionRef={positionRef} placement="bottomEnd" />
);
```

I set `<DateRangePicker>`s `showOneCalendar` property depending on the viewport width like this:

```
showOneCalendar={width < 510}
```

When crossing this border of 510px the position doesn't get updated properly. I have to call `updatePosition()` from within a `setTimeout` (again).

**Comment by simonguo** [comment]
This is not a good solution. It requires developers to update the location. We hope that all of this will be resolved internally in React Suite, and developers only care about the business.

We will solve it in [React Suite v5](https://github.com/rsuite/rsuite/issues/1165) through layout or other better solutions.

**Comment by simonguo** [comment]
Fixed in [rsuite v5](https://next.rsuitejs.com/).

```
npm i rsuite@next
```
