### ISSUE TITLE
Calendar Arrows pointing wrong direction when using RTL stylesheet

### ISSUE THREAD

**Issue by DovahBrownies** [rsuite/rsuite#1157]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `^16.8.6` |
| `rsuite` | `^4.7.1` |

### What is the expected behavior?
I'm currently using the `<DateRangePicker />`:
![image](https://user-images.githubusercontent.com/35106956/86582003-a6ea0200-bf89-11ea-9cdd-9609cf4040d4.png)

When I switch to the RTL stylesheet, the arrows on the picker are reverses **but the functionality is correct** (the arrows work as intended).

### What is the current behavior?
![image](https://user-images.githubusercontent.com/35106956/86582165-e6185300-bf89-11ea-8ece-1bd694196347.png)

### What are the steps to reproduce?
Create any `<DateRangePicker />` and them import `~rsuite/dist/styles/rsuite-default.rtl.css`

**Comment by DovahBrownies** [comment]
Maybe a CSS fix like this would do?
![image](https://user-images.githubusercontent.com/35106956/86748933-841d2380-c045-11ea-88bc-dfea51baa734.png)

**Comment by hiyangguo** [comment]
@DovahBrownies It's work fine on our website [https://rsuitejs.com/components/date-range-picker](https://rsuitejs.com/components/date-range-picker).
![image](https://user-images.githubusercontent.com/15609339/86900177-98444c00-c13d-11ea-8fac-f4ef7dcbe1a1.png)

**Comment by DovahBrownies** [comment]
@hiyangguo - Is it using the Rsuite RTL stylesheet (`~rsuite/dist/styles/rsuite-default.rtl.css`)?

**Comment by hiyangguo** [comment]
@DovahBrownies 
It's already wok fine.  This is my example : https://codesandbox.io/s/wandering-bird-gqn35.
I think you may forget to  add dir attribute  on the `index.html` file:
```
<html dir="rtl"></html>
```
More info about RTL in [https://rsuitejs.com/guide/rtl](https://rsuitejs.com/guide/rtl)

**Comment by DovahBrownies** [comment]
Didn't notice that NextJS was not setting the HTML attribute as I expected it to. For anyone else coming here with a similair NextJS issue: https://nextjs.org/docs/advanced-features/custom-document

Setting `dir='rtl'` worked. Thanks, @hiyangguo !
