### ISSUE TITLE
如何支持服务端渲染

### ISSUE THREAD

**Issue by qwe9527** [rsuite/rsuite#116]
现在直接使用会报错
`2018-06-29 10:53:11,302 ERROR 6848 [-/127.0.0.1/-/34ms GET /] nodejs.ReferenceError: window is not defined
    at Object.<anonymous> (\node_modules\_rsuite@3.1.1@rsuite\lib\utils\BrowserDetection.js:7:35)`

**Comment by SevenOutman** [comment]
@qwe9527 RSUITE 当前尚未支持服务端渲染，我们在文档中也没有提及对服务端的支持。

未来版本*不排除可能*会加入服务端渲染支持，但目前并未有明确的计划。
