### ISSUE TITLE
Calendar - don't see the years

### ISSUE THREAD

**Issue by Ido112** [rsuite/rsuite#1172]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `16.13.1` |
| `rsuite` | `4.6.0` |

### What is the expected behavior?

I except that the calendar shows the years after you click on the name of the month like the example

![](https://i.ibb.co/61zHJ4m/Screenshot-2020-07-15-at-10-01-13-AM.png)

### What is the current behavior?

When I click on the name of the month I don't see anything like the demo on the website.
![](https://i.ibb.co/2Z8mSY1/Screenshot-2020-07-15-at-10-03-03-AM.png)

I just paste it on the page without any change with the style

Like this
`<Calendar renderCell={renderCell} />`

So why when I click on the name of the month I didn't see anything.

Thanks

**Comment by simonguo** [comment]
Please fork this example, reproduce the problem you are issue.
https://codesandbox.io/s/5vq6zo2z5l

**Comment by Ido112** [comment]
Hey, 
Thank you for your answer.
I can not reproduce the problem in this example.
I think I have something that conflicts with the CSS that causes it not to appear.
I also use material UI at the same time.

I said that because I can see in the HTML of the page that the div's are existing.

![](https://i.ibb.co/MfzLmFm/Screenshot-2020-07-16-at-9-42-05-AM.png)

**Comment by simonguo** [comment]
I can't understand the cause of your CSS conflict. You can import the conflicting CSS library in codesandbox to reproduce your problem, so that we can help you.

**Comment by Ido112** [comment]
Hey,
I could not recover the problem on Codepen
Never mind I will use another library.
Thanks
