### ISSUE TITLE
TagPicker 控件的 renderValue 异常

### ISSUE THREAD

**Issue by Link-Kou** [rsuite/rsuite#1173]
### Versions

| package  | version |
| -------- | ------- |
| `rsuite` | `4.8.0` |

之前的版本item返回的不是数组。
升级后返回是数组了

https://rsuitejs.com/zh/components/tag-picker#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%80%89%E9%A1%B9

**Comment by simonguo** [comment]
TagPicker 的 value 是一个数组，所以 renderValue 回调的参数 value 和 items 都应该是数组。
如果之前的版本中返回的不是数组那是不对的。

**Comment by Link-Kou** [comment]
我看了 源代码，之前是循环的  现在是 一次性的。

**Comment by simonguo** [comment]
@Link-Kou  是的，我在想是不是可以加一个 renderTag 属性，用于自定义。

**Comment by Link-Kou** [comment]
@simonguo 

![image](https://user-images.githubusercontent.com/22113151/87742554-95bab400-c819-11ea-9e8c-0ad7fcb70425.png)

完全自定义后，个人觉得问题是

1. 一个玩意不好处理 rs-picker-search 。要写些Css处理一下。换行的情况下的问题。
2. 实际上我在重写的时候，多数情况下还是采用了 <Tag>，然后要自己处理删除的问题

基于上面的场景，我建议：

1.添加renderTag。至少可以不写删除事件的处理
2.对renderValue的修改，我非常认可。多了很大的自由度。让一些需要自定义的场景下，得心应手
