### ISSUE TITLE
希望 Tag 添加 一下  appearance

### ISSUE THREAD

**Issue by Link-Kou** [rsuite/rsuite#1174]
麻烦给 Tag 添加一下 类似于 Button 一样的 appearance 样式

**Comment by simonguo** [comment]
我们准备给 Tag 添加 color 属性。 https://github.com/rsuite/rsuite/issues/1033
appearance 应用场景是什么？

**Comment by Link-Kou** [comment]
我用Tag标签，用途最为广泛的就是描述状态、以及一些配置标签的场景
想要几种不同的样式。因为现在的Tag只有一种样式。
Button是有相关的样式类型的。如果用Button代替Tag。我个人感觉又有点不太合适。
所以建议添加。

**Comment by simonguo** [comment]
Supported in [rsuite v5](https://next.rsuitejs.com/).

```
npm i rsuite@next
```
