### ISSUE TITLE
SelectPicker等Picker的组件编辑场景下defaultValue改进建议

### ISSUE THREAD

**Issue by Link-Kou** [rsuite/rsuite#1201]
背景 : SelectPicker中的data通过异步方式加载过来的。
新增场景中：SelectPicker值默认为空，用户通过点击在下拉框异步加载可以选择信息。
编辑场景中:   SelectPicker默认非空，用户默认看到是保存起来的值。

SelectPicker等Picker的组件defaultValue是在data有值的时候才会起作用，这个时候为了解决，编辑情况下用户可以查看保存的值。目前我在项目中混用了三种解决方案

方法1：对placeholder进行接管。
方法2：根据编辑时候获取的值，创建数组并且设置data。然后设置默认值defaultValue，这时候用户可以看到默认值的表现。当用户点击下拉框异步加载数据
方法3：改异步为同步。直接在进入编辑页面中之前。完成数据的加载，设置默认值defaultValue或Value。

我目前想到的三个方法中,实践结果来看。

缺点：
方法1：在UI表现形式上有差异。一般需要自己动手写写样式保持统一。需要处理新增与编辑的情况下判断
方法2：在UI表现形式上无差异，当是代码重复率大。基本上需要基于SelectPicker进行二次封装一下。配合Form方便有效。
方法3：数据量小的情况下3是最好的解决方法，如果是异步加搜索的情况下。方法3基本上淘汰。基本上采用方法2去实现。

现在解决方法中，用的最多的就是2号解决方案因为基本上需要配合Form去完成。

我建议官方针对SelectPicker之类的控件能否升级一下defaultValue。

效果建议:

即填写了defaultValue值，但是data中无值的时候，将defaultValue显示出来。
当data有值的时候，走现有逻辑。取defaultValue匹配data

**Comment by simonguo** [comment]
你可以通过 `renderValue` 进行自定义渲染，在其判断 data 是否有值，如果没值则返回你想要渲染的内容（defaultValue）。

**Comment by Link-Kou** [comment]
这个问题只有在 Picker 类型的控件中存在，其他的控件不会。Picker 类型控件的值显示受到Data的影响。
@simonguo  你说的是一个解决方案。不过这个编辑的场景下，由于目前控件设计有清空的功能。只有我上述中的方法2是目前最好的。这个也是纠结的。很是难受。

或者说defaultValue也支持Data一样的属性传入Array<DataItemType>，这样子使用者就少了一些代码

代码类似

```js
<SelectPicker defaultValue={[{
 value: string; 
 label: React.Node; 
}]}/>;
```
