### ISSUE TITLE
How to pass the props of Tag component in TagPicker?

### ISSUE THREAD

**Issue by jsierrav14** [rsuite/rsuite#1206]
Hellos, 

I'm trying to use props in tagpicker for pass to tag,  i don't know how to do that, This is the way tha I'm trying
           
tagProps={{onClose:()=>{alert('hola')},closable:true}}

| package  | version |
| -------- | ------- |
| `react`  | 16.13.1 |
| `rsuite` | 4.7.4 |

I want that when I click in the close icon show the alert, actually it dont happen

I hope your answer, 

regards!

**Comment by simonguo** [comment]
![image](https://user-images.githubusercontent.com/1203827/88611876-988c9300-d0bc-11ea-9ad1-1b0e5b49b45a.png)
```tsx
 <TagPicker 
    data={data} 
    style={{ width: 300 }}  
    tagProps={{onClose:()=>{alert('hola')},closable:true}} 
  />
```
