### ISSUE TITLE
关于cdn字体文件的建议

### ISSUE THREAD

**Issue by awesome-coder** [rsuite/rsuite#1208]
建议css内部直接使用本地的font，而不去使用网络上的cdn

**Comment by Link-Kou** [comment]
@awesome-coder  稍微配置一下就可以了。


```js

addLessLoader({
        lessOptions: {
            javascriptEnabled: true,
            modifyVars: {
                '@icon-font-path': './fonts'
            }
        }
    }),

```

**Comment by awesome-coder** [comment]
> @awesome-coder 稍微配置一下就可以了。
> 
> ```js
> addLessLoader({
>         lessOptions: {
>             javascriptEnabled: true,
>             modifyVars: {
>                 '@icon-font-path': './fonts'
>             }
>         }
>     }),
> ```

纯css的，没有less，可以这么配置吗

**Comment by Link-Kou** [comment]
框架内的字体默认非本地化的。你可以使用配置将其本地化

https://rsuitejs.com/zh/guide/themes#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

相关文档看一下

如果你是自己字体。或者你自己弄了非框架内的东西，你的问题，我理解应该是不存在的。
