### ISSUE TITLE
关于babel-preset-rsuite 异常

### ISSUE THREAD

**Issue by Link-Kou** [rsuite/rsuite#1221]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `16.10.2` |
| `rsuite` | `4.8.0` |
| `babel-preset-rsuite` | `4.0.1` |

![image](https://user-images.githubusercontent.com/22113151/89178356-030f6880-d5c0-11ea-83d0-7a8e93565a61.png)

**Comment by simonguo** [comment]
- `babel-preset-rsuite`  在 babel 是怎么配置的？
-  less 变量 `@icon-font-path` 你有重置吗?  如果有，配置是怎么样的？

**Comment by Link-Kou** [comment]
![image](https://user-images.githubusercontent.com/22113151/89193741-06631e00-d5d9-11ea-99f2-2c6025e8b4bc.png)

![image](https://user-images.githubusercontent.com/22113151/89193935-41fde800-d5d9-11ea-9ec2-b35a13fb96ef.png)

**Comment by simonguo** [comment]
@Link-Kou 
你当前可以通过以下方案解决问题：

`@icon-font-path` 改为 CDN 地址: 
```
https://cdn.bootcdn.net/ajax/libs/rsuite/4.8.0/styles/fonts/
// or
https://cdn.jsdelivr.net/npm/rsuite/dist/styles/fonts
```
或者关闭 style 的按需加载，全局引入 less 
```js
{
    "presets": [["rsuite", { style: false }]]
}
```

等待我们进一步排查一下，按需加载带来的字体路径问题。

**Comment by mkanako** [comment]
我遇到的情况可能跟你一样
试试把
`'@icon-font-path': './fonts'`
改成
`'@icon-font-path': '~rsuite/lib/styles/fonts'`
