### ISSUE TITLE
Affix 组件无法导入

### ISSUE THREAD

**Issue by Teadeno** [rsuite/rsuite#1222]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `16.13.1` |
| `rsuite` | `3.2.2` |

### What is the expected behavior?
我需要使用Affix组件 但是组件找不到导出

**Comment by simonguo** [comment]
Affix 是 [rsuite@4.1.0](https://github.com/rsuite/rsuite/blob/next/CHANGELOG.md#410) 版本以后开始支持
