### ISSUE TITLE
关于Checkbox中的value非数组判断处理建议

### ISSUE THREAD

**Issue by Link-Kou** [rsuite/rsuite#1225]
Checkbox在使用过程中,传递非数组数据的时候，组件会直接炸掉。

源代码中的对Value的判断建议改进

![image](https://user-images.githubusercontent.com/22113151/89366794-26462f00-d70a-11ea-981a-df328d3f2cc3.png)

```js

getCheckedByValue() {
    const { value } = this.context;
     //这里做非空判断，远远不够
    if (!_.isUndefined(value) && !_.isUndefined(this.props.value)) {
      //非数组会直接让页面就奔溃
      return value.some(i => i === this.props.value);
    }
    return this.props.checked;
  }

```

**Comment by SevenOutman** [comment]
@Link-Kou `context.value` 的值由 `<CheckboxGroup>` 组件传递下来，其值为 `<CheckboxGroup>` 接收的 `value` 或 `defaultValue` props。在 `<CheckboxGroup>` 上有对这两个 props 的 [propTypes 定义](https://github.com/rsuite/rsuite/blob/v4/src/CheckboxGroup/CheckboxGroup.tsx#L21)和 [TypeScript 声明](https://github.com/rsuite/rsuite/blob/v4/src/CheckboxGroup/CheckboxGroup.d.ts#L16)，如果传入了非数组数据，在编译期和运行时都会有明确的错误信息指出传递的数据类型错误，指导开发者订正传入的数据。

**Comment by Link-Kou** [comment]
@SevenOutman  我建议是，加上Array.isArray 对此处理，让页面不因为数据原因发生奔溃。

**Comment by SevenOutman** [comment]
@Link-Kou 你所截图的地方所做的 undefined 判断，并不是在为*错误地传入了 undefined* 的情况做兼容，而是 CheckboxGroup 本身就预期当 value 为 undefined 时的行为。也就是说，对 CheckboxGroup 来说，value 就应当是数组或者 undefined。

而你所提议的判断 value 是否为数组就是另一回事了，是在兼容错误的 value。**我并不赞同花费库的代码量来为错误使用的开发者节省时间**。库会通过文档、propTypes 定义、TypeScript 声明等来说明应当如何使用，应当传入怎样的数据。而如果使用的方式是错误的，得到错误的结果是理所应当的。

例如，当我定义一个 prop，它的类型是对象，难道每当我从此对象上取字段时都还要判断它是否是一个对象吗

```ts
interface RouterProps {
  history: History;
}

function Router({ history }: RouterProps) {
  function forward() {
    // ❌ 兼容一下开发者硬塞一个不是 History 类型的情况吧，万一是个数字，调 .go() 不就要崩溃了嘛
    if (isHistory(history)) { 
      history.go(1);
    }
  }
  function back() {
    // ✅ 不需要，因为我已经声明了 history 的类型，不然我写 TypeScript 干嘛呢？
    history.go(-1);
  }

  return ...;
}
```

你所提到的情况，听起来像是服务端原本应该传回数组类型的数据，实际却传回了错误的类型。如果是这样的情况，应该让服务端纠正数据，或者由前端在调用接口后做一次判断和处理。这是业务层面的事，而非由库来代替你做的。
