### ISSUE TITLE
fix typo in form method name cleanErrorForFiled

### ISSUE THREAD

**Issue by iwan-uschka** [rsuite/rsuite#1235]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `16.13.1` |
| `rsuite` | `4.8.0` |

`cleanErrorForFiled` should be renamed into `cleanErrorForField`.

**Comment by iwan-uschka** [comment]
See https://github.com/rsuite/rsuite/pull/1236

**Comment by simonguo** [comment]
Thanks
