### ISSUE TITLE
TagPicker doesn't show tags

### ISSUE THREAD

**Issue by ar-terence-co** [rsuite/rsuite#1238]
On version 4.8.0, there is a bug where the tag picker doesn't show any of the options selected.

**Comment by simonguo** [comment]
Please reproduce your problem through [codesendbox](https://codesandbox.io/s/5vq6zo2z5l).

**Comment by fukktalent** [comment]
You can check it in doc. Demo with custom `renderValue` shows nothing in the input.
https://rsuitejs.com/components/tag-picker/

Reproduced problem:
https://codesandbox.io/s/wispy-water-vv0dh?file=/src/index.js

**Comment by simonguo** [comment]
@fukktalent  I figured out your question.

The custom tag does have a style problem. There are 2 solutions:

1. Use the tag rendering option provided by rsuite.
```tsx
return (
  <TagPicker
    renderValue={(values, items, tags) => {
      return values.map((tag, index) => (
        <Tag key={index}>
          <Icon icon="user" /> {tag}
        </Tag>
      ));
    }}
  />
);
```
2.Another solution is to add styles to tags.

```tsx
return (
  <TagPicker
    renderValue={(values, items, tags) => {
      return values.map((tag, index) => (
        <span className="custom-tag">
          <Icon icon="user" /> {tag}
        </span>
      ));
    }}
  />
);
```
```css
.custom-tag {
  position: relative;
  z-index: 6;
  margin: 0 4px;
  padding: 4px;
  border-radius: 4px;
  background: #f1f1f1;
}
```
