### ISSUE TITLE
Warning: Invalid DOM property `colspan`. Did you mean `colSpan`?  

### ISSUE THREAD

**Issue by anup-a** [rsuite/rsuite#1250]
```
<FlexboxGrid justify="center" className="full-width">
                    <FlexboxGrid.Item colspan={16}>
                        <Panel header={formheader} className="auth-card" shaded>
                            <AddQuestionForm {...props} />
                        </Panel>
                    </FlexboxGrid.Item>
                </FlexboxGrid>
```

I'm using colspan to fix grid size for containers, but I'm getting a warning in console --
```Warning: Invalid DOM property `colspan`. Did you mean `colSpan`?
    in div (created by FlexboxGrid)
    in FlexboxGrid (created by defaultProps(FlexboxGrid))
    in defaultProps(FlexboxGrid) (at questions.js:17)```

**Comment by simonguo** [comment]
Please reproduce your problem through [codesendbox](https://codesandbox.io/).

**Comment by anup-a** [comment]
Problem disappeared after app restart. It seems something was wrong from my side.
