### ISSUE TITLE
Is there a way to use Rsuite's scrollbar?

### ISSUE THREAD

**Issue by peguerosdc** [rsuite/rsuite#1252]
Hi!

I was wondering if there is a container, a class, something, to use Rsuite's scrollbar instead of the browser's default?

That is, in the following picture, I would like to have the scrollbar on the left (which I took from a `Table`) if I set `overflow: auto` (or something similar) in a `div` instead of having the default and ugly scrollbar that the browser provides (which is the one that appears on the right).

![scrollbar](https://user-images.githubusercontent.com/7889726/90838937-db3c3680-e31b-11ea-9000-0509f76b18b6.png)

If not, I think it would be a great addition for future versions! :smile: 

Thanks!

**Comment by simonguo** [comment]
The scroll bar of the table is a custom scroll bar to achieve `virtualized`. Rsuite does not provide such a container. I think you can modify the browser's default scroll bar style through CSS reset.

It is not excluded that rsuite will consider supporting this requirement in the future.

**Comment by peguerosdc** [comment]
@simonguo thanks for your reply! It would be awesome if this is ever possible.

For future reference in case someone ends up here, it is not possible to customise the scrollbar with CSS. Some styling is possible, but it's minimum and is browser dependent (i.e. see [here](https://www.w3schools.com/howto/howto_css_custom_scrollbar.asp) for webkit's reference).

A possible solution I found would be to use [malte-wessel/react-custom-scrollbars](https://github.com/malte-wessel/react-custom-scrollbars), but I haven't tried it (nor tested it with Rsuite).
