### ISSUE TITLE
Add bodyClass to Panel

### ISSUE THREAD

**Issue by marceloadsj** [rsuite/rsuite#1258]
### What problem does this feature solve?

I'm using Rsuite with Tailwindcss (collection of utility classes). In that case, I end writing the code below a bunch of times:

```
<Panel>
  <div className="flex items-center justify-between ...">
    // ...
  </div>
</ Panel>
```

Adding an extra div inside the panel, just to manage to add classes "on panel body".

### What does the proposed API look like?

```
<Panel bodyClass="flex items-center justify-between ...">
  // ...
</ Panel>
```

___

I'm able to send a PR if you accept that proposal!

**Comment by simonguo** [comment]
Fixed in  https://github.com/rsuite/rsuite/pull/3845. Please set the className of PanelBody through bodyProps.

```
<Panel bodyProps={{ className: 'custom-class' }}></Panel>
```
