### ISSUE TITLE
icon 不能使用svg

### ISSUE THREAD

**Issue by doudouaixiaoyu** [rsuite/rsuite#1259]
我在代码里导入`import IconLogo from '../../logo.svg;`,并使用`<Icon icon={IconLogo} />`
但是Icon 不显示出来，我配置了webpack.config.js:
```
module.exports = {
  module: {
    rules: [
      {
        test: /\.svg$/,
        use: [{
          loader: 'svg-sprite-loader',
          options: {
            symbolId: 'icon-[name]'
          }
        }]
      }
    ]
  }
}
```
但是icon仍然不出来

**Comment by simonguo** [comment]
svg 的元素被渲染出来了没？ 
控制台有报错吗？

**Comment by doudouaixiaoyu** [comment]
等等，这个问题先放着一下，我新遇到一个问题，就是form 表单的问题，我用hooks 模式，调不出来他的check() 方法，
`let nameRef = useRef(Form);`
然后给form 绑定 ref={nameRef} , nameRef.current 里没有check(),请问应该怎么调？

**Comment by doudouaixiaoyu** [comment]
@simonguo 上述表单的问题解决了，原因是我对react 的语法还不是很熟悉，现在好多了，但是我在搭建
```
<Container>
      <Sidebar>Sidebar</Sidebar>
      <Container>
        <Header>Header</Header>
        <Content>Content</Content>
        <Footer>Footer</Footer>
      </Container>
    </Container>
```
布局是，我在Header 里放置了一个Dropdown。问题是当展开Dropdown的时候，被底下的`<Content>Content</Content>` 遮住了，Dropdown 的展开项已经是相对定位了,为什么还会出现被遮住的问题？求教

**Comment by doudouaixiaoyu** [comment]
![`($75VKFDM$)7E QE5TV4TS](https://user-images.githubusercontent.com/39321867/92098937-764d0a00-ee0c-11ea-862a-99e4c3a407e2.png)

**Comment by doudouaixiaoyu** [comment]
这应该是被渲染出来了，但是在界面上仍然不显示，控制台也没有报错
![QQ图片20200907094906](https://user-images.githubusercontent.com/39321867/92341168-72143b80-f0ef-11ea-915e-9b89cc8a40d2.png)

**Comment by simonguo** [comment]
你的 svg 文件并没有被 svg-sprite-loader 解析，而是被 url-loader 解析了。 成功解析后的 svg 应该是以下 DOM 结构
![image](https://user-images.githubusercontent.com/1203827/92342003-1ac39a80-f0f2-11ea-94d0-79aec835d57b.png)

**Comment by doudouaixiaoyu** [comment]
那这是怎么回事？难道是webpack.config.js 配置文件没有加载？我在webpack.config.js 里配置的
```
      {
        test: /\.svg$/,
        use: [{
          loader: 'svg-sprite-loader',
          options: {
            symbolId: 'icon-[name]'
          }
        }]
      },
```

**Comment by doudouaixiaoyu** [comment]
@simonguo Icon 解决了，原因是svg-sprite-loader的配置地方错了，现在可以加载出来了,还有个问题，现在可以加载网络上的图标吗？

**Comment by simonguo** [comment]
rsuite v5 对 Icon 有改进。 全部改为 svg icon
https://next.rsuitejs.com/components/icon/

```
npm i rsuite@next
```
