### ISSUE TITLE
是否可以增加typescript支持

### ISSUE THREAD

**Issue by zpbc007** [rsuite/rsuite#126]

**Comment by simonguo** [comment]
我们用 Flow 做的静态类型检查，目前还没有计划支持 Typescript , 不排除将来我们会列入到计划中,具体还要看需求。

**Comment by simonguo** [comment]
@zpbc007  当前 3.4.1 版本开始支持 typescript

**Comment by zpbc007** [comment]
好的呢，非常感谢。
