### ISSUE TITLE
Error on cd docs > npm install > npm dev

### ISSUE THREAD

**Issue by pabloiea1995** [rsuite/rsuite#1263]
I was following the steps to collaborate and when I executed the command "npm run dev" inside docs directory, I got this error. I havent changed anything, just cloned the repo and followed the guide.
![image](https://user-images.githubusercontent.com/56727129/91565664-de9a7800-e942-11ea-8cd7-dfdd900094f5.png)

**Comment by simonguo** [comment]
There are multiple versions of react, you can try to execute in the docs directory:

```
rm -R node_modules/react
rm -R node_modules/react-dom
```

The `next` branch is currently not stable and is still under development.
