### ISSUE TITLE
Datepicker translations

### ISSUE THREAD

**Issue by kamranata** [rsuite/rsuite#1272]
### Hi! How we can translate month title? I used internationalization, but didn't find anything about months.

**Comment by simonguo** [comment]
The month title of DatePicker is configured through the [`formattedDayPattern`](https://github.com/rsuite/rsuite/blob/master/src/IntlProvider/locales/default.ts#L20) field in locales, and the default value is `DD MMM YYYY`.

The formatting rules default to English, if you need to change it, you can pass a `formatDate` through date-fns.

https://github.com/rsuite/rsuite/blob/master/docs/pages/guide/intl/en-US/index.md#format-date
