### ISSUE TITLE
Disabled button redirects to href address

### ISSUE THREAD

**Issue by Slaiby** [rsuite/rsuite#1273]
### Versions

| package  | version |
| `react`  | `^16.8.6` |
| `rsuite` | `^4.8.0` |

### What is the expected behavior?
Clicking on the a disabled button should not redirect to the href address
``` <Button appearance="default" disabled href='google.com'>I'm an rsuite Button</Button>```

### What is the current behavior?
Clicking on the disabled button will redirect to the href address
 ```<Button appearance="default" disabled href='google.com'>I'm an rsuite Button</Button>```

### What are the steps to reproduce?
![rsz_1screenshot_from_2020-09-07_16-26-06](https://user-images.githubusercontent.com/35534517/92392649-401ecb80-f127-11ea-8490-59328e577a35.png)
Place the href address string as props simultaniously with the disabled prop
```https://codesandbox.io/s/loving-galileo-q8b6m```

**Comment by simonguo** [comment]
It has been fixed in `rsuite@4.8.2`.
