### ISSUE TITLE
not work with vite react template

### ISSUE THREAD

**Issue by undoZen** [rsuite/rsuite#1274]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `16.13.1` |
| `rsuite` | `4.8.1` |

### What is the expected behavior?
无法在 vite 环境中方便地引入 rsuite

### What are the steps to reproduce?

see https://github.com/undoZen/vite-rsuite-demo

**Comment by simonguo** [comment]
已修复， rsuite 升级到 `4.8.2`
