### ISSUE TITLE
Add row hover callback

### ISSUE THREAD

**Issue by Babettestam** [rsuite/rsuite#1276]
### What problem does this feature solve?

It would be nice to have a `onRowHover` function added, so we can catch an hover effect just like the `onRowClick`. 

### What does the proposed API look like?

The `onRowHover` would be added to the Table properties. It would give back the `rowData` and the `event`.

**Comment by simonguo** [comment]
You can achieve the features you want by encapsulating the Cell. 
https://github.com/rsuite/rsuite/issues/1759
