### ISSUE TITLE
GATSBY build success but no Cell.

### ISSUE THREAD

**Issue by Huihuawk** [rsuite/rsuite#1278]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `latest` |
| `rsuite` | `latest` |

![image](https://user-images.githubusercontent.com/24917797/92705059-fed82700-f385-11ea-9c2d-19cb720a4cc5.png)

**Comment by simonguo** [comment]
It has been fixed: https://github.com/rsuite/rsuite-table/pull/175
https://github.com/rsuite/rsuite-table/issues/160
