### ISSUE TITLE
Table and verticalAlign="middle"

### ISSUE THREAD

**Issue by PartyZan4Life** [rsuite/rsuite#1288]
"rsuite": "^4.8.1"
"react": "^16.13.1",

https://codesandbox.io/s/bold-sound-yyk3b?file=/src/index.js

Line 42. Just erase verticalAlign="middle" and Selectpicker with long placeholder become normal.

I realy do not understand why wrapers don't take 100% of height and I can not control valign by my-self.

**Comment by simonguo** [comment]
`block` can make the component full.
```tsx
<SelectPicker block />
```

**Comment by PartyZan4Life** [comment]
https://codesandbox.io/s/blue-smoke-viibb?file=/src/index.js

It does not help.
