### ISSUE TITLE
scroll loading data scrollbar position error

### ISSUE THREAD

**Issue by LuHaikun** [rsuite/rsuite#1292]
This issue has been fixed, fixed version: v3.5.6

```
npm i rsuite-table@latest
```
Example:
https://codesandbox.io/s/rsuite-table-scroll-demo-f7ijm

_Originally posted by @simonguo in https://github.com/rsuite/rsuite/issues/510#issuecomment-520702596_

**Comment by LuHaikun** [comment]
新版本又出现该问题

**Comment by LuHaikun** [comment]
试了下只有3.5.6一个版本可以支持

**Comment by simonguo** [comment]
rsuite-table@3.5.6 之前的版本中通过自动判断 data 的变化来更新滚动条的位置，但业务场景太复杂，在 tree、expandable、editable 等场景的处理都不一样，所以在最新的版本中把滚动条是否更新位置交给应用开发者。  新增了一个  `shouldUpdateScroll` 属性，默认为 `true`，会在data 更新后滚动条重置到初始位置。 如果你不需要重置滚动条把它设置为 `false` 
```tsx
<Table shouldUpdateScroll={false} >
```

https://github.com/rsuite/rsuite/issues/1041#issuecomment-625748667
