### ISSUE TITLE
Type of Pickers is not correct

### ISSUE THREAD

**Issue by ziofat** [rsuite/rsuite#1294]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `16.12.0` |
| `rsuite` | `4.8.1` |

### What is the expected behavior?
In SelectPicker, renderMenuItem provides data item as its second argument, both the value and the type.

### What is the current behavior?
In SelectPicker, renderMenuItem request a function with `(label, item: ItemDataType) => JSX.Element` as type. The item is actually the data itself on runtime but in IDE it provides other properties, which cause IDE complain the type is not a match.

### What are the steps to reproduce?
![image](https://user-images.githubusercontent.com/8521174/93511416-5e6d9e00-f955-11ea-81ae-6f2763d327a2.png)
![image](https://user-images.githubusercontent.com/8521174/93511439-6a596000-f955-11ea-8fd6-73e04979a891.png)
![image](https://user-images.githubusercontent.com/8521174/93511484-7c3b0300-f955-11ea-86b0-504701fa844b.png)
But I tried to print the `item` to console:
![image](https://user-images.githubusercontent.com/8521174/93511611-ad1b3800-f955-11ea-9bf8-bc77b4e315a8.png)

I am sorry I won't fork the codesandbox to reproduce because it is a type issue.

**Comment by simonguo** [comment]
You can define an `ItemType` to extends `ItemDataType`
```tsx
import { ItemDataType } from 'rsuite/lib/@types/common';
interface ItemType extends ItemDataType {
  quality?: number;
}
```

```tsx
 <SelectPicker
  data={data}
  renderMenuItem={(label, item: ItemType) => {
    return (
      <div>
        <b>{label} </b> {item.quality}
      </div>
    );
  }}
/>
```

**Comment by ziofat** [comment]
You can eliminate the error with this, but I don't think it is a correct solution. In runtime the `item` is not an `ItemDataType`. As you can see in my last screenshot, the `item` has only three properties which I defined in the dataset, it is not a subtype of  `ItemDataType` which has `label` and `value` as required properties.

**Comment by simonguo** [comment]
The solution I currently think of is to add an any attribute to `ItemDataType`. But this can only avoid errors, but can not assist editor code prompts.
```ts
interface ItemDataType {
  label: any;
  value: any;
  [key: string]: any;
}
```

**Comment by ziofat** [comment]
Maybe generics?

```tsx
interface MyDataItem {
    quality: number;
}

<SelectPicker<MyDataItem>
    data={data as MyDataItem[]}
    renderMenuItem={(label, item: MyDataItem) => {
        return <div>
            <b>{label} </b> {item.quality}
        </div>;
    }}
/>
```

And I suppose it is possible to infer the generics type from `data` prop.

**Comment by ziofat** [comment]
BTW, there is no `label` and 'value` passed from the renderMenuItem callback. If this is not intentional, then the item type should be like `MyDataItem & ItemDataType`
