### ISSUE TITLE
HeaderCell className

### ISSUE THREAD

**Issue by PartyZan4Life** [rsuite/rsuite#1299]
HeaderCell className sets to zero-height html object, that's why you can not control styles with the help of "class" attribute of html object.

But "style" attribute on HeaderCell component works fine... Why?

And I guess this problem touches not only HeaderCell component, but other components too because I have already met this problem earlier.

**Comment by PartyZan4Life** [comment]
Hmmm... As I understand classes don't make effects only for "background-color" css in the table? It is bad too...

**Comment by simonguo** [comment]
You can hide the header by `showHeader={false}`
```html
<Table showHeader={false}>
```

In addition, what function do you want to achieve with `className` ?
