### ISSUE TITLE
affixHorizontalScrollbar not working

### ISSUE THREAD

**Issue by veasnabig** [rsuite/rsuite#1306]
Hello everyone, I tried to use affixHorizontalScrollbar in table, but it's not working with horizontal scrollbar. It doesn't show scrollbar. I already follow the example code it still doesn't working. Any help for this part or I lost some config with packages, please show me. Thank you.

**Comment by simonguo** [comment]
Please reproduce your problem through [codesendbox](https://codesandbox.io/).
