### ISSUE TITLE
TypeError (0 , $csb__utils.defaultClassPrefix) is not a function

### ISSUE THREAD

**Issue by mohanrajDev** [rsuite/rsuite#1311]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `16.13.1` |
| `rsuite` | `4.8.2` |

Unable to open 'ColumnGroup.js': File not found (file:///sandbox/node_modules/rsuite-table/es/ColumnGroup.js).
https://codesandbox.io/s/solitary-night-x4ynm?file=/src/index.js

**Comment by simonguo** [comment]
Similar issues https://github.com/rsuite/rsuite/issues/1312.  already fixed.
