### ISSUE TITLE
Button text on Uploader

### ISSUE THREAD

**Issue by pabloiea1995** [rsuite/rsuite#1313]
Is there any way to change displayed text on the Uploader button? I can see that the text "Upload" is shown by default, but I can't find a way to change it.

Thank you

**Comment by simonguo** [comment]
Uploader's children can customize the displayed text.
```tsx
<Uploader>
  <Button>Upload image</Button>
</Uploader>
```

**Comment by pabloiea1995** [comment]
Thank you!
