### ISSUE TITLE
InputGroup.Addon have wrong height if size is large for inside mode

### ISSUE THREAD

**Issue by ziofat** [rsuite/rsuite#1314]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `16.8.6` |
| `rsuite` | `4.8.3` |

### What is the expected behavior?
Addon size and input padding are correct

### What is the current behavior?
Addon size and input padding are incorrect

![image](https://user-images.githubusercontent.com/8521174/95686604-702f2200-0c31-11eb-9c5e-48d312cc1df8.png)
![image](https://user-images.githubusercontent.com/8521174/95686645-be442580-0c31-11eb-83d3-e2a3eb5743f2.png)
![image](https://user-images.githubusercontent.com/8521174/95686608-7f15d480-0c31-11eb-801f-efa3c8b8672e.png)

### What are the steps to reproduce?

Please see this codesandbox:

https://codesandbox.io/s/bold-mestorf-ze7dh

**Comment by CH0213** [comment]
Can I take this issue? I want to fix this bug.

**Comment by simonguo** [comment]
@CH0213 of course. If you want to solve this issue, please fix it on the v4 branch

**Comment by CH0213** [comment]
Let me fix this bug!
