### ISSUE TITLE
关于日历月份更改的外部动态控制方式

### ISSUE THREAD

**Issue by sharks-wang** [rsuite/rsuite#1315]
### What problem does this feature solve?

在控制一个日历的月份更改时，需要更改两个日历的月份。例如：左侧小日历更改月份，右侧大日历月份同样更改。此时就需要能控制日历的月份属性。
### What does the proposed API look like?
能够在外部控制日历的显示月份，不是单一的通过默认的按钮。

**Comment by simonguo** [comment]
你可以通过设置 value 属性，让 Calendar 显示到指定的月份（受控）。
```tsx
 <Calendar value={new Date('2020-12-01')} />
```

**Comment by sharks-wang** [comment]
> 您可以通过设置值属性，让日历显示到指定的月份（预期）。
> 
> ```tsx
>  <日历 值= {新 日期（'2020-12-01' ）} / >
> ```

已解决  谢谢
