### ISSUE TITLE
process.env.RUN_ENV - process is not defined error after upgrading to webpack 5.1.0

### ISSUE THREAD

**Issue by nimrod-cohen** [rsuite/rsuite#1317]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `16.13.1` |
| `rsuite` | `4.8.4` |

### What is the expected behavior?
Screen rendering should work normally

### What is the current behavior?
blank screen, and console error complains about:
Uncaught ReferenceError: process is not defined
    at defaultProps.js:24
    at Module../node_modules/rsuite/es/Grid/Grid.js (Grid.js:47)
    at __webpack_require__ (bootstrap:21)
    at fn (hot module replacement:60)
    at Module../node_modules/rsuite/es/Grid/index.js (main-bundle.js:177984)
    at __webpack_require__ (bootstrap:21)
    at fn (hot module replacement:60)
    at Module../src/client/components/pages/Login.js (main-bundle.js:6705)
    at __webpack_require__ (bootstrap:21)
    at fn (hot module replacement:60)

line of code is:
if (process.env.RUN_ENV === 'test') {

### What are the steps to reproduce?
i'm using webpack 5.1.0, this didn't happen before, I'm what else is required to reproduce this, over the information I gave you.

I was able to circumvent it by adding an import to a file before I import rsuitejs, and added this line of code:
//DIRTY HACK
if (!window.process) window.process = { env :{ RUN_ENV: 'production'}}

**Comment by X-neuron** [comment]
webpack配置的问题吧  不是resuite的issue

**Comment by nimrod-cohen** [comment]
> webpack配置的问题吧 不是resuite的issue

You are correct, I have found how to define it in webpack. If anyone else experiences this - here's a possible solution:
in webpack config file:
`
const webpack = require('webpack')
const dotenv = require('dotenv')

module.exports = {
...
  plugins: [
  ...
      new webpack.DefinePlugin({
      'process.env': JSON.stringify(dotenv.config().parsed) // it will automatically pick up key values from .env file
    })
  ]
}
`
