### ISSUE TITLE
Guide is not working with the latest version of Next.JS

### ISSUE THREAD

**Issue by matepaiva** [rsuite/rsuite#1320]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `16.14.0` |
| `rsuite` | `^4.8.4` |
| `next` | `9.5.5` |

### What is the expected behavior?

As it says in the guide:

```
Open the browser and visit http://localhost:3000/, you can see the application of React Suite page, and then start your development journey.
```

### What is the current behavior?

Error:
```
error - ./styles/globals.css 2:5
Module parse failed: Unexpected token (2:5)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| html,
> body {
|   padding: 0;
|   margin: 0;
```

### What are the steps to reproduce?

Reproducing this issue is very easy. You have to follow the guide. After the last step (`"edit the ./pages/index.js file"`), it crashes.

**Comment by matepaiva** [comment]
Just wrapping the `withLess` config generator with `@zeit/next-css` config generator fixed the issue.

I think the guide should be updated as follow:

```
const withCss = require('@zeit/next-css')
const withLess = require('@zeit/next-less')

module.exports = withCss({
  cssModules: true,
  ...withLess({
    lessLoaderOptions: {
      javascriptEnabled: true,
    },
  })
})
```

**Comment by simonguo** [comment]
https://github.com/rsuite/rsuite/tree/next/examples/with-nextjs
Hope this example can help you.
If you have suggestions for improvement, you can send us a PR.

**Comment by inyourdrimz** [comment]
not working w/ latest nextjs version 10.0.2 w/ webpack 5, typescript and scss config.

`
module.exports = withPlugin([ withSass, withLess, {
 cssModules: true,
 lessLoaderOptions: {
    javascriptEnabled: true,
  },
} ]),
`

i'm getting an error:
`
error - ./styles/globals.scss.
Uncaught TypeError: Cannot read property 'push' of undefined.
`

**Comment by tetrex** [comment]
its still not working 
im getting

TypeError: Cannot set property 'styles' of undefined

i followed the rsuite nextjs guide step by step

**Comment by ndom91** [comment]
Apparently `rsuite` does not support next.js 10 or 11.

I'm assuming this is a combination of next.js moving to webpack5 as default and also not maintaining their `with-less` library anymore - probably not much rsuite can do here other than migrate away from less to sass or "native css" somehow :shrug:.

Unfortunately this is a major dealbreaker for me, I guess I'll be migrating away from rsuite then :(

**Comment by simonguo** [comment]
We will solve this problem in [rsuite v5](https://next.rsuitejs.com/). 

I found that the community has a plug-in next-with-less, which may solve your problem temporarily.
https://github.com/elado/next-with-less

Regarding the support for less in next.js, you can follow this PR.
https://github.com/vercel/next.js/pull/23185

**Comment by simonguo** [comment]
The current solution is to compile less in the webpack custom configuration through less-loader.

The instructions for use and the next.js example have been updated
https://github.com/rsuite/rsuite/blob/v4/docs/pages/guide/use-next-app/en-US/index.md
https://github.com/rsuite/rsuite/blob/v4/examples/with-nextjs/next.config.js
