### ISSUE TITLE
Question | Table row color

### ISSUE THREAD

**Issue by zakokor** [rsuite/rsuite#1329]
Is it possible to assign a color to the whole row according to the value of a cell in the table?

**Comment by simonguo** [comment]
```tsx
<Table 
  rowClassName={(rowData)=>{
     // Check rowData and return a custom className
     return 'custom-row'  
  } 
/>
```

**Comment by zakokor** [comment]
Thank you Simon. I'm loading 2 rows and this record is printing undefined. Any suggestions? Thanks

rowClassName={(rowData: { is_read: boolean }) => (
          console.log('rowClassName', rowData ? rowData.is_read : typeof rowData),
          rowData && !rowData.is_read ? 'rs-table-row-new' : ''
        )}

**Comment by simonguo** [comment]
Use [`optional chaining`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) to make the code more streamlined.
```ts
rowClassName={(rowData) => {
  return rowData?.isRead ? "rs-table-row-new" : "";
}}
```
