### ISSUE TITLE
SelectPicker's search doesn't work on Material UI dialog

### ISSUE THREAD

**Issue by atreya-yelishetti** [rsuite/rsuite#1346]
### Versions
<!-- 
Please tell our you using react version and rsuite version.

"react": "^16.13.0",
"rsuite": "^4.7.0",

### What is the expected behavior? 
Selectpicker's search should work when used on material ui dialog

### What is the current behavior?

The Selectpicker's search input field  is not workins when used it on material ui Dialog 

### What are the steps to reproduce?
![image](https://user-images.githubusercontent.com/49288643/98742996-f9429180-2374-11eb-9283-aa30ba12350d.png)

**Comment by atreya-yelishetti** [comment]
![image](https://user-images.githubusercontent.com/49288643/98743093-1d05d780-2375-11eb-945d-0b41e127c5d2.png)

**Comment by atreya-yelishetti** [comment]
the search box is not working when used on material ui dialog

**Comment by simonguo** [comment]
Please reproduce your problem through [codesandbox](https://codesandbox.io/s/5vq6zo2z5l).

**Comment by atreya-yelishetti** [comment]
https://codesandbox.io/s/jolly-architecture-u0nrn?file=/src/index.js

**Comment by atreya-yelishetti** [comment]
> Please reproduce your problem through [codesandbox](https://codesandbox.io/s/5vq6zo2z5l).
Hi,
Here is the link to the sandbox to reproduce the problem.

https://codesandbox.io/s/jolly-architecture-u0nrn?file=/src/index.js

**Comment by atreya-yelishetti** [comment]
![image](https://user-images.githubusercontent.com/49288643/98827681-c17f2c80-23fc-11eb-8c43-f8a281ed34c5.png)

**Comment by simonguo** [comment]
@atreya-yelishetti 
material-ui is for the sake of accessibility. Let Dialog force the focus.
You can disable it through the `disableEnforceFocus` property of Dialog.

```tsx
<Dialog disableEnforceFocus />
```

https://material-ui.com/api/modal/#props

**Comment by atreya-yelishetti** [comment]
That fix the problem. Thanks Alot @simonguo
