### ISSUE TITLE
关于日程时间渲染

### ISSUE THREAD

**Issue by sharks-wang** [rsuite/rsuite#1355]
### What problem does this feature solve?

需要从接口获取日程数据，但发现rendercell方法好像是不支持异步操作的，一旦在rendercell中调用借口就会报错
### What does the proposed API look like?

renderCell(date) {
        let cellHeight = 0; // cells容器的大小
        let cellNum = 2; //  cells容器里面cell的最大数量 最大默认为2个
        try {
            let height = this.refs.monthSchedule.clientHeight;
            cellHeight = parseInt((height - 30) / 7) - 20;
            cellNum =
                parseInt(cellHeight / 20) - 1 < 2 ||
                parseInt(cellHeight / 20) - 1 < 0
                    ? 2
                    : parseInt(cellHeight / 20) - 1;
        } catch (err) {}

        let list = [];
        getCalendarList({ targetDate: moment(date).format("YYYY-MM-DD") })
            .then((res) => {
                list.push({
                    id: 16,
                    title: "dwdwqdqw",
                    startDate: "2020-11-17 16:00:00",
                    endDate: "2020-11-17 17:00:00",
                    color: "blue",
                    remind: "",
                    meetingRoom: null,
                    repeat: "",
                    description: null,
                    createTime: "2020-11-17 11:06:14",
                    createBy: "1004",
                    createName: "卢子骐",
                    users: "1004,1007",
                    calendarRemindTimeVO: null,
                    startTime: 1605600000000,
                    endTime: 1605603600000,
                });
            })
            .catch((err) => {
                console.log(err);
               
            });
        console.log("哈哈", list);
        if (list.length > 0) {
            const displayList = list.filter((item, index) => index < cellNum);
        }

        if (list.length > 0) {
            const moreCount = list.length - cellNum;

            /* console.log(list);
            console.log(cellNum);
            console.log("剩余的项数:", moreCount); */

            return list.length > cellNum ? (
                <ul className={scheduleClass.calendarTodoList}>
                    {" "}
                    {list.map((item, index) => {
                        return index < cellNum ? (
                            <li
                                className={`${
                                    this.state.activeLi === item.id
                                        ? scheduleClass.activeLi
                                        : ""
                                }`}
                                onClick={(ev) =>
                                    this.showCalendarCard(item, ev)
                                }
                            >
                                <div
                                    className={scheduleClass.itemBlock}
                                    style={{ backgroundColor: item.color }}
                                ></div>{" "}
                                {item.title}{" "}
                            </li>
                        ) : (
                            ""
                        );
                    })}
                    <li
                        className={scheduleClass.moreItem}
                        onClick={(ev) => this.getMoreCard(list, date, ev)}
                    >
                        还有 {moreCount}项{" "}
                    </li>{" "}
                </ul>
            ) : (
                <ul className={scheduleClass.calendarTodoList}>
                    {" "}
                    {displayList.map((item, index) => (
                        <li
                            key={item.id}
                            className={`${
                                this.state.activeLi === item.id
                                    ? scheduleClass.activeLi
                                    : ""
                            }`}
                            onClick={(ev) => this.showCalendarCard(item, ev)}
                        >
                            <div
                                className={scheduleClass.itemBlock}
                                style={{ backgroundColor: item.color }}
                            ></div>{" "}
                            {item.title}{" "}
                        </li>
                    ))}{" "}
                </ul>
            );
        }

        return null;
    }
这样是给不进去list值的    打印出来为空

**Comment by simonguo** [comment]
你可以通过 [codesandbox](https://codesandbox.io/s/5vq6zo2z5l)复现一下问题吗？
