### ISSUE TITLE
Modal with overflow={true} jumping

### ISSUE THREAD

**Issue by eDubrovsky** [rsuite/rsuite#1361]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `16.8.6` |
| `rsuite` | `4.8.3` |

### What is the current behavior?
Bottom part of `Modal` with overflow={true} jumping and change size on open.

### What are the steps to reproduce?
Check CodeSandbox - https://codesandbox.io/s/patient-currying-h8w17?file=/src/index.js
And check this video - https://cln.sh/osKAjI

**Comment by junghyeonsu** [comment]
can i take this issue?
