### ISSUE TITLE
Table "wordWrap" feature error

### ISSUE THREAD

**Issue by StrangersSoftware** [rsuite/rsuite#1371]
### Versions
| package  | version |
| -------- | ------- |
| `react`  | `16.14.0` |
| `rsuite` | `4.8.5` |

Table "wordWrap" feature stretches height of all rows to maximun instead of setting individual height according to the data, as it can be seen on Rsuite website example. 
![2](https://user-images.githubusercontent.com/15338501/101070216-b8205480-35a3-11eb-87d5-e1f24be08f64.jpg)
Cell data is formed in following way:
`<Cell style={{padding:5, paddingLeft:5}} className={classes.Cell}>
                          {
                            rowData => 
                            {return 
                                  <>
                                      <p>{rowData.fullDate.toLocaleString('ua', {year: '2-digit'})}</p>
                                      <NavLink to={'/owner/room/' + rowData.idRoom}>{rowData.address}</NavLink>
                                      <p>{rowData.officeName}</p>
                                      <p style={{marginTop:0}}>{rowData.name}</p>
                                   </>}
                          }
</Cell>`

**Comment by simonguo** [comment]
Please reproduce your problem through [codesandbox](https://codesandbox.io/s/5vq6zo2z5l).

**Comment by StrangersSoftware** [comment]
Looks like I mistaked. Sorry
