### ISSUE TITLE
Table 组件希望暴露出更多的自定义属性

### ISSUE THREAD

**Issue by zjcwill** [rsuite/rsuite#1409]
1. onRowDoubleClick  ，row有双击的需求且组件没有暴露这个属性
2. 希望树状结构表格可以指定children的名称，比如children 不叫children叫别的值还需要手动转换再传进去不是很友好

**Comment by simonguo** [comment]
在 rsuite v5 中可以通过自定义封装 Cell 实现。 
类型问题:  https://github.com/rsuite/rsuite/issues/1759
