### ISSUE TITLE
Error with less ^4.0.0

### ISSUE THREAD

**Issue by eDubrovsky** [rsuite/rsuite#1415]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `17.0.1` |
| `rsuite` | `4.8.6` |

### What is the current behavior?
After update less `less ^3.12.2  →    ^4.0.0 ` I get the error:

```
./src/themes/light.less (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-0-1!./node_modules/less-loader/dist/cjs.js??ref--5-oneOf-0-2!./src/themes/light.less)

    &-x::before {
      .icon-font;
              ^
Unrecognized input. Possibly missing '(' in mixin call.
      Error in /Users/***/node_modules/rsuite/lib/Alert/styles/common.less (line 84, column 16)
```

I found this topic with the same error - https://discuss.write.as/t/less-compiler-css/2235

**Comment by eDubrovsky** [comment]
Sorry, it's less 4 issues: https://github.com/ant-design/ant-design/issues/28427

**Comment by MSharifi78** [comment]
Hi, does anyone know when the fixes PR get released?

**Comment by simonguo** [comment]
@MSharifi78 
In rsuite@5.0.0-alpha.2, it has been updated to less 4.  https://next.rsuitejs.com/
We will fix the rsuite v4 version as soon as possible.

**Comment by SevenOutman** [comment]
> I imported import "rsuite/dist/rsuite-rtl.min.css" and have the same problem. `rsuite` `5.33.1`

Hi @EleRam, could you provide the code snippet where you import the CSS file, the error message you got, and the configuration of your build system (webpack, Vite, etc.)?
