### ISSUE TITLE
Table的 Affix Horizontal Scrollbar 示例中底部有一段空白，要怎么去掉呢

### ISSUE THREAD

**Issue by zhangguimei** [rsuite/rsuite#1431]
Table的 Affix Horizontal Scrollbar 示例中底部有一段空白，要怎么去掉呢

![image](https://user-images.githubusercontent.com/18433241/103400539-74a80e80-4b80-11eb-8859-35eb4201e76a.png)

**Comment by simonguo** [comment]
重复的问题: https://github.com/rsuite/rsuite/issues/1436
