### ISSUE TITLE
当Table组件 affixHeader 时，底部有一段留白，怎么去掉呢

### ISSUE THREAD

**Issue by zhangguimei** [rsuite/rsuite#1436]
当Table组件 affixHeader 时，底部有一段留白，怎么去掉呢

![image](https://user-images.githubusercontent.com/18433241/103725495-ace09e80-5011-11eb-97e4-0f794db8d9ef.png)

**Comment by simonguo** [comment]
这应该是一个 bug ，多算了 table header 的高度。 近期我们会修复掉

**Comment by zhangguimei** [comment]
> 这应该是一个 bug ，多算了 table header 的高度。 近期我们会修复掉

安装了rsuite-table的3.14.2版本，横向滚动条会遮盖最后一行，可以设置不遮盖吗
