### ISSUE TITLE
Nav.Item loose style when used with componentClass

### ISSUE THREAD

**Issue by juanmarti81** [rsuite/rsuite#1442]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | 17.0.1` |
| `rsuite` | `4.8.0` |

### What is the expected behavior?
when using Nav.Item with react-router it should maintain the style when using the example provided in the docs.

### What is the current behavior?
It looses the the style of Nav-Item. I tried adding a classPrefix in every part but still not working

### What are the steps to reproduce?
`
```
const MyLink = React.forwardRef((props, ref) => {
      const { href, as, ...rest } = props;
      return (
        <Link to={href} as={as} >
          <a ref={ref} {...rest} />
        </Link>
      );
    });

<Nav.Item eventKey="1" icon={<Icon icon="dashboard" />} href="/" componentClass={MyLink}>
    Dashboard
</Nav.Item>
```
`

Link to sandbox:
https://codesandbox.io/s/upbeat-yonath-fuok5

### Any additional comments? (optional)
The code in docs should be

`<Link **_to_**={href} as={as} classPrefix="nav-item">`

**Comment by simonguo** [comment]
Your code uses the `next/link` example, which is somewhat different from `react-router`.

## next/link 

```jsx
import Link from 'next/link';

const NavLink = React.forwardRef(({ href, as, ...rest }, ref) => (
  <Link href={href} as={as}>
    <a ref={ref} {...rest} />
  </Link>
));

return (
  <Nav.Item as={NavLink} href="/">
    Home
  </Nav.Item>
);
```
## react-router-dom

```jsx
import { Link } from 'react-router-dom';

const NavLink = React.forwardRef(({ href, children, ...rest }, ref) => (
  <Link ref={ref} to={href} {...rest}>
    {children}
  </Link>
));

return (
  <Nav.Item as={NavLink} href="/">
    Home
  </Nav.Item>
);
```

**Comment by juanmarti81** [comment]
Thanks Simon. The styles are back  but now it presents a new issue. 

The page is reloading instead re-rendering the components. I updated the sandbox for you to check. Thanks.

**Comment by simonguo** [comment]
- If you are using rsuite v4, you should still use the `componentClass` prop.

```diff
import { Link } from 'react-router-dom';

const NavLink = React.forwardRef(({ href, children, ...rest }, ref) => (
  <Link ref={ref} to={href} {...rest}>
    {children}
  </Link>
));

return (
- <Nav.Item as={NavLink} href="/">
+ <Nav.Item componentClass={NavLink} href="/">
     Home
   </Nav.Item>
);
```
- The definition of your NavLink should not be placed in the render of the `App`.

**Comment by juanmarti81** [comment]
Brilliant! It's working perfectly. Great job here. Thanks
