### ISSUE TITLE
Table 组件，最后一列fixed时，横向滚动条滚动到最右侧有个margin-left，导致单元格间距不一致

### ISSUE THREAD

**Issue by zhangguimei** [rsuite/rsuite#1443]
Table 组件，最后一列fixed时，横向滚动条滚动到最右侧有个margin-left，导致单元格间距不一致

**Comment by simonguo** [comment]
请 fork 这个例子，复现你的问题。
https://codesandbox.io/s/5vq6zo2z5l

**Comment by zhangguimei** [comment]
官网的fixed Column的例子，加上bordered、cellBordered可以看出来。最后一列fixed时，悬浮跟未悬浮时，左右间距不一致。

**Comment by simonguo** [comment]
在 rsuite@4.8.9 版本中已修复。
