### ISSUE TITLE
Less compile error using rsuite v4.8 with nextjs v10

### ISSUE THREAD

**Issue by MikeSchaatsbergen** [rsuite/rsuite#1445]
### Versions

| package  | version |
| -------- | ------- |
| `next` | `10.0.4` |
| `typescript` | `^4.1.3` |
| `react`  | `17.0.1` |
| `rsuite` | `^4.8.6` |
| `@zeit/next-less` | `^1.0.1` |
| `less` | `^4.0.0` |

### What is the expected behavior?
It compiles.

### What is the current behavior?
I created a new fresh nextjs app with rsuite according to the guide on rsuitejs.com
Currently whenever I run `yarn dev` It will fail to compile with the following error.

<img width="819" alt="Screenshot 2021-01-07 at 11 51 10 AM" src="https://user-images.githubusercontent.com/41439661/103884354-be43ac80-50de-11eb-9255-92ccb0581ef9.png">

### What are the steps to reproduce?
Follow the steps given on rsuitejs.com by creating a new nextjs app, adding @zeit/next-less, configuring the `next.config.js`, installing rsuite and then importing the `index.less`.

```js
// next.config.js
const withLess = require('@zeit/next-less');
module.exports = withLess({
  lessLoaderOptions: {
    javascriptEnabled: true,
  },
});
```

```tsx
// pages/_app.tsx
import 'rsuite/lib/styles/index.less';
```

```tsx
// pages/index.tsx
import Head from 'next/head';
import { Button } from 'rsuite';

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Button appearance="primary">Test</Button>
      </div>
    </div>
  );
};

export default Home;
```

### Any additional comments? (optional)
I have not been able to find anything myself about this specific issue. I've only found people having issues enabling Less with rsuite and nextjs, which was solved by using the @zeit/next-less package. However for me it just doesn't seem to work, I'm not sure if this is a problem uniquely to me or not.

**Comment by eDubrovsky** [comment]
I think this same error - https://github.com/rsuite/rsuite/issues/1415

**Comment by MikeSchaatsbergen** [comment]
@eDubrovsky Seems to be yeah. I looked into it a bit, you started getting the error when you updated to Less version `^4.0.0`. I just downgraded the version of Less in my project to `3.12.2` and everything works.

Perhaps this is an issue with Less rather than Rsuite.

**Comment by MikeSchaatsbergen** [comment]
Downgrading to `3.12.2` seems to fix this specific issue. However when trying to enable on-demand imports with `.babelrc` it crashes when loading the page with a message complaining about an `@import` within node_modules from rsuite.
So you'll have to live with having to import the entire less file.

I'll close the issue as this seems to be an entirely new problem.
