### ISSUE TITLE
Table组件设置affixHorizontalScrollbar后，需要滚动一下才能出现底部横轴的滚动条，可以直接出来吗

### ISSUE THREAD

**Issue by zhangguimei** [rsuite/rsuite#1447]
Table组件设置affixHorizontalScrollbar后，需要滚动一下才能出现底部横轴的滚动条，可以直接出来吗？

**Comment by simonguo** [comment]
目前版本中不支持，你可以通过 `window.scrollTo(0,1)`，主动触发页面滚动，让 Table 的滚动条显示出来。

**Comment by simonguo** [comment]
已修复
