### ISSUE TITLE
Whisper组件bug

### ISSUE THREAD

**Issue by mkanako** [rsuite/rsuite#1458]
翻源码过程发现，Whisper依赖了OverlayTrigger，然后这里判断是function，但是没有调用，另外你们修复的话，顺带能传个this进去就最好了，这样干啥就方便多了

https://github.com/rsuite/rsuite/blob/90439e8fd11aabd09ce5312eefa9c7269a0c8a4a/src/Overlay/OverlayTrigger.tsx#L213-L215

**Comment by mkanako** [comment]
或者把close函数传进去，不然做点小功能太痛苦了😂

目前我有一个table list然后每行有个删除按钮，点删除弹出个popover进行确认，点击popover里面的确定按钮需要先关闭Whisper，再进行后续操作

现在怎么处理?只能用个数组存下每个Whisper的ref，进而去调用Whisper的close方法，但是这也太蛋疼了😂😂

**Comment by simonguo** [comment]
1.当 speaker 是 function 的时候，会交给 Overlay ，在 Overlay 内执行。
2.关于 close ，你有什么建议请提供详细的 API 设计说明。

**Comment by mkanako** [comment]
@simonguo 
怪了，我是测试过了
```
 if (typeof speaker === 'function') { 
   return <Overlay {...overlayProps}>{speaker}</Overlay>; 
 } 
```
目前这样并没有渲染出东西来

我自己改成
```
 if (typeof speaker === 'function') { 
   return <Overlay {...overlayProps}>{speaker()}</Overlay>; 
 } 
```
就正常了

**Comment by simonguo** [comment]
function 是在自定义 overlay 情况下使用, 参考文档： https://rsuitejs.com/components/popover#Overlay
```tsx
const Overlay = React.forwardRef(({ style, ...rest }, ref) => {
  const styles = {
    ...style,
    background: '#000',
    padding: 20,
    borderRadius: 4,
    position: 'absolute',
    boxShadow: '0 3px 6px -2px rgba(0, 0, 0, 0.6)'
  };
  return (
    <div {...rest} style={styles} ref={ref}>
      Overlay
    </div>
  );
});

const App = () => (
  <Whisper
    trigger="click"
    speaker={(props, ref) => {
      const { className, left, top } = props;
      return <Overlay style={{ left, top }} className={className} ref={ref} />;
    }}
  >
    <Button>Test</Button>
  </Whisper>
);
```

**Comment by mkanako** [comment]
@simonguo 
原来是这么用的啊，非常抱歉，我急于求解问题，反而没细看文档

关于 close，我就想这样，不知妥不妥
```ts
const App = () => (
  <Whisper
    trigger="click"
    speaker={(props, ref) => {
      const { className, left, top,close } = props;
      return <Overlay onCliek={close} style={{ left, top }} className={className} ref={ref} />;
    }}
  >
    <Button>Test</Button>
  </Whisper>
````
大意就是能在speaker里面直接调close，不用去拿Whisper的ref，不然当你有一堆Whisper的时候及其痛苦

**Comment by simonguo** [comment]
https://github.com/rsuite/rsuite/pull/1523
@mkanako  当 speaker 为函数时候，在 props 新增了 onClose 方法，方便在 Overlay 内部关闭浮层。
