### ISSUE TITLE
Table组件bug，rowKey没有发挥应有的作用

### ISSUE THREAD

**Issue by mkanako** [rsuite/rsuite#1462]
发现table每行数据发生一些莫名其妙的渲染，一通排查，确认问题出在rsuite-table上，没有拿rowKey去真正的设置每行div的key

看renderRowData这个函数
https://github.com/rsuite/rsuite-table/blob/883a9cfb61369f467c0a32781d74cfba02958f28/src/Table.tsx#L1107
```
renderRowData(
    bodyCells: any[],
    rowData: any,
    props: TableRowProps,
    shouldRenderExpandedRow?: boolean
  ) {
    const { renderTreeToggle, rowKey, wordWrap, isTree } = this.props;
    const hasChildren = isTree && rowData.children && Array.isArray(rowData.children);
    const nextRowKey = typeof rowData[rowKey] !== 'undefined' ? rowData[rowKey] : props.key;

    const rowProps: TableRowProps = {
      ...props,
      'aria-rowindex': (props.key as number) + 2,
      rowRef: this.bindTableRowsRef(props.key, rowData),
      onClick: this.bindRowClick(rowData),
      onContextMenu: this.bindRowContextMenu(rowData)
    };

    const expandedRowKeys = this.getExpandedRowKeys() || [];
    const expanded = expandedRowKeys.some(key => key === rowData[rowKey]);
    const cells = [];

    for (let i = 0; i < bodyCells.length; i++) {
      const cell = bodyCells[i];
      cells.push(
        React.cloneElement(cell, {
          hasChildren,
          rowData,
          wordWrap,
          renderTreeToggle,
          height: props.height,
          rowIndex: props.key,
          depth: props.depth,
          onTreeToggle: this.handleTreeToggle,
          rowKey: nextRowKey,
          expanded
        })
      );
    }

    return this.renderRow(rowProps, cells, shouldRenderExpandedRow, rowData);
  }
```
nextRowKey已经是计算拿到key了，我也不知道为什么要传给下面的cell，不管了，但关键是这个nextRowKey要传给下面this.renderRow啊
```
<Row {...restRowProps} data-depth={depth} style={rowStyles}   key={最关键这里必须设置key啊}>
```

我自己测试了加上key，一切都好了😭

**Comment by simonguo** [comment]
`rowKey` 指定 data 中的唯一值，当需要指定 `expandedRowKeys` 会用到。
你知道你说的"莫名其妙"的渲染是什么？ 能否通过 codesandbox 复现一下你的问题？

**Comment by mkanako** [comment]
@simonguo 
codesandbox 复现麻烦，我先简单举个例子

看下面的li是通过一个数组渲染出来的，你知道每个li得加key吧，不然对数组进行增删改就会出现“莫名其妙”的渲染bug
`<ul><li>....</li></ul>`

那么类似的现在的table也是同样的情况，每行row并没有设置key，就出现问题

还不能理解我再复现下看看

**Comment by simonguo** [comment]
Row 设置了 key, 默认用的 rowIndex。
https://github.com/rsuite/rsuite-table/blob/master/src/Table.tsx#L1426

**Comment by mkanako** [comment]
@simonguo 哦，那怪不得，rowIndex只是让react不报错而已，实际会有问题你知道吧，你用RowKey就刚刚好啊

我现在删除table中的某个元素后，后面元素会发生不应该有的渲染

**Comment by mkanako** [comment]
我彻底明白了
假设一个数组3个元素索引0,1,2，用索引作为key，然后我删除掉第二个元素，那么第3个元素索引由2变成1，在react看来，这个元素key变了，要重新渲染，实际第3个元素根本没变不需要重新渲染

现在的table组件就出现这种问题

**Comment by mkanako** [comment]
复现来了 https://codesandbox.io/s/wizardly-fog-qwt7v

1.点击第3行绿块，它会变成红块
2.删除第二行

然后你会发现第3行变绿块了，因为这一行被重新渲染了

**Comment by mkanako** [comment]
尴尬了，我上面的理解不对
虽然我是操作删除第二行，但是在react看来是第三行被删除了
然后react对第二行diff，然后更新，实质就是把原本第二行更新成第三行的样子

这个问题有点意思
