### ISSUE TITLE
TagPicker: the "clean" button does not work

### ISSUE THREAD

**Issue by AndreyMZ** [rsuite/rsuite#1467]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | ? |
| `rsuite` | `4.8.8` |

### What is the expected behavior?

The "clean" button:
1. Is highlighted on hover.
2. Cleans the input on click.
 

### What is the current behavior?

The "clean" button:
1. Does not change on hover.
2. Does nothing on click.

### What are the steps to reproduce?

1. Go to <https://rsuitejs.com/components/tag-picker/>.
2. Select something in some TagPicker.
3. Click the far right `×`.

### Any additional comments?

TagPicker should look and behave similar to SelectPicker.

**Comment by simonguo** [comment]
Fixed  #1480
