### ISSUE TITLE
table wordwrap more row height in first render

### ISSUE THREAD

**Issue by mmlatale** [rsuite/rsuite#1468]
Why my wordwarp has more height of row in first render ?

![image](https://user-images.githubusercontent.com/34055469/104887688-49a22500-599e-11eb-82e9-7a6cb9573d73.png)

second render not bug. but all white space move to last row

![image](https://user-images.githubusercontent.com/34055469/104887880-95ed6500-599e-11eb-99e7-ea358aa5f182.png)
 
![image](https://user-images.githubusercontent.com/34055469/104888557-7a368e80-599f-11eb-99e5-7ea82a07607f.png)

```jsx
<Table
  wordWrap
  bordered
  height={400}
  data={fakeData}
  onRowClick={data => {
    console.log(data);
    return props.onRowSelect(data);
  }}
>
  <Column
    //flexGrow={1}
    width={60}
    align="center"
  >
    <HeaderCell>
      <span></span>
    </HeaderCell>
    <Cell dataKey="id" />
  </Column>

  <Column
    flexGrow={1}
    //width={200}
  >
    <HeaderCell>
      <span>ชื่อโครงการ</span>
    </HeaderCell>
    <Cell dataKey="firstName" />
  </Column>
  <Column width={70} align="center" fixed="right">
    <HeaderCell>
      <span>แสดง</span>
    </HeaderCell>

    <Cell>
      {data => {
        function handleAction() {}
        return (
          <ButtonGroup>
            {/* <IconButton icon={<Icon icon="edit" />} onClick={handleAction} /> */}
            <IconButton
              icon={<Icon icon="eye" />}
              // href={`/proposal/overview/overview-${props.urlOverview}`}
              // onClick={handleAction}
            />
          </ButtonGroup>
        );
      }}
    </Cell>
  </Column>
</Table>;
```

**Comment by simonguo** [comment]
Please reproduce your problem through [codesandbox](https://codesandbox.io/s/5vq6zo2z5l).

Or try to remove `flexGrow` and fix the column width.

**Comment by mmlatale** [comment]
> Please reproduce your problem through [codesandbox](https://codesandbox.io/s/5vq6zo2z5l).
> 
> Or try to remove `flexGrow` and fix the column width.

Try to remove flexGrow it work !
Thank you so much
