### ISSUE TITLE
Avatar错位

### ISSUE THREAD

**Issue by TheColdPot** [rsuite/rsuite#1478]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `^16.6.1` |
| `rsuite` | `^4.8.8` |

### What is the expected behavior?

https://rsuitejs.com/components/avatar
所有的`<Avatar>`组件应该对齐同一条线
![image](https://user-images.githubusercontent.com/66854652/106150520-674d6680-61b6-11eb-8090-6aa1c6363317.png)

### What is the current behavior?
![image](https://user-images.githubusercontent.com/66854652/106150652-7fbd8100-61b6-11eb-8517-8af72725eef1.png)
并不在一条线上

### What are the steps to reproduce?

【部分代码】
```jsx
<Whisper speaker={speaker} trigger="hover" placement="topStart">
                    <Avatar
                        size="sm"
                        alt={getShorthand(author)}
                        src={`${process.env.PUBLIC_URL}/avatar/${author}.jpg`}
                        style={{
                            // verticalAlign: 'middle'
                            // 此行是我为解决问题自行加入的
                        }}
                    />
                </Whisper>
```

### Any additional comments? (optional)
此bug产生的原因应该是`inline-flex`，但具体并不知道是怎么产生的，我自行加入style `vertical-align: middle`后问题解决

**Comment by simonguo** [comment]
确实存在这个问题，导致这个问题的原因是基线问题，图片的基线在图片底部，和文字的基线不一样，导致对不齐。
通过你的方式 `verticalAlign: 'middle'` 是可以解决问题。

另外，你也可以通过给父级元素添加一个 `display: flex` 可以修复该问题。
```jsx
<div className="avatar-group">
  <Avatar />
  <Avatar />
</div>
```
```css
.avatar-group {
  display: flex;
  align-items: flex-end;
}
```

**Comment by TheColdPot** [comment]
> 确实存在这个问题，导致这个问题的原因是基线问题，图片的基线在图片底部，和文字的基线不一样，导致对不齐。
> 通过你的方式 `verticalAlign: 'middle'` 是可以解决问题。
> 
> 另外，你也可以通过给父级元素添加一个 `display: flex` 可以修复该问题。
> ```jsx
> <div className="avatar-group">
>   <Avatar />
>   <Avatar />
> </div>
> ```
> ```css
> .avatar-group {
>   display: flex;
>   align-items: flex-end;
> }
> ```

那是否可以将默认的style加verticalAlign来全局解决这个问题呢

**Comment by TheColdPot** [comment]
需要`<AvatarGroup>`在avatar的外侧
