### ISSUE TITLE
TagPicker: the input does not work when focused by keyboard

### ISSUE THREAD

**Issue by AndreyMZ** [rsuite/rsuite#1487]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | ? |
| `rsuite` | `4.8.9` |

### What is the expected behavior?
1. The border color changes:
![expected](https://user-images.githubusercontent.com/9609370/106738925-212b5380-664b-11eb-891e-8810fdf25580.png)
2. Something can be typed in.

### What is the current behavior?
1. The border color does not change:
![actual](https://user-images.githubusercontent.com/9609370/106738943-25f00780-664b-11eb-9741-b45e4d466a1d.png)
2. Nothing is typed in.

### What are the steps to reproduce?

1. Go to <https://rsuitejs.com/components/tag-picker/>.
2. Click near some TagPicker.
3. Press Tab (or Shift+Tab) to focus the TagPicker.
4. Type in something.

### Any additional comments?
TagPicker should look and behave similar to SelectPicker.

**Comment by irogozhova** [comment]
Same issue for InputPicker component. When navigating with Tab key, focus on this field is not set. And it doesn't accept tabindex attribute
