### ISSUE TITLE
Toogle button is rendered for empty children

### ISSUE THREAD

**Issue by vytsci** [rsuite/rsuite#1512]
### What version of rsuite are you using?

4.8.9

### What version of React are you using?

16.14.0

### What browser are you using?

Firefox, Chrome

### Describe the Bug

RSuite components that is capable of rendering tree structure, renders children toggle trigger even if children array is empty. Only if passed null or undefined toggle is not visible. 

### Expected Behavior

RSuite components should detect that children array is empty and prevent toggle buttons from rendering. Now I need to manually removed empty arrays from my API retrieved data sets.

### To Reproduce

Provide table with tree data that some node has empty array as children, toggle button will still be rendered.

**Comment by simonguo** [comment]
Please reproduce your problem through [codesandbox](https://codesandbox.io/s/5vq6zo2z5l).
