### ISSUE TITLE
CheckTreePicker 多项选择器的一个建议

### ISSUE THREAD

**Issue by fanlide** [rsuite/rsuite#152]
在我的项目中，因为**需要父级存在，被选中的子级方能被渲染**。
但在这个组件中，子级被选中的情况，父级是不在被选中数据中的。
并且这个组件，父级存在被选数据中时，子级全为被选中状态。

请问能否改进下？或是否已存在该切换方式？

**Comment by fanlide** [comment]
@simonguo 是这样，我需要级联关系，但是也需要**子级不全部被选中的情况下，父级也存在选中的数组中**

**Comment by simonguo** [comment]
@fanlide  如果是级联关系，你说的这种情况，展示逻辑上是存在冲突的。 

如果你的业务决定了要实现这样的逻辑，那你就只能在非级联关系下进行控制，把 `cascade={false}`。
然后，自己控制组件的 `value` 来让节点选中。

**Comment by fanlide** [comment]
@simonguo 谢谢你的解答，那我还是在后台逻辑层进行处理吧
