### ISSUE TITLE
Not sure where is defined <Collapse> component 

### ISSUE THREAD

**Issue by dipenparmar12** [rsuite/rsuite#1524]
In below link example
https://github.com/rsuite/rsuite/blob/master/docs/pages/components/animation/en-US/collapse.md

I am not sure **Collapse** component is where defined, which is mentioned in example.
when i am try to import that component i got this error 
`import {Collapse} from "rsuite"`
> `Attempted import error: 'Collapse' is not exported from 'rsuite'.`

Mentioned in example
`
<Collapse in={this.state.show}>{(props, ref) => <Panel {...props} ref={ref} />}</Collapse>
`

**Comment by simonguo** [comment]
Sorry, the incomplete examples in the documentation bother you.
reference:
https://github.com/rsuite/rsuite/blob/master/docs/pages/components/animation/en-US/index.md

Useage:
```tsx
import { Animation } from 'rsuite';

return (
  <Animation.Collapse>{...}</Animation.Collapse>
)
```

**Comment by dipenparmar12** [comment]
By the way. Thank you much for you developed such an **great & cool** project ever i have seen in React....
I really like it. your work is `appreciated`, `Peace` & `Love`
