### ISSUE TITLE
column width

### ISSUE THREAD

**Issue by Dianaou** [rsuite/rsuite#153]
it isn't obvious for user to  adjust column width

**Comment by simonguo** [comment]
I understand your question. 
Are you saying that the handle of the custom width of the table is not obvious?

**Comment by Dianaou** [comment]
yes

**Comment by simonguo** [comment]
Fix: https://github.com/rsuite/rsuite-table/commit/1013d5bed2150f7af86f8d81fc2ca25b2c1b42c5
