### ISSUE TITLE
Table Slowdown (Large dataset with interaction)

### ISSUE THREAD

**Issue by DovahBrownies** [rsuite/rsuite#1542]
### What version of rsuite are you using?
^4.9.2

### What version of React are you using?
^16.8.6

### What browser are you using?
Chrome

### Describe the Bug
The table becomes extremely slow and laggy when filled with a large data set and interactive elements are added. Such as when you have 100 rows in the table and each row has a checkbox and an input field. If you click on a checkbox (for example), the checkbox will react 1-2 seconds later. This gets worse with bigger datasets or more interactive elements per row.
Tried with `virtualization` prop as well.

### Expected Behavior
Table interaction response should be <1 second.

### To Reproduce
 - Go to https://rsuitejs.com/components/table/
 
 - Copy the code in the Advanced section (Custom Cell).
![image](https://user-images.githubusercontent.com/35106956/109975901-d19c7e00-7d03-11eb-8c46-6c6ab72ffc2b.png)

 - In the `data` prop, add 100+ items. Or you can quickly do: `data={[...data, ...data, ...data, ...data, ...data]}`
 
 - Click on any checkbox and notice the response time delay. Adding a Select/Input in one of the columns will make this even slower.

**Comment by DovahBrownies** [comment]
Is most probably related to #839

**Comment by simonguo** [comment]
https://codesandbox.io/s/nifty-goldwasser-4uc14?file=/src/index.js

I added an example through codesendbox. There are 1000 rows of data. Clicking on the Checkbox did not appear to be slow.
If your problem persists, please provide a codesendbox example to reproduce your problem.

**Comment by DovahBrownies** [comment]
@simonguo Increasing the table height to show all rows causes this issue.
I suppose that this works by design and I shouldn't be showing all the rows, right?

https://codesandbox.io/s/zen-tdd-p44su?file=/src/index.js

**Comment by simonguo** [comment]
The performance bottleneck on the browser is mainly the rendering of the DOM. If you have more elements to render, it will cause performance problems. So the `virtualized` function is designed so that elements that are not in the visible area are not displayed. And you change the height of the table to make `virtualized` meaningless.
