### ISSUE TITLE
table autoheight 在 Modal 中显示不完整

### ISSUE THREAD

**Issue by lnstock** [rsuite/rsuite#1543]
4.9.2

### What version of React are you using?

16.8.6

### What browser are you using?

Chrome

### Describe the Bug

Modal 内含有 Table(autoHeight=true)，在 Modal onShow 事件中，获取数据后设置 Table 的 data，会导致 Table 显示不完整。
不止是 Table，其他例如 Drawer 这种，也是一样。这个问题从 3.x 发现就一致存在

**Comment by simonguo** [comment]
Table 在 Modal 内，如果在 Modal 在 show 之前已经存在值了，Modal 的动画确实会影响到 Table 对高度的计算。为了告诉 Table 需要更新，你可以在每一次 show 的时候，更新 Table data 的值，让 Table 重新绘制。
以下是一个参考示例：
https://codesandbox.io/s/sweet-jennings-o55s6?file=/src/index.js

如果你有好的方案和建议，欢迎你给我们提 PR。
