### ISSUE TITLE
Uploader clears inputs

### ISSUE THREAD

**Issue by HannesDahlvik** [rsuite/rsuite#1544]
### What version of rsuite are you using?

^4.9.2

### What version of React are you using?

^17.0.1

### What browser are you using?

Chrome

### Describe the Bug

I have a form with Inputs, a SelectPicker, a RadioGroup and an Uploader, and when I upload an image it clears all the inputs values.

### Expected Behavior

Not clear Inputs when uploading an image

### To Reproduce

https://codesandbox.io/s/jovial-dawn-hvz0v

**Comment by HannesDahlvik** [comment]
Edited the post already but here [sandbox](https://codesandbox.io/s/jovial-dawn-hvz0v)

**Comment by simonguo** [comment]
The `Information` component in your code will be declared repeatedly, and you should define it outside the `App` component.
![image](https://user-images.githubusercontent.com/1203827/110463300-b4edb500-810c-11eb-992e-0ca70fcf18db.png)

Adjusted example: https://codesandbox.io/s/quirky-browser-ujp5w?file=/src/index.js

**Comment by HannesDahlvik** [comment]
Alright thanks, this actually makes alot of sense, I'm supprised I didn't think of that.
