### ISSUE TITLE
Allow custom creatable and searchable labels in Pickers

### ISSUE THREAD

**Issue by iSplasher** [rsuite/rsuite#1565]
### What problem does this feature solve?

I am using v5.

This feature would allow for a more appropriate label that suits the context. Imagine an InputPicker like this

![billede](https://user-images.githubusercontent.com/9113348/110889355-42d4c600-82ee-11eb-86ca-8a2b32d79f46.png)

In my case a more appropriate label would be **Create gender "Other"**.
This would also help if you decide to use a custom localization solution outside of rsuite.

I hope this could also be applied to the other related picker components.

### What does the proposed API look like?

Maybe something like this?
```jsx
<InputPicker
      creatable
      creatableLabel="Create gender"
      data={data}
    />
```

Or for maximum flexibility, allow passing a template string:

```jsx
<InputPicker
      creatable
      creatableLabel="Create gender ${value}"
      data={data}
    />
```

**Comment by iSplasher** [comment]
If you would like then I can create a PR for this

**Comment by simonguo** [comment]
You can modify the [locales](https://next.rsuitejs.com/guide/intl/#extended-locale) configuration to meet your business scenarios.
https://github.com/rsuite/rsuite/blob/next/src/locales/en_US.ts#L55

In addition, you can also just modify the locale of InputPicker.

```tsx
<InputPicker
  locale={{createOption: "Create gender ${0}" }}
/>
```

**Comment by iSplasher** [comment]
Wow yes thank you, I missed that!
