### ISSUE TITLE
table组件 classPrefix属性无效

### ISSUE THREAD

**Issue by Frank-MJ** [rsuite/rsuite#1584]
| react | ^17.0.1 |
rsuite是最新版
| rsuite-table | ^3.14.5 |
添加classPrefix属性后，没有穿透到所有div上，只是外层的div生效了；
如图所示：
![image](https://user-images.githubusercontent.com/16225885/111752789-182bd400-88d1-11eb-9f8a-e4183d5dcb96.png)

**Comment by simonguo** [comment]
重复的问题
https://github.com/rsuite/rsuite-table/issues/205#issuecomment-826497007
