### ISSUE TITLE
Drawer body height calculation skips the drawer footer margin bottom

### ISSUE THREAD

**Issue by LukaszGrela** [rsuite/rsuite#1622]
### What version of rsuite are you using?

`"rsuite": "^4.9.3",`

### What version of React are you using?

`"react": "^17.0.1"`

### What browser are you using?

Dissenter, Chrome

### Describe the Bug

Drawer body height calculation is not including the drawer footer bottom margin. Also I was not able to find where that calculation happens to see if it can be fixed. I've tried also to override the style (SASS) of the footer/header but then the height calculation did not picked this correctly.

### Expected Behavior

At most, include the margin but better will be to review the height calculation for body so it picks the margin/padding applied to the header (.rs-drawer-header) and footer ( .rs-drawer-footer)

### To Reproduce

[CODEPEN](https://codepen.io/LukaszGrela/pen/zYNmKGG)

**Comment by simonguo** [comment]
Improved drawer layout in rsuite v5
https://next.rsuitejs.com/components/drawer/

```
npm i rsuite@next
```
