### ISSUE TITLE
Table Component‘s sort SVGicon is so small

### ISSUE THREAD

**Issue by moonlitusun** [rsuite/rsuite#1626]
### What version of rsuite are you using?

v4.9.3

### What version of React are you using?

v16.8.6

### What browser are you using?

Chrome

### Describe the Bug

As the title，[DEMO](https://codesandbox.io/s/rsuite-t2m07?file=/src/index.js)

**Comment by simonguo** [comment]
It has been fixed
```
npm i rsuite@latest
```
