### ISSUE TITLE
CustomProvider - Doesn't recorgnize locale prop

### ISSUE THREAD

**Issue by viniciuscluna** [rsuite/rsuite#1636]
### What version of rsuite are you using?

5.0.0-alpha.5

### What version of React are you using?

17.0.2

### What browser are you using?

Chrome, Edge, Firefox

### Describe the Bug

I'm trying to update rsuite to version 5(next), the mainly reason for that is about the new feature to type on datepicker. I'm using the create-react-option to develop, after reading all documentation and doing in several ways. None of the build option worked for me, the DatePicker language and any other component are still in English (I'm trying to use pt-BR option). 

### Expected Behavior

I'd like that the language of rsuite components comes desired language, in my example in pt-BR with the DatePicker format (dd/MM/yyyy)

### To Reproduce
Refer link: 

https://next.rsuitejs.com/guide/intl/

Below, my example code:

Not using react-intl:
https://codesandbox.io/s/sad-poincare-qpfz2?file=/src/index.js

Using react-intl:
https://codesandbox.io/s/loving-brown-qq2w5

**Comment by denilson157** [comment]
I had the same problem, to try to solve, in the Datepicker component I passed the property "format = 'dd / MM / yyyy'", the format came right, but when I finished typing, the day and month are inverted.
I type '01 / 05/2021 ',
The component returns
'05 / 01/2021 '

[my example code](https://codesandbox.io/s/determined-framework-4pco9)

**Comment by simonguo** [comment]
There is indeed a bug here. The context could not be shared between the lib and es directories. You can solve the bug in the following ways.

```diff
- import { DatePicker, Calendar } from "rsuite";
- import CustomProvider from "rsuite/lib/CustomProvider";
+ import { DatePicker, Calendar, CustomProvider } from "rsuite";
```
