### ISSUE TITLE
Sidenav dropdown not working

### ISSUE THREAD

**Issue by mwasigala** [rsuite/rsuite#1650]
### What version of rsuite are you using?
version 4.10.0

### What version of React are you using?
version 17.0.2

### What browser are you using?
Chrome, Opera

### Describe the Bug

The sidenav dropdown when clicked doen't close or open

### Expected Behavior
The sidenav dropdown to closeor open when clicked

### To Reproduce
Utilize the sidenav component 

![Screenshot 2021-05-09 012337](https://user-images.githubusercontent.com/20720317/117555138-47ef9080-b065-11eb-9b2f-fa82e83e9928.png)

**Comment by simonguo** [comment]
Please reproduce the error via codeandbox. 
https://codesandbox.io/s/rsuite-template-5vq6zo2z5l

**Comment by lauri-n** [comment]
I have the same problem with rsuite 5.0.0.

Here's the repro: [https://codesandbox.io/s/agitated-chihiro-74ftm](https://codesandbox.io/s/agitated-chihiro-74ftm)

**Comment by sanhomealex** [comment]
Add `eventKey` to Dropdown .
https://codesandbox.io/s/reverent-oskar-9rjij?file=/src/index.js

But there will be another warning in dev console:
![image](https://user-images.githubusercontent.com/48746578/135637819-48b50154-0c28-4fa5-8736-d2b114e2a5ca.png)

I've faced this after the switch to rsute v 5

**Comment by subashthiru3** [comment]
While I'm using rsuite sideNav bar Nav.menu and sub-menus(Nav.item), when i collapse-in sideNav bar(collapsed-in state) and Click Nav.menu,sub-menus are popUped Nav.items,And Nav.item clicked Nav.menu are Not highlighted
