### ISSUE TITLE
Dependency Error in rsuite@4.10.0

### ISSUE THREAD

**Issue by raibove** [rsuite/rsuite#1661]
### What version of rsuite are you using?

4.10.0

### What version of React are you using?

17.0.2

### What browser are you using?

Chrome

### Describe the Bug

Unable to install rsuite using npm i rsuite due to dependency error. It gave error unable to resolve dependency tree. I have pasted the error [here](https://pastebin.com/BhPtpk09)

When I tried with yarn add rsuite it installed and gave few warnings. [This](https://pastebin.com/JfXFqpvj) is the message it gave after installing rsuite with yarn.

### Expected Behavior

The package should have been installed

### To Reproduce
Run npm i rsuite in command line.

**Comment by simonguo** [comment]
try to to run the command with --force, or --legacy-peer-deps
```
npm install --force
npm install --legacy-peer-deps
```

**Comment by raibove** [comment]
It worked with npm install --force

**Comment by alexshenker** [comment]
> try to to run the command with --force, or --legacy-peer-deps
> 
> ```
> npm install --force
> npm install --legacy-peer-deps
> ```

Why though, whats is the error caused in the first place? Why for some, and not others?

**Comment by SevenOutman** [comment]
> Why though, why is the error caused in the first place? Why for some, and not others?

See explanation in discussion https://github.com/rsuite/rsuite/discussions/1866#discussioncomment-1262720
