### ISSUE TITLE
Sidenav 

### ISSUE THREAD

**Issue by TiagoPerdigao1983** [rsuite/rsuite#1662]
### What version of rsuite are you using?

4.9.4

### What version of React are you using?

16.11.0

### What browser are you using?

Chrome

### Describe the Bug

When the user click the toogle expand button on the sidenav, the icons below the user group jump. 

### Expected Behavior

The icons below the user group on the sidebav shouldn't jump when the sidenav is expanded.

### To Reproduce

<!--
1- Click the toggle button on the open-close menu of the sidenav.
2 - Notice how icons below the user group, jump.

**Comment by SevenOutman** [comment]
Please provide a minimal demo for your issue on CodeSandbox. You can use the template below. 
https://codesandbox.io/s/rsuite-template-5vq6zo2z5l
