### ISSUE TITLE
Changing the first parameter passed to event callbacks.

### ISSUE THREAD

**Issue by ianpgmoftexas** [rsuite/rsuite#1665]
Hey there, we're using RSuite for one of our current projects. Overall it's been great to work with. The main highlight has been Tables. Most Component Libraries for React make these overly complicated and RSuite's table library has been a breeze.

### What problem does this feature solve?

One thing that is slightly annoying is how event callbacks are handled. For example onChange events for Input elements: the callback function receives the value as the first property instead of an event object. This may be nice for when you only want to use the value but when you want to work with other libraries (Formik for example) that use the event object to get other properties you're forced to create a wrapper function or completely separate component just to pass in the event object. This wrapper function however will need to look like so: `(value, event) => handleChange(event)` which will throw an ESLint warning because you're not using the variable "value" although it's defined. 

We have to create a function every time we need the event object to pass to Formik (or another library that utilizes event objects). You can define a helper function outside of the component or create a higher order component around the Input component to make this process easier. However all solutions are a bit tedious.

### What does the proposed API look like?

Either pass the event object first:
`(event) => handleChange(event)` (so you can do this: `onChange={handleChange}`)
Or switch to passing an object so you an do this:
`({ event }) => handleChange(event)` (so you don't get get an ESLint warning but still have the option to do this: `({value}) => {}`)

Although it is nice to just get the value, when trying to do more complicated things like mix in libraries it's kind of a pain. Especially when working on a project with a lot of Forms.

**Comment by SevenOutman** [comment]
Prefixing the unused variable with a underline `_` supresses the ESLint warning.

```
(_value, event) => handleChange(event)
```
