### ISSUE TITLE
树形选择器右侧滑动条

### ISSUE THREAD

**Issue by fanlide** [rsuite/rsuite#168]
![tim 20180815171811](https://user-images.githubusercontent.com/20534139/44141267-3871fc7e-a0af-11e8-8529-0e257be6fe7f.png)
这个滑动条是怎么回事？我查看样式发现去掉下面的margin-top就会消失
![tim 20180815172031](https://user-images.githubusercontent.com/20534139/44141419-a9a2b58c-a0af-11e8-9162-a6c21bebee26.png)

**Comment by simonguo** [comment]
cc  @superman66

**Comment by hiyangguo** [comment]
@fanlide 麻烦提供一下运行环境：操作系统、浏览器-版本 方便我们这边 debug

**Comment by fanlide** [comment]
@hiyangguo 我是win10 谷歌57。第一个截图是你们官网的例子。具体是使用中发现的
