### ISSUE TITLE
rsuite-table 设置wordWrap，Table内部高度渲染异常

### ISSUE THREAD

**Issue by begoat** [rsuite/rsuite#1686]
### What version of rsuite are you using?
4.10.1

### What version of React are you using?
17.0.2

### What browser are you using?
Chrome

### Describe the Bug
RSuite的Table 设置了WordWrap，固定table高度，会导致有时候显示不全数据，有时候表格下方会有很多白条

### Expected Behavior
高度一致

### To Reproduce

https://codesandbox.io/s/infallible-cache-pukpn?file=/src/App.js

**Comment by begoat** [comment]
https://user-images.githubusercontent.com/22862294/118583490-bfd95b80-b7c7-11eb-86be-b6ca5ed25dac.mov

**Comment by crimson968** [comment]
+1 表格高度会不准确
