### ISSUE TITLE
[SelectPicker] 无法通过键盘导航选中下拉菜单中的搜索框。

### ISSUE THREAD

**Issue by LeiHanCN** [rsuite/rsuite#1688]
### What version of rsuite are you using?
5.0.0-alpha.7

### What version of React are you using?
17

### What browser are you using?
Firefox

### Describe the Bug
无法通过键盘选中下拉框中的搜索框

### Expected Behavior
可以通过键盘导航选中下拉框中的搜索框

### To Reproduce
<img width="362" alt="图片" src="https://user-images.githubusercontent.com/19839331/118755014-b1a83f80-b89a-11eb-8d39-570acc9d3d57.png">

https://rsuite-next-japy540lf-rsuite.vercel.app/components/select-picker/

**Comment by SevenOutman** [comment]
我觉得直接监听输入字符聚焦搜索框好像不错，不过不知道是否满足可访问性。
