### ISSUE TITLE
date-range-picker custom tirgger

### ISSUE THREAD

**Issue by sshmyg** [rsuite/rsuite#1698]
Hello
Use case:
1. Use `toggleComponentClass` and controlled date-range-picker.
2. Change value state manually. (Without calendar)
3. Result date inside datepicker correct, in custom toggle component - not.

Example. Click on button 'Change date' to reproduce bug.
https://codesandbox.io/s/ancient-butterfly-b3e6w

**Comment by sshmyg** [comment]
Would be great to add `date` value as prop to `toggleComponentClass`

**Comment by simonguo** [comment]
The value of DateRangePicker includes start date and end date.
```diff
onClick={() => {
-  setDate([new Date()]);
+  setDate([new Date(), new Date()]);
}}
```
