### ISSUE TITLE
如何使用js 重置DatePicker组件数据

### ISSUE THREAD

**Issue by zpbc007** [rsuite/rsuite#171]
### Bug, feature request, or proposal:
在form中将DatePicker组件对应数据置为空，DatePicker组件依然显示之前的值

### What is the expected behavior?
form数据重置后DatePicker组件应不显示日期

### What is the current behavior?
DatePicker组件显示之前选中日期

**Comment by simonguo** [comment]
@zpbc007  你用的那个版本？

**Comment by simonguo** [comment]
确实存在这个问题，这是一个 bug,  我们下周4新版本发布前解决这个问题。

**Comment by zpbc007** [comment]
@simonguo 谢谢了=。=
