### ISSUE TITLE
table滚动条吸附异常

### ISSUE THREAD

**Issue by 15729520405** [rsuite/rsuite#1716]
### What version of rsuite are you using?
4.10.2

### What version of React are you using?
17.0.2

### What browser are you using?
chrome

### Describe the Bug
当表格设置affixHorizontalScrollbar和autoHeight属性，且表格高度超过容器出现纵向滚条条和横向滚动时,正常；
将表格数据减少使之不出现纵向滚动条，发现横向滚动条依然吸附再底部。

### To Reproduce
https://codesandbox.io/s/react-suite-bug-1qmnk?file=/src/App.js:639-663

**Comment by begoat** [comment]
https://user-images.githubusercontent.com/22862294/120734275-2fb34a00-c51b-11eb-967b-4c3079001f55.mov
