### ISSUE TITLE
Add maxHeight Prop to Table Component

### ISSUE THREAD

**Issue by MalcolmNT** [rsuite/rsuite#1727]
### What problem does this feature solve?

Screen overflow occurs if the height of the table is too large. Setting the `maxHeight` css sets the max height of the table but lots of buggy behaviour occurs. So a maxHeight prop is needed for the table component.

### What does the proposed API look like?

minHeight prop is already implemented. Hopefully copying that and making some small changes should make this implementation easy.

```
...
<Table
    autoHeight
    minHeight={200}
    maxHeight={500}
...
```
or
```
...
<Table
    height={600}
    minHeight={200}
    maxHeight={500}
...
```
Above, 500 would be used instead of 600 since maxHeight has priority over height.

**Comment by simonguo** [comment]
If you want the height of the table not to overflow the screen, you can dynamically update the height of the table by monitoring the size of the window.

```tsx
<Table height={getHeight()} />
```

**Comment by tomlister** [comment]
> If you want the height of the table not to overflow the screen, you can dynamically update the height of the table by monitoring the size of the window.
> 
> ```tsx
> <Table height={getHeight()} />
> ```

This doesn't work when you want to fill the available in an element, with nav-bars, headers and other content.

**Comment by raibikys** [comment]
You could use const `tableHeight = document.documentElement.clientHeight - X;` where the X describes pixels. At least this is how I got "responsivnes". Hope rsuite team could provide us a proper prop.

**Comment by tiana-y** [comment]
I have the same request. Or I'd be happy with any other tool to make table behave the following way:
1. if the table's actual height is less than max-height, it should behave as if it had autoHeight prop;
2. if the table's actual height is more than max-height, it should behave as if it had fillHeight prop, meaning: not to become bigger than max-height and have a scroll.

For now as far as I could see, I can't achieve this behaviour. If I use autoHeight, the table might overflow its container. If I use fillHeight, the table with a few rows will look ridiculously long, and I don't want the table to take this extra space.

I hope you'll consider adding such feature.

**Comment by yurist38** [comment]
+1 for the feature, would love to see it onboard. Just faced a case with dynamic data when I don't know upfront how many rows will be rendered, but I still want the table not to be too long. If I set the fixed height, then I sometimes get empty space when I do not have enough data to render.

**Comment by simonguo** [comment]
I'm ready to add this feature.

**Comment by simonguo** [comment]
In the latest version 5.70.0, it is already supported.
https://rsuitejs.com/components/table/#table-height

**Comment by yurist38** [comment]
FYI: `maxHeight` attribute is only activated when you have the `autoHeight` attribute set to true. I had to spend some time to figure this out
