### ISSUE TITLE
input search bar of selecpicker component doesn't focus when typing

### ISSUE THREAD

**Issue by denilson157** [rsuite/rsuite#1728]
### What version of rsuite are you using?

5.0.0-alpha.8

### What version of React are you using?

17.0.2

### What browser are you using?

Microsoft Edge and Google Chrome.

### Describe the Bug

When opening the SelectPicker component and typing something, the input does not automatically focus, like in the [SelectPicker example](https://next.rsuitejs.com/components/select-picker/#controlled).
I need to click again in the input text box to filter

### Expected Behavior

When I click on selectPicker and type something, I expect to filter by the typed text.

### To Reproduce

Click on SelectPicker and try typing something
I fork an example on [codesandbox](https://codesandbox.io/s/charming-lovelace-pb5l7)

**Comment by simonguo** [comment]
fixed https://github.com/rsuite/rsuite/pull/1700

**Comment by jainrishabh038** [comment]
in the selectPicker i want to that in the onSearch prop input user not to able enter spaces in input.please give me solution
