### ISSUE TITLE
Cascader 级联选择器允许选择父级项

### ISSUE THREAD

**Issue by siminture** [rsuite/rsuite#173]
Cascader 级联选择器目前只允许选择最底级项，在用于类似城市/行政区类选择时时需要允许选择非最底级项。

参考ANTD同功能控件，Cascader有个bool参数打开后，每次选择时就把该层级项的值赋予控件了，因此可以满足不选择到最底级的应用场景需求。

**Comment by simonguo** [comment]
@siminture  Cascader 目前只支持选择叶子节点， 如果你要选择非叶子节点，推荐使用 TreePicker https://rsuitejs.com/en/components/tree-picker
