### ISSUE TITLE
Controlled Input lost focus in Popover and Tooltip after onChange.

### ISSUE THREAD

**Issue by eDubrovsky** [rsuite/rsuite#1736]
### What version of rsuite are you using?
4.10.2

### What version of React are you using?
17.0.2

### What browser are you using?
Chrome, Safari

### Describe the Bug
Controlled Input lost focus in Popover and Tooltip after onChange.

### To Reproduce
Click on the `Assign Location` button and try typing text. Input loses focus after each letter entered.
https://codesandbox.io/s/ecstatic-kowalevski-z1bit?file=/src/index.js

**Comment by slawsork** [comment]
Faced with the same issue.

**Comment by simonguo** [comment]
@slawsork  @eDubrovsky  

The `Speaker` in the example is a component, but it is defined inside the `App` component. This will cause a new speaker component to be created every time you render

https://codesandbox.io/s/ecstatic-kowalevski-z1bit?file=/src/index.js
```diff

+const Speaker = ({ content, ...props }) => {
+  const [newLocationName, setNewLocationName] = useState("");
+  return (
+    <Popover title="Title" {...props}>
+      <Input
+        size="md"
+        placeholder="Location Name"
+        value={newLocationName}
+        onChange={setNewLocationName}
+      />
+    </Popover>
+  );
+};

function App() {
-  const [newLocationName, setNewLocationName] = useState("");

-  const Speaker = ({ content, ...props }) => {
-    return (
-     <Popover title="Title" {...props}>
-        <Input
-          size="md"
-          placeholder="Location Name"
-          value={newLocationName}
-          onChange={setNewLocationName}
-        />
-      </Popover>
-    );
-  };

  return (
    <div className="App">
      <p>Please fork this example, reproduce the problem you are issue.</p>
      <p>请 Fork 这个示例，重现你遇到的问题。</p>
      <hr />
      <Whisper
        enterable
        trigger="click"
        placement="bottomStart"
        speaker={<Speaker />}
      >
        <Button appearance="subtle">Assign Location</Button>
      </Whisper>
    </div>
  );
}
```

**Comment by eDubrovsky** [comment]
@simonguo oh, thank you! Got it! :)
