### ISSUE TITLE
Custom column table with checkboxes example is not aligned properly 

### ISSUE THREAD

**Issue by kychung** [rsuite/rsuite#1738]
Hello,
I took the Custom Cell example from https://rsuitejs.com/components/table/ but my checkboxes are not aligned. 
![image](https://user-images.githubusercontent.com/28690215/122071028-695e3d80-cdc4-11eb-992e-fd6da1ca759b.png)

This is how I wrote it 
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/28690215/122071190-8c88ed00-cdc4-11eb-97f9-c3f7221f4398.png)

I don't understand why it is not aligning when the example from your documentation is aligned

**Comment by simonguo** [comment]
Please reproduce your problem through [codesandbox](https://codesandbox.io/s/5vq6zo2z5l).
