### ISSUE TITLE
Multicascader: checked status problem

### ISSUE THREAD

**Issue by zuosiliang** [rsuite/rsuite#1739]
### What version of rsuite are you using?
4.10.0

### What version of React are you using?
16.13.1 

### What browser are you using?

chrome 91.0.4472.101

### Describe the Bug
consider the data giving to multicascader, there are two nodes on the top level, the first node is the child of the second at the same time. if i checked the first one, the second becomes indeterminate State
### Expected Behavior
the second node should be checked if i checked the first one.
### To Reproduce
https://codesandbox.io/s/vibrant-spence-z3d5l

**Comment by simonguo** [comment]
The value corresponding to valueKey must be a unique value in data. There should not be two identical ids between child and parent nodes
