### ISSUE TITLE
Form Validation examples and some other places incorrectly reference non-existing components

### ISSUE THREAD

**Issue by saschoff** [rsuite/rsuite#1755]
The documentation/examples on this page:
https://next.rsuitejs.com/components/form-validation/#usage

Incorrectly say to use Form.Control, Form.Group, etc...  I spent a good bit of time flattening my head on my desk trying to figure this out because I trusted the documentation and my compiler was not giving me errors.  The documentation uses a forward ref that looks like this:
const Field = React.forwardRef((props, ref) => {
  const { name, message, label, accepter, error, ...rest } = props;
  return (
    <Form.Group controlId={`${name}-10`} ref={ref} className={error ? 'has-error' : ''}>
      <Form.ControlLabel>{label} </Form.ControlLabel>
      <Form.Control name={name} accepter={accepter} errorMessage={error} {...rest} />
      <Form.HelpText>{message}</Form.HelpText>
    </Form.Group>
  );
});

The correct code ended up being this:

const Field = React.forwardRef((props, ref) => {
  const { name, message, label, accepter, error, ...rest } = props;
  return (
    <FormGroup controlId={`${name}-10`} ref={ref} className={error ? 'has-error' : ''}>
      <ControlLabel>{label} </ControlLabel>
      <FormControl name={name} accepter={accepter} errorMessage={error} {...rest} />
      <HelpBlock>{message}</HelpBlock>
    </FormGroup>
  );
});

Using a sophisticated framework like rsuite, especially if you are going to make breaking changes like those in this example, really should be able to rely on the documentation.  I understood the error I was getting, but when it compiled ok, I thought I was missing something else.  Nope, rsuite maintainers just completely re-did how certain pieces work without updating documentation.  Very frustrating.

**Comment by simonguo** [comment]
What version of rsuite are you using?

**Comment by saschoff** [comment]
I switched back to semantic-ui, but while I was puzzling with rsuite, I was using 4.9.3.  Don't get me wrong, rsuite is a powerful framework, but I prefer to use Formik as my validation framework and was struggling there, too, as I think rsuite is more coupled to a different validation framework - components seemed to not extend the normal functionality of form fields the way I expected.  I am fairly new to React and don't get to use it daily, so it may just be my inability to see how I might have better been able to make rsuite work with Formik or was missing some of the ways rsuite abstracted away form field behaviors.  Alas, I already knew how to do it with Semanitic, so to finish the project I was working on, I just switched back to what I was more comfortable with.

Thanks for looking into it, though.  I will definitely look into rsuite again as my knowledge of React grows.

**Comment by simonguo** [comment]
https://next.rsuitejs.com
The document you are accessing is the version of rsuite v5, and you need to upgrade rsuite.

https://next.rsuitejs.com/guide/v5-features/#1-improvements-to-form
There are detailed instructions in the upgrade guide.

If you want to continue using the rsuite v4 , you should visit  https://rsuitejs.com/

**Comment by saschoff** [comment]
Thanks for the info!  I must have been just a touch out of sync.  I like the new improvements!  Will definitely be looking into rsuite in the near future.  Good to know I was not looking at the correct documentation and it gave me a look at the new v5 offerings.

Thanks again!
