### ISSUE TITLE
Limit table data on virtualized for better perfomance

### ISSUE THREAD

**Issue by tudorPopescu** [rsuite/rsuite#1760]
### What problem does this feature solve?
I must render in a lot of components more than 3000 rows on table.
The virtualized feature is great, but when I added buttons or icons it starts to get slow.

My **ideea** is to have a limit on how many items to render on the virtualized table at once, and after that add more items.
For example page loads with 40 items, and when the user starts scrolling the page shows 10 more and 10 more etc.
This would be a great feature.
The user doesn't need to see all of the 3000 rows at once if for example he only needs to scroll to row 200.

**Comment by simonguo** [comment]
Can you provide an example of codesandbox? I would like to learn about specific problems through example in order to find an optimized solution for you.

**Comment by raibikys** [comment]
@simonguo just want to add something to this thread. If there is more data, with popovers, which are on table elements, and table cells are extracted to different component the table gets very slow even the virtualization is on. Table height is about 600. Can you do something about this? Virtualization works just for simple data, when it gets more complicated with labels,divs,popovers,icons ir slows down extremaly.

**Comment by raibikys** [comment]
And I noticed it became even worse when updating from v5.05 to v.5.30.

**Comment by simonguo** [comment]
Hi @raibikys  
I hope that you can provide an example with codesandbox.
https://codesandbox.io/s/rsuite-template-5vq6zo2z5l

**Comment by raibikys** [comment]
> Hi @raibikys I hope that you can provide an example with codesandbox. https://codesandbox.io/s/rsuite-template-5vq6zo2z5l

I will do it as soon as I can

**Comment by SevenOutman** [comment]
Hi @tudorPopescu and @raibikys, I'm closing this issue as it's not active for quite some time. Feel free to re-open if you have further information.
