### ISSUE TITLE
[DatePicker] Calendar doesn't respond time change

### ISSUE THREAD

**Issue by kryaksy** [rsuite/rsuite#1763]
### What version of rsuite are you using?
4.10.2

### What version of React are you using?
16.13.1

### What browser are you using?
Chrome

### Describe the Bug
When value prop change, time toolbar or time view does not respond the change. 

### Expected Behavior
Should respond immediately when value changes.

### To Reproduce
https://codesandbox.io/s/datepicker-time-input-issue-rsuite-42f5l

![Kapture 2021-06-30 at 19 58 38](https://user-images.githubusercontent.com/33466807/124001978-e6510000-d9dd-11eb-83b9-2eb8896944a5.gif)

**Comment by simonguo** [comment]
https://next.rsuitejs.com/components/date-picker/#date-and-time
This bug has been fixed in v5. You try to use the latest version of rsuite.
```
npm i rsuite@next
```

**Comment by kryaksy** [comment]
> https://next.rsuitejs.com/components/date-picker/#date-and-time
> This bug has been fixed in v5. You try to use the latest version of rsuite.
> 
> ```
> npm i rsuite@next
> ```

Nope. There is still same bug in version 5.0.0-alpha9. Here is the fork of project above.
https://codesandbox.io/s/datepicker-time-input-issue-rsuite-500-alpha9-uqqgp
