### ISSUE TITLE
Slight trouble with dark mode in alpha.9

### ISSUE THREAD

**Issue by loganaaaflag** [rsuite/rsuite#1775]
### What version of rsuite are you using?
5.0.0-alpha.9

### What version of React are you using?
17.0.3

### What browser are you using?
Firefox

### Describe the Bug

Two things:

First, [the docs](https://next.rsuitejs.com/guide/dark-mode/) mention dark mode is enabled by default, but it seems like the dark mode styles aren't in `dist/rsuite.css`, and `lib/styles/variables.less` has `@enable-dark-mode: false`. Adding the `rs-dark-mode` class to body has no effect.

Second, I'm having trouble importing  `lib/styles/index.less`, I'm getting an import error stating `@plugin '../plugins/palette'` was't found. Trying to import `less/index.less` yields an error about `../Animation/styles/index/` not being found. I also received a `tinycolor2 not found` error.

### Expected Behavior

Either the docs should indicate dark mode is disabled by default, or it should be included in the dist css file.
The .less import should be allowed without build issues.

### To Reproduce

This codesandbox can be downloaded and setup with `npm install --legacy-peer-deps && npm start`
https://codesandbox.io/s/ecstatic-pasteur-hof65

I'm not sure if this has something to do with my dependencies?

### Suggested Fix

I've installed tinycolor2 from npm, copied `less/plugins` to `lib/styles`, and set `@enable-dark-mode: true` in `lib/styles/variables.less`

Happy to help in any way I can!

**Comment by SevenOutman** [comment]
> First, [the docs](https://next.rsuitejs.com/guide/dark-mode/) mention dark mode is enabled by default, but it seems like the dark mode styles aren't in `dist/rsuite.css`, and `lib/styles/variables.less` has `@enable-dark-mode: false`.

This seems to be a bug. Dark mode is supposed to be enabled by default as documented.

> Second, I'm having trouble importing `lib/styles/index.less`, I'm getting an import error stating `@plugin '../plugins/palette'` was't found.

This is a known issue as described in #1767 . It’s already been fixed and will be included in next release.

**Comment by loganaaaflag** [comment]
Amazing, thanks @SevenOutman
