### ISSUE TITLE
[TagPicker] Incorrect placement of content in plain text mode, not selected.

### ISSUE THREAD

**Issue by LeiHanCN** [rsuite/rsuite#1784]
### What version of rsuite are you using?
5.0.0-alpha.9

### What version of React are you using?
17.0.2

### What browser are you using?
FireFox

### Describe the Bug
<img width="434" alt="图片" src="https://user-images.githubusercontent.com/19839331/125579769-6bf1e224-3f3c-404e-b497-b6509d49569b.png">

### Expected Behavior
Align text

### To Reproduce
1. Vist https://next.rsuitejs.com/components/tag-picker/
2. Make `TagPicker` value is not in list of data, and changed to plaintext mode. 
 <img width="409" alt="图片" src="https://user-images.githubusercontent.com/19839331/125579866-8b8a4cd2-70cb-4c6b-83e8-34a0b3707427.png">

 May be caused by this code.
https://github1s.com/rsuite/rsuite/blob/HEAD/src/InputPicker/InputPicker.tsx#L698-L699

**Comment by simonguo** [comment]
TagPicker is a picker, and the value must exist in the data source. 
Your application scenario may be supported by our upcoming [TagInput](https://github.com/rsuite/rsuite/pull/1848).
