### ISSUE TITLE
Icons broken @ `https://cdn.jsdelivr.net/npm/rsuite/dist/styles/fonts/rsuite-icon-font.ttf`

### ISSUE THREAD

**Issue by ndom91** [rsuite/rsuite#1786]
### What version of rsuite are you using?

`4.8`

### What version of React are you using?

`17.0.1`

### Describe the Bug

The default URL of the icon font (https://cdn.jsdelivr.net/npm/rsuite/dist/styles/fonts/rsuite-icon-font.ttf) seems to be down. Did you guys change the path? 

Icons both on your official docs site, as well as on my implementation of rsuite seem to be broken. Devtools just says `CONNECTION_REFUSED` to the `jsdelivr.net` URL.

i.e.

![image](https://user-images.githubusercontent.com/7415984/125673878-54aecaad-e75a-4e4c-8d50-5354ec76e406.png)

**Comment by simonguo** [comment]
It may be that the network in your area cannot access jsdelivr cdn. It has been changed to the svg icon in the v5 version.
https://next.rsuitejs.com/guide/introduction/

**Comment by ndom91** [comment]
Yeah strange i double checked all that, but okay if you guys are not experiencing the same issue then its definitely on my side. Thanks!
