### ISSUE TITLE
To optimize the style files(css/less).

### ISSUE THREAD

**Issue by stanleyxu2005** [rsuite/rsuite#18]
昨天在知乎上看见rsuite，觉得非常赞。我在看文档并尝试做一个最简单的带按钮的example。对于js，我可以使用babel-plugin-import来瘦身，结合最新的react和rsuite/lib/button，差不多就160kb吧。

但对于css似乎没有找到合理的方法。打包之后css就是你们dist/rsuite.min.css的大小，差不多要600kb吧。我直接尝试构建less，就直接失败了。说什么@charset=utf8不认识。请问在瘦身css方面，你们推荐如何做呢？

**Comment by hiyangguo** [comment]
`less` 构建失败？ 能提供一下 详细的错误日志么 ？
按需加载目前正在设计中，预计会在下一个 `minor` 版本进行更新。

**Comment by stanleyxu2005** [comment]
@hiyangguo 耽搁了几天，抱歉。

首先，我遵循https://rsuitejs.com/en/guide/use-with-create-react-app 中关于Customize Theme的介绍，改了一下code。
然后运行`yarn build`的结果如下
```
yarn run v1.6.0
warning ..\package.json: No license field
$ webpack --mode production
Hash: dd23c6c1bb647d8fb4b3
Version: webpack 4.8.3
Time: 1532ms
Built at: 2018-05-17 22:08:56
 2 assets
Entrypoint main = main.css main.js
 [41] (webpack)/buildin/module.js 519 bytes {0} [built]
 [45] (webpack)/buildin/global.js 509 bytes {0} [built]
 [68] (webpack)/buildin/harmony-module.js 597 bytes {0} [built]
[150] ./src/index.js 588 bytes {0} [built]
    + 147 hidden modules

ERROR in ./node_modules/rsuite/styles/less/index.less
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import "rsuite";
| 
 @ ./src/index.js 7:0-39
Child mini-css-extract-plugin node_modules/css-loader/index.js!node_modules/rsuite/dist/styles/rsuite.min.css:
    Entrypoint mini-css-extract-plugin = *
       2 modules
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by hiyangguo** [comment]
@stanleyxu2005 你有参照文档操作么？ 如果你使用的是 create-react-app ，那么你需要使用 react-app-rewired 才能编译，详见 [在 create-react-app 中使用](https://rsuitejs.com/guide/use-with-create-react-app#%E5%AE%9A%E5%88%B6%E4%B8%BB%E9%A2%98)。
** 当你使用 create-react-app 的情况下是没有办法直接修改 webpack.config.js 的。 **

**Comment by stanleyxu2005** [comment]
我用的是create-react-app，不过也装了webpack并且自己生成了一个webpack.config.js。如果这个操作方法有问题，那么我再试试看去掉webpack好了。谢谢提醒。

**Comment by hiyangguo** [comment]
@stanleyxu2005 如果你使用的是 webpack ，需要为 `less` 配置 一个 [less-loader](https://www.npmjs.com/package/less-loader) 进行处理。详情参照 webpack 的文档，less-loader [这一节](https://webpack.docschina.org/loaders/less-loader/#src/components/Sidebar/Sidebar.jsx)进行配置。或者你也可以参照我们官网的 [`webpack.config.js`](https://github.com/rsuite/rsuite.github.io/blob/master/webpack.config.js#L70)的配置。

**Comment by hiyangguo** [comment]
@stanleyxu2005 我们会陆续更新一些脚手架及 demo ，在此之前带来的不便，深感抱歉。感谢对 `rsuite` 的支持。
