### ISSUE TITLE
Cascader 优化

### ISSUE THREAD

**Issue by lujingfeiyong** [rsuite/rsuite#181]
Cascader 支持选择到任一层级，目前只能选择到最后一级。

**Comment by simonguo** [comment]
@lujingfeiyong 
你的这个需求，`TreePicker` 组件可以满足： https://rsuitejs.com/en/components/tree-picker

**Comment by hiyangguo** [comment]
@lujingfeiyong [multi-cascader](https://rsuitejs.com/components/multi-cascader)
