### ISSUE TITLE
Time selection in DateRangePicker

### ISSUE THREAD

**Issue by hiukky** [rsuite/rsuite#1816]
The DateRanger accepts adds a temporal selection component by identifying a pattern in the prop format "HH:mm:ss". To some specific reason for not having this behavior in DateRangerPicker?

In the DateRanger session there is an example of grouping where two components are rederized simulating a DateRangerPicker but with the loss of the feature of selection between components not to mention breaking the dynamism of a form that depends on the component only using the "accepter" prop without having to depend on groupings etc.

### What problem does this feature solve?

Time selection in DateRangePicker component.

### What does the proposed API look like?
Same pattern as DateRanger.

```
{
 format= 'DD MM YYYY HH:mm:ss'
}
```

**Comment by simonguo** [comment]
In rsuite v5, time range selection will be supported.
https://next.rsuitejs.com/components/date-range-picker/
![image](https://user-images.githubusercontent.com/1203827/128504269-971cf5fc-7e8d-4b2a-bdcf-7bef38a032c3.png)

## Install 
```
npm i rsuite@next
```

## Usage
```tsx
<DateRangePicker format='dd MM yyyy HH:mm:ss'/>
```

**Comment by hiukky** [comment]
Great! What are the support plans for version 4? is testing a migration to version 5 but it seems a bit early not to mention that changes to a large application will take time.

**Comment by simonguo** [comment]
The current v4 version does not plan to develop new features, only fixes the remaining bugs.

You can try to upgrade rsuite v5, we provide an upgrade guide.
https://next.rsuitejs.com/guide/v5-features/

**Comment by hiukky** [comment]
I understand and already started an update to the new version! Thank you!

I'm closing.
