### ISSUE TITLE
Month isn't translate when we use anothe locale

### ISSUE THREAD

**Issue by willsgobi** [rsuite/rsuite#1831]
### What version of rsuite are you using?

4.10.2

### What version of React are you using?

17.0.2

### What browser are you using?

Chrome

### Describe the Bug

When we insert another language, the Months isn't translated

### Expected Behavior

I expected that the month was translate for language that I put previously

### To Reproduce

https://codesandbox.io/s/focused-poitras-9rzrv

Note: I put the pt_BR, however, the month still in US format.

**Comment by simonguo** [comment]
The localization of the date needs to set a formatDate property on `<IntlProvider>`.

https://rsuitejs.com/guide/intl
```tsx
import { DateRangePicker, IntlProvider } from "rsuite";
import ptBR from "rsuite/lib/IntlProvider/locales/pt_BR";
import format from 'date-fns/format';
import pt from 'date-fns/locale/pt';

function formatDate(data, formatStr) {
  return format(data, formatStr, { locale: pt });
}

return (
  <IntlProvider locale={ptBR} formatDate={formatDate}>
    <DateRangePicker
      format="DD/MM/YYYY"
      appearance="default"
      placeholder="Filtrar período"
      preventOverflow={true}
    />
  </IntlProvider>
);
```
