### ISSUE TITLE
S3 upload with Uploader Component makes file corrupted

### ISSUE THREAD

**Issue by aminshamim** [rsuite/rsuite#1853]
### What version of rsuite are you using?
4.10.2

### What version of React are you using?
17.0.1

### What browser are you using?
All

### Describe the Bug
I get the following header and footer while uploading through AWS Apigateway & Lambda.

------WebKitFormBoundaryNkFieiHzBKLDPBi5
Content-Disposition: form-data; name="pexels-diana-8585133.jpg"; filename="pexels-tobi-631988.jpg"
Content-Type: image/jpeg

IMAGE DATA HERE

------WebKitFormBoundaryNkFieiHzBKLDPBi5--

This makes the file corrupted or invisible in web and apps. I can open it with photoshop but not in browser. When I delete this part in notepad ++ the image seems okay. I searched a lot inside Uploader component but helpless without any clue. Please Fix this. Thanks.

### Expected Behavior
------WebKitFormBoundaryNkFieiHzBKLDPBi5
Content-Disposition: form-data; name="pexels-diana-8585133.jpg"; filename="pexels-tobi-631988.jpg"
Content-Type: image/jpeg

IMAGE DATA HERE

------WebKitFormBoundaryNkFieiHzBKLDPBi5--

THIS ABOVE PART SHOULD BE REMOVED FROM XHR REQUEST

**Comment by simonguo** [comment]
https://stackoverflow.com/questions/41188903/what-does-webkitformboundary-mean?rq=1
https://stackoverflow.com/questions/4526273/what-does-enctype-multipart-form-data-mean
I hope that will help you.

**Comment by aminshamim** [comment]
> @aminshamim Create a [`FormData`](https://developer.mozilla.org/en-US/docs/Web/API/FormData) in Uploader, and then upload the file via [`XMLHttpRequest`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest).
> https://github.com/rsuite/rsuite/blob/d1a4b02c873c53f30e5984c3019da8d528a35a9e/src/utils/ajaxUpload.ts#L46-L47

Do I need to pass the formData inside Data Parameter of Uploader Component or I need to send an XHR request Seperately. Would you plz elaborate. Thanks in advance.

**Comment by aminshamim** [comment]
Update:: I found that Multipart payload image broken when uploading through Uploader Component. It might be an issue with AWS also.

**Comment by simonguo** [comment]
https://github.com/aws/aws-sdk-js/issues/547
I found a similar issue in aws-sdk. 
The main reason for this problem is that the data parameter received by Amazon S3 should be `File` instead of `FormData`.

Perhaps, we can add an attribute `disableMultipart` to Uploader to support S3 image upload.
