### ISSUE TITLE
[Whisper] `enterable` prop is not working.

### ISSUE THREAD

**Issue by LeiHanCN** [rsuite/rsuite#1855]
### What version of rsuite are you using?
5.0.0-beta.5

### What version of React are you using?
17.0.2

### What browser are you using?
Chrome

### Describe the Bug
The `enterable` prop of WhisperProps is not working when the `trigger` props is set to `hover`.

### Expected Behavior
When mouse enter the floating layer of popover, the floating layer shouldn't be disappear.

### To Reproduce
1. visit https://next.rsuitejs.com/zh/components/whisper/
2. find any example
3. change whisper `trigger` prop to `hover` and add `enterable` prop
4. test it in preview.
![image](https://user-images.githubusercontent.com/19839331/130718228-cc637065-536b-40ae-a872-03588e6563cc.png)

**Comment by simonguo** [comment]
The `onMouseEnter` and `onMouseLeave` events should be passed to the `Overlay`.
```diff
const Overlay = React.forwardRef(({ style, onClose, ...rest }, ref) => {
  const styles = {
    ...style,
    background: '#fff',
    width: 200,
    padding: 10,
    borderRadius: 4,
    position: 'absolute',
    border: '1px solid #ddd',
    boxShadow: '0 3px 6px -2px rgba(0, 0, 0, 0.6)'
  };

  return (
    <div {...rest} style={styles} ref={ref}>
      Overlay
      <hr />
      <button onClick={onClose}>close</button>
    </div>
  );
});

const App = () => (
  <Whisper
+   trigger="hover"
+   enterable 
    speaker={(props, ref) => {
-     const { className, left, top, onClose} = props;
-     return <Overlay style={{ left, top }} onClose={onClose} className={className} ref={ref} />;
+     const { className, left, top, onClose, ...rest } = props;
+     return <Overlay {...rest} style={{ left, top }} onClose={onClose} className={className} ref={ref} />;
    }}
  >
    <Button>Open</Button>
  </Whisper>
);
```
