### ISSUE TITLE
Unable to install rsuite - ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by alexshenker** [rsuite/rsuite#1867]
Is there a reason that some users are able to install this without -force while others cannot?
Will the dependency issues be resolved soon?

**Macbook pro 2021
React V: 17.0.2**

**rsuitejs installations fail.**
commands: 
**npm i rsuite --save
npm i rsuite@next --save**

Error:
alex@alex-MacBook-Pro client % npm i rsuite@next --save
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"*" from @testing-library/react@11.2.7
npm ERR!   node_modules/@testing-library/react
npm ERR!     @testing-library/react@"^11.2.7" from the root project
npm ERR!   peer react@"^0.14.0 || ^15.0.0 || ^16.0.0 || ^17.0.0" from mini-create-react-context@0.4.1
npm ERR!   node_modules/mini-create-react-context
npm ERR!     mini-create-react-context@"^0.4.0" from react-router@5.2.1
npm ERR!     node_modules/react-router
npm ERR!       react-router@"5.2.1" from react-router-dom@5.2.1
npm ERR!       node_modules/react-router-dom
npm ERR!         react-router-dom@"^5.2.1" from the root project
npm ERR!   7 more (react-dom, react-router, react-router-dom, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0 || ^16.0.0" from react-text-mask@5.4.3
npm ERR! node_modules/rsuite/node_modules/react-text-mask
npm ERR!   react-text-mask@"^5.4.3" from rsuite@5.0.0-beta.5
npm ERR!   node_modules/rsuite
npm ERR!     rsuite@"5.0.0-beta.5" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/alex/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alex/.npm/_logs/2021-08-31T18_03_46_694Z-debug.log

**Comment by SevenOutman** [comment]
Closing due to duplication with #1661.

See explanation in discussion https://github.com/rsuite/rsuite/discussions/1866#discussioncomment-1262720.
