### ISSUE TITLE
如何给分页组件增加disabled状态

### ISSUE THREAD

**Issue by zpbc007** [rsuite/rsuite#187]
如题

**Comment by zpbc007** [comment]
@simonguo 在请求的table数据未返回时，不想让用户对分页进行操作。

**Comment by simonguo** [comment]
我们会在 `3.2.9` 版本中添加支持禁用分页功能。 

另外，你目前的这种业务场景也可以通过中断上一个请求来实现，这样体验或许会好一些。

**Comment by zpbc007** [comment]
@simonguo 好的，谢谢了
