### ISSUE TITLE
local add fa-IR with persian number like ۱۲۳۴۵۶۷۸۹

### ISSUE THREAD

**Issue by Mahdibayat** [rsuite/rsuite#1880]

**Comment by simonguo** [comment]
Hope you can help us add locales about `fa-IR`.
https://github.com/rsuite/rsuite/tree/next/src/locales

**Comment by Mahdibayat** [comment]
be my pleasure, how can in help

**Comment by simonguo** [comment]
@Mahdibayat  You need to submit [your code](https://github.com/Mahdibayat/rsuite/commit/b6de738ff84eb9b8b2d9b5e4a691773fcd0dea5d) through a `New pull request`. 

---
[Guide to contributing to rsuite](https://github.com/rsuite/rsuite/blob/next/CONTRIBUTING.md)
