### ISSUE TITLE
datepicker组件点击组件外部时没有相应的事件

### ISSUE THREAD

**Issue by zpbc007** [rsuite/rsuite#190]
### Bug, feature request, or proposal:
datepicker组件open值受控后，点击组件外部，无法关闭datepicker组件。

### What is the expected behavior?
点击datepicker外部会触发某一事件。

**Comment by simonguo** [comment]
@zpbc007  会在下个版本 `3.2.9` 加一个 `onHide` 的回调函数。 目前你可以自己监听 document。

**Comment by zpbc007** [comment]
@simonguo 好的，谢谢了
