### ISSUE TITLE
form组件如何单独检验某一字段

### ISSUE THREAD

**Issue by zpbc007** [rsuite/rsuite#191]
表单中有某些字段是关联选择出的，选择后需要校验这些字段，而Form组件只能校验全部字段而不能单独校验这些选择的字段。

**Comment by hiyangguo** [comment]
请参考我们文档中 关于表单校验的那几节 https://rsuitejs.com/components/form#%E8%A1%A8%E5%8D%95%E6%95%B0%E6%8D%AE%E6%A0%A1%E9%AA%8C

**Comment by zpbc007** [comment]
@hiyangguo 关联选择的字段是不可以手填的，所以不会触发blur或change事件，如何手动触发这些字段的校验。

**Comment by simonguo** [comment]
@zpbc007  目前 Form 实例只提供 check 方法，对于业务有单个字段校验的这种需求的，后续我们可以提供一个类似 `checkForField` 的函数。  这个功能我们内部在再评估一下。

**Comment by zpbc007** [comment]
好的

**Comment by zpbc007** [comment]
@simonguo 现在暂时通过触发对应字段的input的blur事件来实现此功能。
