### ISSUE TITLE
Table - current/single-selection (w/o checkbox)

### ISSUE THREAD

**Issue by thelazydogsback** [rsuite/rsuite#1949]
Is there a way for the Table component to support a currently-selected item? 
I suppose I'd have to handle onRowClick myself, and then somehow add a className to the selected row to effect rendering and keep the current item in my local state?

**Comment by simonguo** [comment]
You can easily customize your requirements through `rowClassName` and `onRowClick`.
```tsx
const [items, setItmes] = useState([]);
const handleRowClick = rowData => {
  setItmes(preItems => {
    return preItems.includes(rowData.key)
      ? preItems.filter(item => item != rowData.key)
      : [...preItems, rowData.key];
  });
};

return (
  <Table
    rowClassName={rowData => (items.includes(rowData.key) ? 'row-selected' : '')}
    onRowClick={handleRowClick}
  />
);
```

**Comment by thelazydogsback** [comment]
thanks
