### ISSUE TITLE
Table - programmatically scroll item into view 

### ISSUE THREAD

**Issue by thelazydogsback** [rsuite/rsuite#1950]
Is there a way to ensure that a particular row is visible? -- I need to synchronize the current table item with other components in the view.
Note that it may be a nested child item in **isTree** mode.

**Comment by simonguo** [comment]
Table provides a `scrollTop` method to scroll the table to a specified position.

```tsx
const table = useRef();
<Table ref={table} />;

table.current.scrollTop(rowHeight * index);

```

**Comment by thelazydogsback** [comment]
I saw that but glanced over it because it was pixel based and not based on the item, so it figured it wouldn't work if all row heights were not equal - for example, word-wrapping, etc.
But this will work for me for now.
