### ISSUE TITLE
Rsuite default style import override my app styles

### ISSUE THREAD

**Issue by lironezra** [rsuite/rsuite#1953]
### What version of rsuite are you using?

4.10.3

### What version of React are you using?

17.0.2

### What browser are you using?

Chrome

### Describe the Bug

I am using the DateRangePicker component, in your documentation said that import of the default style needed like that: 
 `import 'rsuite/dist/styles/rsuite-default.css'` (without that line the DateRangePicker won't get the style at all), but the problem is that in this file you have style on the `body` element, and it's override my App `body` styles.

There is any idea how to solve that?

### Expected Behavior

when importing the default rsuite styles the body of my App don't need to override,
maybe you need to give class base selectors over element base selector like `body` `button`

**Comment by lironezra** [comment]
> > Is there any way to set rsuite LESS variable from my react app code?
> 
> Create a Less file in your app say `styles.less`, and write Less styles there
> 
> ```css-less
> @import 'rsuite/DateRangePicker/styles/index.less';
> 
> @reset-import: false;
> ```
Still not working, the path of `index.less` does not exists.
Can you help me with that?

Thanks.

**Comment by SevenOutman** [comment]
> Still not working, the path of `index.less` does not exists.
> 
> Can you help me with that?
> 
> 
> 
> Thanks.
> 
> 

Are you using v5 or still using v4 now?

**Comment by lironezra** [comment]
I'm using v4, if I will move to v5 there are a lot of changes I need to perform.
So currently we want to stay on v4.

Do you have a solution for that?

Thanks a lot of the quick response :)

**Comment by SevenOutman** [comment]
> I'm using v4, if I will move to v5 there are a lot of changes I need to perform.
> 
> So currently we want to stay on v4.
> 
> 
> 
> Do you have a solution for that?
> 
> 
> 
> Thanks a lot of the quick response :)

The `@reset-import` Less variable should work in v4. Could you provide a CodeSandbox or repository that demonstrates the issue?

**Comment by lironezra** [comment]
It is not working because it complain that `@import 'rsuite/DateRangePicker/styles/index.less';` path not exists.

**Comment by lironezra** [comment]
![image](https://user-images.githubusercontent.com/28096499/184878326-8c2d88ac-5547-4af1-a333-f26aadcae913.png)

**Comment by SevenOutman** [comment]
> It is not working because it complain that `@import 'rsuite/DateRangePicker/styles/index.less';` path not exists.
> 
> 

That import statement is for v5. The stylesheet path is `'rsuite/lib/DateRangePicker/styles'` in v4. https://v4.rsuitejs.com/guide/modularized/

**Comment by Shaker-Pelcro** [comment]
@SevenOutman Your solution saved me a lot of hassle, thank you.

**Comment by tringuy1993** [comment]
I'm having this same issue here. I tried to create `styles.less` with this line but no luckk...:
```
@import 'rsuite/DateRangePicker/styles/index.less';

@reset-import: false;
```

See my picture for my directory. My `DatePickerComp2.js` have the following imports:
```
import { addDays, startOfWeek, endOfWeek } from "date-fns";
import DateRangePicker from "rsuite/DateRangePicker";
import "./datepickercomp.css";
import "./styles.less";
```
![image](https://user-images.githubusercontent.com/102921107/218389669-4603815e-0457-465e-947f-b343acaf0bf5.png)

This is how it looks like:
![image](https://user-images.githubusercontent.com/102921107/218390108-8cdbba4b-080f-4f34-813b-3f9a9ab0629a.png)


Any help is much appreciated!

**Comment by SevenOutman** [comment]
> I'm having this same issue here. I tried to create `styles.less` with this line but no luckk...:
> 
> ```
> @import 'rsuite/DateRangePicker/styles/index.less';
> 
> @reset-import: false;
> ```

Hi @tringuy1993, it looks like you are using rsuite v5. In v5, `@reset-import` variable has been renamed to `@enable-css-reset`. Update the variable and see if it works. :)

**Comment by tringuy1993** [comment]
No luck on trying this either. 

> > I'm having this same issue here. I tried to create `styles.less` with this line but no luckk...:
> > ```
> > @import 'rsuite/DateRangePicker/styles/index.less';
> > 
> > @reset-import: false;
> > ```
> 
> Hi @tringuy1993, it looks like you are using rsuite v5. The `@reset-import` variable mentioned in comments above was used in rsuite v4, and has been renamed to `@enable-css-reset` in rsuite v5. Update the variable and see if it works. :)

I have no luck on trying `@reset-css-reset : false` in `styles.css` either.

**Comment by tringuy1993** [comment]
> @SevenOutman Your solution saved me a lot of hassle, thank you.

Could you share your directory layout so I can see if I can replicate how you get the css to work?

Thanks in advance if you still see this.

**Comment by SevenOutman** [comment]
> I have no luck on trying `@reset-css-reset : false` in `styles.css` either.

Could you provide a CodeSandbox that reproduces the problem?

**Comment by D-Andreev** [comment]
> 

This works but it requires to add less to your app, which is not ideal. Is there a way to do this without less?

**Comment by iska9der** [comment]
> This works but it requires to add less to your app, which is not ideal. Is there a way to do this without less?

Yes, please. 
Less is not supported in nextjs v13.
Maybe you (maintainers) should split `rsuite.min.css` to two separate files? For example:
`rsuite-reset.min.css` and `rsuite.min.css`

**Comment by SevenOutman** [comment]
> Less is not supported in nextjs v13.

Does this guide work with Next.js 13? https://rsuitejs.com/guide/use-next-app/#using-less

> Maybe you (maintainers) should split `rsuite.min.css` to two separate files? For example:
> `rsuite-reset.min.css` and `rsuite.min.css`

Looks good to me. I would find out if it's doable.

**Comment by iska9der** [comment]
> > Less is not supported in nextjs v13.
> 
> Does this guide work with Next.js 13? https://rsuitejs.com/guide/use-next-app/#using-less

Not work, unfortunately

**Comment by Ramy-Basuoney** [comment]
> > I'm having this same issue here. I tried to create `styles.less` with this line but no luckk...:
> > ```
> > @import 'rsuite/DateRangePicker/styles/index.less';
> > 
> > @reset-import: false;
> > ```
> 
> Hi @tringuy1993, it looks like you are using rsuite v5. The `@reset-import` variable mentioned in comments above was used in rsuite v4, and has been renamed to `@enable-css-reset` in rsuite v5. Update the variable and see if it works. :)

A simple way to solve this issue in rsuite v5

import "rsuite/dist/rsuite-no-reset.min.css";

instead of

import 'rsuite/dist/rsuite.min.css';

**Comment by SevenOutman** [comment]
> A simple way to solve this issue in rsuite v5
> 
> import "rsuite/dist/rsuite-no-reset.min.css";
> 
> instead of
> 
> import 'rsuite/dist/rsuite.min.css';

@Ramy-Basuoney Thanks for the follow-up!

**Comment by HugoFortunato** [comment]
> > > I'm having this same issue here. I tried to create `styles.less` with this line but no luckk...:
> > > ```
> > > @import 'rsuite/DateRangePicker/styles/index.less';
> > > 
> > > @reset-import: false;
> > > ```
> > 
> > 
> > Hi @tringuy1993, it looks like you are using rsuite v5. The `@reset-import` variable mentioned in comments above was used in rsuite v4, and has been renamed to `@enable-css-reset` in rsuite v5. Update the variable and see if it works. :)
> 
> A simple way to solve this issue in rsuite v5
> 
> import "rsuite/dist/rsuite-no-reset.min.css";
> 
> instead of
> 
> import 'rsuite/dist/rsuite.min.css';

FANTATISC! IT WORKS!!!

**Comment by hslc00** [comment]
> > > I'm having this same issue here. I tried to create `styles.less` with this line but no luckk...:
> > > ```
> > > @import 'rsuite/DateRangePicker/styles/index.less';
> > > 
> > > @reset-import: false;
> > > ```
> > 
> > 
> > Hi @tringuy1993, it looks like you are using rsuite v5. The `@reset-import` variable mentioned in comments above was used in rsuite v4, and has been renamed to `@enable-css-reset` in rsuite v5. Update the variable and see if it works. :)
> 
> A simple way to solve this issue in rsuite v5
> 
> ```js
> import "rsuite/dist/rsuite-no-reset.min.css";
> ```
> 
> instead of
> 
> ```js
> import 'rsuite/dist/rsuite.min.css';
> ```



> > > I'm having this same issue here. I tried to create `styles.less` with this line but no luckk...:
> > > ```
> > > @import 'rsuite/DateRangePicker/styles/index.less';
> > > 
> > > @reset-import: false;
> > > ```
> > 
> > 
> > Hi @tringuy1993, it looks like you are using rsuite v5. The `@reset-import` variable mentioned in comments above was used in rsuite v4, and has been renamed to `@enable-css-reset` in rsuite v5. Update the variable and see if it works. :)
> 
> A simple way to solve this issue in rsuite v5
> 
> ```js
> import "rsuite/dist/rsuite-no-reset.min.css";
> ```
> 
> instead of
> 
> ```js
> import 'rsuite/dist/rsuite.min.css';
> ```

it saved my time. thank you.

**Comment by Jefferson-Butler1** [comment]
Hey Folks! (@SevenOutman)
Looks like this thread has gone a but stale, but I am having a hard time getting these fixes to work. 

My project doesn't use less other than for the rsuite date range picker, and when I import the styles into my app.tsx it overrides a bunch of really basic styles -- think h1, table. My current solution is to scour my app for any delinquent styles and manually override them after the import in my global css file. 

This is my import right now:
`@import 'rsuite/dist/rsuite-no-reset.min.css';`

I am using:
```
    "next": "13.4.1",
    "react": "18.2.0",
    "rsuite": "^5.40.0",
    "typescript": "4.9.4"

```

Would love any guidance on how to stop these overrides

**Comment by youKnow9** [comment]
hi everyone! I am not very good at English, but I will still try to describe the problem in as much detail as possible. 
I import styles this way 
![image](https://github.com/rsuite/rsuite/assets/122813149/912758c3-2c4d-4d21-81fb-02fdaea06d8c)
but in the end I see this result
![image](https://github.com/rsuite/rsuite/assets/122813149/18a7ac5b-1b5b-4c59-9ba7-23cf4eefbbe8)
and as soon as I add the min file to the path or vice versa remove it, the layout becomes normal
![image](https://github.com/rsuite/rsuite/assets/122813149/4f03244f-1950-4562-a646-6f8ea20145ca)

but after restarting everything breaks again and the following warning appears
![image](https://github.com/rsuite/rsuite/assets/122813149/abac50db-92d3-4152-839b-db4002d19b85)

I can't find a solution to this problem :(

**Comment by RoseannePeeters** [comment]
> > > I'm having this same issue here. I tried to create `styles.less` with this line but no luckk...:
> > > ```
> > > @import 'rsuite/DateRangePicker/styles/index.less';
> > > 
> > > @reset-import: false;
> > > ```
> > 
> > 
> > Hi @tringuy1993, it looks like you are using rsuite v5. The `@reset-import` variable mentioned in comments above was used in rsuite v4, and has been renamed to `@enable-css-reset` in rsuite v5. Update the variable and see if it works. :)
> 
> A simple way to solve this issue in rsuite v5
> 
> ```js
> import "rsuite/dist/rsuite-no-reset.min.css";
> ```
> 
> instead of
> 
> ```js
> import 'rsuite/dist/rsuite.min.css';
> ```

While it may work for some, not for all.
For me it is still messing with my css. 
For example it is adding `box-sizing: border-box;` to my css which is messing some of my styling up.

How can I prevent this? I want scoped css or css limited per component.

I tried scoping css or using css modules but you are using imports inside the css

**Comment by mateusPPinh** [comment]
> ```css-less
> @reset-import: false;
> ```

thanks dude! i was stuck in this issue, thank you!

**Comment by Yunus0or1** [comment]
import "rsuite/dist/rsuite-no-reset.min.css";

This throws no module found error. I checkd dist folder and there is no such file. Using "rsuite": "5.24.0",

**Comment by simonguo** [comment]
> import "rsuite/dist/rsuite-no-reset.min.css";
> 
> This throws no module found error. I checkd dist folder and there is no such file. Using "rsuite": "5.24.0",

Supports `no-reset` css starting from [v5.30.0](https://github.com/rsuite/rsuite/releases/tag/v5.30.0).
