### ISSUE TITLE
【建议】使用lodash-es替换现在的lodash

### ISSUE THREAD

**Issue by vylan** [rsuite/rsuite#196]
将整个lodash引入会使代码体积过大，可以考虑采用lodash-es按需加载

**Comment by simonguo** [comment]
@vylan ，你好
感谢的建议，目前我们在项目中采用的是通过 `babel-plugin-lodash` 优化。 不过这个问题交给 rsuite 的用户去处理，体验确实不好，我们会在后续的版本中解决这个问题。
