### ISSUE TITLE
[TypeScript] Type problem with @rsuite/icons

### ISSUE THREAD

**Issue by sergey-yabloncev** [rsuite/rsuite#1969]
Problem with TS in component @rsuite/icons

### What version of rsuite are you using?

5.0.0

### What version of TS are you using?

4.4.3

### What version of React are you using?

17.0.2

### Describe the Bug

With Create React App plus TS, or other build tools, project not build in the console you can see ts errors.

### To Reproduce
install new CRA with template TS and try to build a project or run command **tsc**
![2021-10-08_15-24](https://user-images.githubusercontent.com/32197653/136556251-66faa635-e58f-42eb-bb0f-45a8bc711f74.png)

**Comment by simonguo** [comment]
Exclude node_modules in tsconfig.json
https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#tsconfig-bases
```json
{
  ...
  "exclude": ["node_modules"]
}
```
