### ISSUE TITLE
less variable @icon-font-path should by default target local fonts directory

### ISSUE THREAD

**Issue by micnic** [rsuite/rsuite#198]
I would like to use `rsuite` for an electron app and was not able to load the fonts because of electron security policy, yes, I know that I have to edit the css file and use the fonts from the package, but if I update the package I have to edit it again, which is frustrating, from a user perspective it's expected that the fonts are locally available and not provided by default from a CDN.

So this is just a proposal to switch by default to use the fonts from the package, in my opinion it's a more natural way for the users of your package. You can also provide 2 different builds that will use local and CDN fonts

**Comment by simonguo** [comment]
Hi, @micnic 
thank you for your advice.
If you use the css file directly in your app, it's really a bad experience, and we'll fix it in subsequent releases. In the compiled css file, the relative path of the icon is used by default.

If you use less in your application, you can override the variables in your local less file.

```less
@import '~rsuite/styles/less/index.less';
@icon-font-path: "./fonts";
```

**Comment by ethanwillis** [comment]
@simonguo What file would I create in order to use this override? 

I'm not familiar with less and I'm running into the same problem when trying to use this library in an electron app.

**Comment by hiyangguo** [comment]
@ethanwillis 
If you don't need customize theme ,  you can using our CDN css file :
```
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/rsuite/dist/styles/rsuite.min.css" />
```
Otherwise, you must using `less`. If you using [create-react-app](https://github.com/facebook/create-react-app)  to build you app , you can using [react-app-rewired](https://github.com/timarney/react-app-rewired) and [react-app-rewire-less-modules](https://github.com/andriijas/react-app-rewire-less-modules) to support it.

**Comment by ethanwillis** [comment]
Thanks.

I ended up cloning this repository, modifying the variable @icon-font-path, and re-running your dist npm script. Then I installed the dist as a local npm module.

**Comment by hiyangguo** [comment]
OK,But I still recommend you using our solution, and you can reference [Customize theme](https://rsuitejs.com/en/guide/themes).
