### ISSUE TITLE
Table automatic height

### ISSUE THREAD

**Issue by Nick-kel** [rsuite/rsuite#1988]
### What problem does this feature solve?
Currently, you have to set a table height. There is no possibility for an automatic height. If you have to set a static table heightvalue, it does not look nice and is not dynamic.

### What does the proposed API look like?
The table should have an "autoHeight" boolean.

**Comment by simonguo** [comment]
You can make the column width adaptive by setting `flexGrow` for the column, so as to realize the automatic width of the table.
https://rsuitejs.com/components/table/#fluid
```
<Table>
  <Column flexGrow={1}>...</Column>
  <Column flexGrow={1}> ...</Column>  
  <Column flexGrow={2}> ...</Column>
</Table>
```
