### ISSUE TITLE
Tree and TreePicker reference

### ISSUE THREAD

**Issue by picasik** [rsuite/rsuite#1994]
### What version of rsuite are you using?

5.0.1

### What version of React are you using?

16.13.1

### What browser are you using?

Chrome, Firefox

### Describe the Bug

`<Tree ref={reference}... `
reference return node, in rsuite 4.10.2 reference returns TreePicker object

### Expected Behavior

reference returns TreePicker object

### To Reproduce
v5 - https://codesandbox.io/s/dazzling-parm-924j0?file=/src/App.js
v4 - https://codesandbox.io/s/wispy-cloud-yvhg5?file=/src/App.js

**Comment by simonguo** [comment]
@SevenOutman  Using `innerRef` is a solution. If the purpose of `innerRef` is to get the root element of the component DOM, it can actually be obtained directly through the `root` property.  https://github.com/rsuite/rsuite/blob/da95b6d808a474cabb1c4bea7068b49649de5a3e/src/Picker/utils.ts#L571-L584
