### ISSUE TITLE
Formik does not work

### ISSUE THREAD

**Issue by kaveiros** [rsuite/rsuite#1995]
I am trying to integrate formik with Input and it seems that it is not working.  value property is not updating for Input field . 
However, if I change to input value is updated correctly but css breaks. Perhaps I am missing something here. Could you please advice? The code I am trying to make functional is  

`import React, {useEffect} from 'react'
import {Button, Col, Grid, Input, InputGroup, Panel, Row, Form} from 'rsuite'
import './login.css'
import {useHistory} from "react-router-dom";
import TokenService from "../../services/TokenService";
import Avatar from "@rsuite/icons/legacy/Avatar";
import EyeSlash from "@rsuite/icons/legacy/EyeSlash";
import Eye from "@rsuite/icons/legacy/Eye";
import {useFormik} from "formik";
import * as Yup from 'yup'

const LoginComponent = () => {

    const history = useHistory()
    const [visible, setVisible] = React.useState(false);

    useEffect(()=>{
        const token = TokenService.getCurrentUser()
        if (token) {
            history.replace("/")
        }
    },[history])

    const styles = {
        position: 'relative',
        width: '60%',
        marginBottom: 10,
        marginLeft: '25%'
    };

    const handleVisible = () => {
        setVisible(!visible)
    }

    const formik = useFormik({
        initialValues:{
            username:'',
            password:'',
        },
        validationSchema: Yup.object({
            username: Yup.string().required('Το όνομα χρήστη απαιτείται.'),
            password: Yup.string().required('Ο κωδικός απαιτείται.')
        }),
        onSubmit: values => {
            console.log(values)
        }
    })

    console.log(formik)

    return (
        <div className="html">
            <Grid fluid>
                <Row className="show-grid">
                    <Col xs={8} xsOffset={16}/>
                    <Col xs={8} xsOffset={16}>
                        <Panel bordered shaded header="Tracker" className="backgroundStyle">
                            <Form onSubmit={formik.handleSubmit}>
                                <InputGroup  style={styles}>
                                    <InputGroup.Addon>
                                        <Avatar />
                                    </InputGroup.Addon>
                                    <Input classPrefix="input" type="text" id="username" name="username" onChange={formik.handleChange} onBlur={formik.handleBlur}
                                           value={formik.values.username}/>
                                    {formik.errors.username && formik.touched.username ? (
                                                    <div>{formik.errors.username}</div>
                                                  ) : null}
                                </InputGroup>
                                <InputGroup inside style={styles}>
                                    <Input type={visible ? 'text' : 'password'} id="password" name="password"  onChange={formik.handleChange}
                                           onBlur={formik.handleBlur} value={formik.values.password}/>
                                    <InputGroup.Button onClick={handleVisible}>
                                        {visible ? <Eye /> : <EyeSlash />}
                                    </InputGroup.Button>
                                    {formik.errors.username && formik.touched.username ? (
                                        <div>{formik.errors.username}</div>
                                    ) : null}                                </InputGroup>
                                <Button appearance="primary" color="blue" type="submit" style={styles} >Eίσοδος</Button>
                            </Form>
                        </Panel>
                    </Col>
                </Row>
            </Grid>
        </div>
    )

}

export default LoginComponent
`

Thanks in advance.

**Comment by SevenOutman** [comment]
Hi Nikos, the `onChange` prop on `<Input>` has a different call signature with Formik's `handleChange` method, therefore you can't assign to it directly.

You can make `<Input>` work with Formik by using the `setFieldValue` method from Formik.

```jsx
<Input
  value={formik.values.name}
  onChange={newValue => formik.setFieldValue("name", newValue)}
/>
```

**Comment by kaveiros** [comment]
@SevenOutman  Thank you very much for your reply,  seems to be working fine.
