### ISSUE TITLE
The three-level menu does not automatically shrink when MultiCascader the second-level changed

### ISSUE THREAD

**Issue by SeanBurt** [rsuite/rsuite#2052]
### What version of rsuite are you using?

5.0.3

### What version of React are you using?

16.12.0

### What browser are you using?

Chrome

### Describe the Bug

The three-level menu does not automatically shrink when MultiCascader the second-level changed

### Expected Behavior

The three-level menu can automatically shrink when MultiCascader the second-level changed

### To Reproduce

https://codesandbox.io/s/angry-bhaskara-jtymv?file=/src/index.js

**Comment by javidmiandadsb** [comment]
need a solution for above problem
