### ISSUE TITLE
Missing property maxHeight in CheckPicker

### ISSUE THREAD

**Issue by picasik** [rsuite/rsuite#2100]
### What version of rsuite are you using?

5.1.0

### What version of React are you using?

16.13.1

### What browser are you using?

Chrome, Firefox

### Describe the Bug

In 5th version missed `maxHeight` property in `CheckPicker`. The description of the property is in the documentation . It works correctly in the 4th version.

### Expected Behavior

Ability to set the maximum height 

### To Reproduce

`<CheckPicker maxHeight={160} />`

**Comment by SevenOutman** [comment]
Hi @picasik , I'm closing this is due to duplication. Please refer to #2088.
