### ISSUE TITLE
The formControl and Uploader Component props name conflicts

### ISSUE THREAD

**Issue by myNameIsDu** [rsuite/rsuite#2104]
### What version of rsuite are you using?

4.8.6

### What version of React are you using?

16.8.6

### What browser are you using?

chrome

### Describe the Bug

When a formControl is passed to the uploader as an accepter,name will pass through to uploader, so I have to package a layer of Uploader，like this
![image](https://user-images.githubusercontent.com/53305259/140276667-83e7e071-9acb-4a87-aa5a-e97c8878a791.png)

And this is an example in the V5 documentation

### Expected Behavior

formControl doesn't pass the name down, or something else, right?

**Comment by SevenOutman** [comment]
Hi @myNameIsDu , it's expected that `<FormControl>` passes `name` prop down to the accepter component. For example, a `<FormControl name="username" accepter="input" />` should render an HTML `<input>` with `name="username"` attribute.

Just like the `name` attribute of an `<input>` element, `name` prop on `<Uploader>` component acts as the field name of the uploaded file in the `FormData` it creates. You don't have to use `name` prop on `<FormControl>` if you don't need to change the field name in the `FormData`.

**Comment by SevenOutman** [comment]
Hi @myNameIsDu, I'm closing this issue as it seems to have been resolved. Feel free to re-open if it's actually not.
