### ISSUE TITLE
Icon in IconButton doesn't adopt correct colour

### ISSUE THREAD

**Issue by endercrest** [rsuite/rsuite#2125]
### What version of rsuite are you using?

5.2.0

### What version of React are you using?

17.0.2

### What version of TypeScript are you using (if any)?

3.8.3

### What browser are you using?

Chrome

### Describe the Bug

The IconButton component doesn't seem to pass the colouring to the icon when previous versions (v4) did do this. So when you hover over the button, the colouring doesn't look correct.

```jsx
<IconButton
  appearance="subtle"
  color="green"
  icon={<PlusRoundIcon />}
  size="xs"
  onClick={onExpand}
>
  Expand
</IconButton>
```

Produces the following when hovering:
![image](https://user-images.githubusercontent.com/2616075/141431316-ace92825-01a6-4f79-926a-552e593f5737.png)

### Expected Behavior

I expect that the whole button would have the green colouring

**Comment by SevenOutman** [comment]
Hi @endercrest , the "icon with text" pattern of `<IconButton>` only supports `"default"` and `"primary"` appearances in RSuite v5. I'd suggest using a plain `<Button>` instead of `<IconButton>`.

```jsx
<Button
  appearance="subtle"
  color="green"
  size="xs"
  onClick={onExpand}
>
  <PlusRoundIcon /> Expand
</Button>
```
