### ISSUE TITLE
Globally customize class names prefix

### ISSUE THREAD

**Issue by francov** [rsuite/rsuite#213]
### What is the current behavior?
Hi, is there a global way to customize components' class prefix to match `@ns` less variable override, i.e.:
[`const globalKey = 'rs-'`](https://github.com/rsuite/rsuite/blob/3527ecba9a43a5f9856d759850df37331c6c056c/src/utils/prefix.js#L4)?

We need to deploy 2 custom themes of a library created with your lib... and we need that 2 or more instances can cohexists on the same page.

Thank you in advance,
Francesco

**Comment by simonguo** [comment]
Sorry, some component documentation is not clearly described, we will complete it. `classPrefix` is not covered by the component, I will fix it as soon as possible.

Thank you for your support.

**Comment by simonguo** [comment]
@francov   Upgrade rsuite@3.3.0,  and overwrite the constants with the ' webpack ' plugin

```
plugins: [
  //...
  new webpack.DefinePlugin({
    __RSUITE_CLASSNAME_PREFIX__: JSON.stringify('custom-')
  })
];
```

**Comment by francov** [comment]
I'll close this issue, thank you for the support!
