### ISSUE TITLE
Table display error in table cell

### ISSUE THREAD

**Issue by calvin1012** [rsuite/rsuite#2137]
### What version of rsuite are you using?

17.0.2

### What version of React are you using?

5.2.0

### What browser are you using?

chrome

### Describe the Bug

When try to open a components which contain table on modal or drawer, which tagger by table A cell,  the table CSS not working and all word will overlap together

### To Reproduce

--LogsheetDashboard.js
                 <Table
                  loading={tableLoading}
                  virtualized={true}
                  height={window.innerHeight}
                  data={Data}
                  sortColumn={sortColumn}
                  sortType={sortType}
                  onSortColumn={this.handleSortColumn}
                  affixHeader
                  affixHorizontalScrollbar
                >
                  ...
                  <Column width={120} fixed="right">
                    <HeaderCell>動作</HeaderCell>
                    <Cell>
                      {siteData.length !== 0 &&
                        employeeData.length !== 0 &&
                        ((rowData) => {
                          return (
                            <span>
                              <LogsheetInput
                                isNew={false}
                                dataKey={{
                                  rowData: rowData,
                                  siteData: siteData,
                                  employeeData: employeeData,
                                }}
                              />
                              <Divider vertical />
                              <ShowHistory
                                dataKey={{
                                  logData: rowData.backup_data,
                                  siteData: siteData,
                                  employeeData: employeeData,
                                }}
                              />
                            </span>
                          );
                        })}
                    </Cell>
                  </Column>
                </Table>

--LogsheetInput.js
 return (
      <Fragment>
        {this.props.isNew === true ? (
          <Button
            onClick={() =>
              this.setState({
                isNew: true,
                showDataInputDrawer: true,
              })
            }
            appearance="primary"
          >
            新增一組
          </Button>
        ) : (
          <a
            className="rs-btn-link"
            onClick={() =>
              this.setState({
                isNew: false,
                isHistroy: false,
                showDataInputDrawer: true,
              })
            }
          >
            編輯
          </a>
        )}

        {/* Render drawer after showDataInputDrawer === true */}
        {showDataInputDrawer === true && (
          <Fragment>
            {/*  */}
            <Drawer
              open={showDataInputDrawer}
              onClose={() =>
                this.setState({
                  isNew: Boolean(),
                  showDataInputDrawer: false,
                })
              }
              backdrop="static"
              keyboard={false}
              full
            >
              <Drawer.Header>
                <Drawer.Title>{isNew ? "新增" : "編輯"}</Drawer.Title>
                <Drawer.Actions>
                  <Button
                    appearance="primary"
                    disabled={disabledLoginButton}
                    loading={isLoading}
                    onClick={this.handleSubmit}
                    style={{ display: "inline-block" }}
                  >
                    提交
                  </Button>
                </Drawer.Actions>
              </Drawer.Header>
              <Drawer.Body>
                {errorMsg && (
                  <Message showIcon type="error" description={errorMsg} />
                )}
                <Form
                  ref={(ref) => (this.form = ref)}
                  onChange={(formValue) => {
                    this.setState({ formValue });
                    this.handleData(formValue);
                  }}
                  formValue={formValue}
                  model={model}
                  layout="inline"
                >
                 <Table
                                virtualized={true}
                                height={420}
                                data={formRender.site_employee}
                              >
                                <Column width={110} resizable>
                                  <HeaderCell>職位</HeaderCell>
                                  <Cell dataKey="rank" />
                                </Column>
                                <Column width={100} resizable>
                                  <HeaderCell>員工編號</HeaderCell>
                                  <Cell dataKey="employee_id" />
                                </Column>
                                <Column width={90} resizable>
                                  <HeaderCell>員工名稱</HeaderCell>
                                  <Cell dataKey="name" />
                                </Column>
                                <Column width={100} resizable>
                                  <HeaderCell>聯絡電話</HeaderCell>
                                  <Cell dataKey="contact_no" />
                                </Column>
                              </Table>
              </Drawer.Body>
            </Drawer>
            {/* Select Site */}
            <Modal
              open={showSearchSiteTable}
              onClose={() =>
                this.setState({
                  showSearchSiteTable: false,
                })
              }
              backdrop="static"
              full
            >
              <Modal.Body>
                {/* Filter */}
                <Form
                  onChange={(formValue) => {
                    this.setState({ formValue });
                    this.filter(formValue);
                  }}
                  formValue={formValue}
                  layout="inline"
                >
                  <CustomField
                    name="general"
                    label="篩選"
                    style={{ display: "inline-block", width: 1200 }}
                  />
                </Form>
                {/* Site data */}
                <Table
                  loading={tableLoading}
                  virtualized={true}
                  height={window.innerHeight - 290}
                  data={Data}
                  sortColumn={sortColumn}
                  sortType={sortType}
                  onSortColumn={this.handleSortColumn}
                  onRowClick={(rowData) => {
                    this.handleData({
                      site_id: rowData.site_id,
                      call_kc3_datetime: new Date(),
                      turn_up_datetime: null,
                    });
                    this.setState({
                      showSearchSiteTable: false,
                    });
                  }}
                  affixHeader
                  affixHorizontalScrollbar
                >
                  <Column width={90} fixed sortable resizable>
                    <HeaderCell>執位編號</HeaderCell>
                    <Cell dataKey="site_id" />
                  </Column>
                  <Column width={90} sortable resizable>
                    <HeaderCell>機組編號</HeaderCell>
                    <Cell dataKey="equipment_id" />
                  </Column>
                  <Column width={200} sortable resizable>
                    <HeaderCell>慣用名稱</HeaderCell>
                    <Cell dataKey="site_name" />
                  </Column>
                  <Column width={350} sortable resizable>
                    <HeaderCell>慣用地址</HeaderCell>
                    <Cell dataKey="site_address" />
                  </Column>
                  <Column width={250} sortable resizable>
                    <HeaderCell>詳細地址 (中文)</HeaderCell>
                    <Cell dataKey="description_chi" />
                  </Column>
                  <Column width={350} sortable resizable>
                    <HeaderCell>詳細地址 (英文)</HeaderCell>
                    <Cell dataKey="description_eng" />
                  </Column>
                </Table>
              </Modal.Body>
            </Modal>
          </Fragment>
        )}
      </Fragment>
    );

**Comment by SevenOutman** [comment]
Hi @calvin1012, looks like your code example is not formatted properly. Please update your code, or reproduce your issue in this CodeSandbox https://codesandbox.io/s/rsuite-template-5vq6zo2z5l

**Comment by calvin1012** [comment]
hi @SevenOutman 
I have code a template here
https://codesandbox.io/s/fervent-keldysh-7crh6?file=/src/index.js
thx

**Comment by simonguo** [comment]
@calvin1012  In your use, there is a case of Table nesting. Because the useContext is used inside the Table to pass the className prefix, the className of the nested Table will be incorrect.

In addition, in order to avoid creating a large number of duplicate components, I recommend the following solutions:
https://codesandbox.io/s/zen-brattain-qp4ly
```jsx

const ActionCell = React.forwardRef((props, ref) => {
  const { onAction, rowData, ...rest } = props;
  return (
    <Cell {...rest} ref={ref}>
      <p className="rs-btn-link" onClick={() => onAction(rowData)}>
        編輯
      </p>
    </Cell>
  );
});

function App() {
  const [id, setId] = React.useState(null);
  const showDrawer = id !== null;

  const handleAction = (rowData) => {
    setId(rowData.id);
  };

  return (
    <div className="App">
      <Table height={400} data={[{ id: 1 }, { id: 2 }]}>
        <Column width={70} align="center" fixed>
          <HeaderCell>Id</HeaderCell>
          <Cell dataKey="id" />
        </Column>
        <Column width={105} fixed="right">
          <HeaderCell>動作</HeaderCell>
          <ActionCell onAction={handleAction} />
        </Column>
      </Table>

      <Drawer open={showDrawer} onClose={() => setId(null)}>
        <Drawer.Body>
          <Table height={400} data={[{ id: 1 }, { id: 2 }]}>
            <Column width={70} align="center" fixed>
              <HeaderCell>Id</HeaderCell>
              <Cell dataKey="id" />
            </Column>
          </Table>
        </Drawer.Body>
      </Drawer>
    </div>
  );
}
```
