### ISSUE TITLE
Carousel component in RTL just show first image

### ISSUE THREAD

**Issue by Mahdibayat** [rsuite/rsuite#2144]
### What version of rsuite are you using?

5.2.1

### What version of React are you using?

17.0.2

### What browser are you using?

chrome

### Describe the Bug

in Rtl direction Carousel component don't slide to correct side, "translate3d" must go in contrary ,
in RTL just show first image.

### Expected Behavior

in rtl mode show all image in carousel component

**Comment by SevenOutman** [comment]
Hi @Mahdibayat, I couldn't re-produce this issue on our docs site. The Carousel in RTL direction seems to work well. 
Could you provide a CodeSandbox demo? You may use this template https://codesandbox.io/s/rsuite-template-5vq6zo2z5l

**Comment by Mahdibayat** [comment]
ok, my pleasure to help you,
https://codesandbox.io/s/weathered-fog-6fhwf

**Comment by Mahdibayat** [comment]
can you fix this problem soon!? I don't want to add another carousel library to project

**Comment by simonguo** [comment]
hi @Mahdibayat  please use `rsuite-rtl.min.css` instead of `rsuite.min.css` https://rsuitejs.com/guide/rtl/

```diff
- import "rsuite/dist/rsuite.min.css";
+ import "rsuite/dist/rsuite-rtl.min.css";
```

**Comment by SevenOutman** [comment]
> ok, my pleasure to help you, https://codesandbox.io/s/weathered-fog-6fhwf

Add `dir="rtl"` to your root `<html>` element and it shall work.

**Comment by Mahdibayat** [comment]
> hi @Mahdibayat please use `rsuite-rtl.min.css` instead of `rsuite.min.css` https://rsuitejs.com/guide/rtl/
> 
> ```diff
> - import "rsuite/dist/rsuite.min.css";
> + import "rsuite/dist/rsuite-rtl.min.css";
> ```

hi simonguo,  thank you, in my case , i'm use Less import 
![Screen Shot 1400-09-04 at 11 11 44 AM](https://user-images.githubusercontent.com/24737348/143400188-5b24504f-73ff-47c8-996e-698d0728a466.png)

and in variable on less provide for me i can't find Direction,
Perhaps you need to add @direction to you'r less variavles
https://github.com/rsuite/rsuite/blob/main/src/styles/variables.less

**Comment by Mahdibayat** [comment]
> > ok, my pleasure to help you, https://codesandbox.io/s/weathered-fog-6fhwf
> 
> Add `dir="rtl"` to your root `<html>` element and it shall work. Also use `rsuite-rtl.min.css` as @simonguo mentioned.

thank you too SevenOutman, in my case i'm use nextJs and and don't have access to <html> tag Unfortunately

**Comment by SevenOutman** [comment]
> thank you too SevenOutman, in my case i'm use nextJs and and don't have access to tag Unfortunately

In Next.js you're actually able to customize the root element https://nextjs.org/docs/advanced-features/custom-document

**Comment by Mahdibayat** [comment]
> > thank you too SevenOutman, in my case i'm use nextJs and and don't have access to tag Unfortunately
> 
> In Next.js you're actually able to customize the root element https://nextjs.org/docs/advanced-features/custom-document

i'm set direction to my <html> and all done thank from you support.
