### ISSUE TITLE
Panel doesn't have any background color defined

### ISSUE THREAD

**Issue by isRyven** [rsuite/rsuite#2151]
### What version of rsuite are you using?

5.2.2

### Describe the Bug

Not sure whether this is by design or not, but i can see that `Panel` component doesn't define any background color by default (or property to enabled it), though you can clearly add border and shadow to the component. As a result there is no background at all, you would have to define the background for the Panel manually by overriding the theme (or through custom class). No other component seems could provide the capability to fill the area with background (eg. Container and Content).

![image](https://user-images.githubusercontent.com/14905030/142860833-d0828bdd-770e-474a-9d2e-ac268e70e4ed.png)
 

### Expected Behavior

I am expecting to see the background color still defined (for light theme should be white, and for dark obviously something dark).

### To Reproduce

https://codesandbox.io/s/jovial-phoebe-e9l66?file=/src/index.js

**Comment by SevenOutman** [comment]
Hi @isRyven, it's by-design (so far) that Panel doesn't have a default background. You have to apply style to it yourself.
