### ISSUE TITLE
Uploader wont open input dialog on Chrome MacOS

### ISSUE THREAD

**Issue by pabloiea1995** [rsuite/rsuite#2155]
### What version of rsuite are you using?

4.9.0

### What version of React are you using?

17.0.1

### What version of TypeScript are you using (if any)?

4.0.3

### What browser are you using?

Chrome

### Describe the Bug

Uploader wont show file inpunt dialog on MacOS Chrome.

It does work on safari

MacOs Monterey 12.0.1

**Comment by begoat** [comment]
https://user-images.githubusercontent.com/22862294/143417545-2c427883-6497-444a-9b09-9262489ed465.mov

Hi @pabloiea1995 
I tested Uploader components using macOS 12.0.1 + latest version Chrome. It worked as expected.

Could you pls provide more details (chrome version, video record) for us to debug?

**Comment by pabloiea1995** [comment]
Hello, thanls for your time. Looks like it was a bug with chrome. I restarted the computer and started working again.

**Comment by SevenOutman** [comment]
Hi @pabloiea1995, I'm closing this issue as it seems to have been resolved. Feel free to re-open if it's actually not.
