### ISSUE TITLE
Tree - scroll issue when setted listProps.scrollTop

### ISSUE THREAD

**Issue by picasik** [rsuite/rsuite#2173]
### What version of rsuite are you using?

5.2.3

### What version of React are you using?

17.0.2

### What browser are you using?

Chome, Firefox

### Describe the Bug

in some cases we need to set position of scrollbar. if setted listProps.scrollTop the scroll position is never changed

### Expected Behavior

change scrollbar position only if new value of listProps.scrollTop setted otherwise use real scroll position

### To Reproduce

https://codesandbox.io/s/stupefied-golick-t6hsn

**Comment by simonguo** [comment]
fixed in [5.2.4](https://github.com/rsuite/rsuite/releases/tag/5.2.4)
