### ISSUE TITLE
Table with fixed height with Drag and drop scrolls to top everytime the cell is dropped.

### ISSUE THREAD

**Issue by kychung** [rsuite/rsuite#2184]
### What version of rsuite are you using?

4.10.2

### What version of React are you using?

17.0.2

### What browser are you using?

Chrome and Edge

### Describe the Bug

We have a virtualized table with a fixed height that also uses drag and drop from the documentation https://codesandbox.io/s/rsuite-table-with-react-dnd-forked-60mkf?file=/src/index.js

We use the fixed height in order for the virtualization to work. However, it seem that the fixed height is causing the drag and drop to scroll all the way to the top of the table everytime a row is dropped following a drag. 

### Expected Behavior

The same behaviour as when the height is set to autoHeight which is to leave the scrollbar as it is, or at least leave the dragged item within view. 

### To Reproduce

**Pre-conditions**: Have a table with fixed height and enough data so that you are able to scroll down.
1. scroll to bottom of the table
2. drag the cell in the before last position (in codesandbox, that is Id 24)
3. drop the item to the last row position (in codesandbox, that is Id 25)

Actual behaviour: Table scrolls to top.

**Comment by simonguo** [comment]
hi @kychung Table will re-render after the data is updated, and reset the scroll bar position. If you don't want the scroll bar to be reset, you can disable it by setting `shouldUpdateScroll={false}`.

```tsx
<Table shouldUpdateScroll={false}> 
...
</Table>
```

**Comment by kychung** [comment]
Thank you! Dont know how I missed that prop.
