### ISSUE TITLE
TagPicker HTML Elements Embedding Slower in rsuite 5 compared to rsuite 4

### ISSUE THREAD

**Issue by alyzatuchler** [rsuite/rsuite#2189]
### What version of rsuite are you using?

5.2.3

### What version of React are you using?

16.12.0

### What version of TypeScript are you using (if any)?

3.7.4

### What browser are you using?

Chrome

### Describe the Bug

I'm using a TagPicker within a Form with a large number of selectable options (~1000). The responsiveness of opening/closing the TagPicker or when selecting/deselecting Tags decreased significantly upon upgrading from rsuite 4.10.3 to 5.2.3.

### Expected Behavior

The TagPicker component being responsive with less of a delay when opening/closing the TagPicker or when selecting/deselecting tags within it.

**Comment by SevenOutman** [comment]
Hi @alyzatuchler, in v5 virtualization on pickers (which helps with performance with large data) [are disabled by default](https://rsuitejs.com/guide/v5-features/#disable-all-picker-code-virtualized-code-by-default). If you need virtualization you need to use `virtualized` prop now.

```jsx
<TagPicker data={largeData} virtualized />
```

See if this helps.

**Comment by alyzatuchler** [comment]
Thanks, that was what I was missing!
