### ISSUE TITLE
每个模块引入什么样式，没写清楚呀，难搞

### ISSUE THREAD

**Issue by Yakovtam** [rsuite/rsuite#220]

**Comment by simonguo** [comment]
@Yakovtam   你能否把你的问题描述清楚？

**Comment by Yakovtam** [comment]
> @Yakovtam 你能否把你的问题描述清楚？你是要做按需加载？

是图标的问题， 我不清楚为啥手机浏览器上，图标异常显示
![765986997274242851](https://user-images.githubusercontent.com/23466613/46440850-3fd96100-c797-11e8-89e7-3bb24517b1a7.jpg)

**Comment by simonguo** [comment]
检查一下 jsdelivr 是否可以正常访问，因为图标的字体文件默认是放在 jsdelivr CDN：
```
https://cdn.jsdelivr.net/npm/rsuite-icon-font@3.0.0/fonts/
```

如果，你当前的网络不能正常访问这个 CDN, 可以修改配置,  修改到国内有 rsuite 镜像的 CDN。 
或者修改为本地部署: [如何在本地配置字体文件？](https://rsuitejs.com/guide/themes)

**Comment by Yakovtam** [comment]
> 检查一下 jsdelivr 是否可以正常访问，因为图标的字体文件默认是放在 jsdelivr CDN：
> 
> ```
> https://cdn.jsdelivr.net/npm/rsuite-icon-font@3.0.0/fonts/
> ```
> 如果，你当前的网络不能正常访问这个 CDN, 可以修改配置, 修改到国内有 rsuite 镜像的 CDN。
> 或者修改为本地部署: [如何在本地配置字体文件？](https://rsuitejs.com/guide/themes)

手机电脑都可以正常访问这个网站 的
![643838289588441329](https://user-images.githubusercontent.com/23466613/46466828-dd1bb000-c7fe-11e8-87e2-f907eeac93c8.jpg)

**Comment by Yakovtam** [comment]
具体是引入min有问题，import 'rsuite/dist/styles/rsuite.min.css';  
你加一下我的QQ：1591741926
如果你不用QQ，也可以给我发邮件：  1591741926@qq.com

**Comment by simonguo** [comment]
@Yakovtam  关于样式的疑问，还有吗？ 如果没有，这个 issue 将会被关闭。 如果你有其他问题，请新开一个 issue， 另外，请按照模板把问题描述清楚，如果你要演示一个示例可以通过 `codesandbox` 说明，如果你要贴示例代码，请把代码格式化。
