### ISSUE TITLE
Next.js + Typescript NavLink component doesn't compile

### ISSUE THREAD

**Issue by igrekun** [rsuite/rsuite#2201]
### What version of rsuite are you using?

5.2.4

### What version of React are you using?

17.0.2

### What version of TypeScript are you using (if any)?

4.5.2

### Describe the Bug

`Type error: Property 'as' does not exist on type '{ children?: ReactNode; }'.`

When using example from documentation
```
const NavLink = React.forwardRef((props, ref) => {
  const { as, href, ...rest } = props;
  return (
    <Link href={href} as={as}>
      <a ref={ref} {...rest} />
    </Link>
  );
});
```

**Comment by SevenOutman** [comment]
Hi @igrekun, what is the `<Link>` component in your snippet?

**Comment by igrekun** [comment]
It is a Next.Js link from the official example for rsuite

https://rsuitejs.com/guide/use-next-app/#navigation-component-and-link-combination

**Comment by SevenOutman** [comment]
With TypeScript you have to specify `props`'s type.

```tsx
import Link, { type LinkProps } from 'next/link';

const NavLink = React.forwardRef<HTMLAnchorElement, LinkProps>((props, ref) => {
  const { as, href, ...rest } = props;
  return (
    <Link href={href} as={as}>
      <a ref={ref} {...rest} />
    </Link>
  );
});
```

**Comment by SevenOutman** [comment]
@igrekun I'm closing this issue as it seems to have been resolved. Feel free to re-open if it's actually not.
