### ISSUE TITLE
Form Input Field Loses Focus when Inside Modal

### ISSUE THREAD

**Issue by cowofevil** [rsuite/rsuite#2205]
### What version of rsuite are you using?

5.3.0

### What version of React are you using?

17.0.2

### What version of TypeScript are you using (if any)?

4.4.0

### What browser are you using?

Chrome

### Describe the Bug

Given when a form input field is contained within a modal
When a user types a single character into an input field
Then the input field will lose focus and the user will need to refocus the input field to start typing again

This scenario was tested against rsuite 5.2.4 and the issue could NOT be reproduced.

### Expected Behavior

Form input fields should not lose focus when a user is typing regardless if the form is contained within a modal or not.

### To Reproduce

https://codesandbox.io/s/broken-react-suite-form-in-modal-4u3lm?file=/src/index.js

**Comment by simonguo** [comment]
Fixed in [5.4.0](https://github.com/rsuite/rsuite/releases/tag/v5.4.0)

**Comment by electroheadfx** [comment]
I have the same issue with 5.55.0

**Comment by simonguo** [comment]
> I have the same issue with 5.55.0

Change the version of rsuite in the following example to 5.55.0, and the problem cannot be reproduced. Please reproduce your problem
https://codesandbox.io/s/broken-react-suite-form-in-modal-4u3lm?file=/src/index.js

**Comment by electroheadfx** [comment]
Hey Simonguo thanks to point me on this. I will check later for reproduce it.
For now for avoid react re-render I prefer to use useRef:
`<Form onChange={(formValue: object) => (formValueRef.current = formValue)}`
and look the formValueRef.current after onSubmit.
