### ISSUE TITLE
DateRangePicker can't select second date

### ISSUE THREAD

**Issue by raibikys** [rsuite/rsuite#2211]
### What version of rsuite are you using?

5.3.0

### What version of React are you using?

17.0.2

### What version of TypeScript are you using (if any)?

4.3.2

### What browser are you using?

Chrome

### Describe the Bug

On this new version daterangepicker can't select second date. Same on your website where examples are located. Just try it out.

### Expected Behavior

Both dates can be selected.

### To Reproduce

Just visit your rsuite documentation where daterangepicker component is located.

**Comment by simonguo** [comment]
Fixed in [5.4.0](https://github.com/rsuite/rsuite/releases/tag/v5.4.0)
