### ISSUE TITLE
DateRangePicker possibly broken

### ISSUE THREAD

**Issue by AdrienFromToulouse** [rsuite/rsuite#2212]
### What version of rsuite are you using?

5.3.0

### What version of React are you using?

17.0.2

### What version of TypeScript are you using (if any)?

4.5.4

### What browser are you using?

Chrome

### Describe the Bug

Hi there!

Thank you for maintaining `rsuite` that's an awesome library!

The `DateRangePicker` seems to be borken on the documentation.
https://rsuitejs.com/components/date-range-picker/

The picker seems to not select any date anymore.

It seems to be linked to an update on https://github.com/rsuite/rsuite/commit/4c55db9a3a96927589d4366ece1f329c011ccb0f

Cheers,

### Expected Behavior

The date should be updated once picked.

### To Reproduce

Use the latest release `DateRangePicker` as per the documentation.

**Comment by raibikys** [comment]
Relates also to https://github.com/rsuite/rsuite/issues/2211 . Second date can't be selected.

**Comment by SevenOutman** [comment]
Fixed in #2217
