### ISSUE TITLE
Selectpicker search doesn't work in drawer

### ISSUE THREAD

**Issue by dgastudio** [rsuite/rsuite#2225]
### What version of rsuite are you using?

5

### What version of React are you using?

17

### What browser are you using?

chrome

### Describe the Bug

Selectpicker inside drawer, doesn't allow to search 

### Expected Behavior

Should search

### To Reproduce

https://codesandbox.io/s/new-sky-t7rk0

**Comment by raibikys** [comment]
What is that reproduction about?

**Comment by dgastudio** [comment]
sorry, wrong link
updated

**Comment by simonguo** [comment]
hi @raibikys 
We have located the cause of the problem and will fix it soon. 

A solution you put to temporarily solve your problem. Set up a container for SelectPicker.

```tsx
const bodyRef = React.useRef();

<Drawer.Body ref={bodyRef}>
  <SelectPicker container={() => bodyRef.current} />
</Drawer.Body>
```
