### ISSUE TITLE
Search on rsuitejs.com is not working properly

### ISSUE THREAD

**Issue by dgastudio** [rsuite/rsuite#2234]
### What version of rsuite are you using?

5

### What version of React are you using?

17

### What browser are you using?

chrome

### Describe the Bug

Check it yourself
any keypress removes focus from the input because it re-renders the entire component

<img width="248" alt="Home - React Suite 🔊 2021-12-16 23-07-30" src="https://user-images.githubusercontent.com/161524/146441866-7341f881-1afb-47a0-9fed-c0244e11d239.png">

**Comment by simonguo** [comment]
Fixed in https://github.com/rsuite/rsuite/pull/2208
