### ISSUE TITLE
Draggable rows (whole row can be selected, not cell)

### ISSUE THREAD

**Issue by raibikys** [rsuite/rsuite#2238]
### What problem does this feature solve?

I implemented draggable table elements with your example which is integrated with react-dnd. Now only cell can be selected and dragged all over the table. Would be great to have an opportunity to select whole row, and when specific cell is selected then whole row is dragged within. Like a smooth animation. For examples Just check it how antD library team solved this with draggable-sortable rows table component.

**Comment by simonguo** [comment]
Supported in https://github.com/rsuite/rsuite-table/pull/287
