### ISSUE TITLE
表格组件问题

### ISSUE THREAD

**Issue by xiaocheng1997** [rsuite/rsuite#224]
使用可调整列宽 遇到的问题 
当我调整列宽出现滚动条后  如果继续调整后面的列 滚动条会突然回到原点  这样我还要拖动滚动条到后面去查看数据  这样很不方便 能有什么好的解决方法嘛？

**Comment by simonguo** [comment]
@xiaocheng1997 确实存在这个问题，主要原因是列宽的改变导致Table的宽度改变，需要重新计算滚动条的大小以及位置，这个问题我们想办法处理一下。

**Comment by simonguo** [comment]
问题已修复，修复版本： 3.3.1

**Comment by xiaocheng1997** [comment]
之前使用的是单独的rsuite-table rsuite-table能更新嘛 
我使用rsuite 会报错 
Module not found: Can't resolve '@babel/runtime/helpers/objectWithoutPropertiesLoose' in 'D:\xxx\xxx\xxx\node_modules\rsuite\lib'

这个错误一直没解决 我用的是dva-cli 搭建的项目  同时使用了antd  表格只能单独使用rsuite-table

**Comment by simonguo** [comment]
@xiaocheng1997  rsuite-table@3.1.5

**Comment by xiaocheng1997** [comment]
谢谢 OK

**Comment by hiyangguo** [comment]
当列数发生改变时（如：10列边2列），应该重置滚动条的位置。
