### ISSUE TITLE
Toggle Component Changing Uncontrolled Input to Controlled

### ISSUE THREAD

**Issue by cowofevil** [rsuite/rsuite#2240]
### What version of rsuite are you using?

5.2.4

### What version of React are you using?

17.0.2

### What version of TypeScript are you using (if any)?

4.4.4

### What browser are you using?

Chrome

### Describe the Bug

The <Toggle> component is causing a React error in the console log with regards to an input changing from uncontrolled to controlled. This could cause all sorts of problems with event triggers for the component itself which would result in odd rendering behavior under certain circumstances.

Also, this console error is a headache for developers using rsuite because we spend a ton of time trying to figure out where the uncontrolled state error is coming from. (I know because I thought I was messing things up with a very complex component and spent a whole day debugging my own code just to discover it was rsuite all along!)

### Expected Behavior

The <Toggle> component should not cause any React warnings when used correctly by developers.

### To Reproduce

https://codesandbox.io/s/toggle-uncontrolled-input-react-error-y8d9h?file=/src/index.js

(You need to refresh the page an open the console before clicking the toggle control)

I tracked down this error to being first introduced in rsuite 5.2.0.

![Screenshot](https://i.imgur.com/bolt8s0.png)

**Comment by SevenOutman** [comment]
Hi @cowofevil, I didn't see `<Toggle>` usage in the demo you provide. Did you forget to save your changes?

**Comment by cowofevil** [comment]
@SevenOutman Oops! I didn't save it! I just updated the sandbox, please take a look again.

**Comment by SevenOutman** [comment]
> @SevenOutman Oops! I didn't save it! I just updated the sandbox, please take a look again.

I'm able to see the warning now. This should be fixed in next patch release.
