### ISSUE TITLE
Submenus in Navbar do not work anymore

### ISSUE THREAD

**Issue by vykintazo** [rsuite/rsuite#2249]
### What version of rsuite are you using?

5.4.0

### What version of React are you using?

17.0.2

### What version of TypeScript are you using (if any)?

N/A

### What browser are you using?

Chrome

### Describe the Bug

When adding  a submenu inside a `Dropdown` which is part of `Navbar`, the code crashes with an error
```
<MenuItem> must be rendered within a <Menu>
```
This only seems to happen on rsuite >=5.3.0, older versions are fine.
Another perhaps notable detail is that it looks like `MenuItem` mentioned in the error is not the child of `Dropdown.Menu` as the error is present even if `Dropdown.Menu` hasn't got any children. The `MenuItem` in question is probably [this one](https://github.com/rsuite/rsuite/blob/8f79d4a8aafb123f75f420a3adf3f680386aae68/src/Dropdown/DropdownMenu.tsx#L138).

### Expected Behavior

Dropdowns inside navbars should be able to have functioning submenus, as they do when used without navbar.

### To Reproduce

https://codesandbox.io/s/navbar-submenu-bug-sub0t

**Comment by raibikys** [comment]
@SevenOutman is there any chance that this fix will be released soon? Can't use menu in my projects anymore... Everything is braking.

**Comment by SevenOutman** [comment]
> @SevenOutman is there any chance that this fix will be released soon? Can't use menu in my projects anymore... Everything is braking.

There's already a working PR fixing this issue, but it didn't catch up with the release this week.

@simonguo Maybe we should release canary versions so that vital fixes can be delivered in time regardless of the default weekly releasing cycle?

**Comment by raibikys** [comment]
Would be great, good luck in solving the issue.

**Comment by simonguo** [comment]
@SevenOutman If it's some new feature, you can consider releasing canary version according to the situation. If the bug is fixed, the PATCH version will be released directly.
