### ISSUE TITLE
Checkpicker there is a delay in the listing

### ISSUE THREAD

**Issue by Roger-Franco** [rsuite/rsuite#2257]
### What version of rsuite are you using?

5.4.2

### What version of React are you using?

16.14.0

### What browser are you using?

Chrome

### Describe the Bug

There is a delay in listing these orders on Checkpicker. Apparently this only occurs when the listing has many elements. When there are few elements, it is fast. But that didn't happen in the previous versions, I mean in versions 4... I saw that you guys did a new update just today, so I submitted it to my project and I noticed an improvement in this problem. It's loading faster but it's still not as it was in version 4...

![Captura de Tela 2021-12-24 às 11 15 27](https://user-images.githubusercontent.com/78622773/147361851-dd750b0a-ecfc-4cb5-8f87-e9baf4bfb30b.png)

### Expected Behavior

I was hoping that when rendering the order list, it would be faster, as it used to be in versions 4... I believe it's a performance issue

**Comment by SevenOutman** [comment]
Hi @Roger-Franco, see if this comment https://github.com/rsuite/rsuite/issues/2189#issuecomment-989407330 helps.

**Comment by Roger-Franco** [comment]
Hi @SevenOutman, this work for me. Thank you very much...

**Comment by SevenOutman** [comment]
Hi @Roger-Franco, I'm closing this issue as it seems to have been resolved. Feel free to re-open if it's actually not.
