### ISSUE TITLE
Allow Specifying Direction of Submenu Expansion

### ISSUE THREAD

**Issue by cowofevil** [rsuite/rsuite#2267]
### What problem does this feature solve?

The <Nav.Dropdown.Menu> component does not have a property for specifying the direction of expansion and always defaults to "right" expansion. Without being able to specify expansion direction the submenu component cannot be used with a top-right-hand hamburger menu. (See screenshot below)

![screenshot](https://i.imgur.com/CIJTOeZ.png)

### What does the proposed API look like?

The <Nav.Dropdown.Menu> should use the same "placement" prop as <Nav.Dropdown> so a top-right-hand hamburger menu could have a submenu that uses "leftStart" placement to look correct.

**Comment by cowofevil** [comment]
@SevenOutman I just wanted to reach out to let you know that I'm still really interested in seeing this feature get implemented.

**Comment by SevenOutman** [comment]
> @SevenOutman I just wanted to reach out to let you know that I'm still really interested in seeing this feature get implemented.

Hi @cowofevil, thanks for reaching out. The Dropdown API has some legacy design that makes it hard to extend. We are doing a big refactoring for Dropdown API after which we may be able to find a solution to this feature. See PR #2458 and discussion #2456 for details.

**Comment by cowofevil** [comment]
@SevenOutman thanks for the quick reply. I'll watch #2458 for progress and hopefully adding my feature request after merge won't be a big hassle.
