### ISSUE TITLE
Wrong popover placement "auto" calculation

### ISSUE THREAD

**Issue by raibikys** [rsuite/rsuite#2270]
### What version of rsuite are you using?

5.5.2

### What version of React are you using?

17.0.2

### What version of TypeScript are you using (if any)?

4.3.2

### What browser are you using?

Chrome

### Describe the Bug

"auto" whisper placement wrong calculates the popover position.

### To Reproduce

https://codesandbox.io/s/damp-night-hmgt2

**Comment by simonguo** [comment]
I did not find the popover component in your codesandbox example.  If you want the popover to be rendered inside the Table, please add the container property to Whisper.

**Comment by raibikys** [comment]
I'm sorry, wrong url! Thats the correct one:

https://codesandbox.io/s/damp-night-hmgt2

**Comment by simonguo** [comment]
- The overlay should be absolute positioning.
- The coordinates calculated by Whisper need to be passed to overlay.

```tsx
const overlay = (props, ref) => {
  const { left, top, onClose, className } = props;
  return (
    <span style={{ left, top, position: "absolute" }} ref={ref}>
      Hi there!
    </span>
  );
};

function App() {
  return (
    <div className="App" style={{ padding: "3rem" }}>
      <Whisper speaker={overlay} trigger="hover" placement="auto">
        <Button>Hover me</Button>
      </Whisper>
    </div>
  );
}
```

**Comment by SevenOutman** [comment]
Hi @raibikys, I'm closing this issue as it seems to have been resolved. Feel free to re-open if it's actually not.
