### ISSUE TITLE
DatePicker onChange 事件在 clean 时异常

### ISSUE THREAD

**Issue by dekuofa1995** [rsuite/rsuite#2277]
### What version of rsuite are you using?

5.3.0

### What version of React are you using?

17.0.1

### What browser are you using?

Chrome

### Describe the Bug

https://github.com/rsuite/rsuite/blob/a2151208cf6915e98d6df22bab946fabbbe06dca/src/DatePicker/DatePicker.tsx#L265
此处校验没有考虑清理时会传入Null，所以清理功能无法正常使用

可以直接去官网复现
https://rsuitejs.com/components/date-picker/

**Comment by SevenOutman** [comment]
Duplicated with #2269.
