### ISSUE TITLE
Sidenav icon extra padding when using FontAwesomeIcon

### ISSUE THREAD

**Issue by dszmaj7** [rsuite/rsuite#2288]
### What version of rsuite are you using?

5.4.3

### What version of React are you using?

16.14.0

### What browser are you using?

Firefox, Chrome

### Describe the Bug

I have Sidenav with dropdowns in my App. When i put into icon props FontAwesomeIcon instead of rsuite icon, i'm getting some like an extra padding. 

![obraz](https://user-images.githubusercontent.com/14976101/148467656-2020db16-6391-417c-abb3-0ff9987b7298.png)

![obraz](https://user-images.githubusercontent.com/14976101/148468286-d33dfe05-6a0a-46ca-9a70-524971971a07.png)

### Expected Behavior

I would like the FontAwesomeIcons passed by the icon property to be in the same position as the rsuite icons.

![obraz](https://user-images.githubusercontent.com/14976101/148468154-7bfc1fef-6a62-4c7a-a615-1dad65b19593.png)

### To Reproduce

https://codesandbox.io/s/elated-fermat-0dvp9?from-embed

**Comment by SevenOutman** [comment]
Could you provide a CodeSandbox demo so that we can reproduce and debug your case easily? You may use this template https://codesandbox.io/s/rsuite-template-5vq6zo2z5l

**Comment by dszmaj7** [comment]
I've added demo. 

As you can see, fontawesome icon landing above label users, not like rsuite icon for departments.

**Comment by SevenOutman** [comment]
@dszmaj7 Please follow this guide so that you can use fontawesome icons with rsuite. https://rsuitejs.com/components/icon/#font-awesome-icons

I've also forked you demo and fa icons are working fine https://codesandbox.io/s/sidenav-faicons-0s5s1

**Comment by dszmaj7** [comment]
Ok, i missed it in documentation. Sorry for my mistake!
