### ISSUE TITLE
[Toaster] 在定时时间范围之内多次执行，所有的应该过时消失的 Message 都不消失。

### ISSUE THREAD

**Issue by LeiHanCN** [rsuite/rsuite#2314]
### What version of rsuite are you using?

5.5.0

### What version of React are you using?

17.0.0

### What version of TypeScript are you using (if any)?

4.4.4

### What browser are you using?

Chrome

### Describe the Bug

`toaser.push(<Message duration={1000} />)`

这个代码，如果在每隔不到一秒的时间执行，那么之前出现的 Message 都不会消失.
要停止执行一秒之后才开始逐个消失.

### Expected Behavior

上述代码如果在每隔小于一秒的时间内执行，先前产生的 Message 如期在出现1秒之后自动消失。

### To Reproduce

`toaser.push(<Message duration={1000} />)`

每隔小于一秒的时间执行一次，例如每隔 0.8 秒执行一次。

codesanbox: https://codesandbox.io/s/compassionate-swanson-kug2e?file=/src/App.js

**Comment by simonguo** [comment]
我没能复现这个问题，或者我没有明白你的意思，能通过 codesandbox 复现一下这个问题吗?

**Comment by LeiHanCN** [comment]
> 我没能复现这个问题，或者我没有明白你的意思，能通过 codesandbox 复现一下这个问题吗?

@simonguo To Reproduce 中增加了 codesandbox 示例，其中内容为 message 0 的 message 永远都不会消失。
