### ISSUE TITLE
Table horizontal scrollbars jumps over last table element

### ISSUE THREAD

**Issue by raibikys** [rsuite/rsuite#2315]
### What version of rsuite are you using?

5.4.4

### What version of React are you using?

17.0.2

### What version of TypeScript are you using (if any)?

4.3.2

### What browser are you using?

Chrome

### Describe the Bug

![image](https://user-images.githubusercontent.com/70314658/150311659-e818ccc9-14d4-4cd0-9484-38e1e0ae7980.png)

Same in my project.

### Expected Behavior

Needs more margin at the bottom.

### To Reproduce

Check your table documentation examples.

**Comment by raibikys** [comment]
@SevenOutman @simonguo  it's been a while since I had no response on this. Could this be fixed please? :)

**Comment by simonguo** [comment]
Hi @raibikys 
I think you can fit your needs by changing the table height. I don't think this behavior of scrollbars is a problem, it's closer to the way the browser's native scrollbars are displayed.

**Comment by raibikys** [comment]
Changing table height doesn't fix this. Solution is to manualy calculate every rows height - then scrollbar is shown correctly. Othervise if table calculates by himself - horizontal scrollbar overlapses last row.

**Comment by AdrienFromToulouse** [comment]
+1 there should be a way to add an extra few tens of pixel based on the fact that autoheight is set or not.

https://github.com/rsuite/rsuite-table/blob/d16c6b67c4741999b7df17cccf02123b0b194d29/src/utils/useTableDimension.ts#L88

**Comment by simonguo** [comment]
Table does not have table height issues by default. The horizontal scroll bar occupies the height of the table only when `autoHeight` is set. Fixed in https://github.com/rsuite/rsuite-table/pull/362.

**Comment by AdrienFromToulouse** [comment]
> Table does not have table height issues by default. The horizontal scroll bar occupies the height of the table only when `autoHeight` is set. Fixed in [rsuite/rsuite-table#362](https://github.com/rsuite/rsuite-table/pull/362).

@simonguo awesome that you could give some attention to this 👍 
Many thx for your work and rsuite in general ❤️ !
