### ISSUE TITLE
表格组件滚动条bug

### ISSUE THREAD

**Issue by xiaocheng1997** [rsuite/rsuite#234]
### Bug, feature request, or proposal:
表格组件滚动条bug
### What is the expected behavior?
在出现滚动条的表格下 编辑表格行 也就是表格行全是输入框  从第一个输入框 开始 填写
然后 按TAB键 进行下一个输入框填写  直到滚动条滚动  这个时候滚动条应该跟着滚动。总长度应该保持不变！！！

### What is the current behavior?
目前 他有滚动 但是总的滚动条会缩短！！！ 这个bug会导致表格无法拉到后面去

**Comment by simonguo** [comment]
@xiaocheng1997 这个问题的主要原因还是Table的滚动条非原生，是采用HTML元素模拟，在操作 Tab 键的时候触发浏览器一些默认行为，但是滚动条不会更新。  这个问题我们研究一下怎么解决比较合理。
