### ISSUE TITLE
Autocomplete open and defaultOpen not working

### ISSUE THREAD

**Issue by avifatal** [rsuite/rsuite#2344]
### What version of rsuite are you using?

5.24

### What version of React are you using?

17.02

### What version of TypeScript are you using (if any)?

4.4.3

### What browser are you using?

edge & chrome

### Describe the Bug

Autocomplete  open and defaultOpen are not functioning

### Expected Behavior

the menu should be opened

### To Reproduce

https://codesandbox.io/s/kind-framework-ocj3p?file=/src/index.js

**Comment by simonguo** [comment]
hi @avifatal 
Autocomplete requires key characters to retrieve the content before it is displayed. For example, add a defaultValue to `<Autocomplete>`.
```tsx
<AutoComplete open data={data} defaultValue="h"  />
```

Maybe InputPicker can meet your needs.
https://rsuitejs.com/components/input-picker/

**Comment by SevenOutman** [comment]
Hi @avifatal, I'm closing this issue as it seems to have been resolved. Feel free to re-open if it's actually not.
