### ISSUE TITLE
form组件应使用react新的context api

### ISSUE THREAD

**Issue by zpbc007** [rsuite/rsuite#235]
由于[#2517](https://github.com/facebook/react/issues/2517)，当FormControl作为一个PureComponent的子组件时，无论From上的data如何变化，FormControl都不会作出响应。

[![Edit rsuite form context bug](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ko90rpnlm5)

**Comment by simonguo** [comment]
目前的版本，如果使用 context 新的 API 应该会存在历史兼容性问题。不妨先用 `shouldComponentUpdate` 自己进行判断来代替 `PureComponent `

**Comment by zpbc007** [comment]
好的，谢谢。
