### ISSUE TITLE
caretAs is not changing the DateRangePickers icon

### ISSUE THREAD

**Issue by alieliacik** [rsuite/rsuite#2356]
### What version of rsuite are you using?

^5.6.0

### What version of TypeScript are you using (if any)?

17.0.2

### What browser are you using?

Chrome

### Describe the Bug

import DateRangeIcon from '@mui/icons-material/DateRange'

     <DateRangePicker
        onChange={(e) => console.log(e)}
        caretAs={<DateRangeIcon />}
      />

### Expected Behavior

I am not able to change the icon.

**Comment by simonguo** [comment]
hi @alieliacik  fixed in `rsuite@5.6.1`

```diff
<DateRangePicker
    onChange={(e) => console.log(e)}
-    caretAs={<DateRangeIcon />}
+    caretAs={DateRangeIcon}
  />
```
