### ISSUE TITLE
Nested tables are broken

### ISSUE THREAD

**Issue by dgastudio** [rsuite/rsuite#2367]
### What version of rsuite are you using?

5

### What version of React are you using?

17

### What browser are you using?

chrome

### Describe the Bug

nested table loses classes

### To Reproduce

https://codesandbox.io/s/cool-goldberg-uixpo4?file=/src/index.js

**Comment by dgastudio** [comment]
![CleanShot 2022-02-20 at 22 14 31@2x](https://user-images.githubusercontent.com/161524/154860058-68b31a82-4f69-4044-843d-01f06b713b89.png)

**Comment by simonguo** [comment]
Sorry, table nesting is not supported
