### ISSUE TITLE
MultiCascader menu collapsed when using onChange()

### ISSUE THREAD

**Issue by PotatoPlan** [rsuite/rsuite#2380]
### What version of rsuite are you using?

5.6.2

### What version of React are you using?

16.14.1

### What version of TypeScript are you using (if any)?

None

### What browser are you using?

Chrome

### Describe the Bug

Every time when firing onChange() and save the user input data into a state, the 3-level MultiCascader menu will be collapsed to the first level.

### Expected Behavior

It should be look like the demo here: https://rsuitejs.com/components/multi-cascader/#props

No matter how many times I check and uncheck the option, the menu stays where it is (if it's level 2, then it stays at level 2, if it's level 3, then it stays at level 3).

### To Reproduce

https://codesandbox.io/s/rsuite-hello-world-5-0-forked-2olr2c?file=/src/index.js

**Comment by simonguo** [comment]
Hi @PotatoPlan , what causes the menu to collapse is that the data update causes it to re-render.

The `testingData` defined inside the App component will generate a new array every time it is rendered, and we should define it outside the component.

```diff
+ const testingData=[...]

const App = () => {
- const testingData=[...]
  const [theValue, setValue] = React.useState(["1-1", "1-2"]);
  
 return (
    <MultiCascader onChange={setValue} value={theValue} data={testingData} />
  );
}
```

Can also be `useMemo` to avoid data updates.

```jsx
const App = () => {

 const testingData= React.useMemo(()=>([...]), []);
 const [theValue, setValue] = React.useState(["1-1", "1-2"]);
  
 return (
    <MultiCascader onChange={setValue} value={theValue} data={testingData} />
  );
}
```

**Comment by PotatoPlan** [comment]
> Hi @PotatoPlan , what causes the menu to collapse is that the data update causes it to re-render.
> 
> The `testingData` defined inside the App component will generate a new array every time it is rendered, and we should define it outside the component.
> 
> ```diff
> + const testingData=[...]
> 
> const App = () => {
> - const testingData=[...]
>   const [theValue, setValue] = React.useState(["1-1", "1-2"]);
>   
>  return (
>     <MultiCascader onChange={setValue} value={theValue} data={testingData} />
>   );
> }
> ```
> 
> Can also be `useMemo` to avoid data updates.
> 
> ```js
> const App = () => {
> 
>  const testingData= React.useMemo(()=>([...]), []);
>  const [theValue, setValue] = React.useState(["1-1", "1-2"]);
>   
>  return (
>     <MultiCascader onChange={setValue} value={theValue} data={testingData} />
>   );
> }
> ```

Hi Simon,

Appreciate your answer!! I'll try to do this now.

Thank you so much.

**Comment by SevenOutman** [comment]
Hi @PotatoPlan, I'm closing this issue as it seems to have been resolved. Feel free to re-open if it's actually not.
