### ISSUE TITLE
Table automatic Height based on parent div

### ISSUE THREAD

**Issue by nfnvsc** [rsuite/rsuite#2406]
### What problem does this feature solve?
Currently the `Table` component only allows the height prop to be manually set, or either to use the `autoHeight` prop which does not seem to respect the parent div size.

### What does the proposed API look like?
The idea is to create a new prop, or to add the possibility to set a % on the current `height` prop so that it can automatically scale with the height of the parent div just like the width does.

**Comment by simonguo** [comment]
https://github.com/rsuite/rsuite-table/pull/330

**Comment by SevenOutman** [comment]
`fillHeight` is now available in 5.9.0

**Comment by Xrzys** [comment]
Does `fillHeight` only work on explicit parent heigh? What if parent is 100% heigh flex box?
