### ISSUE TITLE
Dropdown with popover, no hover highlight

### ISSUE THREAD

**Issue by dgastudio** [rsuite/rsuite#2412]
### What version of rsuite are you using?

5

### What version of React are you using?

17

### What browser are you using?

chrome

### Describe the Bug

Standard dropdown
![CleanShot 2022-03-22 at 23 56 54@2x](https://user-images.githubusercontent.com/161524/159574524-8e9df289-b606-4b2a-b9db-a6955d241368.png)

Popover dropdown
![CleanShot 2022-03-22 at 23 57 21@2x](https://user-images.githubusercontent.com/161524/159574581-fde153b7-0958-4444-b765-7c514104fbca.png)

there are no hover effect applied on menu items (except nested one)

### To Reproduce

https://next.rsuitejs.com/components/dropdown/
Dropdown user with popover

**Comment by SevenOutman** [comment]
Closed via #2415
