### ISSUE TITLE
Invalid options object About PostCSS Loader

### ISSUE THREAD

**Issue by PrinOrange** [rsuite/rsuite#2436]
Invalid options object for PostCSS Loader

Today (2022-4-7) I try to follow the custom theme with create-react-app tutorial in the official documentation

(https://rsuitejs.com/zh/guide/use-with-create-react-app/)

After following the tutorial completely in a blank project,and I promise to follow the steps of the official documentation without any errors, I found the following error in my React:

---

Compiled with problems:X

ERROR in ./node_modules/rsuite/styles/index.less (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[9].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[9].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[1].oneOf[9].use[3]!./node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[9].use[4]!./node_modules/rsuite/styles/index.less)

Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
ValidationError: Invalid options object. PostCSS Loader has been initialized using an options object that does not match the API schema.

- options has an unknown property 'plugins'. These properties are valid:
  object { postcssOptions?, execute?, sourceMap?, implementation? }
  at validate (E:\DragonBook\myblog_cms\node_modules\schema-utils\dist\validate.js:105:11)
  at Object.getOptions (E:\DragonBook\myblog_cms\node_modules\webpack\lib\NormalModule.js:585:19)
  at Object.loader (E:\DragonBook\myblog_cms\node_modules\postcss-loader\dist\index.js:40:24)

---

I have tried to solve these problems, but nothing works. I initially thought **there was a conflict between the postCSS loader and the current React Webpack configuration**.

This error can still be reproduced on most computers.
I think the tutorial above on the official documentation is outdated. So I sincerely hope that the operation and maintenance of the project can correct the errors in the official documents.

**Comment by SevenOutman** [comment]
Hi @PrinOrange, could you show me your `postcss-loader`/`postcss` options and versions?

**Comment by SevenOutman** [comment]
Looks like it's an [issue within `customize-cra`](https://github.com/arackaf/customize-cra/issues/315). Consider replacing it with tools like `craco`. We may also have to update our documentation.

**Comment by Seldom29** [comment]
Same problem I encountered. Latest version of customize-cra and less-loader were installed.

**Comment by SevenOutman** [comment]
> Same problem I encountered. Latest version of customize-cra and less-loader were installed.

See if [this solution](https://github.com/arackaf/customize-cra/issues/315#issuecomment-1017081592) works.

**Comment by PrinOrange** [comment]
Stale
