### ISSUE TITLE
defaultValue problem when validating form

### ISSUE THREAD

**Issue by erfanpaslar** [rsuite/rsuite#2437]
### What version of rsuite are you using?

5.6.3

### What version of React are you using?

17.0.2

### What version of TypeScript are you using (if any)?

4.1.2

### What browser are you using?

Brave, Chrome

### Describe the Bug

When I use rsuite form validation and have a `defaultValue` prop for a text field, if the field is required, The Form won't submit and says that field is required.

So it's like I'm using `placeholder`

### Expected Behavior

It should validate the field by it's defaultValue to and treat it like an entered value not a placeholder

### To Reproduce

![image](https://user-images.githubusercontent.com/53585129/162266053-3348d0b6-1783-4e61-b77d-44b254d42a12.png)

**Comment by SevenOutman** [comment]
Hi @erfanpaslar, if you're using this text field within the `<Form>` component, you should use `formDefaultValue` prop of `<Form>` to set the initial value for the whole form, rather than setting them separately on fields.

**Comment by erfanpaslar** [comment]
@SevenOutman  Wow That worked, Thanks.
