### ISSUE TITLE
DateRangePicker - rsuit css is disturbing project's overall global css

### ISSUE THREAD

**Issue by VishalDudeja** [rsuite/rsuite#2472]
### What version of rsuite are you using?

5.8.0

### What version of React are you using?

17.0.2

### What version of TypeScript are you using (if any)?

none

### What browser are you using?

Chrome, Firefox, Safari

### Describe the Bug

I'm using rsuit  v5.8.0", Date Range Picker in React.js project,  and importing CSS using '/node_modules/rsuite/dist/rsuite.css''
But the imported rsuit css is disturbing project's overall global css 
Is there any way to prevent this? 
![Uploading rsuit css issue.png…]()

### Expected Behavior

rsuit.css shouldn't impact the overall css of the project.

### To Reproduce

just integrate DateRangePicker and import CSS using '/node_modules/rsuite/dist/rsuite.css''

**Comment by SevenOutman** [comment]
Answered in discussion #2471
