### ISSUE TITLE
CheckTreePicker does not update correctly

### ISSUE THREAD

**Issue by ivan-bragin** [rsuite/rsuite#2486]
### What version of rsuite are you using?

5.11

### What version of React are you using?

16.8 - 18

### What browser are you using?

Chrome, Edge

## Issue
It seems that the CheckTreePicker(CTP for short) component does not update its internal state properly when the data attribute is changed.
## My Case 
I have a custom filter for a tree, based on an additional attribute, so it makes sense to have a separate selector instead of custom filtering everything on the CTP. Before I filter everything is working correctly, but when I reassign the data attribute and try to pick an item I am getting duplicated key error and in the selected list I can see two same items instead of one(ex. two Node 7 items, even tho there is only one in the tree).

### Expected Behavior

To not have a duplicated key issue when changing the data attribute

### To Reproduce

# Steps to reproduce: 
- render CTP with initial data value
- reassign data value with filtered/rearranged value
- select an item -> leads to duplicated key error

Sandbox link - https://codesandbox.io/s/cranky-davinci-11s578?file=/src/App.tsx

**Comment by ivan-bragin** [comment]
Hey, @superman66 ! Are there any updates on the topic?

**Comment by superman66** [comment]
hi, @ivan-bragin I was busy these days. i'm be working on it, this bug will be fixed this week.

**Comment by PankajKumarSh** [comment]
![Capture22](https://user-images.githubusercontent.com/97426526/220081194-d36a6cb2-2d11-409c-94f0-c9516e168c8e.PNG)
Hii 
i am not able to writing on input box of serached in this component 
can anyone help me regarding this

**Comment by SevenOutman** [comment]
Hi @PankajKumarSh , 
Could you provide a CodeSandbox demo? You may use this template https://codesandbox.io/s/rsuite-template-5vq6zo2z5l
