### ISSUE TITLE
Popover on window/container resize

### ISSUE THREAD

**Issue by mohammedzamakhan** [rsuite/rsuite#250]
### Bug, feature request, or proposal:
Bug

### What is the expected behavior?
The popover should remain at the position where it opened after resize of the window or resize of the container

### What is the current behavior?
Changes the position

### What are the steps to reproduce?

![resize browser](https://user-images.githubusercontent.com/2327532/47931840-f9624980-de9d-11e8-92d4-9922bd1276ac.gif)

**Comment by simonguo** [comment]
This is indeed a bad experience. You can change the position using ref. Although this method is not very convenient, it can solve your current problem.

```js
<Whisper
    placement="top"
    speaker={speaker}
    positionRef={ref => {
       this.position = ref;
    }}
>
    <span>Popover</span>
</Whisper>
```

```js
on(window, 'resize', ()=>{
   this.position.updatePosition(true)
});
```
