### ISSUE TITLE
Lack of information

### ISSUE THREAD

**Issue by RamonPessoa** [rsuite/rsuite#2501]
Hi, i'm starting a lot of issues becaus i like the lib and I Want it to go on, so...

Maybe for a lot of people, it's easy to figure out how things work, but for some people it's not. There is no area showing how to use the methoda of a component, or it's not easely found. I had to guess using refs work, and I had to go through the files to find the typing of the methods to parse to the ref generics. I cant find a lot of information in the docs

**Comment by SevenOutman** [comment]
Hi @RamonPessoa, thanks for reaching out! Could you be more specific about which components are you referring to, so that we can improve our documentation?

**Comment by RamonPessoa** [comment]
> Hi @RamonPessoa, thanks for reaching out! Could you be more specific about which components you were referring to, so that we can improve our documentation?

I was trying to trigger the Wihisper component to open, and I saw there is a method in documentation, but no explanation on how to trigger the method, I figured out that I can use ref to do that, but there is also no typing specifications.

In the end I was able to do what I wanted, but not using the docs

**Comment by SevenOutman** [comment]
@RamonPessoa Thanks for providing the information. I'm sure the docs should have mentioned the ref.
