### ISSUE TITLE
Typing problems in form ref

### ISSUE THREAD

**Issue by RamonPessoa** [rsuite/rsuite#2515]
### What version of rsuite are you using?

5.9.0

### What version of React are you using?

17.0.2

### What version of TypeScript are you using (if any)?

4.4.4

### What browser are you using?

chrome

### Describe the Bug

The check method has a typing problem, I cant call it
![image](https://user-images.githubusercontent.com/91036565/171265802-06ef2c0c-140c-4d7f-b78d-7e2bd07f3a37.png)

And another problem is that I have to import the FormInstance type to type my ref and the check method is possibly undefined, that's why I get the error above

### To Reproduce

Import the FormInstance and type yout formRef with FormInstance, then try to call a method

**Comment by SevenOutman** [comment]
Hi @RamonPessoa,

Could you provide a CodeSandbox demo? You may use this template https://codesandbox.io/s/rsuite-template-5vq6zo2z5l

**Comment by RamonPessoa** [comment]
> Hi @RamonPessoa,
> 
> Could you provide a CodeSandbox demo? You may use this template https://codesandbox.io/s/rsuite-template-5vq6zo2z5l

in this example I used two different forms and form refs, for you to see that I need to import the FormInstance or I won't have the typing, but all methods inside FormInstance are possibly undefined and I can't invoke a possibly undefined object

oh and I had to reload the page to code sand box show the error, in case it doesn't appear to you, and it also has a delay to show up

https://codesandbox.io/s/rsuite-typescript-error-uyucxe

Error without FormInstance
![image](https://user-images.githubusercontent.com/91036565/171393455-7cc5f1cf-9a63-4545-b456-c8fca8ba4371.png)

Error with FormInstance
![image](https://user-images.githubusercontent.com/91036565/171394056-503bcb47-e4b2-4de1-b0a4-90a4bf365994.png)
