### ISSUE TITLE
DateRangePicker: Ok button still not clickable v5.15.2

### ISSUE THREAD

**Issue by akrutsko-intellective** [rsuite/rsuite#2569]
### What version of rsuite are you using?

5.15.2

### What version of React are you using?

"^17.0.2 || ^18.1.0"

### What browser are you using?

Chrome Version 102.0.5005.115 (Official Build) (64-bit)

### Describe the Bug

Retested in latest release issue https://github.com/rsuite/rsuite/pull/2564
Still does not work as expected
![chrome_bbViGfLfLO](https://user-images.githubusercontent.com/72732536/176890881-b87b6536-9903-4dbc-aa83-6577cf63f1ce.gif)

**Comment by simonguo** [comment]
@akrutsko-intellective The version number in the documentation has not been updated, the documentation will be updated later. However, you can use rsuite@5.15.1 directly in your project to verify. Below is the preview page after the fix.
https://rsuite-nextjs-git-fix-daterangepicker-shortcut-rsuite.vercel.app/components/date-range-picker/

@SevenOutman The version of rsuite was not updated to 5.15.2 in the documentation.
https://github.com/rsuite/rsuite/blob/2ffe767d019be5c648e9d0bbbf725f62bbf043c8/docs/package.json#L48

**Comment by SevenOutman** [comment]
> @SevenOutman The version of rsuite was not updated to 5.15.2 in the documentation.
> 
> https://github.com/rsuite/rsuite/blob/2ffe767d019be5c648e9d0bbbf725f62bbf043c8/docs/package.json#L48

It's fixed now.
