### ISSUE TITLE
Button's color prop not working

### ISSUE THREAD

**Issue by aaroneva43** [rsuite/rsuite#2596]
### What version of rsuite are you using?

5.16.0

### What version of React are you using?

16.14.0

### What browser are you using?

Chrome

### Describe the Bug

color property is not working on Button -- <Button color="green">Green</Button>

### Expected Behavior

Color applied to the button

### To Reproduce

https://codesandbox.io/s/rsuite-button-5-x-forked-b0ipr9?file=/src/index.js

**Comment by simonguo** [comment]
You need to set `appearance` for Button. https://rsuitejs.com/components/button/#colorful-button
```tsx
<Button appearance="primary" color="green">
  Green Button
</Button>
```

**Comment by aaroneva43** [comment]
Thanks, I was in the wrong version of docs  lol
