### ISSUE TITLE
Slider on change shows artefacts

### ISSUE THREAD

**Issue by yurii-averin-dev-optima** [rsuite/rsuite#2598]
### What version of rsuite are you using?

5.6.0

### What version of React are you using?

17.0.2

### What version of TypeScript are you using (if any)?

4.1.2

### What browser are you using?

Chrome (MacOS and Windows), Safari

### Describe the Bug

Chrome (screen recording attached):

https://user-images.githubusercontent.com/37195050/179466146-8c0a0745-8565-4b23-9df1-cb4957c17c81.mov

Safari (screen recording attached):

https://user-images.githubusercontent.com/37195050/179466203-5d162a39-0b82-4efc-a0b9-d921b80b982c.mov

### Expected Behavior

Slider on change should not show artefacts.

### To Reproduce

Move slider.

**Comment by flexguy** [comment]
We also have this issue

**Comment by YevhenShalenko** [comment]
I have the same issue in my project.

**Comment by simonguo** [comment]
We will fix it asap. In order not to affect the use, you can temporarily add a css override to fix it.
```css
.rs-slider-handle{
  outline: none
}
```

**Comment by yurii-averin-dev-optima** [comment]
Thanks @simonguo, I will try this workaround.
