### ISSUE TITLE
TypeScript  Dropdown.Menu TS2339 

### ISSUE THREAD

**Issue by Link-Kou** [rsuite/rsuite#261]
在TypeScript中

<Dropdown.Menu eventKey="4-3" title="Custom Action">

会提示
TS2339: Property 'eventKey' does not exist on type 'IntrinsicAttributes & DropdownMenuProps & { children?: ReactNode; }'.

**Comment by simonguo** [comment]
这个问题已经修复了， 更新到 rsuite@3.4.2
