### ISSUE TITLE
Tree组件不能自定义行高

### ISSUE THREAD

**Issue by HanShuai-me** [rsuite/rsuite#2616]
### What problem does this feature solve?
可以自定义Tree组件每个节点的行高

### What does the proposed API look like?
`<Tree rowHeight={number}>`

**Comment by simonguo** [comment]
TreeNode 的高度默认情况下是没有设置固定高度，同时会根据内容文字的长度自动换行。如果你希望固定自定义可以通过 `renderTreeNode` 去自定义 Tree 节点，设置高度... 

如果你使用了 virtualized ，行高则必须固定，可以通过  listProps 设置行高。

```tsx
<Tree virtualized listProps={{ rowHeight:70 }} />
```

**Comment by HanShuai-me** [comment]
ts 模板下想要按照上述设置listProps必须包含{rowHeight，height，rowCount，width，rowRenderer}就会变得很冗余，能否提供一个简单设置行高的属性

**Comment by simonguo** [comment]
后续会 `Partial<listProps>` 处理，你可以先过滤该校验。

```tsx
<Tree virtualized listProps={{ rowHeight: 70 } as any} />
```
