### ISSUE TITLE
rsuite v5 - Datepicker doesn't work correctly on browser Firefox

### ISSUE THREAD

**Issue by daisy381** [rsuite/rsuite#2625]
### What version of rsuite are you using?

5.0.3

### What version of React are you using?

17.0.2

### What browser are you using?

Firefox

### Describe the Bug

When you click on the datepicker, the focus goes to the input element (in Google, when you click on the component, it immediately opens), only after the second click, the modal opens. In earlier versions 3 and 4 it works fine.

Using onClick one level above the elements and changing the state to open didn't help

### Expected Behavior

In order for the Firefox browser to work correctly in the same way as Google Chrome

**Comment by daisy381** [comment]
If someone is interested in how to get around this bug, I would like to show probably not the most correct one, but how I decided
To open correctly, I added a "div" wrapper and added a click event to it when it was pressed so that it opens
```
<div
    className='proxy-datepicker'
    style={{cursor:'pointer'}}
    onClick={proxyClick}>
        <DatePickerRS {...config}/>
</div>
```
config has state:
```
open: open
 onExit:()=>setOpen(false),
 onOk : ()=>setOpen(false),
```
```
function proxyClick (event) {
        if(event.target.classList.contains('rs-picker-toggle-textbox') ||
            event.target.classList.contains('proxy-datepicker')){
                setOpen(true);
        }
    }
```

now everything opens fine but there is one problem when clicking outside the datepicker container it won't close
to close when the outer container is clicked, you can use [https://stackoverflow.com/questions/32553158/detect-click-outside-react-component](url)

**Comment by simonguo** [comment]
hi @daisy381 
We will fix it asap. Below is a temporary solution to override via css.

```css
.rs-picker-toggle-read-only{
  pointer-events: unset;
}
```
