### ISSUE TITLE
Tree 组件可以自动展开选中父节点

### ISSUE THREAD

**Issue by HanShuai-me** [rsuite/rsuite#2630]
### What problem does this feature solve?
自动展开选中节点的所有父节点

### What does the proposed API look like?
`<Tree autoExpandParent={boolean}>`

**Comment by simonguo** [comment]
### 展开节点

默认展开所有节点你可以使用: `defaultExpandAll`

```tsx
<Tree defaultExpandAll />
```

如果只是想默认展开一级父节点可以使用: `defaultExpandItemValues`

```tsx

const data=[...]
const expandValues=data.map(item=>item.value);

return <Tree defaultExpandItemValues={expandValues} />
```

如果想要展开的节点受控可以使用: `expandItemValues`

### 选中节点

如果要默认选中节点使用: defaultValue，受控使用 value。但是没办法选中所有父节点，因为 Tree 组件只支持单选，如果你要多选请使用 [CheckTree](https://rsuitejs.com/components/check-tree/)
