### ISSUE TITLE
[Web accessibility] `Input` does not handle the action confirmed when the user keyboard input 'Enter' / 'Return' / 'NumpadEnter'

### ISSUE THREAD

**Issue by cangSDARM** [rsuite/rsuite#2659]
### What version of rsuite are you using?

latest

### What version of React are you using?

17.0.3

### What version of TypeScript are you using (if any)?

4.4.3

### What browser are you using?

Chrome 103

### Describe the Bug

For better accessibility, Input should handle the "confirm" action for keyboard keys. The current version of Input does not handle it correctly

### Expected Behavior

handle "confirm" keys like "enter", "numpadenter"

**Comment by SevenOutman** [comment]
Form submission on Enter key is not supposed to be handled by inputs but the form. The browser has already implemented it for `<form>` elements which contain a `type="submit"` button.

**Comment by cangSDARM** [comment]
You mean I need to wrap a form? If yes, then I will close this issue

**Comment by SevenOutman** [comment]
> You mean I need to wrap a form? If yes, then I will close this issue

Yes. Wrap the input in a `<form>` element and (better) make sure there's a submit button within the form, your browser would automatically handle the Enter key for you.
