### ISSUE TITLE
Table tree with custom Cell first - rowData undefined

### ISSUE THREAD

**Issue by AdrienFromToulouse** [rsuite/rsuite#2666]
### What version of rsuite are you using?

latest

### What version of React are you using?

18

### What version of TypeScript are you using (if any)?

latest

### What browser are you using?

Chrome, Safari, Firefox

### Describe the Bug

Hi, 

We noticed an issue with Table as tree and custom Cell.

It seems that having a custom cell placed in the **first** Column of a Table tree would end up crashing all the table's handlers such as `renderTreeToggle` or `onExpandChange` because `rowData` would be `undefined`.

Here is a code sandbox link to reproduce the issue: https://codesandbox.io/s/cool-montalcini-ycvy5w?file=/index.js

- when using `<LabelCell dataKey="label" />` the handlers would crash 🚫 
- when using `<Cell dataKey="label" />` all good ✅ 

Cheers,

### Expected Behavior

The `rowData` should be defined as per "normal" Cell. We should be able to have custom cell in the first column of a Table tree.

### To Reproduce

https://codesandbox.io/s/cool-montalcini-ycvy5w?file=/index.js

**Comment by simonguo** [comment]
After you destructure the Cell props, you should pass the rowData and rowKey to the Cell, because they will be used inside the Cell.

```diff
const LabelCell = ({ rowData, dataKey, ...props }) => (
-  <Cell {...props} style={{ padding: 0 }}>
+  <Cell {...props} rowData={rowData} dataKey={dataKey} style={{ padding: 0 }}>
    <div
      style={{
        width: 40,
        height: 40,
        background: "#f5f5f5",
        borderRadius: 6,
        marginTop: 2
      }}
    >
      {rowData.label}
    </div>
  </Cell>
);
```

**Comment by AdrienFromToulouse** [comment]
Thanks for your answer!

Ok, that's only true for the first column then, because the exact same custom cell placed anywhere else would not make the handlers have a rowData undefined. 

If so, and if it is specific to this use case then we could update the current documentation to add a warning or a full example of a custom cell placed in the first column of a tree table.

**Comment by simonguo** [comment]
Thanks for your suggestion.
We will continue to improve the documentation and add relevant warning on the use of component props.
