### ISSUE TITLE
How to implement js file export *.d.ts

### ISSUE THREAD

**Issue by fannaoshaoxiang** [rsuite/rsuite#269]
有没有相关的资料可以借鉴参考，如何将一个普通js文件，导出 *.d.ts 说明。
我看到你们的项目中，组件都是js结尾的，然后桥接了TypeScript，我没有看明白你们是如何做到了。
能否透露告知一下

**Comment by simonguo** [comment]
@fannaoshaoxiang  

如果你想要自动生成 .d.ts  文件，我能想到比较方便的方法就是写一个 Babel 插件，去解析组件的 PropTypes, 或者解析 Flow 的 Props。然后再做一些规则匹配处理 function，enum等类型。

可以参考相似的代码
https://github.com/simonguo/babel-plugin-transform-react-flow-handled-props/blob/6a31ed2c495b25fdda3505528536610c8a53b0a8/src/visitors/propVisitor.js#L74-L92

我们的 types 文件的定义，是我们加上社区的朋友们一起写的。

**Comment by fannaoshaoxiang** [comment]
我自己写一个 简单的组件
```
取名 demojs.js

import React from "react";

export default class demojs extends React.Component {

    constructor(props) {
        super(props);
    }

    render() {
        return (
            <div>

            </div>
        );
    }
}
```

```
取名 demojs.d.ts

declare const demojs: React.ComponentType;
export default demojs;
```

实际情况是
引用
```
import {demojs} from "./demojs"

```

出现两个错误

TS6133: 'demojs' is declared but its value is never read

TS2305: Module **  has no exported member 'demojs'.

**Comment by simonguo** [comment]
使用者通过 npm 安装你的组件，会读取 package.json 中的 typings 来解析你的定义。

https://github.com/rsuite/rsuite/blob/63ec8c011e55d3ad4a68b9908e04e92461299439/package.json#L6

你也可以把你定义的 d.ts 文件提交到这个仓库：[DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)
