### ISSUE TITLE
Risk: RSuite already exists

### ISSUE THREAD

**Issue by Fordi** [rsuite/rsuite#27]
Hey, I'm not like an official rep of Orbis or anything - I just used to work for them when they were RSI.

They own the trademark "[RSuite](https://www.orbistechnologies.com/rsuite)" - which is an XML content management system written in Java, XQuery, and Javascript.

I know updating your name is a pain - and it might not even be a thing - but the new management are not as laid back as the people I worked with, so you might get a C&D.

Just thought I'd give you a heads-up so you can get ahead of things.

**Comment by SevenOutman** [comment]
@Fordi Thanks for letting us know! We'll be working on this issue.
