### ISSUE TITLE
Navbar > Nav > Nav.Menu open by hovering of mouse

### ISSUE THREAD

**Issue by Han-D-Peter** [rsuite/rsuite#2720]
### What problem does this feature solve?
I have to click menu if I want to see menu's items now
Sometimes we want to show my navbar that can be opened by hovering of a mouse.

### What does the proposed API look like?
If i want to see items in menu, I should just click menu. but I wish menu has hovering feature so when it has hovering feature, it doesn't have arrow icon. when I make a mouse move to menu section, menu will be opened automatically

**Comment by simonguo** [comment]
hi @Han-D-Peter  `<Nav.Menu>` has a trigger property which when set to `hover` can meet your needs. 
```tsx
<Nav.Menu title="title" trigger="hover" />
```
But the above code works under `<Nav>`, but not inside `<Navbar>`, this should be a bug. @SevenOutman please fix it.
