### ISSUE TITLE
The last item of CheckTreePicker is invisible if virtualized and renderExtraFooter

### ISSUE THREAD

**Issue by begoat** [rsuite/rsuite#2733]
### What version of rsuite are you using?

5.18.1

### What version of React are you using?

18.2.0

### What browser are you using?

Chrome latest

### Describe the Bug

When `<CheckTreePicker />` received both `virtualized` and `renderExtraFooter` props, the last item is invisible.

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/22862294/190946691-9b8edbae-208e-4e8a-a21a-26766b4cf582.png">

data we provided with `Picker` ranges from demo0 --- demo299

### Expected Behavior

All options are visible

### To Reproduce

https://codesandbox.io/s/adoring-gould-755g2n?file=/src/App.js:0-511

**Comment by simonguo** [comment]
Fixed in  #2745

Fixed example: https://codesandbox.io/s/strange-davinci-6e7ssd
![image](https://user-images.githubusercontent.com/1203827/191488052-e3371951-b06b-4ec5-8150-4fc496329763.png)
