### ISSUE TITLE
Dropdown trigger=hover 時disabled 下仍然會顯示

### ISSUE THREAD

**Issue by calvin1012** [rsuite/rsuite#2737]
### What version of rsuite are you using?

5.16.1

### What version of React are you using?

17.0.2

### What browser are you using?

Chrome

### Describe the Bug

Dropdown trigger=hover時 disabled 下仍然會顯示

Example: https://codesandbox.io/s/upbeat-bohr-llneel

**Comment by simonguo** [comment]
Fixed in https://github.com/rsuite/rsuite/pull/2740. 
Example: https://codesandbox.io/s/brave-maxwell-39c1iu
