### ISSUE TITLE
CheckPicker lacking space between Label and value

### ISSUE THREAD

**Issue by gomesmat** [rsuite/rsuite#2738]
### What version of rsuite are you using?

5.18.1

### What version of React are you using?

18.2.0

### What browser are you using?

Firefox, Safari, Chrome

### Describe the Bug

Minor bug.
The CheckPicker component doesnt have a space character between the "Label:" and the selected value(s).
This behaviour doesnt happen in the SelectPicker component.

I tried snooping around and suspect the issue occurs in the Picker component, but i'm not sure.

Weird thing is that there's a [test condition specifically for this case](https://github.com/rsuite/rsuite/blob/6b37ff40b46928fb7258990b9a80ef512417fb2a/src/CheckPicker/test/CheckPickerSpec.js#L424), so i imagine that the issue is somewhere in the styling, instead the value itself (?).

<img width="344" alt="image" src="https://user-images.githubusercontent.com/21205109/190562665-6659a517-747f-45db-9333-3439ba255aa8.png">

### Expected Behavior

The CheckPicker to have a space between the colon from the label and the selected value(s), just like SelectPicker does.
picker

**Comment by simonguo** [comment]
Fixed in https://github.com/rsuite/rsuite/pull/2739
