### ISSUE TITLE
Can't use a Table component with both sort and react-dnd

### ISSUE THREAD

**Issue by yuta519** [rsuite/rsuite#2752]
### What version of rsuite are you using?

5.6.6

### What version of React are you using?

17.0.39

### What browser are you using?

Chrome

### Describe the Bug

I'm using a table component.  And I'm trying to use both sort and react-dnd, referring the docs ([sort](https://rsuitejs.com/components/table/#sort), [dnd](https://rsuitejs.com/components/table/#draggable-with-react-dnd)).

So I added `sortable` at Column tag on this [Codesandbox](https://codesandbox.io/s/rsuite5-table-with-react-dnd15-ttrsck).

But any sort icons does not happen. From my research, I think the icons go to next line like below screenshot.

![Screen Shot 2022-09-23 at 10 06 57](https://user-images.githubusercontent.com/12853233/191877132-584e8aa5-136d-4381-aa20-d2b8c8ad11e6.png)

### Expected Behavior

My expectation is using both sort and dnd well.

**Comment by simonguo** [comment]
https://github.com/rsuite/rsuite/discussions/2766
Duplicate discussions will be closed.
