### ISSUE TITLE
invalid value of DateRangePicker causing page crash

### ISSUE THREAD

**Issue by begoat** [rsuite/rsuite#2756]
### What version of rsuite are you using?

5.18.1

### What version of React are you using?

18.2.0

### What browser are you using?

Chrome

### Describe the Bug

When I pass `invalid Date object` as value to `<DateRangePicker />`, the page will crash...
![image](https://user-images.githubusercontent.com/22862294/191884715-3413409d-a0c0-433e-8804-7bdabd498e63.png)

Actually I upgrade from Rsuite v4. Rsuite V4 handles this scenario well, but when i upgrade to v5, the page crash.
There maybe other smiliar scenarios like this in our repo, if rsuite v5 can hahavior the same like v4, the transition will be smoother.

### Expected Behavior

Rsuite5 handles exception case well. At least the page will not crash.

### To Reproduce

https://codesandbox.io/s/peaceful-matsumoto-u24eud?file=/src/App.js

**Comment by simonguo** [comment]
The library developer throws out syntax errors in programming that the end developer must fix. I don't think it's a problem, it even makes the app stronger.

What needs to be done in the component library is to locate errors and guide developers to make quick fixes.

**Comment by begoat** [comment]
Yeah, It can make the app stronger if we carefully locate all potential problems.

But for the component library, if library handles it well, things will be **easier**, especially for a project using a lot of `<DateRangePicker />` and didn't use a `encapsulated` component that import `RSuite`

If we compare a component library to a function (ui = f(state)), for more robustness, I think it also needs taking care of some edge cases at least it will not break the whole page.
