### ISSUE TITLE
Tree 控件 拖拽时会丢失项

### ISSUE THREAD

**Issue by annyshen** [rsuite/rsuite#2777]
### What version of rsuite are you using?

4.*

### Describe the Bug

Tree 控件 拖拽时会丢失项

### Expected Behavior

Tree 控件可以合并checkbox

### To Reproduce

Steps to reproduce the behavior, please provide a clear code snippets that always reproduces the issue or a GitHub repository. Screenshots can be provided in the issue body below.

**Comment by superman66** [comment]
@annyshen 能提供一下可复现到 Demo 吗？
