### ISSUE TITLE
Checktreepicker bug? Preset selected value can't be removed. Checkbox misses up

### ISSUE THREAD

**Issue by hwy1992129** [rsuite/rsuite#2784]
### What version of rsuite are you using?

5.19

### What version of React are you using?

18.2

### Describe the Bug

<CheckTreePicker defaultExpandAll value={['pages-fragments']} data={data} style={{ width: 280 }} />
![image](https://user-images.githubusercontent.com/70329303/193978407-6cd8feca-c280-479b-a7bd-78e01e40c5ca.png)
![image](https://user-images.githubusercontent.com/70329303/193978418-131dd2bd-6fbb-4e92-b00a-eca97954f17d.png)
Cancel uncheck the checkboxes, but the "fragments" is not removed.
![image](https://user-images.githubusercontent.com/70329303/193978537-78690146-202e-415e-bf77-448d186afc76.png)
besides, all the checkboxes are uncheckable.....

**Comment by superman66** [comment]
@hwy1992129
It's a bug when clean all values.

But If you want to controlled `CheckTreePicker`, you should pass the `onChange` prop to `CheckTreePicker`.

```js

const handleOnChange = (values) => {
  // save values to local state
}

<CheckTreePicker defaultExpandAll value={['pages-fragments']} data={data} style={{ width: 280 }} onChange={handleOnchange} />
```
