### ISSUE TITLE
Getting error on Vercel Build

### ISSUE THREAD

**Issue by jsonpreet** [rsuite/rsuite#2786]
### What version of rsuite are you using?

5.19.0

### What version of React are you using?

18.2.0

### What version of TypeScript are you using (if any)?

18.0.21

### What browser are you using?

Chrome

### Describe the Bug

![image](https://user-images.githubusercontent.com/26606638/194603901-64fbd839-0bbc-495e-aa05-603a3d86e77c.png)

I am getting this error in Vercel build how i can solve it?

**Comment by simonguo** [comment]
Please check your babel and webpack configuration for issues. The following projects are deployed in vercel and can provide you with reference.

https://github.com/rsuite/rsuite-admin-template
