### ISSUE TITLE
DateRangePicker has Empty Toolbar

### ISSUE THREAD

**Issue by MarvelSQ** [rsuite/rsuite#2793]
### What version of rsuite are you using?

5.18

### What version of React are you using?

17.0.2

### What browser are you using?

Chrome

### Describe the Bug

set `ranges` as empty & enable `oneTap`

```tsx
<DateRangePicker
      format="yyyy-MM-dd HH:mm:ss"
      defaultCalendarValue={[new Date('2022-02-01 00:00:00'), new Date('2022-03-01 23:59:59')]}
      ranges={[]}
      oneTap
/>
```
![截屏2022-10-10 下午3 45 37](https://user-images.githubusercontent.com/14308293/194819662-99480811-71e2-490a-9780-80ab193d6576.png)

### Expected Behavior

expect the toolbar doesn't take any space

![截屏2022-10-10 下午3 49 28](https://user-images.githubusercontent.com/14308293/194819832-1c79350e-b064-42d6-a456-444fc213d441.png)

**Comment by simonguo** [comment]
Fixed in https://github.com/rsuite/rsuite/pull/2794
