### ISSUE TITLE
Cannot read property 'requestAnimationFrame' of undefined

### ISSUE THREAD

**Issue by Dianaou** [rsuite/rsuite#28]
### Bug, feature request, or proposal:
```bash
index.js:5 Uncaught TypeError: Cannot read property 'requestAnimationFrame' of undefined
    at eval (index.js:5)
    at eval (index.js:11)
    at Object.<anonymous> (vendor.js:4823)
    at __webpack_require__ (vendor.js:694)
    at fn (vendor.js:115)
    at eval (Table.js:65)
    at Object.<anonymous> (vendor.js:6777)
    at __webpack_require__ (vendor.js:694)
    at fn (vendor.js:115)
    at eval (index.js:8)
```

### What is the expected behavior?
I can use rsuite component

### What is the current behavior?
webpack complied successed
but brower is error 

### What are the steps to reproduce?
import this component

**Comment by simonguo** [comment]
@Dianaou  rsuite version?

**Comment by Dianaou** [comment]
"rsuite": "^3.0.0",
        "rsuite-table": "^3.0.0"

**Comment by simonguo** [comment]
Please use `rsuite@3.0.4`, and you do not need to install `rsuite-table`.
Document:  https://rsuitejs.com/components/table

**Comment by Dianaou** [comment]
The version of rsuite 3.0.4 have an error,before install rsuite-table; so i used rsuite 3.0.0 and  rsuite-table ,however, it  brings new error

**Comment by Dianaou** [comment]
I don't know why about error that is 'Cannot read property 'requestAnimationFrame' of undefined', I only install rsuite 3.0.4 but not install rsuite-table, how can i do that ?

**Comment by simonguo** [comment]
You only need to configure rsuite@3.0.4 in `package.json`.  You try to remove dependency reinstall:

```bash
$ rm -R node_modules/
$ npm install 
```

**Comment by simonguo** [comment]
Let me have a look at your `. babelrc` Configuration

**Comment by Dianaou** [comment]
{
  "presets": [ "es2015", "stage-0", "react"],
  "plugins": [["import", { "libraryName": "antd", "style": true }]],
  "env": {
    "build": {
      "optional": ["optimisation", "minification"]
    }
  }
}

**Comment by Dianaou** [comment]
"webpack": "^2.4.1"

**Comment by simonguo** [comment]
because of babel 6 add use strict by default. add plugin transform-remove-strict-mode will be ok.

https://github.com/genify/babel-plugin-transform-remove-strict-mode
