### ISSUE TITLE
【CheckTreePicker】text exceed the boundary when we select too many options

### ISSUE THREAD

**Issue by begoat** [rsuite/rsuite#2833]
### What version of rsuite are you using?

5.20.0

### What version of React are you using?

17

### What browser are you using?

Chrome latest

### Describe the Bug

![image](https://user-images.githubusercontent.com/22862294/197509799-ca7a97fc-b648-4c44-9807-3f0141d285e8.png)

### Expected Behavior

`CheckTreePicker` limit the text within boundary

### To Reproduce

https://rsuitejs.com/zh/components/check-tree-picker/

select some options

**Comment by simonguo** [comment]
Fixed in https://github.com/rsuite/rsuite/pull/2826
