### ISSUE TITLE
Panel Component not working in next JS with TypeScript in Chrome Browser Rsuite

### ISSUE THREAD

**Issue by CharlesNjau** [rsuite/rsuite#2842]
### What version of rsuite are you using?

^5.19.0

### What version of React are you using?

18.2.0

### What version of TypeScript are you using (if any)?

^18.0.21

### What browser are you using?

Chrome

### Describe the Bug

Panel component doesn't work/render the panel effects as expected in chrome browser  it  loads the component but with out the panel effects 

### Expected Behavior

upon import ting the below component in index.tsx in next i expected it to render the component with full effects

const LoanComponentItem = ({title}:any) => {

    const ButtonStyle = {
        backgroundColor:'silver',
        width:120,
        margin:5,
        fontWeight:600
      }
      
  return (
    <div style={{
        display: 'block', width: 700, paddingLeft: 30
      }}>
        <h4>React Suite Panel Component</h4>
        <Panel header="Sample Panel title" shaded>
          Greetings from GeeksforGeeks
        </Panel>
      </div>
  )
}

export {LoanComponentItem}

### To Reproduce

Create a Panel component and import it in index.tsx in next JS and run

the following out put will be produced on the browser
![image](https://user-images.githubusercontent.com/22008416/198240591-e7814b31-8405-43a6-85ab-795cc128a4b2.png)

**Comment by vitalijalbu** [comment]
hi, did you imported the less or css file??
