### ISSUE TITLE
Async handler for AutoComplete controller

### ISSUE THREAD

**Issue by cinnamonbreakfast** [rsuite/rsuite#2846]
### What problem does this feature solve?

Lot of data is not static and it must be fetched from a server (for example Google Places API). An Async handler for AutoComplete would make the work much easier. Lots of controllers already have such kind of handler.

### What does the proposed API look like?

`onTypeTimeout: (value: string) => void` called after a Timeout to fetch data for the options menu
`typingTimeout: number` timeout after the last keystroke
`spinner: ReactNode` spinner...

**Comment by SevenOutman** [comment]
Hi @cinnamonbreakfast, thanks for the suggestion! We'll consider whether the library is going to maintain async data for the user.
For now it's possible to work with async data with the existing props and several states.

```jsx 
const [isLoading, setLoading] = useState(false);
const [data, setData] = useState([]);

return (
  <AutoComplete
    data={data}
    defaultValue=""
    onChange={(value) => {
      setLoading(true);
      fetchData(value)
        .then((newData) => {
          setData(newData);
          setLoading(false);
        });
    }}
    renderMenu={(menu) => {
      if (isLoading) {
        return <Spinner />;
      }
      return menu;
    }}
  />
);
```

**Comment by cinnamonbreakfast** [comment]
Thank you @SevenOutman for considering my suggestion and also for the code snippet. I would add one thing, to make it easier for everybody that's looking for the same solution. I recommend using this hook: https://usehooks-ts.com/react-hook/use-debounce
Really helps if you don't want to ddos your backend or increase your bills.
