### ISSUE TITLE
Static/Fixed (No shifting to new month) Display of Month Upon Selecting a date

### ISSUE THREAD

**Issue by joelmm1** [rsuite/rsuite#2867]
### Describe the Bug

When a date is selected, the month the date belongs to is pushed to the left side. The user may lose track of the dates he/she is selecting with this behaviour.

This should be the desired outcome: 

https://stackblitz.com/edit/react-mdyn85?file=index.js

### Expected Behavior

This should be the desired outcome: 

https://stackblitz.com/edit/react-mdyn85?file=index.js

### To Reproduce

This should be the desired outcome: 

https://stackblitz.com/edit/react-mdyn85?file=index.js

**Comment by simonguo** [comment]
Hi @joelmm1 

The issue has been fixed in #3911, please upgrade to the latest version.
