### ISSUE TITLE
rsuite-table的使用问题

### ISSUE THREAD

**Issue by wangjianjun0730** [rsuite/rsuite#29]
```javascript
import {Table} from 'rsuite'
const { Column, HeaderCell, Cell, Pagination } = Table;
```
安装文档，我在我的页面导入了rsuite
```javascript
render() {
    console.log(mockData)
    const { data } = this.state;
    return (
      <div className="tutor-client-container">
        <header className="home-header">
          <div className="home-header-item">SHOULADY</div>
          <div className="home-header-item" onClick={()=>{this.linkToCompanyDetail()}}>公司概况</div>
          <div className="home-header-item" onClick={()=>{this.linkToPayRecord()}}>缴费详情</div>
          <div className="home-header-item-about-us"
               onClick={()=>{this.aboutUsOn()}}>会员登录</div>
        </header>
        <div className="table-container">
          <Table
            height={400}
            data={data}
            onRowClick={data => {
              console.log(data);
            }}
            bordered={true}
          >
            <Column width={70} align="center" fixed>
              <HeaderCell>Id</HeaderCell>
              <Cell dataKey="id" />
            </Column>

            <Column width={200} fixed align={'center'}>
              <HeaderCell>First Name</HeaderCell>
              <Cell dataKey="firstName" />
            </Column>

            <Column width={200} align={'center'}>
              <HeaderCell>Last Name</HeaderCell>
              <Cell dataKey="lastName" />
            </Column>

            <Column width={200} align={'center'}>
              <HeaderCell>City</HeaderCell>
              <Cell dataKey="city" />
            </Column>

            <Column width={200} align={'center'}>
              <HeaderCell>Street</HeaderCell>
              <Cell dataKey="street" />
            </Column>

            <Column width={300} align={'center'}>
              <HeaderCell>Company Name</HeaderCell>
              <Cell dataKey="companyName" />
            </Column>

            <Column width={300} align={'center'}>
              <HeaderCell>Email</HeaderCell>
              <Cell dataKey="email" />
            </Column>
          </Table>
        </div>
      </div>
    );
  }
}
```
但是生成的页面效果，所有数据都靠左显示，且每一行的数据都重叠在一起......我是不是还缺少什么操作？比如在当前页面的style.less文件中导入样式？

**Comment by simonguo** [comment]
@wangjianjun0730  你只需要在全局引入：
```
import 'rsuite/styles/less/index.less';
```

**Comment by wangjianjun0730** [comment]
页面index.js文件顶部写入：import 'rsuite/styles/less/index.less';包如下错误
`
Failed to compile.

./node_modules/rsuite/styles/less/index.less
Module build failed: 

//** Unit-less `line-height` for use in components like buttons.
@line-height-large: unit(@line-height-large-computed/@font-size-base); // ~1.375
                  ^
Error evaluating function `unit`: the first argument to unit must be a number. Have you forgotten parenthesis?
      in /Users/wangjianjune/pc-webside/node_modules/rsuite/styles/less/variables.less (line 88, column 20)

`

**Comment by simonguo** [comment]
检查一下你 webpack 中是否配置 less-loader    css-loader

**Comment by wangjianjun0730** [comment]
我用的脚手架是react-cavalier-cli ，工程基于`create-react-app` `webpack3.x` `React16.x`搭建的。
`
# download cli
npm install react-cavalier-cli -g

# create a project
react-cavalier init <my-project-name>
`
通过上面命令生成的模板项目，以下是项目目录结构
![Uploading Snip20180513_1.png…]()
![Uploading Snip20180513_4.png…]()

less-loader css-loader都已经安装，我想应该是已经配置过了.
以下是项目中webpack.config.dev.js文件中的一段代码：
`
 {
            test: /\.less$/,
            use: [
              require.resolve('style-loader'),
              {
                loader: require.resolve('css-loader'),
                options: {
                  importLoaders: 1,
                },
              },
              {
                loader: require.resolve('less-loader'),
                options: {
                  strictMath: true,
                  noIeCompat: true
                }
              }
            ]
          },
`

**Comment by simonguo** [comment]
cc @hiyangguo

**Comment by wangjianjun0730** [comment]
目前我使用的node版本及npm版本分别是：v10.1.0和6.0.1

**Comment by wangjianjun0730** [comment]
这是我写的demo的链接地址：
https://github.com/wangjianjun0730/test

项目首页入口路径：test/src/container/App/index.js

分别在顶部导入了：
import { Table } from 'rsuite';
const { Column, HeaderCell, Cell, Pagination } = Table;

这里没有加：import 'rsuite/styles/less/index.less';这句代码，一旦加上就会js报错

**Comment by wangjianjun0730** [comment]
在204行添加  javascriptEnabled: true,但貌似并没有起到作用：
`
{
                      loader: require.resolve('less-loader'),
                      options: {
                        javascriptEnabled: true,
                        //sourceMap: shouldUseSourceMap,
                        plugins: [
                          new LessPluginAutoPrefix({
                            browsers: lessAutoPrefixConfig
                          })
                        ]
                      },
                    }
`

`
./node_modules/rsuite/styles/less/index.less
Module build failed: 

//** Unit-less `line-height` for use in components like buttons.
@line-height-large: unit(@line-height-large-computed/@font-size-base); // ~1.375
                  ^
Error evaluating function `unit`: the first argument to unit must be a number. Have you forgotten parenthesis?
      in /Users/wangjianjune/test/node_modules/rsuite/styles/less/variables.less (line 88, column 20)

`

**Comment by simonguo** [comment]
你可以只留一个 `javascriptEnabled: true` 配置，把其他配置都删除掉，看看到底是哪里配置问题造成的影响。

**Comment by LindaStolen** [comment]
我使用 daterangepicker組件也有相同的問題，
在app.js引入 `import 'rsuite/styles/index.less'` 後報錯

報錯訊息：
./node_modules/rsuite/styles/index.less (./node_modules/react-scripts/node_modules/css-loader/dist/cjs.js??ref--6-oneOf-7-1!./node_modules/postcss-loader/src??postcss!./node_modules/less-loader/dist/cjs.js??ref--6-oneOf-7-3!./node_modules/rsuite/styles/index.less)

// It is hacky way to make this function will be compiled preferentially by less
.color-palette-mixin();
^
Inline JavaScript is not enabled. Is it set in your options?
 .. node_modules\rsuite\styles\mixins\palette.less (line 44, column 0)

**Comment by simonguo** [comment]
@LindaStolen  你用的 rsuite 那边版本？

**Comment by hiyangguo** [comment]
@LindaStolen 你需要在 `less-loader` 中打开 `javascriptEnabled`，以 `webpack@4` 的配置为例：
```
{
  loader: 'less-loader',
  options: {
    javascriptEnabled: true
  }
}
```

**Comment by LindaStolen** [comment]
@hiyangguo  是這個部分嗎?
`function lessLoader(source) {
  const loaderContext = this;
  const options = (0, _getOptions.default)(loaderContext);
  options.javascriptEnabled = true;  // 這行
  const done = loaderContext.async();
  const isSync = typeof done !== 'function';`
昨天加上後專案正常了 但無法透過`overrides.config.js` 覆蓋樣式 是我漏作了甚麼嗎? 
謝謝你們

**Comment by hiyangguo** [comment]
@LindaStolen 你使用什么工具编译代码的？CRA 配合 [react-app-rewired](https://github.com/timarney/react-app-rewired) 吗？

**Comment by LindaStolen** [comment]
@hiyangguo 是的 我是create-react-app 再依照你們的指示操作
[https://rsuitejs.com/guide/use-with-create-react-app]
原本到 app.js 引入 import 'rsuite/styles/index.less' 後就報錯 目前這部分已經解決
但無法使用 `overrides.config.js` 來修改樣式

**Comment by hiyangguo** [comment]
@LindaStolen 修改样式请参考 [定制主题](https://rsuitejs.com/guide/use-with-create-react-app#%E5%AE%9A%E5%88%B6%E4%B8%BB%E9%A2%98)  
我们的 [CRA 示例](https://github.com/rsuite/examples/tree/master/create-react-app)

**Comment by LindaStolen** [comment]
@hiyangguo  是的 這部分我也做了 仍然無法
查了大多數的資料 幾乎都要安裝antd ?
想請問一下 
`@import '~rsuite/styles/less/index.less'; //引入默认的样式文件`
`@import 'custom-theme.less'; // 进行样式定制`
這兩支檔案 是引入在我自己新建立的less檔嘛?

**Comment by hiyangguo** [comment]
@LindaStolen 不需要安装 antd
```
@import '~rsuite/styles/less/index.less'; //引入默认的样式文件
```
这个是你安装 rsuite 以后就有了。
```
@import 'custom-theme.less';
```
这个如果你没有自己的样式可以不用引入这个文件

**Comment by hiyangguo** [comment]
@LindaStolen 使用 CRA 的详细教程可以参见 [在 create-react-app 中使用](https://rsuitejs.com/guide/use-with-create-react-app) 这一章节。此章节对应的 CRA 版本为 v3。
