### ISSUE TITLE
Form model addRule() can not work when no value

### ISSUE THREAD

**Issue by lmovse** [rsuite/rsuite#290]
### Bug, feature request, or proposal:
Bug

### What is the expected behavior?
我的需求是对这个输入框的校验是有条件的，当表单符合某种规则时，该字段不能为空，当表单不符合某种规则时，该字段可以为空，所以当我的输入框没有输入值时，添加的自定义 addRule()  应该也能够正常校验

### What is the current behavior?
这次是直接在官方文档的 Form  一节的表单数据校验 CheckForm 的源代码中修改的，我只添加了一个自定义规则，直接返回了 false。

```js
  name: StringType().isRequired('This field is required.'),
  email: StringType()
    .addRule(() => false, 'false...'),
```

这时，如果我的 Email  输入框没有输入任何值的话，点  `Check Email` 控制台打印出无错误。然后我输入了字符，错误提示才会正常弹出，并且点击 `Check Email` 按钮也能够正常显示。

我有查看近期版本升级的 bug  修复日志，并没有提到这个问题相关记录，由于我的项目原因，无法升级到最新版本测试，所以我直接在官网的源码展示里测试的。这个问题依旧存在。

在官网提供了这样一个例子，我有在我 3.2.8 的版本测试，结果并不一致

```js
const model = Schema.Model({
  password1: StringType().isRequired('该字段不能为空'),
  password2: StringType().addRule((value, data) => {
    if (value !== data.password1) {
      return false;
    }
    return true;
  }, '两次密码不一致')
});

model.check({ password1: '123456', password2: 'root' });

expected:
/**
{
  password1: { hasError: false },
  password2: {
    hasError: true,
    errorMessage: '两次密码不一致'
  }
};
**/

actual: 
/**
{
 password1: { hasError: false },
 password2: { hasError: false },
}
**/
```

### What are the steps to reproduce?
如上

**Comment by simonguo** [comment]
@lmovse 示例中确实存在这个问题，我们会在这个版本中修复， 不过 `<FormControl>` 是支持受控的 `errorMessage`， 你可以通过 `<Form>` 的 `onCheck` 维护 `errorMessage`。

示例:  https://codesandbox.io/s/oqpzn12mqq

**Comment by lmovse** [comment]
OK，谢谢，暂时先用这种方式实现吧
