### ISSUE TITLE
The "noCaret" has No Effect on a Sub-menu

### ISSUE THREAD

**Issue by cowofevil** [rsuite/rsuite#2959]
### What version of rsuite are you using?

5.23.1

### What version of React are you using?

17.0.2

### What version of TypeScript are you using (if any)?

17.0.2

### What browser are you using?

Chrome

### Describe the Bug

If `<Nav.Menu>` has the `noCaret` prop set and is a child of a parent `<Nav.Menu>`, the caret icon will still be displayed on the sub-menu.

![Current behavior](https://i.imgur.com/nB4iS8u.png)

### Expected Behavior

When the `noCaret` prop is set on a sub-menu then the caret icon should not be present.

### To Reproduce

https://codesandbox.io/s/compassionate-cannon-s0ugsd?file=/src/index.js

**Comment by Yuiai01** [comment]
let me try

**Comment by Yuiai01** [comment]
Hello, I found such a paragraph in the source code.
<img width="869" alt="image" src="https://user-images.githubusercontent.com/112228030/205532213-1cdb8f99-48c4-41b5-b559-e68df7e10c62.png">

**Comment by Yuiai01** [comment]
The NavDropdownMenu component does not have the noCaret property configured. I will try to add it to this component.

**Comment by SevenOutman** [comment]
Fixed in #2960
