### ISSUE TITLE
Incorect CellProps type anotation

### ISSUE THREAD

**Issue by GedisG** [rsuite/rsuite#2975]
### What version of rsuite are you using?

5.23.2

### What version of React are you using?

17.0.2

### What version of TypeScript are you using (if any)?

4.8.2

### What browser are you using?

Chrome

### Describe the Bug

Just upgraded rsuite from version 5.8.1 to 5.23.2, and now typescript has errors with CellProps. 

Right now importing CellProps from rsuite types are different from importing CellProps from rsuite-table types. This creates a typescript error because of a dataKey difference in both annotations when using Table.Cell and importing type annotation from rsuite

### Expected Behavior

Make both CellProps types same or just remove one of the types and delete the one that is not necessary

**Comment by simonguo** [comment]
I can't reproduce this bug, could you reproduce the bug through codesandbox?
