### ISSUE TITLE
Navbar.Brand missing href prop

### ISSUE THREAD

**Issue by DrogoNevets** [rsuite/rsuite#2980]
### What version of rsuite are you using?

5.23.3

### What version of React are you using?

18.2.0

### What version of TypeScript are you using (if any)?

4.4.2

### What browser are you using?

Chrome

### Describe the Bug

According to the documentation located [here](https://rsuitejs.com/components/navbar/#examples) I should be able to give the `Navbaar.Brand` component a `href` prop, where as on inspection of the source code, this isn't possible.

### Expected Behavior

It is desired that when the use clicks the branding I have placed here, I can dictate the route to go to.

### To Reproduce

Simply use the `Navbar.Brand` component.

Either the documentation needs updating, or the source code.

**Comment by Yuiai01** [comment]
Hello, `Navbar.Brand` is rendered as an` a` tag in the source code, so you can add paths to jump around. 
![image](https://user-images.githubusercontent.com/112228030/209457058-e8212602-d7aa-4749-a54c-7b5bb027ecb5.png)

**Comment by Yuiai01** [comment]
Just like that
~~~jsx
 <Navbar.Brand href="https://www.bilibili.com/">RSUITE</Navbar.Brand>
~~~
