### ISSUE TITLE
AutocompletePicker size can not be changed

### ISSUE THREAD

**Issue by GedisG** [rsuite/rsuite#2982]
### What version of rsuite are you using?

5.23.3

### What version of React are you using?

17.0.2

### What version of TypeScript are you using (if any)?

4.8.2

### What browser are you using?

Chrome

### Describe the Bug

Size prop does not affect the component. Changed in version 5.23.1

### Expected Behavior

Should be able to change a size with size prop

### To Reproduce

https://codesandbox.io/s/rsuite-playground-forked-2ddf7s

**Comment by Yuiai01** [comment]
Hello, the codesandbox link you provided seems to have nothing to do with your problem, could you please provide a new link?

**Comment by GedisG** [comment]
Hello, sorry for that. Fixed the same fork: https://codesandbox.io/s/rsuite-playground-forked-2ddf7s

**Comment by Yuiai01** [comment]
Hi, I found by checking the official documentation that `AutoComplete` does not currently provide `size` to modify component dimensions

**Comment by GedisG** [comment]
It still inherits PickerComponent props, so in documentation it is not necessary to provide this information in my opinion. Also as mentioned in description it always worked until 5.23.1 release was made, so there were fault with prop drilling made
