### ISSUE TITLE
InputPicker minimum width is too large

### ISSUE THREAD

**Issue by GedisG** [rsuite/rsuite#2983]
### What version of rsuite are you using?

5.23.3

### What version of React are you using?

17.0.2

### What version of TypeScript are you using (if any)?

4.8.2

### What browser are you using?

Chrome

### Describe the Bug

If I put InputPicker into a Column width fixed width and want to make inputPicker as small as possible, it's limits are to small for minimum width available until picker becomes unusable. Is there any ways you suggest to work around without increasing it's width?

### Expected Behavior

Should be possible to make it smaller than right now with all it's UI being nice

### To Reproduce

https://codesandbox.io/s/rsuite-playground-forked-cxqsfh

**Comment by simonguo** [comment]
Hi @GedisG 
This incorrect style is indeed caused by the minimum width. In order not to affect your normal use, you can try to fix it through css coverage.
```css
.rs-picker-toggle {
  min-width: auto;
}
```

**Comment by simonguo** [comment]
@SevenOutman  This problem is caused by the new `loading` prop. You check to make sure that how to fix it does not affect the existing features.

https://github.com/rsuite/rsuite/pull/2808/files#diff-40d2ff0da64077ad1acd3fd35bf47058422a0a8d44d26b699047c41637ee2e65R21-R24

**Comment by simonguo** [comment]
Fixed in [v5.44.0](https://github.com/rsuite/rsuite/releases/tag/v5.44.0)
