### ISSUE TITLE
Sidenav Multilevel Nav.Menu has strange behavior

### ISSUE THREAD

**Issue by andrewtquick** [rsuite/rsuite#2985]
### What version of rsuite are you using?

5.23.2

### What version of React are you using?

18.2.0

### What browser are you using?

Chrome, Edge, Firefox

### Describe the Bug

Sidenav Multilevel submenus are not working correctly. The caret does not rotate and is stuck in the up position and the submenu option is not indented.

In the demo below, please see the submenu with title "Issue". 

- Caret does not rotate when clicked
- Submenu options are not indented

Also appears that the eventKey property is only 3 levels deep "1-1-1", cannot expand to "1-1-1-1".

### Expected Behavior

All submenus should act like the parent menu and parent submenu.

### To Reproduce

```js
import React from 'react';
import ReactDOM from 'react-dom';
import './styles.css';


import { Sidenav, Nav } from 'rsuite';
import DashboardIcon from '@rsuite/icons/legacy/Dashboard';
import GroupIcon from '@rsuite/icons/legacy/Group';
import MagicIcon from '@rsuite/icons/legacy/Magic';
import GearCircleIcon from '@rsuite/icons/legacy/GearCircle';

const App = () => (
  <div style={{ width: 240 }}>
    <Sidenav defaultOpenKeys={['3', '4']}>
      <Sidenav.Body>
        <Nav activeKey="1">
          <Nav.Item eventKey="1" icon={<DashboardIcon />}>
            Dashboard
          </Nav.Item>
          <Nav.Item eventKey="2" icon={<GroupIcon />}>
            User Group
          </Nav.Item>
          <Nav.Menu eventKey="3" title="Advanced" icon={<MagicIcon />}>
            <Nav.Item eventKey="3-1">Geo</Nav.Item>
            <Nav.Item eventKey="3-2">Devices</Nav.Item>
            <Nav.Item eventKey="3-3">Loyalty</Nav.Item>
            <Nav.Item eventKey="3-4">Visit Depth</Nav.Item>
          </Nav.Menu>
          <Nav.Menu eventKey="4" title="Settings" icon={<GearCircleIcon />}>
            <Nav.Item eventKey="4-1">Applications</Nav.Item>
            <Nav.Item eventKey="4-2">Channels</Nav.Item>
            <Nav.Item eventKey="4-3">Versions</Nav.Item>
            <Nav.Menu eventKey="4-5" title="Custom Action">
            <Nav.Menu eventKey="4-5-1" title="Issue">
              <Nav.Item eventKey="4-5-1-1">Action Name</Nav.Item>
              <Nav.Item eventKey="4-5-1-2">Action Params</Nav.Item>
              </Nav.Menu>
            </Nav.Menu>
          </Nav.Menu>
        </Nav>
      </Sidenav.Body>
    </Sidenav>
  </div>
);

ReactDOM.render(<App />, document.getElementById('root'));
```

**Comment by Yuiai01** [comment]
Hello, I found the deep sub-menu description problem, maybe I can try to fix it

**Comment by andrewtquick** [comment]
Fix looks good. Any chance at allowing deeper nested menus? eventKey="4-5-1-1" or even eventKey="4-5-1-1-1", or does the fix handle that issue as well?

**Comment by Yuiai01** [comment]
> Fix looks good. Any chance at allowing deeper nested menus? eventKey="4-5-1-1" or even eventKey="4-5-1-1-1", or does the fix handle that issue as well?

Yes, I fixed this by having each nested Nav.Menu display the arrow icon according to its own expanded or collapsed state, so it doesn't matter how deep it is nested.
