### ISSUE TITLE
check-tree-picker extreme slow loading

### ISSUE THREAD

**Issue by mingjieATuber** [rsuite/rsuite#2987]
### What version of rsuite are you using?

5.23.3

### Describe the Bug

Hi, i am trying to load a large ton of data into the check-tree-picker component; However, the page just froze;
and any interaction with the dropdown will cause the page to be frozen again. 
Fairly easy to reproduce -> 
change the data limits to limits: [20, 20, 20] on this page: https://rsuitejs.com/components/check-tree-picker/#basic

### Expected Behavior

normal loading time / slow loading time on the first load, and faster interaction speed with other nodes

### To Reproduce

change the data limits to limits: [20, 20, 20] on this page: https://rsuitejs.com/components/check-tree-picker/#basic

**Comment by Yuiai01** [comment]
Hello, if change the data limits to limits: [20, 20, 20], then you need to create 20 * 20 * 20 pieces of data, which will cause the page to freeze with a high probability.  Maybe you can refer to: https://rsuitejs.com/components/check-tree-picker/#async

**Comment by simonguo** [comment]
Hi @mingjieATuber 
If your data volume can be controlled within one or two thousand data. You can set a virtualized attribute for CheckTreePicker to ensure that the component can be used normally. 
```tsx
 <CheckTreePicker virtualized  />
```
If you exceed a certain amount of data, it is recommended that you load data asynchronously.  Alternatively you may consider using the [MultiCascader](https://rsuitejs.com/components/multi-cascader/) component.

**Comment by mingjieATuber** [comment]
understand! thanks for the detailed explaination! thanks!
