### ISSUE TITLE
Rsuite selectpicker moves around with page on page scroll

### ISSUE THREAD

**Issue by DorsLetstok** [rsuite/rsuite#3001]
### What version of rsuite are you using?

4.8.8

### What version of React are you using?

17.0.2

### What version of TypeScript are you using (if any)?

4.7.4

### What browser are you using?

Chrome

### Describe the Bug

When implementing SelectPicker,it seems that the menu component is not fixed to place and is affected by the users scroll/page position

Before scroll:
![image](https://user-images.githubusercontent.com/110838906/210573041-0d0c936b-59a5-40bf-a023-92d017e83263.png)

After scroll:
![image](https://user-images.githubusercontent.com/110838906/210573104-b471b758-81e5-408a-b4ff-f7360103ea8a.png)

The menu goes down with the page itself

### Expected Behavior

Menu should stay in place on page scroll

I tried fixing the component to place with useRef/createRef but it did not help
Making the relevant components positions to relative/fixed did not help either

**Comment by simonguo** [comment]
Hi @DorsLetstok  You can set a `container` property for `SelectPicker` to change where the menu is rendered on the DOM.

```tsx
const App = () => {
  const containerRef = React.useRef();
  return (
    <div ref={containerRef} style={{ position: 'relative' }}>
      <SelectPicker data={data} style={{ width: 224 }} container={() => containerRef.current} />
    </div>
  );
};
```

> similar issue: https://github.com/rsuite/rsuite/issues/2989

**Comment by DorsLetstok** [comment]
Hi @simonguo ,thanks for the answer,I'm afraid I'm getting tons on typescript errors with this solution,I already tried it and it didn't work well
I agree that this is the general correct direction,but regarding cyntax/exact methodology to use here is beyond me
Thanks again for the input, but I don't believe this cyntax will help on this case

**Comment by simonguo** [comment]
If you need further help, please reproduce your issue via codesandbox so we can find the cause.

**Comment by DorsLetstok** [comment]
This sandbox represents the errors I get for the method you suggested, it does not reproduce the exact issue (the scroll behavior is static ,it does not reproduce the original issue), but should be enough for you to understand which errors I've encountered:
https://codesandbox.io/s/react-typescript-forked-zzp8iu?file=/src/App.tsx

Thanks again @simonguo !

**Comment by simonguo** [comment]
Set a type for containerRef.
```ts
const containerRef = React.useRef<HTMLDivElement>(null);
```

Full example:  https://codesandbox.io/s/react-typescript-forked-ecfwgx

**Comment by DorsLetstok** [comment]
Broke the component all together I'm afraid,not usable with this method
I'll guess I'll keep this broken/replace with another component in the future
@simonguo I really appreciate the help,thanks again

**Comment by DorsLetstok** [comment]
Managed to solve by overhauling the whole component
