### ISSUE TITLE
Dropdown onSelect not getting selected value

### ISSUE THREAD

**Issue by appamvenkatesh** [rsuite/rsuite#3002]
### What version of rsuite are you using?

5.22.2

### What version of React are you using?

18.2.0

### What browser are you using?

Chrome

### Expected Behavior

Dropdown onSelect callback function , not getting selected item value, instead getting undefined

**Comment by simonguo** [comment]
Hi @appamvenkatesh, please check if `eventKey` is set for `Dropdown.Item`

```tsx
const App = () => (
  <Dropdown title="Dropdown" onSelect={(item)=>{
    	console.log(item)
    }}>
    <Dropdown.Item eventKey="1">Item 1</Dropdown.Item>
    <Dropdown.Item eventKey="2">Item</Dropdown.Item>
  </Dropdown>
);
```
