### ISSUE TITLE
<InputNumber> return as string type

### ISSUE THREAD

**Issue by calvin1012** [rsuite/rsuite#3004]
### What version of rsuite are you using?

5.24

### What version of React are you using?

16.8.6

### What browser are you using?

Chrome

### Describe the Bug

The return value type is string

### Expected Behavior

The return value type is number

**Comment by simonguo** [comment]
See: https://github.com/rsuite/rsuite/issues/1720#issuecomment-861327908

**Comment by SevenOutman** [comment]
I'm closing this issue as it seems to be duplicated with #1720. Feel free to re-open if it's actually not.
