### ISSUE TITLE
[Whisper Component]  whisper的children应该在<></>包裹字符串的时候也报错，至少给个warning

### ISSUE THREAD

**Issue by medmin** [rsuite/rsuite#3008]
### What version of rsuite are you using?

5.x

### What version of React are you using?

18.x

### What version of TypeScript are you using (if any)?

4.9.3

### What browser are you using?

chrome

### Describe the Bug

// error
```javascript
<Whisper trigger="hover"  {...OtherProps}>
    "Hello World"
</Whisper>
```

**// no error, but no tooltip either**
**// 但应该报错，或者给个warning**
```javascript
<Whisper trigger="hover"   {...OtherProps}>
   </>"Hello World"</>
</Whisper>
```

### Expected Behavior

error or warning

**Comment by simonguo** [comment]
Whisper 需要获取 children 的位置，导致 children 必须是一个 DOM 元素。 
感谢反馈，我们修复一下。

**Comment by medmin** [comment]
Thanks
