### ISSUE TITLE
[createComponent function] merge class names的时候，应该让props里的className放在后面，这样就方便覆盖现有的css

### ISSUE THREAD

**Issue by medmin** [rsuite/rsuite#3021]
### What problem does this feature solve?

有的时候，需要传入custom className来覆盖rsuite里的css样式，比如，**使用css module的时候**

但现在如截图所示，developer传入了自己的className，merge的时候放在前面了，所以导致自己写的css不能生效，必须加上`!important`才可以

所以是否可以考虑，把这`merge`函数的两个参数调换一下顺序，这样用户在传入自己写的className的时候就更容易覆盖rsuite的css样式

谢谢

<img width="930" alt="Screen Shot 2023-01-13 at 5 15 04 PM" src="https://user-images.githubusercontent.com/16820635/212443960-d9d2f0d0-90e2-42cf-b8cc-9c7d5769bcbd.png">

所以导致我自己的class排在前面，必须加`!important`才能生效。后来我也没有用`!important`，而是用了别的方式，就是用全局css来覆盖的，**用css module总是不能生效**

![screenshot-20230113-173700](https://user-images.githubusercontent.com/16820635/212444701-5602482a-6d8f-4795-82ba-5ea1971fca5e.png)

### What does the proposed API look like?

before: 
`      const classes = merge(className, withClassPrefix());`

after
`      const classes = merge(withClassPrefix(), className);`

**Comment by simonguo** [comment]
@medmin  CSS 的优先级和 className 上的顺序无关，而是和 class 的定义顺序有关。

**Comment by medmin** [comment]
> @medmin CSS 的优先级和 className 上的顺序无关，而是和 class 的定义顺序有关。

能否详细说明一下，谢谢

我的代码就是这样的：

```javascript

<Navbar.Brand href="/" className="kspm-navbar-brand">
    <Image src={Logo} alt="logo" width={30} height={30} />
    My Brand
</Navbar.Brand>

```

我就是传入了一个class，没有其他操作，请问什么是`class 的定义顺序` ?

**Comment by simonguo** [comment]
以下两个按钮的背景颜色将都是蓝色，`class="red blue"` 和 `class="blue red"` 不会改变 CSS 的优先级。

```css
.red{
  background-color: red;
}
.blue{
  background-color: blue;
}
```
```html
<button class="red blue">A</button>
<button class="blue red">B</button>
```

如果我们把 css 定义的顺序改变，两个按钮将都显示为红色。

```css
.blue{
  background-color: blue;
}
.red{
  background-color: red;
}
```

你可以详细了解一下 CSS 优先级相关的知识： https://developer.mozilla.org/zh-CN/docs/Web/CSS/Specificity

**Comment by medmin** [comment]
好，谢谢
