### ISSUE TITLE
Whisper is not working with my components

### ISSUE THREAD

**Issue by abdullaev388** [rsuite/rsuite#3034]
### What version of rsuite are you using?

5.25.0

### What version of React are you using?

18

### What browser are you using?

Chrome

### Describe the Bug

Whisper is not working with my components event if they forwardRef

### To Reproduce

https://codesandbox.io/s/zen-dew-ew2u9o?file=/src/index.js

**Comment by simonguo** [comment]
Hi @abdullaev388  
The codesandbox example you provided does not reproduce your problem. Please check that the sample is not saved.

**Comment by abdullaev388** [comment]
Solved. 

> Hi @abdullaev388 The codesandbox example you provided does not reproduce your problem. Please check that the sample is not saved.

Solved. Forgot to pass props to forwarded component
