### ISSUE TITLE
Toggle doesn't take default value from Form when being used in Form.Control/Form.Group

### ISSUE THREAD

**Issue by pkocak** [rsuite/rsuite#3036]
### What version of rsuite are you using?

5.25.0

### What version of React are you using?

18.2.0

### What version of TypeScript are you using (if any)?

4.9.4

### What browser are you using?

Chrome Version 109.0.5414.119 (Official Build) (arm64)

### Describe the Bug

I am using a Form and passing initialValues via formValues. Everything works fine for now except for Toggle. I am passing true in initialValues but Toggle initially renders as unchecked. When i switch on and off formValue is being set correctly however i couldn't find any solution about Toggle's initial checked.

### Expected Behavior

When true is given initially for a Form.Control with Toggle accepter, Toggle should be defaultChecked.

### To Reproduce

[Check codesandbox](https://codesandbox.io/s/shy-worker-s635nl?file=/index.js)

**Comment by simonguo** [comment]
Hi @pkocak 
`Form.Control` needs to take over the `value` and `onChange` props of the form component. But `Toggle` does not have a `value` prop, if Toggle is to be used in `Form.Control`, simple encapsulation is required.

```jsx
const ControlledToggle = React.forwardRef((props, ref) => {
  const { value, ...rest } = props;
  return <Toggle {...rest} ref={ref} checked={value} />;
});

...

<Form.Control accepter={ControlledToggle} />
```

> https://codesandbox.io/s/autumn-feather-j8kjgj

**Comment by SevenOutman** [comment]
@simonguo I think it's good to add a `type` prop to Form.Control component, resembling `type` attribute of `<input>` element. When `type` is `"checkbox"`, Form.Control passes `checked` prop to the accepter component instead of `value`. In addition, Toggle can be regarded as `"checkbox"` by default for convenience.

**Comment by pkocak** [comment]
Hey @simonguo, thanks for the fast answer, means too much.

I'm using your way and it works perfectly fine for now but i will leave this issue open because @SevenOutman 's comment really makes sense. However, if you want to close this issue it's all yours.

**Comment by simonguo** [comment]
We can check the value of `accepter` in `Form.Control`, if it is `Toggle`, use `checked` as the value of the form field.
