### ISSUE TITLE
various issues with TagInput

### ISSUE THREAD

**Issue by julesx** [rsuite/rsuite#3042]
### What version of rsuite are you using?

5.25

### What version of React are you using?

18.0.26

### What version of TypeScript are you using (if any)?

4.9.44

### What browser are you using?

Chrome

### Describe the Bug

1. creating a basic TagInput errors. it insists that the `trigger` and `data` props need to be provided. the `data` prop is not listed in the docs. is there some confusion between `data` and `value`?
`<TagInput />`
`Type '{}' is missing the following properties from type 'TagInputProps': trigger, data`	

2. clearing all values using the rightmost X results in a `null` being provided in the `onChange` callback. 

### Expected Behavior

1. i don't think the `trigger` or `data` props should need to be specified. clarify difference between `data` and `value`
2. return an empty array instead of null

**Comment by SevenOutman** [comment]
Hi @julesx, thanks for your feedback!

If I understand it correctly, 

1. `trigger` prop should be optional and `data` should not be present on TagInput component.
2. Clicking "Clear" button should fire `onChange` with an empty array.

@simonguo Is it correct?

**Comment by simonguo** [comment]
These issues do exist and should be fixed.

**Comment by julesx** [comment]
thanks. i do have another question.
what is the purpose of the `defaultValue` prop? why would i use `defaultValue` instead of providing `value` with the items that should be present initially?

**Comment by SevenOutman** [comment]
> what is the purpose of the `defaultValue` prop? why would i use `defaultValue` instead of providing `value` with the items that should be present initially?

It's related to the concept of [uncontrolled components](https://reactjs.org/docs/uncontrolled-components.html). A rough conclusion is: _use `value` if you would take care of `onChange` yourself._
