### ISSUE TITLE
[Message] component onClose callback invokes on render

### ISSUE THREAD

**Issue by dduafa** [rsuite/rsuite#3056]
### What version of rsuite are you using?

5.25.0

### What version of React are you using?

18.2.0

### What version of TypeScript are you using (if any)?

4.9.3

### What browser are you using?

Chrome

### Describe the Bug

Hello,

The `onClose` callback on the `Message` component invokes on render

### Expected Behavior

The `onClose` callback should only be invoked when the close icon is clicked, not when the component renders

### To Reproduce

```
function App() {
  return (
      <Message
        closable={true}
        onClose={() => {
          console.log("Closed");
        }}
      >
        Example Message
      </Message>
  );
}
```

**Comment by simonguo** [comment]
Hi @dduafa 

The reason for this problem is that Message has a default delay of 2 seconds to close when it is used in combination with toaster. You can fix it by adding the `duration` property:

```diff
function App() {
  return (
      <Message
        closable
+       duration={0}
        onClose={() => {
          console.log("Closed");
        }}
      >
        Example Message
      </Message>
  );
}
```

**Comment by SevenOutman** [comment]
> The reason for this problem is that Message has a default delay of 2 seconds to close when it is used in combination with toaster.

Should the auto-closing logic be handled by toaster instead of the Message component?

**Comment by dduafa** [comment]
> 

Thank you @simonguo, setting the `duration` worked. As per @SevenOutman's question, I only needed the Message component

**Comment by simonguo** [comment]
This is an issue that needs to be fixed, auto-close should work on toaster push.
