### ISSUE TITLE
Missing class properties transform.

### ISSUE THREAD

**Issue by akbar-myant** [rsuite/rsuite#3096]
### What version of rsuite are you using?

5.28.0

### What version of React are you using?

16.14.0

### What version of TypeScript are you using (if any)?

non

### What browser are you using?

Chrome

### Describe the Bug

After running a clean install last night, started seeing this error.
<img width="1056" alt="Screenshot 2023-03-02 at 8 08 08 PM" src="https://user-images.githubusercontent.com/105008358/222467712-bdf87706-be53-414f-bdc1-b50ab4dbff6f.png">

### To Reproduce

Install rsuite version `"rsuite": "5.28.0",` and try building the project with `"react": "16.14.0"`.

**Comment by SevenOutman** [comment]
Hi @akbar-myant , if you are using Babel, you may have to add [`@babel/plugin-proposal-class-properties`](https://www.npmjs.com/package/@babel/plugin-proposal-class-properties).

Reference: https://stackoverflow.com/a/49553497

**Comment by andreogara** [comment]
hello, thanks for all you do. I just started setting this up and stuck with the same error message as above. I see a fix has been merged and wondering when it will be released. thank you!

**Comment by SevenOutman** [comment]
> hello, thanks for all you do. I just started setting this up and stuck with the same error message as above. I see a fix has been merged and wondering when it will be released. thank you!

Hi @andreogara , try uninstalling and re-installing rsuite, you should then get the latest fixed version of `schema-typed`.
