### ISSUE TITLE
React Suite Tooltip Whisper methods

### ISSUE THREAD

**Issue by AdityaGupta20871** [rsuite/rsuite#3098]
### What version of rsuite are you using?

5.28.0

### What version of React are you using?

18.2.0

### What browser are you using?

Microsoft Edge

### Describe the Bug

I am trying to use the open method of the whisper component via using the handleclick function in button component which should delay the opening of Tooltip by 5 milliseconds. But the output shows the tooltip component immediately after clicking it . 

### Expected Behavior

It should show the overlay after a delay of 5000 ms 

### To Reproduce

This is the [link to code](https://codesandbox.io/s/dazzling-blackburn-q2cpej?file=/src/App.js) I am trying..
and this is the code snippet :
![snippet](https://user-images.githubusercontent.com/103377205/222703174-1eccdc94-77b8-43cd-8807-7208678b24b8.png)

**Comment by Yuiai01** [comment]
This looks like a bug.

**Comment by Yuiai01** [comment]
@AdityaGupta20871  Hello, Since Whisper's trigger is click, it fires immediately, and if you put a button on the outside that triggers the delayed opening, Whisper will behave as expected.

**Comment by SevenOutman** [comment]
Hi @AdityaGupta20871 , as your Whisper receives `trigger="click"` prop, it will inject `onClick` behavior on Button, so your `onClick` will be overwritten and not work. To delay the opening of Whisper, use `delayOpen` prop.

```jsx
<Whisper
  trigger="click"
  delayOpen={5000}
  speaker={...}
>
  <Button>Open after 5000ms</Button>
</Whisper>
```

**Comment by AdityaGupta20871** [comment]
> Hi @AdityaGupta20871 , as your Whisper receives `trigger="click"` prop, it will inject `onClick` behavior on Button, so your `onClick` will be overwritten and not work. To delay the opening of Whisper, use `delayOpen` prop.
> 
> ```js
> <Whisper
>   trigger="click"
>   delayOpen={5000}
>   speaker={...}
> >
>   <Button>Open after 5000ms</Button>
> </Whisper>
> ```

Thanks @SevenOutman I tried putting the delayOpen prop and it worked fine , but I wanted to use the whisper method for delay which is not working properly, Approach I tried for it:
1. I tried putting the button outside of whisper component and removed the trigger property from whisper so that onclick works fine.
- Output : Nothing got displayed for the above approach
2.  I tried putting the button inside of whisper component and removed the trigger property from whisper so that onclick works fine.
- Output : the button got displayed but the onclick was still not working
Although the prop is working fine I can't use the method directly . Hope to resolve it.

**Comment by AdityaGupta20871** [comment]
> @AdityaGupta20871 Hello, Since Whisper's trigger is click, it fires immediately, and if you put a button on the outside that triggers the delayed opening, Whisper will behave as expected.

Thanks @Yuiai01 But the button doesn't get displayed if i put it outside with whisper component and I also tried removing the trigger property and putting button outside and inside both but onclick was still not working.

**Comment by simonguo** [comment]
Hi @AdityaGupta20871 
You set `trigger="click"` for Whisper and added a click event for Button. The button's click event will not replace the event bound on Whisper, so each click will be triggered in time.
You can set the value of `trigger` to `none` to not bind the event.

```diff
<Whisper
  ref={whisperRef}
- trigger="click"
+ trigger="none" 
  placement="right"
  speaker={<Popover>Required Text</Popover>}
>
  <Button appearance="subtle" onClick={handleclick}>
    Right
  </Button>
</Whisper>
```

**Comment by AdityaGupta20871** [comment]
> Hi @AdityaGupta20871 You set `trigger="click"` for Whisper and added a click event for Button. The button's click event will not replace the event bound on Whisper, so each click will be triggered in time. You can set the value of `trigger` to `none` to not bind the event.
> 
> ```diff
> <Whisper
>   ref={whisperRef}
> - trigger="click"
> + trigger="none" 
>   placement="right"
>   speaker={<Popover>Required Text</Popover>}
> >
>   <Button appearance="subtle" onClick={handleclick}>
>     Right
>   </Button>
> </Whisper>
> ```

Thanks a lot @simonguo , Now Its working fine.
