### ISSUE TITLE
(Cascader): load async data error in inline mode

### ISSUE THREAD

**Issue by SrScottz** [rsuite/rsuite#3130]
### What version of rsuite are you using?

5.28.3

### What version of React are you using?

18.2.0

### What browser are you using?

Chrome

### Describe the Bug

Cascader does not load children when in LINE mode. If you click again while the loader is shown, it appears.
<img width="237" alt="Captura de Tela 2023-03-23 às 16 39 45" src="https://user-images.githubusercontent.com/52793930/227332761-ab30d2f2-1bb7-4a8f-b9f4-042431f05a1d.png">

### Expected Behavior

Get childs.

### To Reproduce

https://rsuitejs.com/components/cascader/

Add inline mode in async example.

**Comment by imyuanx** [comment]
I can fix it 🙋

**Comment by imyuanx** [comment]
Don't worry, it only takes some time.
