### ISSUE TITLE
SelectPicker component "name" prop is not passed to input element

### ISSUE THREAD

**Issue by iska9der** [rsuite/rsuite#3137]
### What version of rsuite are you using?

^5.29.0

### What version of React are you using?

^18.2.0

### What version of TypeScript are you using (if any)?

^4.9.4

### What browser are you using?

Chromium

### Describe the Bug

SelectPicker component "name" prop is not passed to input element

### Expected Behavior

Pass value of prop "name" to the input element

### To Reproduce

https://codesandbox.io/s/compassionate-morse-rgktzk?file=/src/index.tsx

**Comment by SevenOutman** [comment]
Hi @iska9der, SelectPicker is not guaranteed to assign `name` to underlying `<input>` element. Could you clarify the necessity in doing so?

**Comment by iska9der** [comment]
> Hi @iska9der, SelectPicker is not guaranteed to assign `name` to underlying `<input>` element. Could you clarify the necessity in doing so?

Hey! 
For example, when used in form:
1. filling formData uncontrollable way
2. after submitting form, reset it using formRef.current.reset()

**Comment by SevenOutman** [comment]
> For example, when used in form:
> 
> 1. filling formData uncontrollable way
> 2. after submitting form, reset it using formRef.current.reset()

That doesn't look like how it's recommended to control form fields with React. You may use Form component to control values of fields in a form.

```jsx
const [formValue, setFormValue] = useState({ user: 'Tom' })

return (
  <Form formValue={formValue} onChange={setFormValue}>
    <Form.Control name="user" accepter={SelectPicker} data={users} />
  </Form>
)
```

If you want to use SelectPicker without Form, use `value`/`onChange` props. This is the pattern called ["controlled component" according to React documentation](https://react.dev/reference/react-dom/components/input#controlling-an-input-with-a-state-variable).

```jsx
const [user, setUser] = useState('Tom')

return (
  <SelectPicker data={users} value={user} onChange={setUser} />
)
```

**Comment by SevenOutman** [comment]
> Then maybe remove the ability to set a name? To save us from thinking that this is possible 😃

I'll look into it to find out whether `name` prop exists intentionally or it could be removed.

**Comment by medi11** [comment]
Same issue in Datepicker, not sure whats the benefit of removing/not passing to the input.

**Comment by dongalor** [comment]
Phew, now I understand why InputPicker is not accessible in FormData by name :) 😥
