### ISSUE TITLE
Navbar component overlaps with the sidebar 

### ISSUE THREAD

**Issue by AdityaGupta20871** [rsuite/rsuite#3142]
### What browser are you using?

Microsoft Edge

### Describe the Bug

![2023-04-03-20-35-33](https://user-images.githubusercontent.com/103377205/229583343-6384fb39-ab36-49e6-9bf0-ed3c6342ee90.png)
**The responsive nav is overlapping with the sidebar after the max prop value reaches 1000** 

### Expected Behavior

![2023-04-03-23-11-59](https://user-images.githubusercontent.com/103377205/229586591-20ea2c1f-1fc5-411f-8eed-4d30d90e2b66.png)
**The responsive Nav should remain inside the block to enhance the UX** 

### To Reproduce

To resolve this issue we can change the max prop value to 700 and min prop value to 100 within the Slider component. Also  we can set the default width to 300.
```diff
-min={300}
-max={1000}
-progress step={50}
+min={100}
+max={700}
+progress step={50}
```
I can resolve this issue if you can assign it to me.
Hope it helps.

**Comment by SevenOutman** [comment]
Hi @AdityaGupta20871, thanks for being willing to help! I'm assigning this issue to you :)

**Comment by AdityaGupta20871** [comment]
Hi @SevenOutman I have created a PR Kindly check it Hope it helps!
