### ISSUE TITLE
rsuite cdn not working

### ISSUE THREAD

**Issue by hgonzalezcelis** [rsuite/rsuite#3143]
### What version of rsuite are you using?

5.30.0

### What version of React are you using?

18

### Describe the Bug

Hello I try use react on web page 

transformScriptTags.ts:252 You are using the in-browser Babel transformer. Be sure to precompile your scripts for production - https://babeljs.io/docs/setup/
(anonymous) @ transformScriptTags.ts:252
Jve @ index.ts:230
Yve @ index.ts:214
_createWrap.js:28 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at t (_createWrap.js:28:31)
    at useClassNames.js:17:24
    at Icon.js:61:107
    at renderWithHooks (react-dom.development.js:15015:20)
    at updateForwardRef (react-dom.development.js:17074:22)
    at beginWork (react-dom.development.js:19128:18)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3942:16)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3991:18)
    at invokeGuardedCallback (react-dom.development.js:4053:33)
    at beginWork$1 (react-dom.development.js:23994:9)
    at performUnitOfWork (react-dom.development.js:22806:14)
    at workLoopSync (react-dom.development.js:22737:7)
    at renderRootSync (react-dom.development.js:22700:9)
    at performSyncWorkOnRoot (react-dom.development.js:22323:20)
    at react-dom.development.js:11357:28
    at unstable_runWithPriority (react.development.js:2764:14)
    at runWithPriority$1 (react-dom.development.js:11306:12)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11352:11)
    at flushSyncCallbackQueue (react-dom.development.js:11339:5)
    at discreteUpdates$1 (react-dom.development.js:22450:11)
    at discreteUpdates (react-dom.development.js:3753:14)
    at dispatchDiscreteEvent (react-dom.development.js:5919:5)
t @ _createWrap.js:28
(anonymous) @ useClassNames.js:17
(anonymous) @ Icon.js:61
renderWithHooks @ react-dom.development.js:15015
updateForwardRef @ react-dom.development.js:17074
beginWork @ react-dom.development.js:19128
callCallback @ react-dom.development.js:3942
invokeGuardedCallbackDev @ react-dom.development.js:3991
invokeGuardedCallback @ react-dom.development.js:4053
beginWork$1 @ react-dom.development.js:23994
performUnitOfWork @ react-dom.development.js:22806
workLoopSync @ react-dom.development.js:22737
renderRootSync @ react-dom.development.js:22700
performSyncWorkOnRoot @ react-dom.development.js:22323
(anonymous) @ react-dom.development.js:11357
unstable_runWithPriority @ react.development.js:2764
runWithPriority$1 @ react-dom.development.js:11306
flushSyncCallbackQueueImpl @ react-dom.development.js:11352
flushSyncCallbackQueue @ react-dom.development.js:11339
discreteUpdates$1 @ react-dom.development.js:22450
discreteUpdates @ react-dom.development.js:3753
dispatchDiscreteEvent @ react-dom.development.js:5919
react_devtools_backend.js:2655 The above error occurred in the <Icon> component:

    at https://cdn.jsdelivr.net/npm/rsuite@5.30.0/dist/rsuite.min.js:2:63754
    at AngleDown
    at div
    at i (https://cdn.jsdelivr.net/npm/rsuite@5.30.0/dist/rsuite.min.js:2:497744)
    at div
    at https://cdn.jsdelivr.net/npm/rsuite@5.30.0/dist/rsuite.min.js:2:495872
    at div
    at https://cdn.jsdelivr.net/npm/rsuite@5.30.0/dist/rsuite.min.js:2:99279
    at ToggleButton
    at https://cdn.jsdelivr.net/npm/rsuite@5.30.0/dist/rsuite.min.js:2:404658
    at div
    at https://cdn.jsdelivr.net/npm/rsuite@5.30.0/dist/rsuite.min.js:2:370293
    at https://cdn.jsdelivr.net/npm/rsuite@5.30.0/dist/rsuite.min.js:2:409389
    at https://cdn.jsdelivr.net/npm/rsuite@5.30.0/dist/rsuite.min.js:2:452508
    at div
    at https://cdn.jsdelivr.net/npm/rsuite@5.30.0/dist/rsuite.min.js:2:238760
    at div
    at https://cdn.jsdelivr.net/npm/rsuite@5.30.0/dist/rsuite.min.js:2:244713
    at <anonymous>:28:20
    at div
    at https://cdn.jsdelivr.net/npm/rsuite@5.30.0/dist/rsuite.min.js:2:310341
    at form
    at https://cdn.jsdelivr.net/npm/rsuite@5.30.0/dist/rsuite.min.js:2:232365
    at div
    at div
    at div
    at https://cdn.jsdelivr.net/npm/rsuite@5.30.0/dist/rsuite.min.js:2:311762
    at t (https://cdn.jsdelivr.net/npm/rsuite@5.30.0/dist/rsuite.min.js:2:83356)
    at https://cdn.jsdelivr.net/npm/rsuite@5.30.0/dist/rsuite.min.js:2:78668
    at div
    at https://cdn.jsdelivr.net/npm/rsuite@5.30.0/dist/rsuite.min.js:2:592841
    at https://cdn.jsdelivr.net/npm/rsuite@5.30.0/dist/rsuite.min.js:2:361753
    at https://cdn.jsdelivr.net/npm/rsuite@5.30.0/dist/rsuite.min.js:2:306830
    at App (<anonymous>:45:31)

### To Reproduce

Index.html

<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>MarkEdit</title>
        <script crossorigin src="https://unpkg.com/react@17/umd/react.development.js"></script>
        <script crossorigin src="https://unpkg.com/react-dom@17/umd/react-dom.development.js"></script>
        <script crossorigin src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
        <link crossorigin rel="stylesheet" href="https://cdn.jsdelivr.net/npm/rsuite@5.30.0/dist/rsuite.min.css" crossorigin="anonymous" referrerpolicy="no-referrer" />
        
        <script type="text/babel" src="app.js"></script>
        
        
    </head>
    <body>
        <main id="application"></main>
        <script src="https://cdn.jsdelivr.net/npm/rsuite@5.30.0/dist/rsuite.min.js" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
   
    </body>
    
 
</html>

App.js

const {Button, ButtonToolbar,
Modal, Placeholder, Schema, Form , SelectPicker, Icon} = rsuite;

const { StringType } = Schema.Types;
const model = Schema.Model({
  dataActionId: StringType().isRequired('This field is required.'),
  email: StringType()
    .isEmail('Please enter a valid email address.')
    .isRequired('This field is required.')
});

const Field = React.forwardRef((props, ref) => {
    const { name, message, label, accepter, error, ...rest } = props;
    return (
      <Form.Group controlId={`${name}-10`} ref={ref} className={error ? 'has-error' : ''}>
        <Form.ControlLabel>{label} </Form.ControlLabel>
        <Form.Control name={name} accepter={accepter} errorMessage={error} {...rest} />
        <Form.HelpText>{message}</Form.HelpText>
      </Form.Group>
    );
  });

function App() {
    const [open, setOpen] = React.useState(false);
    const handleOpen = () => setOpen(true);
    const handleClose = () => setOpen(false);
    const formRef = React.useRef();
    const [formError, setFormError] = React.useState({});
    return (
        <>
            <ButtonToolbar>
                <Button onClick={handleOpen}> Open</Button>
            </ButtonToolbar>

            <Modal open={open} onClose={handleClose}>
                Ingrese info
                <Form model={model}  ref={formRef}>
                <Modal.Body>
                    
                    <Field
                        name="dataActionId"
                        label="Tipo de movimiento"
                        accepter={SelectPicker}
                        error={formError.dataActionId}
                        style={{ display: 'inline-block', width: 200 }}
                        data={[
                        { label: 'Todo', value: 'todo' },
                        { label: 'Open', value: 'open' },
                        { label: 'Close', value: 'close' },
                        { label: 'Error', value: 'error' },
                        { label: 'Processing', value: 'processing' },
                        { label: 'Done', value: 'done' }
                        ]}
                    />
                        <ButtonToolbar>
                            <Button appearance="primary" type="submit">
                            Submit
                            </Button>
                        </ButtonToolbar>
                    
                </Modal.Body>
                <Modal.Footer>
                    <Button onClick={handleClose} appearance="primary" type="submit">
                        Ok
                    </Button>
                    <Button onClick={handleClose} appearance="subtle">
                        Cancel
                    </Button>
                </Modal.Footer>
                </Form>
            </Modal>

        </>);
}

ReactDOM.render(<App />,document.getElementById("application"));

**Comment by SevenOutman** [comment]
Could you provide a demo repo that reproduces this issue?

**Comment by hgonzalezcelis** [comment]
![image](https://user-images.githubusercontent.com/11946702/231129869-05c962e1-cdf3-41e2-989c-62b7cdcb30b1.png)

**Comment by hgonzalezcelis** [comment]
https://codesandbox.io/s/react-cdn-rojibv?file=/index.html

**Comment by hgonzalezcelis** [comment]
Hello Seven tks
