### ISSUE TITLE
Online example in quickstart guide not working

### ISSUE THREAD

**Issue by kevgilmore** [rsuite/rsuite#3148]
### Describe the Bug

The example code in the sandbox environment isn't working and have an error in the console.

### Expected Behavior

The example code in the sandbox should not error and show the drawer slide in menu

### To Reproduce

Visit the quickstart page https://rsuitejs.com/guide/usage/

**Comment by SevenOutman** [comment]
Hi @kevgilmore, the CodeSandbox seems to be functioning well (with some error messages to be dismissed though).

<img width="1362" alt="image" src="https://user-images.githubusercontent.com/8225666/230534950-de194db2-d831-44fb-9c2c-b6c735856cc9.png">

**Comment by kevgilmore** [comment]
But the drawer doesn't open, it's not working for me.

**Comment by SevenOutman** [comment]
Sorry, I'm a bit lost here. I'm not sure whether you are saying "the embedded CodeSandbox itself is not working" or "the CodeSandbox is working correctly, but the example code does not output expected result when run". Could you provide a screenshot so that I can understand what's going on?

**Comment by kevgilmore** [comment]
My screenshot would be the same as the above screenshot. The page loads, and when I press the blue 'Hello World' button nothing happens. 

I'd expect the drawer to open.

**Comment by SevenOutman** [comment]
> I'd expect the drawer to open.

In the CodeSandbox on https://rsuitejs.com/guide/usage/ , the Button is not supposed to open a Drawer.

Do you mean you have another CodeSandbox other than the one on https://rsuitejs.com/guide/usage/ , in which you rendered a Button that's supposed to open a Drawer, but it's not working as expected? If so, please provide a link to your CodeSandbox.
