### ISSUE TITLE
Timeline component: add a new boolean prop: reverse

### ISSUE THREAD

**Issue by medmin** [rsuite/rsuite#3160]
### What problem does this feature solve?

**sometimes, we need the timeline to be reversed.** 

For now, i use css override, but that's not ideal

### What does the proposed API look like?

```javascript

<Timeline reverse />

```
<img width="459" alt="Screen Shot 2023-04-12 at 12 22 33 AM" src="https://user-images.githubusercontent.com/16820635/231382439-e0837219-f47c-47c3-95c7-e85fc3d245cc.png">

**Comment by SevenOutman** [comment]
Hi @medmin, could you describe more in-detail what you mean by "timeline be *reveresed*"? Should it reverse the items passed in, or move the highlight dot to the top-first item?

**Comment by medmin** [comment]
> Hi @medmin, could you describe more in-detail what you mean by "timeline be _reveresed_"? Should it reverse the items passed in, or move the highlight dot to the top-first item?

Both.

Please see the attached screenshot in the image. That's my use case.

I need the date and time sorted in a way that the most recent date and time is the top-first item. And of course, the blue dot should be the first too.

**Comment by SevenOutman** [comment]
> I need the date and time sorted in a way that the most recent date and time is the top-first item. And of course, the blue dot should be the first too.

I see. The display order of items can be achieved by simply reverse the Timeline.Item array you're rendering. We just need to provide a way to customize the blue dot's position. WDYT?

**Comment by medmin** [comment]
Exactly

It's easy to reverse the array

Just need to customize the blue dot

**Comment by medmin** [comment]
> > I need the date and time sorted in a way that the most recent date and time is the top-first item. And of course, the blue dot should be the first too.
> 
> 
> 
> I see. The display order of items can be achieved by simply reverse the Timeline.Item array you're rendering. We just need to provide a way to customize the blue dot's position. WDYT?
> 
> 

Exactly

It's easy to reverse the array. But please reverse it inside of your component. Developers do not need to reverse the array.

Just need to customize the blue dot.
