### ISSUE TITLE
Tree组件优化

### ISSUE THREAD

**Issue by kaiwen9602** [rsuite/rsuite#3162]
### What version of rsuite are you using?

5.31.0

### What version of React are you using?

18.2.0

### What version of TypeScript are you using (if any)?

4.9.3

### What browser are you using?

Chrome

### Describe the Bug

可以给 Tree, TreePicker, TreeCheck等 树形相关的组件在每个onSelect时新增parent的值（不仅仅是value值）吗， 并且在每个组件的onChange时：可以提供除Value值外的Item全部信息（可参考antd组件）。 

### Expected Behavior

可以给 Tree, TreePicker, TreeCheck等 树形相关的组件在每个onSelect时新增parent的值（不仅仅是value值）吗， 并且在每个组件的onChange时：可以提供除Value值外的Item全部信息（可参考antd组件）。 

### To Reproduce

可以给 Tree, TreePicker, TreeCheck等 树形相关的组件在每个onSelect时新增parent的值（不仅仅是value值）吗， 并且在每个组件的onChange时：可以提供除Value值外的Item全部信息（可参考antd组件）。

**Comment by SevenOutman** [comment]
> 可以给 Tree, TreePicker, TreeCheck等 树形相关的组件在每个onSelect时新增parent的值（不仅仅是value值）吗

@kaiwen9602 你好。我想这是可行的，我们在 Cascader 组件中也是这样做的。不过，现在的 Tree/TreePicker/CheckTree/CheckTreePicker 组件的 `onSelect` 中已经包含了许多的参数，再为其增加一个新的参数可能会显得有些冗长。我倾向于新增一个譬如 `onSelectItem(item, path)` 回调，在其中会包含选中条目的完整路径。这对于解决你的问题来说是否是可行的？

> 并且在每个组件的onChange时：可以提供除Value值外的Item全部信息（可参考antd组件）。

我并不认为 `onChange` 回调是一个适合传递这些额外信息的地方。如果我们提供了这个新的 `onSelectItem` 回调，对你来说是否其实并不需要在 `onChange` 中获取路径了呢？如果并不是这样，请简单描述一下你的使用场景。

**Comment by kaiwen9602** [comment]
> @kaiwen9602 你好。我想这是可行的，我们在 Cascader 组件中也是这样做的。不过，现在的 Tree/TreePicker/CheckTree/CheckTreePicker 组件的 `onSelect` 中已经包含了许多的参数，再为其增加一个新的参数可能会显得有些冗长。我倾向于新增一个譬如 `onSelectItem(item, path)` 回调，在其中会包含选中条目的完整路径。这对于解决你的问题来说是否是可行的？

新增一个onSelectItem是可行的。

**Comment by SevenOutman** [comment]
> 当我单击子级的时候，我同时想查看当前父级的信息；通过路径的形式也是可行的，这个路径是数组下标路径还是树节点的valueKey路径。

@kaiwen9602 我想 `path` 中应当是路径上各个节点的数组。

```js
const path = [..., parent, selectedItem]
```

> 此外，我发现当我点击父级时会带有Children信息，children中的子节点元素中包含了parent信息。

在目前的实现中，我们确实向传入的 `data` 条目上插入了 `.parent` 属性，以便在组件内部的某些逻辑中回溯元素的祖先节点。但这一实现被认为是不安全的，将会在后续的更新中移除（相关的 PR #3157），因此在应用中不应该依赖此 `.parent` 属性包含的信息。

**Comment by kaiwen9602** [comment]
> 我想 `path` 中应当是路径上各个节点的数组。
> 
> ```js
> const path = [..., parent, selectedItem]
> ```
> 
> 如果只需要查看父级元素，可以通过 `path[path.length - 2]` 访问。

这个是什么时候会更新，更新至哪个版本？？

**Comment by SevenOutman** [comment]
> 这个是什么时候会更新，更新至哪个版本？？

在 v5 中就会添加。你现在在哪些组件上需要添加这个回调？

**Comment by kaiwen9602** [comment]
> 在 v5 中就会添加。你现在在哪些组件上需要添加这个回调？

目前在Tree组件中用到，希望的所有树组件都添加这个回调。例如：treePicker 和 checkTree.

**Comment by kaiwen9602** [comment]
> > 这个是什么时候会更新，更新至哪个版本？？
> 
> 在 v5 中就会添加。你现在在哪些组件上需要添加这个回调？

我看你已经更新到主分支了， 具体会在哪个版本发布出来使用？
