### ISSUE TITLE
Form表单数字验证NumberType的min(0)和range(0,*)中的0提示信息显示为[min]（不显示0）

### ISSUE THREAD

**Issue by wangwc-dev** [rsuite/rsuite#3164]
### What version of rsuite are you using?

5.19.0

### What version of React are you using?

18.0.0

### What version of TypeScript are you using (if any)?

4.4.2

### What browser are you using?

Chrome

### Describe the Bug

![001](https://user-images.githubusercontent.com/78397810/232662968-86ea9940-2eab-4bc9-81b3-e9c3dbcccad4.png)
![002](https://user-images.githubusercontent.com/78397810/232662992-7ff28294-ae9c-461b-9dd2-b41c5e85611f.png)
Form表单数字验证NumberType的min(0)和range(0,*)中的0提示信息显示为[min]（不显示0）

**Comment by imyuanx** [comment]
这个 bug 是 rsuite 的依赖项 [schema-typed](https://github.com/rsuite/schema-typed) 引起的，我在 schema-typed 新开了一个 [issue](https://github.com/rsuite/schema-typed/issues/68) 来推进解决这个问题

**Comment by wangwc-dev** [comment]
好的，谢谢

**Comment by wangwc-dev** [comment]
会在[https://github.com/rsuite/schema-typed/issues/68](url)关注后续

**Comment by simonguo** [comment]
Fixed in https://github.com/rsuite/schema-typed/pull/69 and  https://github.com/rsuite/rsuite/pull/3181
