### ISSUE TITLE
CheckPicker Option To Collapse All Grouped Sections By Default

### ISSUE THREAD

**Issue by aemonm** [rsuite/rsuite#3165]
### What problem does this feature solve?
Could the CheckPicker have an option - similar to the CheckTreePicker's `defaultExpandAll` to have grouped sections collapsed by default, instead of having them expanded?

**Comment by SevenOutman** [comment]
@aemonm CheckTreePicker with `uncheckableItemValues` can achieve something similar to CheckPicker with `groupBy`. Does that fits your use case?

```jsx
const data = [
  { 
    label: 'Group 1',
    value: 1,
    children: [
      {
        label: 'Item 1',
        value: 11
      }
    ]
  }
]

<CheckTreePicker
  data={data}
  uncheckableItemValues={[1]}
/>
```
