### ISSUE TITLE
The Picker can still be selected by keyboard in readOnly mode

### ISSUE THREAD

**Issue by superman66** [rsuite/rsuite#3166]
### What version of rsuite are you using?

latest

### What version of React are you using?

latest

### What browser are you using?

Chrome

### Describe the Bug

Online demo: https://rsuitejs.com/components/form/#disabled-and-read-only.

When I select readOnly mode, all the Pickers expect `DatePicker`, `DateRangePicker` can still select data via the keyboard.

https://user-images.githubusercontent.com/12592949/233312454-c73952ca-9ef7-4342-894a-beed300b4282.mov

### Expected Behavior

In readOnly mode, the Pickers should not support selecting data by keyborad.

**Comment by SevenOutman** [comment]
> To fix the issue where dropdowns are still selectable and modifiable even when the readOnly mode is set, you need to set the disabled attribute to true on each of the dropdowns when the readOnly mode is enabled.

Hi @Cs4K1Sr4C It's actually a bug that dropdowns still open in `readOnly` mode. But thanks for the workaround!
