### ISSUE TITLE
rsuite-table renderSortIcon in Headers within a ColumnGroup does not work

### ISSUE THREAD

**Issue by martinianol** [rsuite/rsuite#3169]
### What version of rsuite are you using?

rsuite-table: 5.9.0

### What version of React are you using?

16.12.0

### What version of TypeScript are you using (if any)?

None

### What browser are you using?

Chrome

### Describe the Bug

Hi!
First of all let me tell you that I love rsuite-table. Thank you so much for doing such a fine product.

The renderSortIcon function works well on single columns without any grouping.
However, when it comes to columns which are grouped the standard/default icons appears. The sorting functionality is fine. Is just the renderSortIcon which is not.

### Expected Behavior

The custom icon should appear instead of the default when renderSortIcon is active no matter if it is a grouped column or a single column

### To Reproduce

https://user-images.githubusercontent.com/78988545/234132948-e2bbee41-50a6-4c2c-812e-e4065e3c5a63.mov

I am not able to share my full code but here is a screenshot.
It works fine when there is no ColumnGroup as a parent of Column and HeaderCell

<img width="1112" alt="Screenshot 2023-04-24 at 19 54 57" src="https://user-images.githubusercontent.com/78988545/234133449-d8ce8b80-0695-4eeb-8673-82449a2659ec.png">

**Comment by SevenOutman** [comment]
I'm routing this issue to @simonguo as it's related to `rsuite-table`.

**Comment by simonguo** [comment]
Fixed in https://github.com/rsuite/rsuite-table/pull/426

> example: https://rsuite-table-git-fix-rendersorticon-rsuite.vercel.app/#sort
