### ISSUE TITLE
DatePicket time separator not showing the one set in the format pattern but the fixed ":" separator

### ISSUE THREAD

**Issue by scharlito** [rsuite/rsuite#3174]
### What version of rsuite are you using?

5.32.0

### What version of React are you using?

18.2.0

### What version of TypeScript are you using (if any)?

4.9.5

### What browser are you using?

Chrome

### Describe the Bug

When setting the format pattern for Finland, which includes a "." instead of ":" in the time format (dd.MM.yyyy HH.mm), I see following in the placeholder and DatePicker:

![image](https://user-images.githubusercontent.com/20658934/234841199-35b3ae4c-2230-40c2-8fa7-978c1a82ccc7.png)

as you can see the placeholder and the selected value are being displayed in the correct format but in the date picker the ":" separator is being used. Does this work as design? or is it possible to correct this to set this separator as in the given format pattern?

### Expected Behavior

Something like this:

![image](https://user-images.githubusercontent.com/20658934/234842291-571fac27-53a8-4f35-acc7-2e9756b6e5d9.png)

### To Reproduce

Set the format of the date picker as following: "dd.MM.yyyy HH.mm"

**Comment by SevenOutman** [comment]
@scharlito It's by-design as far as I'm concerned. The month title on the top-left of the calendar view does not apply the `format` either. But I think it's worth considering if we should make them apply the `format` as well. @simonguo What do you think?

**Comment by simonguo** [comment]
The date formatting on the calendar panel is not set through the format parameter, but rather through the localization configuration of the component. 

https://github.com/rsuite/rsuite/blob/6722b10e5e4a292b91f23daf9ee3090a3bf2538e/src/locales/default.ts#L21-L22

Currently, only the date has been configured, and in the future, the formatting of time can be added to the configuration.

**Comment by simonguo** [comment]
Fixed in v5.72.0
