### ISSUE TITLE
flexGrow在性能不太好时，能看到初始宽度不对。

### ISSUE THREAD

**Issue by fallenleavesguy** [rsuite/rsuite#3176]
### What version of rsuite are you using?

5.32.0

### What version of React are you using?

18

### What browser are you using?

Chrome

### Describe the Bug

table组件在切换界面时，使用flexGrow，会看见初始宽度不对，然后马上撑开了，会不会是因为，没在useLayoutEffect中更新宽度呢

### Expected Behavior

初始宽度设置正确再显示，宽度不闪烁

### To Reproduce

https://codesandbox.io/s/flexgrow-update-too-late-cb3ylb?file=/index.js:1282-1286

上面是bug demo.
mac性能太好，看不出来，更新太快了。可以像下面的视频这样，切换到手机调试模式，右上角选择low end mobile，限制性能至低端设备，就很容易触发了。win上chrome 67是有些明显的。
谢谢大佬修复。🤗

https://user-images.githubusercontent.com/9261562/235033482-d11ea954-f43e-4f3d-8edf-7cd6005d6e61.mov

**Comment by SevenOutman** [comment]
这是一个关于 `rsuite-table` 的议题，我将转发给 @simonguo 来查看

**Comment by simonguo** [comment]
@fallenleavesguy  你好，按照你的方式在我本地确实无法复现问题。 

不过通过你提供的视频，我们分析一下原因：当表格 Column 设置 flexGrow 以后，当前列的宽度就应该动态设置，它的计算公式：通过 Table 的 width 减去所有其他列的 width。 在初始化的时候，Table 的 width 是未知的，只有当渲染到 DOM 后，才获取到 Table 实际的 width，然后再通过它重新去计算设置了 flexGrow 列的 width。 

在以上过程中主要的性能瓶颈在 DOM 的渲染速度，如果你当前的客户端环境性能较差，可能就会出现视频中的情况。

要解决这个问题，就要想办法减少对 DOM 的访问直接拿到表格的 width。你可以尝试在 Table 上设置一个固定的 width 看看是否能够解决你遇到的问题。 

```
<Table width={500} >
```

**Comment by fallenleavesguy** [comment]
@simonguo 设置width={500}确实不会有问题，但是需求是100%宽度，跟着窗口变，不能设置固定宽度。很容易复现的，你把codesandbox右边的地址https://cb3ylb.csb.app/复制出来单独打开，chrome设置成low end mobile性能，我在i3 12100 + chrome 67正常情况下不限制性能， 很也很容易复现。
能不能在类似useLayoutEffect中第一次mount时，读取宽度并更新呢。

**Comment by simonguo** [comment]
@fallenleavesguy 目前就是在 mount 的时候获取 Table width 做的更新。你如果不设置 width , Table 内部始终需要:等待DOM渲染=> 获取宽度 => 计算列宽这个过程 。你如果有好的改进建议可以去给 rsuite-table 提 PR。

另外，你可以动态给 Table 设置 width ，类似这种: https://github.com/rsuite/rsuite-admin-template/blob/master/src/pages/tables/members/DataTable.tsx#L126

**Comment by fallenleavesguy** [comment]
好吧，不科学啊，mount了应该能拿到正确宽度了才对。

**Comment by fallenleavesguy** [comment]
@simonguo 感觉是应该读到了，但是没触发马上重新渲染，等我有空了也瞅瞅

**Comment by fallenleavesguy** [comment]
@simonguo 
我修好了，给你发了个PR，有空能看看合并到rsuite主仓库吗？项目等你合并救火了，我不想fork一个出来重新发NPM。原因是原来的代码:
[原代码](https://github.com/rsuite/rsuite-table/blob/dd7c9ed6476a1cde27fba490221fa4fa70cece62/src/utils/useCellDescriptor.ts#LL95C8-L95C8)
用的useUpdateEffect跳过了第一次Mount的情况。我加上了
[修复PR](https://github.com/rsuite/rsuite-table/pull/432)
