### ISSUE TITLE
Unable to use rsuite.min.css in Next Js and Tailwind

### ISSUE THREAD

**Issue by TeamVikngs** [rsuite/rsuite#3189]
### What version of rsuite are you using?

4.10.2

### What version of React are you using?

17.0.2

### What version of TypeScript are you using (if any)?

4.3.4

### What browser are you using?

Chrome

### Describe the Bug

When I import "rsuite/dist/rsuite.min.css"; it's saying Module not found: Can't resolve 'rsuite/dist/rsuite.min.css'. 

I want to use rsuite css along with my tailwind css and I don't want to use less specific styles.

I tried this demo repo https://github.com/takeItIzzy/tailwind_cli_demo but this repo is also not working as intended

### Expected Behavior

I can import the css and use it without any Module Not found errors

**Comment by SevenOutman** [comment]
Hi @TeamVikngs, in rsuite v4 the import path of CSS files should be `'rsuite/dist/styles/rsuite-default.css'`.

Ref v4 doc https://v4.rsuitejs.com/guide/usage/

**Comment by TeamVikngs** [comment]
will try, but I really liked the code base. Is there any documentation of which method is where. I want to learn how you have implemented the Methods / Components

**Comment by SevenOutman** [comment]
> Is there any documentation of which method is where. I want to learn how you have implemented the Methods / Components
> in particular, I want to know how the RangeSlider component is implemented.

Codebase of 4.x version is on the [`v4` branch](https://github.com/rsuite/rsuite/tree/v4).
As of RangeSlider component, it's at https://github.com/rsuite/rsuite/blob/v4/src/RangeSlider/RangeSlider.tsx
