### ISSUE TITLE
selectPicker defaultValue can't be set async

### ISSUE THREAD

**Issue by sullivtr** [rsuite/rsuite#3194]
### What version of rsuite are you using?

5.11.1

### What version of React are you using?

18.2.0

### What version of TypeScript are you using (if any)?

4.6.4

### What browser are you using?

Chrome

### Describe the Bug

I am using an RTK query to fetch a list of accounts, and I use the response data to load in the options for the selectPicker component. 

For example: 

```
const { data: accounts = [], isLoading: isLoadingAccounts } = useGetAccountsQuery('');

. . . 
return(
. . .
 <SelectPicker size="lg" className="filterGroup" loading={isLoadingAccounts} label="Account" data={accounts.map(a => ({ label: a.name, value: a.name}))} defaultValue={accounts[0].name}/>
. . .
)
```

As you can see from the example, I want to set the defaultValue to the fist item returns in the accounts list. However, on first load, it will not render with the default value selected asynchronously. The input remains blank until I leave & return to the page. 

### Expected Behavior

I would expect the value for defaultValue to populate once the data is present. I have even tried to implement a custom hook with useEffect and a conditionally loading component to ensure the element does in fact exist by the time the component loads, but it still shows blank defaultValue. 

### To Reproduce

My example should demonstrate how to reproduce. But you just need to ensure the defaultValue is being set based on the response from an async query.

**Comment by simonguo** [comment]
Hi @sullivtr 
`defaultValue` is only initialized once after the component is mounted, and updating it later will not change the state of the component. It is similar to an input form element, and the following is an example to help you understand.

```tsx
const App = () => {
  const [value, setValue] = React.useState("1");

  React.useEffect(() => {
    setTimeout(() => {
      setValue("2");
    }, 1000);
  }, []);

  return <input type="text" defaultValue={value} />;
};
```

The value of the `input` will not become 2 after one second if you use `defaultValue`. If you want it to become 2, you should make the component controlled by using `value` instead of `defaultValue`.

> Controlled SelectPicker  : https://rsuitejs.com/components/select-picker/#controlled

**Comment by SevenOutman** [comment]
I'm closing this issue as it seems to have been resolved. Feel free to re-open if it's actually not.
