### ISSUE TITLE
CheckTree: props "searchKeyword" and "searchBy" filter the tree using the previous react state value

### ISSUE THREAD

**Issue by Alessandro-Polcini** [rsuite/rsuite#3196]
### What version of rsuite are you using?

^5.31.0

### What version of React are you using?

^18.2.0

### What browser are you using?

Chrome

### Describe the Bug

The internal search performed on CheckTree when using either the `searchKeyword` or the `searchBy` prop is "delayed": it is possible that the component is using the previous state to filter the tree instead of the current text value.

Example:

- `searchKeyword` = "a" -> tree values are filtered by ""
- `searchKeyword` = "ab"  -> tree values are filtered by "a"
- `searchKeyword` = "abc"  -> tree values are filtered by "ab"
- `searchKeyword` = "ab"  -> tree values are filtered by "abc"

### Expected Behavior

The CheckTree should be filtered using the current (updated) value passed using the `searchKeyword` prop.

#### In CodeSandbox:
```
import React, { useState } from "react";
import ReactDOM from "react-dom";
import "./styles.css";
import { CheckTree } from "rsuite";
import { mockTreeData } from "./mock";

const data = mockTreeData({
  limits: [3, 3, 4],
  labels: (layer, value, faker) => {
    const methodName = ["jobArea", "jobType", "firstName"];
    return faker.name[methodName[layer]]();
  }
});

const App = () => {
  const [textFilterValue, setTextFilterValue] = useState("");

  function onChange(e) {
    setTextFilterValue(e.target.value);
  }

  return (
    <>
      <input value={textFilterValue} onChange={onChange} />
      <CheckTree data={data} defaultExpandAll searchKeyword={textFilterValue} />
    </>
  );
};

ReactDOM.render(<App />, document.getElementById("root"));
```

**Comment by SevenOutman** [comment]
I'm routing this issue to @superman66 as it's related to CheckTree component.

**Comment by zeari** [comment]
Any news on this @superman66 ?

**Comment by superman66** [comment]
@zeari  I have been busy with other things recently. I anticipate resolving this issue within the current week.

**Comment by zeari** [comment]
> @zeari I have been busy with other things recently. I anticipate resolving this issue within the current week.

Thanks for the update @superman66
