### ISSUE TITLE
Table rowHeight not working when virtualized

### ISSUE THREAD

**Issue by ivanvaccari** [rsuite/rsuite#3202]
### What version of rsuite are you using?

5.33.1

### What version of React are you using?

>17.0.0

### What browser are you using?

Chrome

### Describe the Bug

rowHeight is not working properly when combined with virtualized.
The row expands accordingly to the rowHeight value, but cells does not expand to fill the row height.

This bug appeared somewhere after V5.10.2 of rsuite-table, because forcing that version solves the issue.

Example image:
![image](https://github.com/rsuite/rsuite/assets/28731723/25fd1cb8-e2fd-46de-8a08-6b5d4d8286fd)

The bottom border of the row appear floating somewhere under the text instead of the bottom of he row

### Expected Behavior

Cell expand his height to fill row, as it happens when the virtualization is disabled.

### To Reproduce

Jsfiddle demo: https://codesandbox.io/s/new-snow-hqfty9

**Comment by SevenOutman** [comment]
I'm routing this issue to @simonguo as it's related to `rsuite-table`

**Comment by simonguo** [comment]
Fixed in [rsuite-table@5.10.6](https://github.com/rsuite/rsuite-table/releases/tag/5.10.6)
