### ISSUE TITLE
When the RTL switch is turned on, the style width of the "close menu" button is abnormal.

### ISSUE THREAD

**Issue by leon-fong** [rsuite/rsuite#3221]
### What version of rsuite are you using?

5.34.1

### What version of React are you using?

--

### What version of TypeScript are you using (if any)?

--

### What browser are you using?

Chrome

### Describe the Bug

<img width="1440" alt="image" src="https://github.com/rsuite/rsuite/assets/45456105/2113e20e-8ea4-481e-a1ef-d561079f6153">

link: [https://rsuitejs.com/components/overview/](https://rsuitejs.com/components/overview/)

When the RTL switch is turned on, the style width of the "close menu" button is abnormal.

### Expected Behavior

Expected behavior: The "close menu" button should display normally when the RTL switch is turned on.

### To Reproduce

If it is confirmed that this is a bug, I am willing to do my best to fix it.

**Comment by SevenOutman** [comment]
> If it is confirmed that this is a bug, I am willing to do my best to fix it.

Hi @leon-fong, thanks for raising this issue. I can confirm that it's a bug. 

Thanks for being willing to help, I'm assigning this issue to you :)
