### ISSUE TITLE
InputNumber unexpectedly emits empty value

### ISSUE THREAD

**Issue by wangwc-dev** [rsuite/rsuite#3249]
### What version of rsuite are you using?

5.19.0

### What version of React are you using?

18.0.0

### What version of TypeScript are you using (if any)?

4.4.2

### What browser are you using?

Chrome

### Describe the Bug

InputNumber You can enter the character e, and the value collected by the form after entering the character e is empty
![image](https://github.com/rsuite/rsuite/assets/78397810/45af5f2c-b5e4-46ac-a7c5-6856c47f625e)

**Comment by SevenOutman** [comment]
@wangwc-dev Looks like it's the default behavior of a native `<input type="number" />` according to the [specification](https://html.spec.whatwg.org/multipage/input.html#number-state-(type=number)).

> If the [value](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#concept-fe-value) of the element is not a [valid floating-point number](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#valid-floating-point-number), then set it to the empty string instead.
