### ISSUE TITLE
Make trigger of Whisper component an array to be able to have multiple ways to trigger the whisper

### ISSUE THREAD

**Issue by mkhib** [rsuite/rsuite#3252]
I wanted to open the speaker of the whisper both by hover and also if the user focuses the element by tab key on the keyboard but if I set the trigger to hover focusing the element with tab won't open the speaker and if I set it to focus it won't open by hovering. So I think having a set of trigger options in an array would be helpful.

**Comment by SevenOutman** [comment]
Hi @mkhib, I believe the `trigger` prop of Whisper component does accept arrays, [per documentation](https://rsuitejs.com/components/whisper/).

<img width="603" alt="image" src="https://github.com/rsuite/rsuite/assets/8225666/945799f3-9cf8-4069-96f6-8701529c468f">
