### ISSUE TITLE
Calendar onMonthChange callback not fired when clicking on day from next/previous month or Today button

### ISSUE THREAD

**Issue by Jeremy-Doneghue** [rsuite/rsuite#3272]
### What version of rsuite are you using?

5.36.0

### What version of React are you using?

18.2.0

### What version of TypeScript are you using (if any)?

4.9.3

### What browser are you using?

Firefox

### Describe the Bug

The calendar renders days that fall outside the current month as a part of the first and last week. Clicking on one of those days takes you to the corresponding month for that day.

The month being viewed has changed, but the onMonthChange callback does not fire. 
Similarly, clicking the "Today" button does not fire the callback if the current day is not in the month being viewed.

### Expected Behavior

Any built in action that changes which month is shown in the calendar should also fire the onMonthChange callback.

### To Reproduce

Add a handler for the onMonthChange callback.
In the calendar, click on a day from the first or last week that belongs to the previous/next month.
Observe that the callback does not fire.

Navigate to a different month than the current month.
Click the "Today" button.
Observe that the callback does not fire.

**Comment by SevenOutman** [comment]
I'm routing this issue to @simonguo as it's related to API design of Calendar component.

**Comment by simonguo** [comment]
This is a bug we need to fix.
