### ISSUE TITLE
Auto close popover when focus on input in table

### ISSUE THREAD

**Issue by hoangminh306** [rsuite/rsuite#3284]
### What version of rsuite are you using?

5.26.0

### What version of React are you using?

18.2.0

### What version of TypeScript are you using (if any)?

4.9.4

### What browser are you using?

All

### Describe the Bug

Focus on input in popover in table cell, its auto close

### Expected Behavior

Do not close popover

**Comment by nhtminh2999** [comment]
I face the same issue

**Comment by SevenOutman** [comment]
Hi @hoangminh306, does `enterable` prop of Whisper component help?
