### ISSUE TITLE
InputNumber组件失去焦点会触发onChange事件

### ISSUE THREAD

**Issue by icefee** [rsuite/rsuite#3287]
### What version of rsuite are you using?

5.37.0

### What version of React are you using?

18.0.0

### Describe the Bug

https://stackblitz.com/edit/react-7tgdr7?file=index.js

**Comment by SevenOutman** [comment]
Hi @icefee, according to source code and tests, this is the expected behavior. @simonguo could you please confirm this?

**Comment by icefee** [comment]
Ok, Thank you for your replay.
