### ISSUE TITLE
unable to find font-family and font-size variable for Nav.Menu

### ISSUE THREAD

**Issue by jhylton** [rsuite/rsuite#3289]
Hello,

working with the sidenav i have several <Nav.Menu> with <Nav.Item> with-in. I can override the font-family for the items, but not for menu items:

@font-size-base: 14px;
@font-family-base: Verdana, Geneva, Tahoma, sans-serif;

how can I override the font-family and size for Nav.Menu?

Thanks,

**Comment by SevenOutman** [comment]
Hi @jhylton, I'm not sure that I understand your question as accurately, but I tried setting `@font-size-base` and `@font-family-base` Less variables and it seems that both Nav items and Nav menu items applied the style correctly.

<img width="545" alt="image" src="https://github.com/rsuite/rsuite/assets/8225666/c9c65cd4-234b-4430-a329-7f5cb0f8cba5">
