### ISSUE TITLE
Table fixed 最右侧列无效

### ISSUE THREAD

**Issue by fannaoshaoxiang** [rsuite/rsuite#330]
<Table
                        height={750}
                        autoHeight={false}
                        data={this.state.data}
                        onRowClick={data => {
                            console.log(data);
                        }}
                    >
                        <Column width={70} align="center" fixed={true}>
                            <HeaderCell>序号</HeaderCell>
                            <Cell dataKey="id"/>
                        </Column>

                        <Column fixed={true}>
                            <HeaderCell>订单备注</HeaderCell>
                            <Cell dataKey="firstName"/>
                        </Column>

                        <Column resizable={true}>
                            <HeaderCell>客户名称</HeaderCell>
                            <Cell dataKey="lastName"/>
                        </Column>

                        <Column>
                            <HeaderCell>操作时间</HeaderCell>
                            <Cell dataKey="email"/>
                        </Column>

                        <Column  width={70} fixed={true}>
                            <HeaderCell>操作</HeaderCell>
                            <Cell dataKey="email"/>
                        </Column>

                    </Table>

        代码中， 【操作】 一列 给与 fixed={true} 发现没有固定

**Comment by simonguo** [comment]
@fannaoshaoxiang 目前支持固定在右侧。

**Comment by fannaoshaoxiang** [comment]
大神们辛苦！建议予以支持
