### ISSUE TITLE
Number input allows extra characters despite min and max

### ISSUE THREAD

**Issue by dgastudio** [rsuite/rsuite#3309]
### What version of rsuite are you using?

5.31

### What version of React are you using?

nextjs 13

### What browser are you using?

Chrome

### Describe the Bug

https://rsuitejs.com/components/input-number/
is possible to add + and - to field values
i can't understand about -, but it shoud not work if you have set 0 as min
but +??

![CleanShot 2023-07-26 at 15 57 16@2x](https://github.com/rsuite/rsuite/assets/161524/f4f863ac-1221-4723-ae9a-39ba5f1bfc30)

it can be cleared by form state updates, but... 

thank you

### Expected Behavior

only number are allowed in input
in case "min" param is not set, - can be applied
but not +

**Comment by SevenOutman** [comment]
@dgastudio Thanks for raising this. It's indeed unexpected to allow trailing plus/minus signs if the principle of InputNumber is "only omit value that `isNaN(value)` is false` IMO. It should be fixed. 

But I believe + should be allowed at the beginning of value, acting as "positive sign" (when `max` is above 0), WDYT?

**Comment by dgastudio** [comment]
@SevenOutman thank you for your response.
IMHO, all depends on backend and simplicity.
- becomes a negative number
the presence of + or its absence, is a positive number. have you ever seen +signed numbers somethere?

i'm working on backend based on nestjs, numberfield is typed as number, so + is automatically removed.

i mean, is a little bit tricky to handle data in this widget,  but, take a look at this example. it's how it should work in my opinion
https://www.bryntum.com/products/scheduler/docs/api/Core/widget/NumberField

thank you

**Comment by SevenOutman** [comment]
@dgastudio After some more investigation, I realized that it's the native `<input type="number" />` that is allowing those characters, and it's the expected behavior per [specification](https://html.spec.whatwg.org/multipage/input.html#number-state-(type=number)). 

I'm leaving it as is for now, until we find the necessity to add additional constraints to alter what we should expect from InputNumber despite specification.
