### ISSUE TITLE
5.37.2 SelectPicker error

### ISSUE THREAD

**Issue by erodriguezvesti** [rsuite/rsuite#3318]
### What version of rsuite are you using?

5.37.2

### What version of React are you using?

18.2.0

### What version of TypeScript are you using (if any)?

4.8.4

### What browser are you using?

Chrome

### Describe the Bug

Since 5.37.2 select picker not recognize dynamic data.  If data array changes the picker not changes visible options.

In 5.37.1 works perfect

Regards!

### Expected Behavior

visible options may be change when data changes

### To Reproduce

Update 5.37.1 to 5.37.2

**Comment by SevenOutman** [comment]
Hi @erodriguezvesti thanks for reporting this! We've just published a hotfix version [`rsuite@5.37.3`](https://www.npmjs.com/package/rsuite/v/5.37.3), please try out and see if this issue is resolved.
