### ISSUE TITLE
SelectPicker with Form questions about using together about form reset

### ISSUE THREAD

**Issue by sinianzhiren** [rsuite/rsuite#3330]
### What version of rsuite are you using?

5.28.2

### What version of React are you using?

5.28.2

### What browser are you using?

chrome

### Describe the Bug

`<Form ref={formRef as any} formDefaultValue={defaultFormValue} formValue={formValue} onChange={setFormValue} layout="inline">
<Control accepter={SelectPicker} {...controlProps} />
<Button style={{marginLeft: 10}} onClick={handleReset} type="reset" loading={isLoading || isFetching} className={'reset-btn'}
                appearance="default">
          重置
        </Button>
</Form>`

When I click the reset button, I expect the SelectPicker option to be blank, but the button on the page appears as a selection item. Only when the reset is set to a blank character will the selection be cleared

### Expected Behavior

When I click the reset button, I expect the SelectPicker option to be blank, but the button on the page appears as a selection item. Only when the reset is set to a blank character will the selection be cleared

**Comment by SevenOutman** [comment]
Hi @sinianzhiren, I couldn't quite get it how you were using the SelectPicker from the snippet you provide. Could you provide a CodeSandbox demo? You could use this template https://codesandbox.io/s/rsuite-template-jdydg7

**Comment by sinianzhiren** [comment]
@SevenOutman the link is example [https://codesandbox.io/s/gracious-williamson-v6j752?file=/src/App.js](https://codesandbox.io/s/gracious-williamson-v6j752?file=/src/App.js) ,   use  `setFormValue({ op: undefined });` can not empty SelectPicker components selected option, but use `setFormValue({op: ''});` is ok

**Comment by SevenOutman** [comment]
> use `setFormValue({ op: undefined });` can not empty SelectPicker components selected option, but use `setFormValue({op: ''});` is ok

This is the expected behavior. Setting `value={undefined}` on SelectPicker makes it an uncontrolled component. That's similar to an `<input>` element.
