### ISSUE TITLE
Custom background color of Calendar cells

### ISSUE THREAD

**Issue by SevenOutman** [rsuite/rsuite#3333]
Add an API for customizing the style of a Calendar cell based on the date it represents.

Something like (to be further considered):

```typescript
type CalendarProps = {
  cellClassName?: (date: Date) => string | undefined;
}
```

---

### Discussed in https://github.com/rsuite/rsuite/discussions/3331#discussioncomment-6717813

<div type='discussions-op-text'>

<sup>Originally posted by **harshRishi** August 11, 2023</sup>
Please help me to give these dates background color accordingly! currently it is showing badges which content!

</div>

**Comment by itsajay1029** [comment]
I'd love to work on this. Can you assign it to me @SevenOutman ? Also can you explain the issue and what needs to be done a little?

**Comment by SevenOutman** [comment]
> I'd love to work on this. Can you assign it to me @SevenOutman ? Also can you explain the issue and what needs to be done a little?

Hi @itsajay1029, it seems there's already a PR for this. Thanks all the same for being willing to help!
