### ISSUE TITLE
CheckPicker error in Form

### ISSUE THREAD

**Issue by wangwc-dev** [rsuite/rsuite#3338]
### What version of rsuite are you using?

5.19

### What version of React are you using?

18.0

### What version of TypeScript are you using (if any)?

4.4.2

### What browser are you using?

Chrome

### Describe the Bug

![image](https://github.com/rsuite/rsuite/assets/78397810/dec0d6f6-354c-4328-b20a-39f191ad1388)

![image](https://github.com/rsuite/rsuite/assets/78397810/38ae41df-3178-49a5-bacd-02793ac7f224)
　@simonguo I want to use the onSelect callback function in the property, but it will give an error

**Comment by SevenOutman** [comment]
It's a known issue that pickers are short of generic types support. But it's not easy to fix without introducing breaking change. We're trying to fix this in v6. For now you can declare `item: any` to dismiss this error.

```jsx
<CheckPicker
  data={[{ label: 'a', value: 'a' }]}
  onSelect={(value: string, item: any) => {
    console.log(value, item);
  }}
/>
```

**Comment by wangwc-dev** [comment]
Thank you.
