### ISSUE TITLE
<InputNumber > 输入汉字问题

### ISSUE THREAD

**Issue by kaiwen9602** [rsuite/rsuite#3350]
### What version of rsuite are you using?

5.38.0

### What version of React are you using?

5.38.0

### What version of TypeScript are you using (if any)?

5.33.0

### What browser are you using?

Chrome

### Describe the Bug

5.38.0和5.33.0都存在这个问题
在InputNumber输入中文时，在onChnage中打印value为空字符串。 空字符串又会转为0。
那么问题出现了， 我在输入“。”的时候（本意要输入 "."）我的数值变为0。
我再handle中判断空字符串（即：中文输入时）时， return。 那么我删除值时无法全部删除。

### Expected Behavior

 在判断value输入为非数值类型时onChange回调中的value返回null/undefined或其他标识 与 使用delete删除后的空字符串做区分。或者inputNumber删除后使用0而不是空字符串

**Comment by SevenOutman** [comment]
你好 @kaiwen9602，请你提供一个可以复现此问题的 CodeSandbox。你可以使用这个模板 https://codesandbox.io/s/rsuite-template-jdydg7。同时请你验证一下原生的 `<input type="number" />` 是否也是相同的表现。
