### ISSUE TITLE
delayOpen bug for Whisper Tooltips

### ISSUE THREAD

**Issue by kevincrossgrove** [rsuite/rsuite#3358]
### What browser are you using?
Google Chrome Version 110.0.5481.177

### Describe the Bug

When adding `delayOpen` prop to Whisper tooltips that are side by side, and then swiping cursor over all of those whispers, the tooltips remain open even after cursor leaves. I was able to reproduce on rsuite docs itself.

https://rsuitejs.com/components/tooltip/ 

![image](https://github.com/rsuite/rsuite/assets/58451014/5ba20f3a-6f59-4850-bfa2-e0ebc64ad197)

This happens in a project of mine as well, but only on production.

### Expected Behavior

Tooltips should close after cursor leaves, even if delayOpen prop is set

### To Reproduce

Go to [Rsuite tooltip docs](https://rsuitejs.com/components/tooltip/)

Paste this code in the example: 
```js
import { Tooltip, Whisper, Button, ButtonToolbar } from 'rsuite';

const tooltip = (
  <Tooltip>
    This is a help <i>tooltip</i> .
  </Tooltip>
);

const App = () => (
  <ButtonToolbar>
    <Whisper placement="top" controlId="control-id-1" trigger="hover" speaker={tooltip} delayOpen={500}>
      <Button>Hover</Button>
    </Whisper>
    <Whisper placement="top" controlId="control-id-2" trigger="hover" speaker={tooltip} delayOpen={500}>
      <Button>Hover</Button>
    </Whisper>
    <Whisper placement="top" controlId="control-id-3" trigger="hover" speaker={tooltip} delayOpen={500}>
      <Button>Hover</Button>
    </Whisper>
  </ButtonToolbar>
);

ReactDOM.render(<App />, document.getElementById('root'));
```

Swipe your cursor over the 3 hover buttons. And notice tooltips appear after then never close

![image](https://github.com/rsuite/rsuite/assets/58451014/4bc67ce6-22f4-4b19-875b-740782d75051)

**Comment by SevenOutman** [comment]
Hi @kevincrossgrove, thanks for raising this. This can be reproduced by moving the cursor into the Button then move out before time reaches `delayOpen` - the tooltip will show anyway. We're discussing on whether this should be considered a bug.

**Comment by simonguo** [comment]
Fixed in https://github.com/rsuite/rsuite/pull/3401
