### ISSUE TITLE
Document nav is getting cut from the bottom

### ISSUE THREAD

**Issue by harshagarwal08** [rsuite/rsuite#3366]
### Describe the Bug

<img width="222" alt="Screenshot 2023-09-12 at 4 51 59 PM" src="https://github.com/rsuite/rsuite/assets/57107237/f1d8098d-45b5-4147-80db-248160440732">

### Expected Behavior

It should either have an overflow: scroll or the height shouldn't be fixed.

**Comment by simonguo** [comment]
Fixed
