### ISSUE TITLE
TreePicker 能否包含存在子节点的选项不可选

### ISSUE THREAD

**Issue by Lorwell** [rsuite/rsuite#3369]
TreePicker 的属性配置中能否存在类似 Cascader 属性 parentSelectable 的配置，用于设置父节点不可选

**Comment by SevenOutman** [comment]
关于向 TreePicker 添加 `unselectableItemValues` prop 的提议 #3352 可覆盖此需求。我会将此 issue 作为重复 issue 关闭。如果你有不同的看法，可以随时重新开启。
