### ISSUE TITLE
表单 Form.Control accepter 一个 Textarea，参数 rows 无法传递

### ISSUE THREAD

**Issue by hczs** [rsuite/rsuite#3374]
### What version of rsuite are you using?

5.37.3

### What version of React are you using?

18.2.0

### What version of TypeScript are you using (if any)?

5.0.2

### What browser are you using?

Chrome

### Describe the Bug

按照官方文档表单部分demo，使用一个最简单表单，编写后报错，但是不影响运行；
使用的官方文档的代码：https://rsuitejs.com/zh/components/form/#%E9%BB%98%E8%AE%A4
复现 demo codesandbox 地址: https://codesandbox.io/s/cranky-roman-64wfd7?file=/src/example.tsx
以下是报错图：
![image](https://github.com/rsuite/rsuite/assets/43227582/77a21a6a-e322-4c87-9ae3-30d301be6ba0)
错误信息：
TS2769: No overload matches this call.
Overload  1  of  2 ,
(props: FormControlProps<any, any> & { accepter?: ForwardRefExoticComponent<RefAttributes<unknown>> | undefined; } & RefAttributes<...>): ReactElement<...> | null
, gave the following error.
Type
{     rows: number;     name: string;     accepter: ForwardRefExoticComponent<RefAttributes<unknown>>; }
is not assignable to type
IntrinsicAttributes & FormControlProps<any, any> & { accepter?: ForwardRefExoticComponent<RefAttributes<unknown>> | undefined; } & RefAttributes<...>
Property  rows  does not exist on type
IntrinsicAttributes & FormControlProps<any, any> & { accepter?: ForwardRefExoticComponent<RefAttributes<unknown>> | undefined; } & RefAttributes<...>
Overload  2  of  2 ,
(props: FormControlProps<any, any>, context?: any): ReactNode
, gave the following error.
Type
{     rows: number;     name: string;     accepter: ForwardRefExoticComponent<RefAttributes<unknown>>; }
is not assignable to type
IntrinsicAttributes & FormControlProps<any, any>
Property  rows  does not exist on type
IntrinsicAttributes & FormControlProps<any, any>

**Comment by simonguo** [comment]
你尝试给 Textarea 添加一个 TextAreaProps 。
```tsx
import { Form, Input, InputPicker, InputProps } from "rsuite";

type TextAreaProps = InputProps & React.TextareaHTMLAttributes<HTMLTextAreaElement>;

const Textarea = React.forwardRef(
  (props: TextAreaProps, ref) => (<Input {...props}  as="textarea" />)
);
```

**Comment by hczs** [comment]
> 你尝试给 Textarea 添加一个 TextAreaProps 。
> 
> ```tsx
> import { Form, Input, InputPicker, InputProps } from "rsuite";
> 
> type TextAreaProps = InputProps & React.TextareaHTMLAttributes<HTMLTextAreaElement>;
> 
> const Textarea = React.forwardRef(
>   (props: TextAreaProps, ref) => (<Input {...props}  as="textarea" />)
> );
> ```
感谢！问题成功解决
