### ISSUE TITLE
Form inside drawer, on drag, modal is closed

### ISSUE THREAD

**Issue by dgastudio** [rsuite/rsuite#3394]
### What version of rsuite are you using?

5.x

### What version of React are you using?

18

### What browser are you using?

chrome

### Describe the Bug

Drawer be accidentally closed when the user enters some data in the form, then selects the value in the field and moves the cursor outside the panel, it will close. 

### Expected Behavior

modal must remain opened

### To Reproduce

https://codesandbox.io/s/hungry-gianmarco-qwdmcs?file=/index.js

**Comment by dgastudio** [comment]
seems the solution will be to remove mouseup from the list of events which can close the modl

**Comment by simonguo** [comment]
Hi @dgastudio , you can set the value of backdrop to `static` to deal with this usage scenario.

```tsx
<Drawer backdrop="static">
```

**Comment by dgastudio** [comment]
@simonguo 
i don't think is a proper solution, because in this case, backdrop becomes totally unclickable.
