### ISSUE TITLE
TagPicker not focusable when using ref and programmatically focusing

### ISSUE THREAD

**Issue by amjadbouhouch** [rsuite/rsuite#3396]
### What version of rsuite are you using?

5.40.0

### What version of React are you using?

18.2.0

### What version of TypeScript are you using (if any)?

5.0.2

### What browser are you using?

Chrome

### Describe the Bug

The `TagPicker` component is not focusable when using a ref and trying to programmatically set focus on the input field.

### Expected Behavior

When using a ref and calling ` .focus()` on the TagPicker component, it should focus on the input field, allowing keyboard input.

### To Reproduce

1. Go to the provided CodeSandbox link: https://codesandbox.io/s/tagpicker-focus-issue-gyfstd?file=/src/App.js

2. Observe that the TagPicker component is not focusable even after attempting to set focus programmatically.

**Comment by simonguo** [comment]
Hi @amjadbouhouch ,try calling the `click` event to see if it fits your usage scenario.
```js
ref.current.click();
```

**Comment by amjadbouhouch** [comment]
@simonguo Thank you for you answer it's works!
