### ISSUE TITLE
ok button of daterangepicker disappearing

### ISSUE THREAD

**Issue by RISHIRGK** [rsuite/rsuite#3408]
### What version of rsuite are you using?

5.40.0

### What version of React are you using?

18.2

### What browser are you using?

edge

### Describe the Bug

ok button  is getting diappeared after picking  2nd date from date picker 
![Web capture_19-10-2023_4262_localhost](https://github.com/rsuite/rsuite/assets/96022835/54351bd8-f436-4886-acd5-9a45fd7e90ff)

**Comment by alvincast** [comment]
Did you find any solution ?

**Comment by dsdsharma** [comment]
any solutions for this issue?
