### ISSUE TITLE
官网文档UI格式非常帮，可以把官网的文档UI开源成一个包不

### ISSUE THREAD

**Issue by kemistep** [rsuite/rsuite#3411]
官网文档的样式蛮好的，可以开源一个基于next的最小组件库文档嘛

![image](https://github.com/rsuite/rsuite/assets/16223610/1464cd5c-1928-47ac-be08-234e0055bd98)

自定义组件，用这个官网文档蛮好的

**Comment by simonguo** [comment]
暂时没这个精力去做这个事情，你可以直接拉 docs 目录下的代码运行。

> https://github.com/rsuite/rsuite/tree/main/docs
