### ISSUE TITLE
Not able to copy text from table

### ISSUE THREAD

**Issue by yourvishal007** [rsuite/rsuite#3412]
### What version of rsuite are you using?

5.2.4

### What version of React are you using?

17.0.2

### Describe the Bug

Not able to copy text from the table. 

### To Reproduce

**Steps to reproduce the step.**

1. Go to [https://rsuitejs.com/components/table/#examples](https://rsuitejs.com/components/table/#examples).
2. Select a text from the table as shown in the screenshot.
3. Use **Cmd/Ctrl + C** to copy the text.
4. Paste it copied content.
5. It is not being pasted.

<img width="1440" alt="Screenshot 2023-10-24 at 8 46 46 AM" src="https://github.com/rsuite/rsuite/assets/37593161/8d7b862b-24c1-49de-af41-0d8df5dcd074">.

But if you check in previous versions documentation then it is working.
Please refer above steps with [https://v4.rsuitejs.com/components/table/#Examples](https://v4.rsuitejs.com/components/table/#Examples) this link includes the documentation of Version 4 of rsuite.

**Comment by simonguo** [comment]
https://codesandbox.io/s/suspicious-booth-7dnlfm

Hi  @yourvishal007,  the above is an example using rsuite@5.2.4, but I cannot reproduce the problem of not copying text.

**Comment by simonguo** [comment]
> @simonguo Please refer to https://rsuitejs.com/components/table/#examples Not able to copy any text from that table also.

![image](https://github.com/rsuite/rsuite/assets/1203827/f48f823d-6b0d-4c73-893a-972aee055f14)

🤔

**Comment by yourvishal007** [comment]
@simonguo Sorry, I forgot to mention that I'm not able to copy content using **Cmd/Ctrl + C**  commands.
But in previous versions, it is working seamlessly. 
**Steps to reproduce the step.**

1. Go to [https://rsuitejs.com/components/table/#examples](https://rsuitejs.com/components/table/#examples).
2. Select a text from the table as shown in the screenshot.
3. Use **Cmd/Ctrl + C** to copy the text.
4. Paste it copied content.
5. It is not being pasted.

<img width="1440" alt="Screenshot 2023-10-24 at 8 46 46 AM" src="https://github.com/rsuite/rsuite/assets/37593161/8d7b862b-24c1-49de-af41-0d8df5dcd074">.

But if you check in previous versions documentation then it is working.
Please refer above steps with [https://v4.rsuitejs.com/components/table/#Examples](https://v4.rsuitejs.com/components/table/#Examples) this link includes the documentation of Version 4 of rsuite.

**Comment by yourvishal007** [comment]
@simonguo could you please let me know an approximate time by when this fix will be reflected on the package.
