### ISSUE TITLE
Table 在没有数据的显示 默认无数据视图？如何实现！！

### ISSUE THREAD

**Issue by fannaoshaoxiang** [rsuite/rsuite#342]
我看了文档 没有发现如何实现 Table 在没有数据的时候，显示默认图的方法

**Comment by simonguo** [comment]
```js
<Table 
    data={[]} 
    locale={{
        emptyMessage: <div>数据为空</div>,
        loading: '加载中...'
    }}
>
```

**Comment by fannaoshaoxiang** [comment]
建议大神 提供一下 表格 选中行 高亮功能

**Comment by fannaoshaoxiang** [comment]
@simonguo  建议大神 提供一下 表格 选中行 高亮功能

**Comment by simonguo** [comment]
你可以通过 `onRowClick ` + `rowClassName`  组合实现，  rowClassName 支持传递一个 function

**Comment by fannaoshaoxiang** [comment]
@simonguo  rowClassName在初始化的可以被调用到， onRowClick可以获取到数据。 我没有明白如何结合实现 高亮功能

**Comment by fannaoshaoxiang** [comment]
@simonguo  我实现了，谢谢
