### ISSUE TITLE
Whisper bug when SelectPicker is children

### ISSUE THREAD

**Issue by abdullaev388** [rsuite/rsuite#3421]
### What version of rsuite are you using?

5.41.0

### What version of React are you using?

18.2.0

### What browser are you using?

Chrome

### Describe the Bug

When Selectpicker is children of Whisper and you hover on SelectPicker, there is an error

### To Reproduce

open this [link](https://stackblitz.com/edit/stackblitz-starters-bmjxjn?file=src%2FApp.js) and hover on Selectpicker

**Comment by simonguo** [comment]
Hi @abdullaev388  SelectPicker's ref is not associated with an HTMLElement. When Whisper obtains the position of an element, it needs to obtain the attributes of HTMLElement.

So it can be solved by:
```tsx
<Whisper speaker={<Tooltip>hi</Tooltip>}>
  <span>
  <SelectPicker data={[]} />
  </span>
</Whisper>
```

or
```tsx
<Whisper speaker={<Tooltip>hi</Tooltip>}>
  {(triggerEvents, triggerRef) => {
    return (
      <SelectPicker
        {...triggerEvents}
        data={[]}
        ref={(ref) => {
          triggerRef.current = ref?.target;
        }}
      />
    );
  }}
</Whisper>
```
