### ISSUE TITLE
Add 'onRangesChange' API to support return current predefined range

### ISSUE THREAD

**Issue by coolyard** [rsuite/rsuite#3431]
### What problem does this feature solve?
Now I need to save current predefined range status, but I found that if there have same predefinedRanges(like THIS MONTH(When today is the end of the month) and LAST 30 DAYS) there won't trigger onChage callback, so I can NOT get that which predefined range  user click unless there have onRangesChange API.

### What does the proposed API look like?
`onRangesChange | (label: string) => void`

**Comment by helloint** [comment]
This is the [demo](https://codesandbox.io/s/daterangepicker-same-date-range-gmz3w6?file=/index.js) shows that on `2023-09-30`, if you choose "This month" and "Last 30 days", it represent the same date range, so `onChange` won't be triggered.
I understand that the component treat the selected date range as the core data so the behavior seems right. But we hope to find a way to get the predefined range label that user clicked.

**Comment by simonguo** [comment]
Support `onShortcutClick` event in [rsuite@5.44.0](https://github.com/rsuite/rsuite/releases/tag/v5.44.0)

**Comment by coolyard** [comment]
Verifyied.
