### ISSUE TITLE
Picker Interaction with Popover

### ISSUE THREAD

**Issue by hedzerkoolstra** [rsuite/rsuite#3433]
### What version of rsuite are you using?

latest

### What version of React are you using?

18.0.0

### What version of TypeScript are you using (if any)?

4.4.0

### What browser are you using?

Chrome

### Describe the Bug

I'm adding `<InputPicker />` to `<Popover />` and the z-indeces of these components don't seem be compatible with eachother. The menu of the picker is behind the popover.

### Expected Behavior

Menu of the picker should be in front of the popover.

### To Reproduce

[Sandbox](https://codesandbox.io/s/admiring-rgb-yhmrpv) 
Open popover
Open selector menu
See the menu is behind the popover

**Comment by simonguo** [comment]
Hi @hedzerkoolstra , the option of `<InputPicker />` will render at the outermost layer of the document by default through absolute positioning. If you want to use it in combination with `<Popover>`, you need to set its rendering container to inside `<Popover>`.


```tsx
const container = React.useRef(null);

const speaker = (
  <Popover title="Title" style={{ width: 200 }}>
    <div ref={container} style={{ position: "relative" }} />
    <InputPicker data={data} container={() => container.current} />
  </Popover>
);
```
> https://codesandbox.io/s/kind-microservice-7xz4g2

**Comment by hedzerkoolstra** [comment]
Hi @simonguo, thanks for the quick reply. It did work with your solution, very helpful!
