### ISSUE TITLE
DatePicker does not remove the value from the field if I select the date and delete it using the keyboard

### ISSUE THREAD

**Issue by helderrsantos** [rsuite/rsuite#3443]
### What version of rsuite are you using?

5.43.0

### What version of React are you using?

18.2.0

### What version of TypeScript are you using (if any)?

4.9.3

### What browser are you using?

Chrome

### Describe the Bug

When I select the date in the date picker component and delete the values by pressing the keyboard, the value is initially removed, but when clicking anywhere on the screen the value returns to the field

### Expected Behavior

The correct option would be after selecting the field values and deleting the values by pressing the keyboard, in the same way as activating onClean

### To Reproduce

![Recording 2023-11-09 at 10 50 37](https://github.com/rsuite/rsuite/assets/106779562/874f516a-fbe8-4c96-83ac-d5eb45b87307)

**Comment by simonguo** [comment]
Fixed in [v5.44.0](https://github.com/rsuite/rsuite/releases/tag/v5.44.0)

**Comment by helderrsantos** [comment]
Thank you bro, see you later
