### ISSUE TITLE
Add a MultiResourceTagPicker component

### ISSUE THREAD

**Issue by firstdorsal** [rsuite/rsuite#3468]
#### Use Case
I'm building a file server where the user can apply tags to the files in the UI.
For one file at a time the TagPicker component works like a charm. For multiple files and their collective tags this gets difficult.
I don't even need the logic behind it but the Checkboxes on the TagPicker would need to have the `indeterminate` state available that is possible with the standalone Checkbox Component.

This is why:

Select 2 Files and display their collective tags/keywords 
 1. Common Tags between both files get a full Checkbox
 2. Tags that are present on other files but not on these 2 files get an empty checkbox
 3. Tags that are only present on one of the two files need to have a third state so that they either can be removed from both files or applied to both files

### What does the proposed API look like?

The Proposal is to add an option to set the `indeterminate` state on the tags and have the checkboxes render and reflect that state back.

**Comment by simonguo** [comment]
Hi @firstdorsal 
If you add a `renderMenuItemCheckbox` prop, through which you can customize a `<Checkbox indeterminate />`, will it solve your current problem?

**Comment by firstdorsal** [comment]
@simonguo 

Using it like this does not work:
```tsx
<TagPicker
    data={this.state.data}
    value={this.state.selectedTags}
    renderMenuItemCheckbox={<Checkbox indeterminate />}
/>
```
Could you provided some guidance on how to use this prop? I don't think it is present in the documentation is it?

**Comment by simonguo** [comment]
TagPicker does not currently support `renderMenuItemCheckbox`, I am thinking about how to meet your needs in a more flexible way.

So prepare to add a renderMenuItemCheckbox attribute, and cooperate with the renderValue attribute, which should be able to achieve your needs.

```tsx
<TagPicker
  renderMenuItemCheckbox={checkboxProps => {
    const { value, ...restProps } = checkboxProps;
    
    // Should it be in indeterminate state? 
    const indeterminate = ...

    return <Checkbox {...restProps} indeterminate={indeterminate} />;
  }}
  renderValue={(values, items, tags) => {
    return values.map((tag, index) => <Tag key={index}>{tag}</Tag>);
  }}
/>;
```

**Comment by firstdorsal** [comment]
Do I understand this right:
This example is currently not working but will maybe work in a future version? 🙈

**Comment by simonguo** [comment]
> This example is currently not working but will maybe work in a future version? 🙈

Yes, I plan to add this feature in version 5.47.0 or 5.48.0.

**Comment by firstdorsal** [comment]
Awesome! Thank you! I left you a tip for your great work on Open Collective <3

**Comment by firstdorsal** [comment]
Works like a charm. Thank you!
