### ISSUE TITLE
Cannot access the website

### ISSUE THREAD

**Issue by jkomyno** [rsuite/rsuite#35]
### What is the expected behavior?

https://rsuitejs.com should load without oddities.

### What is the current behavior?

https://rsuitejs.com seems stuck in a loop. It keeps refreshing itself after dismissing the loader icon.

### What are the steps to reproduce?

Open https://rsuitejs.com with whichever browser

**Comment by SevenOutman** [comment]
@jkomyno Can not reproduce that. Could you please be more specific about wich which browsers you have encountered this issue?

**Comment by jkomyno** [comment]
OS: Android 5, Windows 10
Browsers: Chrome, Chrome mobile, Microsoft Edge

**Comment by simonguo** [comment]
@jkomyno  
Try again, Does the problem still exist?

**Comment by bboydflo** [comment]
the website seems down again, or is not accessible

**Comment by simonguo** [comment]
@bboydflo 

Where is your current location?
What browser are you using?

**Comment by bboydflo** [comment]
I'm in Denmark and I'm using firefox

**Comment by simonguo** [comment]
Firefox access is fine. The React Suite website is built with netlify and you can see if the network is working.

https://www.netlifystatus.com/
