### ISSUE TITLE
 <Nav.Item> 建议支持非换行 ，横向滚动支持

### ISSUE THREAD

**Issue by fannaoshaoxiang** [rsuite/rsuite#350]
<Nav.Item> 加到多个超出屏幕宽度的时候 ，目前情况下 <Nav.Item>是换行处理，
建议大神 提供 ：不换行，横向滚动支持。

场景：中后台应用中有Tab页面的展示实现多窗口一样的场景，类似于浏览器多标签一样的。

**Comment by simonguo** [comment]
这个功能需求我会和设计团队讨论后再决定是否支持，现在我更推荐你这样使用：

```html
<Nav appearance="tabs" >
    <Nav.Item active>Item A</Nav.Item>
    <Nav.Item>Item B</Nav.Item>
    <Nav.Item>Item C</Nav.Item>
    <Nav.Item>Item D</Nav.Item>
    <Dropdown title="More...">
        <Dropdown.Item>Item E-1</Dropdown.Item>
        <Dropdown.Item>Item E-2</Dropdown.Item>
        <Dropdown.Item>Item E-3</Dropdown.Item>
        <Dropdown.Item>Item E-4</Dropdown.Item>
    </Dropdown>
</Nav>
```

**Comment by fannaoshaoxiang** [comment]
@simonguo  大神您给的方案是可以的，就是有一点，需要自己判断宽度然后实现缩率为 <Dropdown >
代码干干的多，还要操作dom。心累！！！，然后然后就是不能复用。。。。。

**Comment by simonguo** [comment]
https://github.com/rsuite/tab-nav
https://rsuite.github.io/tab-nav/

**Comment by fannaoshaoxiang** [comment]
@simonguo  大神目前没有计划 集成到rsuite吗？

**Comment by simonguo** [comment]
为了保持 rsuite 库能在一定体积量内，类似这种有针对性业务的组件都不会放到 rsuite 里面去。
用户在使用的时候是可以基于 rsuite 进行扩展封装的。

目前我们正在准备 Extensions 相关的文档，同时也非常欢迎社区的开发者也能够基于 rsuite 封装一些针对业务场景的组件。

使用的话，需要单独安装：
```
npm install @rsuite/responsive-nav --save
```
