### ISSUE TITLE
DatePicker menuStyle prop is not applied to the menu

### ISSUE THREAD

**Issue by GideonMax** [rsuite/rsuite#3508]
### What version of rsuite are you using?

5.0.0

### What version of React are you using?

18.0.24

### What browser are you using?

Chrome

### Describe the Bug

setting menuStyle prop on DateSelector does not affect the style of the menu element.

### Expected Behavior

The menuStyle prop should affect the menu element's style.

### To Reproduce

https://codesandbox.io/s/happy-joji-lr8pzj
this example shows a DatePicker with both the menuStyle and menuClassName props set.

1. open the date picker (click on it)
2. open developer tools and select the menu element.
3. as you can see the menuClassName attribute is applied to the menu but the menuStyle prop does not affect the element.

**Comment by simonguo** [comment]
Fixed in v5.48.1
