### ISSUE TITLE
5.44.0以上日期范围选择器，生产打包会崩溃

### ISSUE THREAD

**Issue by fallenleavesguy** [rsuite/rsuite#3520]
### What version of rsuite are you using?

5.48.0

### What version of React are you using?

18.2.0

### What browser are you using?

Chrome 100

### Describe the Bug

编译生产包，日期范围选择器, 会运行到process.env.RUN_ENV代码，浏览器上process变量为undefined.可能是npm上的编译结果，webpack没替换掉process.env.RUN_ENV

**Comment by fallenleavesguy** [comment]
5.44.0是正常的

**Comment by simonguo** [comment]
Fixed in v5.48.1
