### ISSUE TITLE
日期选择器在屏幕右边时报错，排版混乱

### ISSUE THREAD

**Issue by fallenleavesguy** [rsuite/rsuite#3522]
### What version of rsuite are you using?

5.48.0

_No response_

### What version of React are you using?

18.2.0

_No response_

### What browser are you using?

chrome: 120.0.6099.109
os: m1 Macos Sonoma 14.0

_No response_

### Describe the Bug

![image](https://github.com/rsuite/rsuite/assets/9261562/85ed138b-3881-4304-adec-a12d64af24be)

![image](https://github.com/rsuite/rsuite/assets/9261562/72980ec2-c30f-4fb8-9583-e5151dd795ce)

控制台不会输出报错，需要webpack dev server环境，参考下面的codesandbox

### Expected Behavior

显示正常，不报错

### To Reproduce
[sample](
https://codesandbox.io/p/devbox/crazy-calendar-qzz8hm?file=%2Fsrc%2FApp.js%3A4%2C28&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqgif5aw00073b6muxrw81zv%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqgif5av00023b6msq2ev3w2%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqgif5av00043b6mfyhsx2gd%2522%257D%252C%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqgifsmp005u3b6mt2cdqtx7%2522%257D%255D%252C%2522sizes%2522%253A%255B56.181335265000605%252C43.818664734999395%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqgif5av00063b6mkwcfu5k0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqgif5av00023b6msq2ev3w2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqgif5av00013b6mj4wnpqku%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clqgiyy2m00023b6mb1u3e1gf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A4%252C%2522startColumn%2522%253A28%252C%2522endLineNumber%2522%253A4%252C%2522endColumn%2522%253A28%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqgif5av00023b6msq2ev3w2%2522%252C%2522activeTabId%2522%253A%2522clqgiyy2m00023b6mb1u3e1gf%2522%257D%252C%2522clqgif5av00063b6mkwcfu5k0%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqgif5av00053b6mr74ofyzd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqgif5av00063b6mkwcfu5k0%2522%252C%2522activeTabId%2522%253A%2522clqgif5av00053b6mr74ofyzd%2522%257D%252C%2522clqgif5av00043b6mfyhsx2gd%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqgif5av00033b6mvrnmyfve%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%255D%252C%2522id%2522%253A%2522clqgif5av00043b6mfyhsx2gd%2522%252C%2522activeTabId%2522%253A%2522clqgif5av00033b6mvrnmyfve%2522%257D%252C%2522clqgifsmp005u3b6mt2cdqtx7%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqgifelm005q3b6mx1cefk2c%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clqgifsqo000cefhfflvpb053%2522%257D%255D%252C%2522id%2522%253A%2522clqgifsmp005u3b6mt2cdqtx7%2522%252C%2522activeTabId%2522%253A%2522clqgifelm005q3b6mx1cefk2c%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by simonguo** [comment]
https://codesandbox.io/p/devbox/crazy-calendar-forked-hpsq5q
看一下这个示例是否还存在该问题

**Comment by fallenleavesguy** [comment]
> https://codesandbox.io/p/devbox/crazy-calendar-forked-hpsq5q 看一下这个示例是否还存在该问题

你提供的在线例子里已经没问题了。周一我再在项目里也试一下是否有问题，赞啊

**Comment by fallenleavesguy** [comment]
https://pkg.csb.dev/rsuite/rsuite/commit/c17ae3ba/rsuite
这个版本没问题了
