### ISSUE TITLE
希望可以修改日期选择器的日历图标

### ISSUE THREAD

**Issue by fallenleavesguy** [rsuite/rsuite#3534]
### What problem does this feature solve?
希望可以替换图标，原来的图标不好看，和其它项目的风格不统一
![image](https://github.com/rsuite/rsuite/assets/9261562/25d057b7-4687-4422-ad71-3597f87053ec)

### What does the proposed API look like?
暂无

**Comment by simonguo** [comment]
使用 caretAs 属性: 

```tsx
import { FaCalendar } from "react-icons/fa";

<DatePicker caretAs={FaCalendar} />
```
>  自定义 SVG 的图标，参考 Icon as 属性的使用。

**Comment by fallenleavesguy** [comment]
> 使用 caretAs 属性:
> 
> ```tsx
> import { FaCalendar } from "react-icons/fa";
> 
> <DatePicker caretAs={FaCalendar} />
> ```
> 
> > 自定义 SVG 的图标，参考 Icon as 属性的使用。
这个我看说明还以为是日历里面的箭头，我试试，谢谢

**Comment by fallenleavesguy** [comment]
可以哦
