### ISSUE TITLE
CheckTree深层嵌套checkbox选中异常

### ISSUE THREAD

**Issue by HanShuai-me** [rsuite/rsuite#3559]
### What version of rsuite are you using?

latest

### What version of React are you using?

^17.0.0 || ^18.0.0

### What browser are you using?

Chrome

### Describe the Bug

对于树中的组，进行深层嵌套，对checkTree的属性value设置最深层次子节点的value值，其上层组的checkbox选中异常

### Expected Behavior

对于上述描述的错误，有解决方案吗，或者说我默认可以得到最深层次子节点的value值，将其设置给checktree的属性value后，可以使其上层组的checkbox全部选中√

### To Reproduce

https://codesandbox.io/p/sandbox/naughty-leavitt-97ntwq

**Comment by HanShuai-me** [comment]
![image](https://github.com/rsuite/rsuite/assets/61405826/6e269546-b5ad-4723-8a41-ce99da9e6971)

**Comment by simonguo** [comment]
在 [`rsuite@5.61.0`](https://github.com/rsuite/rsuite/releases/tag/v5.61.0) 版本中已修复
