### ISSUE TITLE
Undocumented breaking change in Form component

### ISSUE THREAD

**Issue by vykintazo** [rsuite/rsuite#3564]
### What version of rsuite are you using?

5.50

### What version of React are you using?

17.0.2

### Describe the Bug

A recently introduced feature in version 5.50.0 which allows `Form` field name nesting ([3511](https://github.com/rsuite/rsuite/pull/3511)) is actually not backwards compatible, as semversion would suggest, and also I don't see it mentioned in the documentation.

In particular, field names like `name[something]` are now being nested due to lodash's `set()`, while previously they were not. It has broken many forms for me.
Of course, field names like `name.something` which were previously flat as well are now affected.

I would expect this new behaviour be documented properly and perhaps communicated as a breaking change.

**Comment by simonguo** [comment]
Hi @vykintazo , the compatibility problem of the form field name nesting this feature has not been considered. I will add an prop to enable this feature to make it compatible with previous versions. Thank you for your feedback.

**Comment by simonguo** [comment]
Fixed in https://github.com/rsuite/rsuite/pull/3568
