### ISSUE TITLE
Modal's backdrop has to be gray

### ISSUE THREAD

**Issue by nikiforov-org** [rsuite/rsuite#3567]
### What version of rsuite are you using?

latest

### What version of React are you using?

latest

### What version of TypeScript are you using (if any)?

latest

### What browser are you using?

Firefox latest, MacOS latest

### Describe the Bug

Modal's backdrop has a transparent background
![image](https://github.com/rsuite/rsuite/assets/25713874/072fac29-e652-471b-89c9-beb5a992c12d)

### Expected Behavior

Modal's backdrop has a gray background

### To Reproduce

Call modal at https://rsuitejs.com/components/modal/ in Firefox

**Comment by simonguo** [comment]
Fixed in [v5.52.0](https://github.com/rsuite/rsuite/releases/tag/v5.52.0)
