### ISSUE TITLE
Import component styles on demand does not work

### ISSUE THREAD

**Issue by pkawula** [rsuite/rsuite#3573]
### What version of rsuite are you using?

5.51.0

### What version of React are you using?

18.2.0

### What version of TypeScript are you using (if any)?

5.2.2

### What browser are you using?

Doesn't matter

### Describe the Bug

When using `import 'rsuite/DateRangePicker/styles/index.less'` styles are not imported properly (only this file styles are applied but not imports inside).
When using `import 'rsuite/dist/rsuite.min.css'` everything works fine.

However when using version 5.49.0 it works fine.

Examples:

- rsuite@5.49.0:
<img width="387" alt="Screenshot 2024-01-19 at 12 08 45" src="https://github.com/rsuite/rsuite/assets/33988240/9abd0b94-bbeb-4128-b118-317125223703">

- rsuite@5.50.0-5.51.0:
<img width="335" alt="Screenshot 2024-01-19 at 12 09 00" src="https://github.com/rsuite/rsuite/assets/33988240/1f0c5536-85f1-4dd8-bcc3-f54265e7e334">

### Expected Behavior

import styles on demand works always

### To Reproduce

The working version (5.49.0) - https://codesandbox.io/p/devbox/rsuite-5-49-0-kpfcry

The **not** working version (5.51.0) - https://codesandbox.io/p/devbox/rsuite-5-51-0-hvr7yp

**Comment by simonguo** [comment]
Hi @pkawula , in rsuite@5.50.0, Input is used as the textbox. You can temporarily fix it by:

```js
import "rsuite/Input/styles/index.less";
import "rsuite/InputGroup/styles/index.less";
```

> We will fix this issue in the next version
