### ISSUE TITLE
Cannot set  picker toolbar width 

### ISSUE THREAD

**Issue by MikhailBakaevdev** [rsuite/rsuite#3580]
### What version of rsuite are you using?

5.50.0

### What version of React are you using?

18.2.0

### What version of TypeScript are you using (if any)?

4.3.5

### What browser are you using?

Chrome

### Describe the Bug

Cannot set width for picker toolbar. If i want to set new "OK" button name  then button will be like this 
<img width="381" alt="Screenshot 2024-01-23 at 15 44 14" src="https://github.com/rsuite/rsuite/assets/65615052/6fe103a9-063c-4966-aaf7-b5988aa9fc63">

also  i dont have opportunity to change button color

**Comment by MikhailBakaevdev** [comment]
Hi @simonguo ! thanks for your answer! I have the same settings as in your example but all presets on the bottom like this 
<img width="793" alt="Screenshot 2024-01-25 at 18 45 23" src="https://github.com/rsuite/rsuite/assets/65615052/d82d1e92-4783-4205-a729-99e6b248639d">
<img width="523" alt="Screenshot 2024-01-25 at 18 47 15" src="https://github.com/rsuite/rsuite/assets/65615052/ba3d4c1b-37dc-402a-bcbd-390633a21820">

**Comment by simonguo** [comment]
>  now its always blue but i need primary color for presets and "Ok" button

Currently, custom "Ok" button is not supported, but you can customize the theme color by customizing Less or CSS variables.

Less: https://rsuitejs.com/guide/customization-less/

```less
@primary-color: #4caf50;
```

CSS Variables: https://rsuitejs.com/guide/css-variables/

```css
:root {
  // Colors palette
  // See: https://rsuitejs.com/resources/palette/
  --rs-primary-50: #eeffed;
  --rs-primary-100: #c8f0c7;
  --rs-primary-200: #a5e0a4;
  --rs-primary-300: #82cf82;
  --rs-primary-400: #65bf67;
  --rs-primary-500: #4caf50;
  --rs-primary-600: #37ab3c;
  --rs-primary-700: #22a12a;
  --rs-primary-800: #0f9119;
  --rs-primary-900: #007d0c;
}
```

**Comment by MikhailBakaevdev** [comment]
it works thank u @simonguo
