### ISSUE TITLE
Hide format date when choose period

### ISSUE THREAD

**Issue by MikhailBakaevdev** [rsuite/rsuite#3582]
Hi there! i dont wanna show the client what the date format he is typing. Its will be small fix but very comfortable not only for me. Hide this one 
![Uploading Screenshot 2024-01-23 at 15.49.43.png…]()

Add Boolean flag for format view and also fix styles for this case

**Comment by MikhailBakaevdev** [comment]
<img width="381" alt="Screenshot 2024-01-23 at 15 49 43" src="https://github.com/rsuite/rsuite/assets/65615052/6405e679-f880-47e4-8ff1-8af28ac86b88">

**Comment by simonguo** [comment]
Hi @MikhailBakaevdev add a `showHeader` prop in the next version, when the value is set to `false`, the header is not displayed.

```tsx
<DateRangePicker showHeader={false} />
```
