### ISSUE TITLE
Input: clicking isn’t working when use type='date/datetime-local/week/time'

### ISSUE THREAD

**Issue by myNameIsDu** [rsuite/rsuite#3592]
### What version of rsuite are you using?

5.51.0

### Describe the Bug

https://github.com/rsuite/rsuite/assets/53305259/bcd3c109-d876-46d8-877b-d6212de89101

**Comment by simonguo** [comment]
Hi @myNameIsDu, I don't understand the problem you demonstrated. Isn't this example supposed to be like this?
