### ISSUE TITLE
Cannot use shouldDisableDate 

### ISSUE THREAD

**Issue by MikhailBakaevdev** [rsuite/rsuite#3596]
### What version of rsuite are you using?

5.50.0

### What version of React are you using?

18.2.0

### What version of TypeScript are you using (if any)?

4.3.5

### What browser are you using?

Chrome

### Describe the Bug

Hi there! After import methods in this example with shouldDisableDate https://rsuitejs.com/components/date-range-picker/ 
Methods not works and i got  error like in screenshot. How i can avoid this error and pass available date range to shouldDisableDate prop? 
<img width="739" alt="Screenshot 2024-01-30 at 17 34 58" src="https://github.com/rsuite/rsuite/assets/65615052/c446c7b2-fa08-495f-b478-8690856d5382">

**Comment by simonguo** [comment]
Hi @MikhailBakaevdev , The reason for this problem is that the declaration of the `afterToday` function in TypeScript may be `undefined`. You can temporarily solve this problem in the following ways:

```diff
<DateRangePicker 
-  shouldDisableDate={afterToday()} 
+  shouldDisableDate={afterToday?.()} 
/>;
```
