### ISSUE TITLE
Table 如何撑满？

### ISSUE THREAD

**Issue by fannaoshaoxiang** [rsuite/rsuite#361]
我把Table放置到div中，想让表格撑满div，并且随着div大小改变而改变

**Comment by simonguo** [comment]
![image](https://user-images.githubusercontent.com/1203827/50957386-1435e780-14f9-11e9-9568-caf9cbc48a00.png)

**Comment by fannaoshaoxiang** [comment]
@simonguo   看文档 宽度是可以的 ，高度是固定

**Comment by simonguo** [comment]
文档里面有，设置 autoHeight， 建议同时配置 minHeight

**Comment by fannaoshaoxiang** [comment]
@simonguo  我试试了一下 无法满足 
我重复一下我的需求：
div 高度取值是 css ：calc(100vh - 150px);

按照做法：autoHeight 高度是每行高度  是无法撑满的
![5.png](https://uploads.codesandbox.io/uploads/user/54d06f4d-17b5-465c-83df-cb94c7484cde/WgTH-2019-01-10_17-04-14.png)

**Comment by simonguo** [comment]
不支持，不过处理起来也非常简单。 你取到你容器 div 的高度设置给 table height。

```js
import { DOMHelper as _ } from 'rsuite';

componentDidMount() {
  this.setState({
    height: _.getHeight(this.wrapper)
  });
}

render() {
  return (
    <div
      ref={ref => {
        this.wrapper = ref;
      }}
    >
      <Table height={this.state.height} minHeight={500} />
    </div>
  );
}




```

**Comment by simonguo** [comment]
如果还有什么问题可以进群讨论
![](https://user-images.githubusercontent.com/1203827/51027866-eae68b80-15cc-11e9-8cab-a0bbe14ea516.jpeg)
