### ISSUE TITLE
console.log in production while using async Checkpicker

### ISSUE THREAD

**Issue by JuanCaCode** [rsuite/rsuite#3613]
### What version of rsuite are you using?

5.53.0

### What version of React are you using?

17.0.0

### What browser are you using?

Chrome

### Describe the Bug

While using the checkpicker component in async mode. it generates multiples consoles.log 

and it is getting delays

![image](https://github.com/rsuite/rsuite/assets/118025146/c64dfd0f-b1f5-4c73-a346-14c1b396b3bc)

### To Reproduce

using Checkpicker in asyncmode, even in your components guide it's happening

**Comment by simonguo** [comment]
Fixed in v5.53.2
