### ISSUE TITLE
Latest documentation doesn't include npm commands to install

### ISSUE THREAD

**Issue by gabereiser** [rsuite/rsuite#3619]
### What version of rsuite are you using?

5.53.1

### What version of React are you using?

18.2

### What version of TypeScript are you using (if any)?

5.2.2

### What browser are you using?

Chrome

### Describe the Bug

https://rsuitejs.com/guide/usage/
Is missing the npm commands to install. Minor, but important as you wouldn't want someone installing a phishing package.

### Expected Behavior

The npm commands show the correct package(s) to install.

### To Reproduce

https://rsuitejs.com/guide/usage/
Visit the page and look for yourself.

**Comment by simonguo** [comment]
Fixed in https://github.com/rsuite/rsuite/pull/3620
