### ISSUE TITLE
Textarea not working properly in Form with validation

### ISSUE THREAD

**Issue by andry-tino** [rsuite/rsuite#3621]
### What version of rsuite are you using?

5.48.0

### What version of React are you using?

18.2.0

### What browser are you using?

Edge, Chrome

### Describe the Bug

I am using [React Suite](https://rsuitejs.com/) to build a page with a text area in it. I am using the [Form Validation](https://rsuitejs.com/components/form-validation/) feature in the library and I have to use a text-area.

Following the [examples on custom control validation](https://rsuitejs.com/components/form-validation/#custom-form-control) and the [examples on how to create a text area control](https://rsuitejs.com/components/input/#textarea), I built the following:

```
import React from "react";
import ReactDOM from "react-dom";
import { Input, Form, Schema } from "rsuite";

const App = () => {
  const [formValue, setFormValue] = React.useState({ desc: "" });

  const model = Schema.Model({
    desc: Schema.Types.StringType().isRequired("required"),
  });

  const TextArea = React.forwardRef((props, ref) => (
    <Input {...props} as="textarea" ref={ref} />
  ));

  const formRef = React.useRef();

  return (
    <>
      <Form
        model={model}
        formValue={formValue}
        onChange={setFormValue}
        ref={formRef}
      >
        <Input as="textarea" rows={3} placeholder="Textarea1" />
        <Form.Control
          name="desc"
          placeholder="Form textarea"
          accepter={TextArea}
        />
      </Form>
    </>
  );
};

ReactDOM.render(<App />, document.getElementById("root"));
```

### The problem
However, when I run it, all renders fine, but the text box using the `Form.Control` has a weird behavior on input, where only one char at a time can be added. The first text area has a normal behavior.

### Expected Behavior

When I write in the text area, the focus should not drop out of the control each time I enter a character, making the typing experience impossible.

### To Reproduce

There is a [CodeBox available for reproing this](https://codesandbox.io/p/sandbox/festive-snowflake-9c8r29?file=%2Findex.js).

**Comment by simonguo** [comment]
Hi @andry-tino ,  `React.forwardRef` is used to create a component, but you declare it inside the App, causing the App to recreate a new component every time it is rendered.

You should declare TextArea outside your app.

```tsx
import React, { useState } from "react";
import ReactDOM from "react-dom";
import { Input, Form, Schema } from "rsuite";

const TextArea = React.forwardRef((props, ref) => (
  <Input {...props} as="textarea" ref={ref} />
));

const model = Schema.Model({
  desc: Schema.Types.StringType().isRequired("required"),
});

const App = () => {
  const [formValue, setFormValue] = useState({ desc: "" });

  return (
    <Form model={model} formValue={formValue} onChange={setFormValue}>
      <Input as="textarea" rows={3} placeholder="Textarea1" />
      <Form.Control
        name="desc"
        placeholder="Form textarea"
        accepter={TextArea}
      />
    </Form>
  );
};

ReactDOM.render(<App />, document.getElementById("root"));
```

**Comment by andry-tino** [comment]
Yes, I am an idiot :D Thank you
