### ISSUE TITLE
[TreePicker] - height property seems to be ignored even with virtualized set

### ISSUE THREAD

**Issue by AdrienFromToulouse** [rsuite/rsuite#3623]
### What version of rsuite are you using?

5.53.2

### What version of React are you using?

18.2.0

### What version of TypeScript are you using (if any)?

5.3.3

### What browser are you using?

Chrome

### Describe the Bug

Hi  @superman66 ,

I might do something wrong I guess, but I think the height of the menu is not affected by the height property

[![Edit angry-bush-2whhpl](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/polished-brook-8xzrqz?file=%2Findex.js)

Cheers,

### Expected Behavior

The menu should follow the height set in prop when virtualized is true.

### To Reproduce

[![Edit angry-bush-2whhpl](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/polished-brook-8xzrqz?file=%2Findex.js)

**Comment by superman66** [comment]
This should be a bug, let me confirm it briefly

**Comment by AdrienFromToulouse** [comment]
> This should be a bug, let me confirm it briefly

Thank you very much for checking on it 🙏

**Comment by AdrienFromToulouse** [comment]
Hi @superman66 did you have a chance to have a look at it?
Thanks for your time.

Cheers,

**Comment by simonguo** [comment]
Fixed in [v5.61.0](https://github.com/rsuite/rsuite/releases/tag/v5.61.0).  Use `treeHeight` instead of `height`.
