### ISSUE TITLE
Uploader children component

### ISSUE THREAD

**Issue by andersonbruno** [rsuite/rsuite#3624]
### What version of rsuite are you using?

5.53.0

### What version of React are you using?

18.2.0

### What version of TypeScript are you using (if any)?

4.9.3

### What browser are you using?

chrome

### Describe the Bug

Uploader children not rendering if they are coming from a different file.

The example provided by the doc has the children added like the following:

   <Uploader action="//jsonplaceholder.typicode.com/posts/" draggable>
      <div style={{ height: 200, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <span>Click or Drag files to this area to upload</span>
      </div>
    </Uploader>
    
    
    If you create a component with  the content from above
  ```
  const CustomComponent = ()=>  (<div style={{ height: 200, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <span>Click or Drag files to this area to upload</span>
      </div> )
      
```
```
      
   <Uploader action="//jsonplaceholder.typicode.com/posts/" draggable>
      <CustomComponent />
    </Uploader>
    
```
    It does not work anymore, the click event does not work and the classes from rsuite are not applied.

### Expected Behavior

It should trigger the upload even if the the children is coming from the components prop.

### To Reproduce

[codesandbox example](https://codesandbox.io/p/sandbox/crimson-tree-vbksrt?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clslzshsr00063b6hs5zmtxzw%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clslzshsr00023b6huo624at3%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clslzshsr00033b6hbiy8s7ur%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clslzshsr00053b6hmm2gp0b2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clslzshsr00023b6huo624at3%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clslzshsr00013b6haxybjo9z%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clslzshsr00023b6huo624at3%2522%252C%2522activeTabId%2522%253A%2522clslzshsr00013b6haxybjo9z%2522%257D%252C%2522clslzshsr00053b6hmm2gp0b2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clslzshsr00043b6hlzs672rq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clslzshsr00053b6hmm2gp0b2%2522%252C%2522activeTabId%2522%253A%2522clslzshsr00043b6hlzs672rq%2522%257D%252C%2522clslzshsr00033b6hbiy8s7ur%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clslzshsr00033b6hbiy8s7ur%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by simonguo** [comment]
Hi @andersonbruno, you should pass child component props to the element.

```tsx
const styles = {
  height: 200,
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
};

const CustomComponent = React.forwardRef((props, ref) => {
  return (
    <div {...props} ref={ref} style={styles}>
      <span>Click or Drag files to this area to upload</span>
    </div>
  );
});

const App = () => {
  return (
    <Uploader action="//jsonplaceholder.typicode.com/posts/" draggable>
      <CustomComponent />
    </Uploader>
  );
};
```

**Comment by andersonbruno** [comment]
Thank you! It worked now.

**Comment by andersonbruno** [comment]
Thank you! It worked now.
