### ISSUE TITLE
Pagination dropdown not close automatically when is wrapped in children component

### ISSUE THREAD

**Issue by jeandiego** [rsuite/rsuite#3629]
### What version of rsuite are you using?

5.53.0

### What version of React are you using?

18.2.0

### What version of TypeScript are you using (if any)?

4.9.3

### What browser are you using?

Chrome, Brave

### Describe the Bug

When the component `<Pagination>` is wrapped in a children component with an additional layer element, the dropdown option keep floating on the screen. Similar to the behavior reported on #3562 .

When a Page is selected, the options keep floating on the screen:

[BUG](https://github.com/rsuite/rsuite/assets/60490701/fc1d4bc6-fd99-4ce2-bf90-c5c91e03bd9b)

### Expected Behavior

Expected when I select a page, the options hide automatically. 

### To Reproduce

```tsx
const ListagemColaboradores = ({ activeFilters, setActiveFilters }: IListagemColaboradoresProps) => {
    const { data } = useDocsTrabalhistasListagemColaboradores(activeFilters)
    const onChangePage = (currentPage: number) => setActiveFilters((prev) => ({ ...prev, currentPage }))
    const onChangeLimit = (currentLimit: number) => {
      setActiveFilters((prev) => ({ ...prev, currentLimit, currentPage: 1 }))
    }

    return (
      <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
        {data?.dados.map((colaborador) => (
          <Cards key={colaborador.id} {...colaborador} />
        ))}
        <Pagination
          total={activeFilters.total}
          limit={activeFilters.currentLimit}
          layout={['limit', '|', 'pager']}
          limitOptions={[10, 20, 30, 50]}
          onChangeLimit={onChangeLimit}
          activePage={activeFilters.currentPage}
          onChangePage={onChangePage}
        />
      </div>
    )
  },
}

const Page = () => {
const [activeFilters, setActiveFilters] = useState({
  currentPage: 1,
  currentLimit: 10,
  total: 100
})

return (<div>
 <Suspense fallback={<ListaColaboradoresPlaceholder />}>
   <ListagemColaboradores activeFilters={activeFilters} setActiveFilters={setActiveFilters} />
 </Suspense>
// if pagination is inserted here, works.
</div>
)}
```

**Comment by simonguo** [comment]
Hi @jeandiego, please fork the following example to reproduce the problem you encountered.

https://stackblitz.com/edit/react-yx9qg2

**Comment by andersonbruno** [comment]
I have had the same problem! The workaround here was to add a force update state and useEffect so that I could manage the paginator and be able to close it.

**Comment by jeansantodb1** [comment]
I've installed this package today and it appears fixed the problem. However I could notice that if I pass the `classPrefix="pagination"` property on `<Pagination />` in this commit (d8a83d2b), the options doesn't open. It's a problem with this commit (d8a83d2b)?

**Comment by simonguo** [comment]
> I've installed this package today and it appears fixed the problem. However I could notice that if I pass the `classPrefix="pagination"` property on `<Pagination />` in this commit ([d8a83d2](https://github.com/rsuite/rsuite/commit/d8a83d2bb98207ef7958d186a878ed2c9dcd0fe4)), the options doesn't open. It's a problem with this commit ([d8a83d2](https://github.com/rsuite/rsuite/commit/d8a83d2bb98207ef7958d186a878ed2c9dcd0fe4))?

This issue is not related to this PR. The default value of `classPrefix` is 'pagination-group'.

**Comment by jeansantodb1** [comment]
Perfect! Waiting the official release(d8a83d2b) to confirm the fix. Thank you @simonguo for your attention.

**Comment by jeandiego** [comment]
I can confirm this issue was fixed. Updated to `"rsuite": "^5.55.1"` and the expected behavior is working.
