### ISSUE TITLE
TagPicker throw an error after clear selected values and re-open the menu

### ISSUE THREAD

**Issue by 3li7u** [rsuite/rsuite#3651]
### What version of rsuite are you using?

5.53.0

### What version of React are you using?

18

### What version of TypeScript are you using (if any)?

5

### What browser are you using?

Chrome

### Describe the Bug

TagPicker throw an error says: "Uncaught TypeError: activeItemValues.some is not a function" after clear selected values and re-open the menu

**Comment by simonguo** [comment]
Hi @3li7u, Can you create an example using CodeSandbox or stackblitz to reproduce the issue?

**Comment by 3li7u** [comment]
While creating the example and testing the issue, I found the problem that led to the described error. it's not related to "rsuite" itself but to the "formik" useFeild hook that controls the TagPicker.

**Comment by 3li7u** [comment]
So I'm going to close this issue since it's solved
