### ISSUE TITLE
shouldDisableHour is not working properly when using the showMeridian prop.

### ISSUE THREAD

**Issue by Nitesh000** [rsuite/rsuite#3656]
### What version of rsuite are you using?

5.54.0

### What version of React are you using?

18.2.0

### What version of TypeScript are you using (if any)?

-

### What browser are you using?

Chrome, Firefox

### Describe the Bug

Using the <Datepicker /> component for time input. Also using the showMeridian prop. When want to disable hour inputs between 9 pm to 9 am. It wasn't working out. The AM and PM state is still the same.

### Expected Behavior

The expected behavior is to work fine and should be work with both AM and PM state.

### To Reproduce

Steps:
- use a DatePicker component.
- add props showMeridian and put format of "hh:mm aa"
- add a prop `shouldDisableHour={(hour) => hour < 9 || hour > 19}` 
- The state of AM and PM is staying same (which should not)

**Comment by simonguo** [comment]
Hi @Nitesh000, you can temporarily use `editable={false}` to only allow the DatePicker to update the time by selection.
```tsx
<DatePicker showMeridian format="HH:mm aa" editable={false} />
```

**Comment by Nitesh000** [comment]
HI @simonguo Thanks for your response,
But I think, I wasn't able to phrase it correctly.

I am having difficulty with disabling the hours, like disabling before **9AM** and disabling after **9PM**. I tried to do that with this line of code.
```js
<DatePicker showMeridian format="HH:mm aa" shouldDisableHour={(hour) => hour < 9 || hour > 19}
```

But if the showMeridian prop is enabled then it allows the time between 9AM to 11:59AM and 9PM to 11:59PM. What I expected and wanted to allow time between 9AM to 11:59AM and 12:00PM to 8:59PM.

It works perfectly for the 24hrs format, it allows time between 9 to 19, I am just having difficulty with the 12hrs formatting.

**Comment by simonguo** [comment]
> But if the showMeridian prop is enabled then it allows the time between 9AM to 11:59AM and 9PM to 11:59PM. What I expected and wanted to allow time between 9AM to 11:59AM and 12:00PM to 8:59PM.

That can be achieved through the second parameter of `shouldDisableHour`, as follows:
```tsx
<DatePicker
  format="HH:mm aa"
  showMeridian
  shouldDisableHour={(hour, date) => {
    const h = date.getHours();
    const isPM = h >= 12;

    return isPM ? hour > 7 : hour < 9;
  }}
/>
```

**Comment by Nitesh000** [comment]
Thanks for your help man.


> > But if the showMeridian prop is enabled then it allows the time between 9AM to 11:59AM and 9PM to 11:59PM. What I expected and wanted to allow time between 9AM to 11:59AM and 12:00PM to 8:59PM.
> 
> That can be achieved through the second parameter of `shouldDisableHour`, as follows:
> 
> ```tsx
> <DatePicker
>   format="HH:mm aa"
>   showMeridian
>   shouldDisableHour={(hour, date) => {
>     const h = date.getHours();
>     const isPM = h >= 12;
> 
>     return isPM ? hour > 7 : hour < 9;
>   }}
> />
> ```

Thanks man, rater than the GitHub issue this was a skill issue.
