### ISSUE TITLE
picker inside drawer crashes browser with error 5

### ISSUE THREAD

**Issue by nickcom** [rsuite/rsuite#3662]
### What browser are you using?

Chrome

### Describe the Bug

using CheckPicker or SelectPicker inside a Drawer causes the browser to crash onSelect:

```
export default function Example() {
  return (
    <Drawer open={true} size="sm" placement="botton">
      <CheckPicker
        data={[
          {
            label: "option1",
            value: "1",
          },
          {
            label: "option2",
            value: "2",
          },
        ]}
      />
    </Drawer>
  );
}
```

### Expected Behavior

the browser to not crash, or same behavior as noted if picker is not placed inside a Drawer

### To Reproduce

Place a CheckPicker inside a Drawer and select from the list

https://stackblitz.com/edit/react-yzrgju?file=index.js

**Comment by simonguo** [comment]
Hi @nickcom  I see no other errors from your example except a usage warning for `ReactDOM.render`.

<img width="1247" alt="image" src="https://github.com/rsuite/rsuite/assets/1203827/5aaff6d7-fbb0-439a-a429-6d85b954b172">

**Comment by nickcom** [comment]
Ahh, since it worked for you I thought to update Chrome - running the latest version ( 122.0.6261.112 ) it indeed works. 

I was running chrome Version 122.0.6261.94 (Feb 27) and it will cause the browser to crash immediately. 

I will close this issue since it is no longer a bug for me.
