### ISSUE TITLE
Popover位置以及小箭头位置计算错误

### ISSUE THREAD

**Issue by 1977474741** [rsuite/rsuite#3667]
### What version of rsuite are you using?

4.0.0

### What version of React are you using?

18.0

### What browser are you using?

chrome最新版

### Describe the Bug

当Popover组件的container属性设置为他的父元素时，Popover弹窗箭头以及位置错误，而且不会跟随鼠标，下面有复现链接

### Expected Behavior

Popover位置以及小箭头位置，根据鼠标位置正确计算

### To Reproduce

https://codesandbox.io/p/sandbox/naughty-aj-jwpwhs?file=%2Findex.js%3A15%2C31

**Comment by simonguo** [comment]
你给的Codesandbox 示例是一个非公开的链接

![image](https://github.com/rsuite/rsuite/assets/1203827/ecd9e55b-b2c1-4142-96ac-8dc0bd896ae3)

**Comment by 1977474741** [comment]
设置为公开了，你再看一下

**Comment by simonguo** [comment]
@1977474741  你 Popover 中的内容太多，撑宽了，可以给Popover设置固定宽度，或者控制一下内容文本换行。

```tsx
 <Popover style={{ width: 300 }}>
```
