### ISSUE TITLE
onOpen,onClose with the open prop is not working

### ISSUE THREAD

**Issue by IceCubexZ** [rsuite/rsuite#3684]
### What version of rsuite are you using?

5.37.0

### What version of React are you using?

18.0.24

### What version of TypeScript are you using (if any)?

5.1.6

### What browser are you using?

Chrome

### Describe the Bug

![image](https://github.com/rsuite/rsuite/assets/33515941/ca839330-f200-4434-9832-fd3a1aabf3f2)
![image](https://github.com/rsuite/rsuite/assets/33515941/8de7b428-0817-40cc-8bd0-4c16f806a77b)

When using it like this and clicking on the input it wont open the dialog

### Expected Behavior

It should open the dialog

### To Reproduce

![image](https://github.com/rsuite/rsuite/assets/33515941/23f01482-925f-49dd-93e5-17539365506f)
![image](https://github.com/rsuite/rsuite/assets/33515941/e46f935b-0ad3-4928-92d2-bfe658b0f242)

Use Datepicker with onOpen and onClose . Pass open variable to the datePicker and try to open the datepicker .

**Comment by simonguo** [comment]
Fixed in https://github.com/rsuite/rsuite/pull/3228
