### ISSUE TITLE
In the RangeSlider, the onChangeCommitted event does not return the correct target

### ISSUE THREAD

**Issue by niug** [rsuite/rsuite#3687]
### What version of rsuite are you using?

5.55.0

### What version of React are you using?

18.2.0

### What browser are you using?

Chrome

### Describe the Bug

When I move one of the handlers of the RangeSlider, if I release the mouse button outside the slider bar in onChangeCommitted the target of the event has the value of the element where I have positioned the mouse. If I release the mouse button inside the slider, the event has the value of the handler that has generated it.

### Expected Behavior

When releasing the button to move one of the rangeslider handlers, the onChangeCommited method should return as event target the html element of the handler that generated the event.

### To Reproduce

In the moving handler if I release the mouse button on the div (id="previous-div") of the rangeSlider console.log console.log returns (bug): 
`~ onChangeCommited ~ event: <span>​Previous​</span>​`

In the moving handler, if I release the mouse button on the rangeSlider bar, console.log console.log returns (correct): 
```
~ onChangeCommited ~ event: <div tabindex=​"0" class=​"rs-slider-handle" data-range=​"0,64" data-key=​"end" data-testid=​"slider-handle" style=​"bottom:​ 64%;​">​…​</div>​
```

```
import React from 'react';
import { RangeSlider } from 'rsuite';

const App = () => {
   const onChangeCommited = (value, event) => {
	console.log("🚀 ~ onChangeCommited ~ event:", event.target)
    }

    return (
        <div id="root" style={{height: 200, width: 200, marginLeft: 200, marginTop: 50}}>
            <div id="previous-div">
                <span>Previous</span>
            </div>
            <RangeSlider onChangeCommitted={onChangeCommited} vertical></RangeSlider>
            <div id="after-div">
                <span>After</span>
            </div>
        </div>
    );
};

ReactDOM.render(<App />, document.getElementById('root'));
```
Knowing the target that generated the event, I can know which of the two handlers has been modified.

**Comment by simonguo** [comment]
Mouse events are bound to the [`document.body` element](https://github.com/rsuite/rsuite/blob/main/src/Slider/useDrag.ts#L56
) , so you cannot get the handle element through `event.target`.

**Comment by niug** [comment]
Thanks for your answer @simonguo, and how can I know which of the two handlers has triggered the onChangeCommitted event in the RangeSlider?

**Comment by simonguo** [comment]
> How can I know which of the two handlers has triggered the onChangeCommitted event in the RangeSlider?

You can listen to the value change to determine which handler triggered the event. Also, I want to know what your specific use case is? So I can better help you.

**Comment by niug** [comment]
I have two InputNumber components and a RangSlider component (as in example 2 of the documentation: https://rsuitejs.com/components/slider/#show-value-controlled) that are constantly updated (3 times per second) through the min/max values that arrive via redux useSelector connected to websocket middleware. When the values arrive by useSelector, if I use the hook useState the component is rerendered causing an infinite loop, so I update the values through the hook useRef, besides I want to be able to modify some of the values of the min/max, either with the InputNumber or RangSlider, and that the component is not rerendered when an update of values arrives waiting to finish the edition to continue updating values. Therefore the control of the update is done from the parent component, and by means of ref I update the InputNumbers and RangeSlider components. Everything works ok, except when I modify the RangSlider that I can't detect which value has been modified if the min or max. I had the intention of using the event received in the onChangeCommitted, but as you indicate me I can't obtain the target of the specific handle (min or max).

**Comment by simonguo** [comment]
I can't fully understand the reason for the infinite loop caused by your use of useState, but I think there should be a problem between controlling the value and encapsulating the component. You use `useRef`, can you determine whether the minimum value or the maximum value is updated by listening to the change of the value?

```tsx
const App = () => {
  const valueRef = useRef([10, 50]);
  return (
    <RangeSlider
      defaultValue={[10, 50]}
      onChangeCommitted={([start, end]) => {
        if (start !== valueRef.current[0]) {
          console.log('Min value is changed to:', start);
        }
        if (end !== valueRef.current[1]) {
          console.log('Max value is changed to:', end);
        }

        valueRef.current = [start, end];
      }}
    />
  );
};
```

**Comment by niug** [comment]
Thank you very much @simonguo for your comments, finally I have been able to solve it by creating the following component:

```
import React, { useEffect, useRef, useState } from 'react'
import { useSelector } from 'react-redux';
import { InputNumber, RangeSlider } from 'rsuite'
import { selectSliderValue } from './redux/slidersSlice';

const CustomSlider = ({id, min, max, onChangeMin = () => {}, onChangeMax = () => {}}) => {
    const [valueState, setValueState] = useState([10, 50]);
    const [oldValue, setOldValue] = useState(valueState);
    const isEditingRef = useRef(false);

    const sliderValue = useSelector((state) => selectSliderValue(state, id))

    const onBlur = (isMax) => {
        isEditingRef.current = false
        if (isMax) {
            onChangeMax(valueState);
        } else {
            onChangeMin(valueState);
        }
    }

    const onChangeCommittedSlider = (_value) => {
        if (_value[0] !== oldValue[0]) {
            onChangeMax(valueState);
        } else {
            onChangeMax(valueState);
        }
        isEditingRef.current = false;
    }

    const onChangeInput = (_value, isMax) => {
        let newValue = [];
        if (isMax) {
            newValue = [valueState[0], Number(_value)];
        } else {
            newValue = [Number(_value), valueState[1]];
        }
        setValueState(newValue);
        setOldValue(newValue);
    }

    const onChangeSlider = (_value) => {
        isEditingRef.current = true;
        setValueState(_value)
    }

    useEffect(() => {
        if (!sliderValue) return;
        if (!isEditingRef.current) {
            setValueState(sliderValue.value);
            setOldValue(sliderValue.value);
        }
    }, [sliderValue])

    return (
        <>
            <InputNumber 
                value={valueState[1]} 
                onFocus={() => isEditingRef.current = true}
                onBlur={() => onBlur(true)}
                onChange={(_value) => onChangeInput(_value, true)} 
            />
            <RangeSlider 
                min={min} 
                max={max}
                style={{justifyContent: "center", height: 200}}
                value={valueState}
                onChange={onChangeSlider}
                onChangeCommitted={onChangeCommittedSlider}
                vertical />
            <InputNumber 
                onFocus={() => isEditingRef.current = true}
                onBlur={() => onBlur(false)}
                value={valueState[0]} 
                onChange={(_value) => onChangeInput(_value, false)}
            />
        </>
    )
}

export default CustomSlider
```

This component is updated by a Redux Slice about three times per second, and if the user selects an InputNumber or moves the Slider he can modify its value correctly without having problems with the rerendering.
