### ISSUE TITLE
Dropdown.Menu icon={<Icon icon="dashboard"/>}

### ISSUE THREAD

**Issue by fannaoshaoxiang** [rsuite/rsuite#369]
Dropdown.Menu icon={<Icon icon="dashboard"/>}

我在加入 icon 的时候发现 会有布局问题

**Comment by simonguo** [comment]
什么问题 ?

**Comment by fannaoshaoxiang** [comment]
![5.png](https://uploads.codesandbox.io/uploads/user/54d06f4d-17b5-465c-83df-cb94c7484cde/DVi5-2019-01-17_15-47-19.png)

**Comment by simonguo** [comment]
你的描述，让我很难判断到底是哪里影响存在的问题。

示例: https://rsuitejs.com/components/sidenav
参考: https://github.com/rsuite/rsuite.github.io/blob/master/src/components/sidenav/en/basic.md

**Comment by fannaoshaoxiang** [comment]
@simonguo 
相关案例
https://codesandbox.io/embed/nj4z157q4
