### ISSUE TITLE
Table表格希望加入  表尾

### ISSUE THREAD

**Issue by fanlide** [rsuite/rsuite#37]
表尾有时候需要合计，挺实用的。往加入，谢谢

**Comment by simonguo** [comment]
@fanlide  这是一个很好的建议，我们现在业务中也会遇到表格汇总功能，不过我的设计风格不是放在表尾，而是放在表头, 放在 `HeaderCell` 里面。

如果你急需使用这个功能，可以在自定义 `HeaderCell` 自定义，同时设置 `headerHeight`, 放入统计的汇总数据。 通过简单的 css 控制显示。

如果你不是很紧急，那耐心等待一下，我们会在最近的版本示例中加入这个功能，并通知你。

**Comment by fanlide** [comment]
谢谢，等你们下一个版本

**Comment by fanlide** [comment]
@simonguo 对了，多级嵌套表头是否会加入？虽然用的不多，但有时也有这个需求

**Comment by simonguo** [comment]
Table 汇总数据, 示例：https://rsuitejs.com/en/components/table#Advanced

![image](https://user-images.githubusercontent.com/1203827/40299165-fc53b35c-5d17-11e8-8fd4-4f8e15efc456.png)

**Comment by fanlide** [comment]
@simonguo 谢谢
