### ISSUE TITLE
Dropdown.Menu 菜单中快速点击后有无法显示文字的情况

### ISSUE THREAD

**Issue by fannaoshaoxiang** [rsuite/rsuite#370]
试了一下官方案例的情况也有类似的问题
![4.png](https://uploads.codesandbox.io/uploads/user/54d06f4d-17b5-465c-83df-cb94c7484cde/jpho-2019-01-20_16-43-50.gif)

**Comment by simonguo** [comment]
cc @hiyangguo  跟踪一下问题。
