### ISSUE TITLE
Bug for search input in SelectPicker while using a Drawer without Backdrop

### ISSUE THREAD

**Issue by JuanCaCode** [rsuite/rsuite#3710]
### What version of rsuite are you using?

5.57.0

### What version of React are you using?

18.0.0

### What browser are you using?

brave, chrome

### Describe the Bug

I'm working with the ui, that needs a drawer active without backdrop to be available to interact with the right part of the app like so:

![image](https://github.com/rsuite/rsuite/assets/118025146/45b467f8-dcda-430b-8797-b84ecbc2f2ac)

Everything works good, but the searchable from SelectPicker or CheckPicker doesn't work. I can't type anything in the input.

I realize it is because the "rs-drawer-wrapper" div. because when I delete it, the searchable works again. but when I delete it, it also deletes the drawer.

### Expected Behavior

The expected behavior is to use the searchable input while the drawer is actived and ofcourse without backdrop.

### To Reproduce

# I left you there a sandbox to reproduce

![image](https://github.com/rsuite/rsuite/assets/118025146/ddc51eaa-b12c-4b63-859b-441276dd5bd6)

[LINK SANDBOX](https://codesandbox.io/p/sandbox/weathered-sunset-ztyzlh?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clua0j9ca0006356deg09trnz%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clua0j9c90002356ddko9rapj%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clua0j9c90003356dhobjcufp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clua0j9c90005356delzoek5e%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B41.539743663428936%252C58.460256336571064%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clua0j9c90002356ddko9rapj%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clua0j9c80001356d473y0lqu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A34%252C%2522startColumn%2522%253A22%252C%2522endLineNumber%2522%253A34%252C%2522endColumn%2522%253A22%257D%255D%257D%255D%252C%2522id%2522%253A%2522clua0j9c90002356ddko9rapj%2522%252C%2522activeTabId%2522%253A%2522clua0j9c80001356d473y0lqu%2522%257D%252C%2522clua0j9c90005356delzoek5e%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clua0j9c90004356d6jy6ot2p%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clua0j9c90005356delzoek5e%2522%252C%2522activeTabId%2522%253A%2522clua0j9c90004356d6jy6ot2p%2522%257D%252C%2522clua0j9c90003356dhobjcufp%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clua0j9c90003356dhobjcufp%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by simonguo** [comment]
Hi @JuanCaCode,  The reason for this issue is that the Drawer will focus forcibly after opening. You can close it by setting `enforceFocus={false}` on the Drawer. 

```tsx
<Drawer backdrop={false} enforceFocus={false} >
```

I will fix it in the next version, if the backdrop value of the Drawer is false, it will not focus forcibly by default.

**Comment by JuanCaCode** [comment]
Thank you so much. it worked as expected
