### ISSUE TITLE
Checkboxes don't working in Firefox

### ISSUE THREAD

**Issue by Rrhapsod** [rsuite/rsuite#3724]
### What version of rsuite are you using?

5.59.0

### What version of React are you using?

18

### What browser are you using?

Firefox

### Describe the Bug

On docs, the MultiCascadeTree, for exemple, the checkboxes don't work on Firefox, just in Chrome.

https://rsuitejs.com/components/multi-cascade-tree/

### Expected Behavior

The checks isn't checking on Firefox, they are working like a charm on Chrome.

### To Reproduce

Just access the docs (https://rsuitejs.com/components/multi-cascade-tree/) on Firefox browser and try to check any checkbox.

**Comment by simonguo** [comment]
Hi @Rrhapsod , the bug has been fixed in https://github.com/rsuite/rsuite/pull/3728 and will be released in the next version. (April 12th.) 

You can try to install the following temporary version:

```bash
npm i https://pkg.csb.dev/rsuite/rsuite/commit/e4a0bec3/rsuite
```
> https://rsuite-nextjs-git-fix-checkbox-size-rsuite.vercel.app/components/multi-cascade-tree/
