### ISSUE TITLE
Wrong position when Sidenav nav.menu expanded

### ISSUE THREAD

**Issue by morrislaw715** [rsuite/rsuite#3731]
### What version of rsuite are you using?

5.59.0

### What version of React are you using?

18.2

### What browser are you using?

Firefox

### Describe the Bug

I found I have this issue after updated to 5.59.0.
I found same issue in your document page also.
![image](https://github.com/rsuite/rsuite/assets/85062611/6b92d6e9-aa88-44ee-86a7-89732d23fe9c)

**Comment by simonguo** [comment]
Fixed in rsuite@5.59.1
