### ISSUE TITLE
How can I change the last hour for a DateRangeInput 

### ISSUE THREAD

**Issue by JuanCaCode** [rsuite/rsuite#3739]
### What version of rsuite are you using?

5.53.0

### What version of React are you using?

18.0.0

### Describe the Bug

Hello, hope you all are good. 

In this case I'm unsing a small DateRangePicker, with only one calendar.  The thing is that I can't choose an end hour for the dates range. As you can see in the screenshot, it only shows the start hour but not the end one. 

![image](https://github.com/rsuite/rsuite/assets/118025146/f671e304-702d-427b-b8db-29a3408dc0d3)

### To Reproduce

[CODESANDBOX](https://codesandbox.io/p/sandbox/white-water-wt6426?file=%2Findex.js%3A13%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cluwume8v0006356dgueon2s0%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cluwume8v0002356dy5fiv4cf%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cluwume8v0003356djjqxp52o%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cluwume8v0005356drlkaphao%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cluwume8v0002356dy5fiv4cf%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluwume8u0001356dh6hztsk8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A13%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A13%252C%2522endColumn%2522%253A1%257D%255D%257D%255D%252C%2522id%2522%253A%2522cluwume8v0002356dy5fiv4cf%2522%252C%2522activeTabId%2522%253A%2522cluwume8u0001356dh6hztsk8%2522%257D%252C%2522cluwume8v0005356drlkaphao%2522%253A%257B%2522id%2522%253A%2522cluwume8v0005356drlkaphao%2522%252C%2522activeTabId%2522%253A%2522cluwuq7j5001e356d6ty0gbck%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cluwuq7j5001e356d6ty0gbck%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cluwume8v0003356djjqxp52o%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cluwume8v0003356djjqxp52o%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by simonguo** [comment]
Fixed in https://github.com/rsuite/rsuite/pull/3743.
