### ISSUE TITLE
<Tree> data属性 setstate 不改变

### ISSUE THREAD

**Issue by fannaoshaoxiang** [rsuite/rsuite#375]
https://codesandbox.io/embed/nj4z157q4

@superman66

**Comment by superman66** [comment]
@fannaoshaoxiang 建议根据 ISSUE_TEMPLATE.md 来描述问题。这样我也方便查看是否为bug。
如果能提供在线demo的话，那就更棒了

**Comment by fannaoshaoxiang** [comment]
@superman66  我上传了一个demo 看一下是不是我的代码问题

**Comment by superman66** [comment]
@fannaoshaoxiang 
![image](https://user-images.githubusercontent.com/12592949/51528243-2e64b380-1e71-11e9-9066-5bea8232cf06.png)
写错了。正确写法是：
```
this.setState({})
```
