### ISSUE TITLE
SelectPicker doesn't work properly when it's inside a Drawer with the backdrop={false}

### ISSUE THREAD

**Issue by JuanCaCode** [rsuite/rsuite#3757]
### What version of rsuite are you using?

5.59.2

### What version of React are you using?

18.0.0

### What browser are you using?

Chrome

### Describe the Bug

SelectPicker doesn't work properly when it's inside a Drawer with the backdrop={false}
I'm selecting the item but, it doesn't even hover .
![image](https://github.com/rsuite/rsuite/assets/118025146/24e4206a-6f95-4225-939c-5687d25ea3a3)

I can't select any option from the SelectPicker list.

### Expected Behavior

while using the Drawer backdrop={false}, the SelectPicker inside it, can work.

![image](https://github.com/rsuite/rsuite/assets/118025146/e6ba0c8e-ca0f-4942-90b0-88fd96fd7858)

### To Reproduce

sandbox https://codesandbox.io/p/sandbox/elegant-cdn-mt3mrt?file=%2Findex.js%3A10%2C16

**Comment by JuanCaCode** [comment]
Hello, sorry, is this fixed?

**Comment by simonguo** [comment]
Fixed in https://github.com/rsuite/rsuite/pull/3759
