### ISSUE TITLE
DateRangePicker altered input behavior

### ISSUE THREAD

**Issue by Ville-Wennerlund** [rsuite/rsuite#3763]
### What version of rsuite are you using?

5.59.2

### What version of React are you using?

18.2.0

### What browser are you using?

Microsoft Edge

### Describe the Bug

The DateRangerPicker input is not behaving as it did previously (compared to version 5.6.6).

This is reproducible here: https://rsuitejs.com/components/date-range-picker/
1. click once on "04"
2. 
![image](https://github.com/rsuite/rsuite/assets/152278395/48a2f6bb-1bc9-435a-80bd-1cf5ad45afb1)
3. type "0"
4. 
![image](https://github.com/rsuite/rsuite/assets/152278395/02ae4f00-c17f-46b7-a7a5-15e3ca70708b)
5. type "2"
6. 
![image](https://github.com/rsuite/rsuite/assets/152278395/2c49eb35-4941-4c99-a902-2fe8fc4771fc)

### Expected Behavior

This is the behavior from Rsuite 5.6.6

1. double click on "04"
2.
![image](https://github.com/rsuite/rsuite/assets/152278395/320cb90a-1bf1-45b9-bf6b-ec0d005ff683)
3. type "0"
4.
![image](https://github.com/rsuite/rsuite/assets/152278395/185a26fa-c8a9-4d37-b7c1-08cec3c2e2eb)
5. type "2"
6. 
![image](https://github.com/rsuite/rsuite/assets/152278395/4ac7cc79-ed3d-4aef-9951-a5949d81df8f)

**Comment by simonguo** [comment]
Fixed in rsuite@5.60.2

**Comment by Ville-Wennerlund** [comment]
Many thanks :)
