### ISSUE TITLE
DateRangePicker: [Violation] 'keydown' handler took XXXms.

### ISSUE THREAD

**Issue by Ville-Wennerlund** [rsuite/rsuite#3764]
### What version of rsuite are you using?

5.59.2

### What version of React are you using?

The version you are running on https://rsuitejs.com/components/date-range-picker/

### What browser are you using?

Microsoft Edge

### Describe the Bug

It takes a long time to edit the year when the DateRangePicker is open.

1. 
![image](https://github.com/rsuite/rsuite/assets/152278395/0b32080a-71a9-4b35-aa27-4e5d83713169)
2. click on "2024"
3. 
![image](https://github.com/rsuite/rsuite/assets/152278395/10592b68-9cfc-443f-87c6-e6531d3b6230)
4. type "2020"
5.  the following violation will be present in the console: [Violation] 'keydown' handler took 945ms

**Comment by simonguo** [comment]
Fixed in [v5.61.0](https://github.com/rsuite/rsuite/releases/tag/v5.61.0).
