### ISSUE TITLE
Date Picker entry issues on days 01 to 03

### ISSUE THREAD

**Issue by helderrsantos** [rsuite/rsuite#3768]
### What version of rsuite are you using?

5.55.1

### What version of React are you using?

18.2.0

### What version of TypeScript are you using (if any)?

5.4.2

### What browser are you using?

Chrome

### Describe the Bug

When I type the dates and months with 01, 02 and 03 the field behaves wrong, transforming the numbers to 10, 20 and 30, starting from 04 the behavior is correct for both the dates and the months.

### Expected Behavior

What would be expected would be the behavior of these dates like the others from 04 onwards

### To Reproduce

No gif iniciei digitando 01 01 01 ocorreu esse comportamento, e com o 04 o comportamento correto
![Recording 2024-04-24 at 11 16 27](https://github.com/rsuite/rsuite/assets/106779562/2d7f76c4-0368-4110-b5a8-839fb63abe37)

**Comment by simonguo** [comment]
Fixed in rsuite@5.60.2
