### ISSUE TITLE
Time selector doesn't update in DataRangePicker 

### ISSUE THREAD

**Issue by nosheen-permiso** [rsuite/rsuite#3775]
### What version of rsuite are you using?
5.55.0

### What version of React are you using?

17.0.0

### What version of TypeScript are you using (if any)?

5.0.3

### What browser are you using?

chorme

### Describe the Bug

While trying to update date and time using code or from input, time selector does not update. It is major issue.
Reference -  https://github.com/rsuite/rsuite/discussions/3617

### Expected Behavior

Time selector should update the value

**Comment by simonguo** [comment]
Hi @nosheen-permiso. 
How to reproduce the problem you encountered?

https://github.com/rsuite/rsuite/assets/1203827/f269ba5f-ff22-4296-bd4a-73c664b7692d

**Comment by nosheen-permiso** [comment]
Hi Simon,
Try changing the date and time from input field directly. Date gets updated on the calendar but time does not.
Find the attached GIF for more reference.

From: Simon Guo ***@***.***>
Date: Tuesday, 30 April 2024 at 8:14 PM
To: rsuite/rsuite ***@***.***>
Cc: Nosheen Pathan ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL]: Re: [rsuite/rsuite] Time selector doesn't update in DataRangePicker (Issue #3775)

Hi @nosheen-permiso<https://github.com/nosheen-permiso>.
How to reproduce the problem you encountered?

https://github.com/rsuite/rsuite/assets/1203827/f269ba5f-ff22-4296-bd4a-73c664b7692d

**Comment by nosheen-permiso** [comment]
> Hi @nosheen-permiso. How to reproduce the problem you encountered?

Hi @simonguo 

Try changing the date and time from input field directly. Date gets updated on the calendar but time does not.
Find the attached GIF for more reference.

![rsuiteIssue](https://github.com/rsuite/rsuite/assets/143783473/5e3f07be-ef10-458d-ab84-e4302b092404)

**Comment by simonguo** [comment]
Fixed in rsuite@5.60.1
