### ISSUE TITLE
Modifying DaterangePicker according to document is invalid

### ISSUE THREAD

**Issue by Tian-YJ** [rsuite/rsuite#3776]
Modifying DaterangePicker according to document is invalid
1. I need to remove the blue rounded border from the input box when hovering, and set the background color of the date to black, as shown in the following figure:
![WechatIMG2626](https://github.com/rsuite/rsuite/assets/35914704/b2161232-a4fc-4814-8d67-a6bbae4241fd)
![WechatIMG2627](https://github.com/rsuite/rsuite/assets/35914704/b3cb34de-7dfc-478c-954f-0f922d97c035)

2When I click reset, the date in the input box can be cleared, and I use usestate to set the status to invalid

**Comment by simonguo** [comment]
> 1. I need to remove the blue rounded border from the input box when hovering, and set the background color of the date to black

DateRangePicker's input box depends on the style of InputGroup. If you want to modify its style, directly override it through CSS style.

> 2.When I click reset, the date in the input box can be cleared, and I use usestate to set the status to invalid

I didn't understand what you meant, could you provide a code example?

**Comment by Tian-YJ** [comment]
hi，Simon，The question2 was solved


The question1 still no method to solve&nbsp;


but the default style still can not modified&nbsp;





------------------ Original ------------------
From: Simon Guo ***@***.***&gt;
Date: Thu,May 2,2024 2:37 PM
To: rsuite/rsuite ***@***.***&gt;
Cc: Tian-YJ ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [rsuite/rsuite] Modifying DaterangePicker according to documentis invalid (Issue #3776)





   
I need to remove the blue rounded border from the input box when hovering, and set the background color of the date to black
   
DateRangePicker's input box depends on the style of InputGroup. If you want to modify its style, directly override it through CSS style.
  
2.When I click reset, the date in the input box can be cleared, and I use usestate to set the status to invalid
  
I didn't understand what you meant, could you provide a code example?

**Comment by simonguo** [comment]
> but the default style still can not modified&nbsp;

How did you modify it? Can you paste the code to see it?

**Comment by Tian-YJ** [comment]
![26351714916533_ pic](https://github.com/rsuite/rsuite/assets/35914704/32004693-bc71-4aa6-8c04-1c8abf6d258b)
![26361714916534_ pic](https://github.com/rsuite/rsuite/assets/35914704/9f637070-aa92-45d9-bcfc-eb9c11eb0f92)
![26371714916535_ pic](https://github.c
![26381714916536_ pic](https://github.com/rsuite/rsuite/assets/35914704/ed538391-1c73-4242-b031-818d30d19a76)
om/rsuite/rsuite/assets/35914704/00e4cf1c-7e69-46bf-b5af-8944ce2a29d7)

Please refer to the picture. My requirement is to remove the default blue border with rounded corners when hovering over the mouse. However, I have not been able to set the style within the line and remove the hover style within the line

**Comment by Tian-YJ** [comment]
you can add my wechat : KaylaBranch

**Comment by simonguo** [comment]
Overriding styles by writing CSS.

```css
.rs-picker-daterange .rs-input-group {
    border-radius: 0;
}
.rs-picker-daterange .rs-input-group:hover {
    border-color: #000;
}
.rs-picker-daterange .rs-input-group:focus-within {
    outline: none;
}
```

**Comment by Tian-YJ** [comment]
I tried you gave ，but still invalid





------------------ Original ------------------
From: Simon Guo ***@***.***&gt;
Date: Mon,May 6,2024 11:11 AM
To: rsuite/rsuite ***@***.***&gt;
Cc: Tian-YJ ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [rsuite/rsuite] Modifying DaterangePicker according to documentis invalid (Issue #3776)





 
Overriding styles by writing CSS.
 .rs-picker-daterange .rs-input-group {     border-radius: 0; } .rs-picker-daterange .rs-input-group:hover {     border-color: #000; } .rs-picker-daterange .rs-input-group:focus-within {     outline: none; }

**Comment by Tian-YJ** [comment]
![26401715004043_ pic](https://github.com/rsuite/rsuite/assets/35914704/544f2cd7-d9a7-47e8-97c8-1e437b644a06)
![26411715004044_ pic](https://github.com/rsuite/rsuite/assets/35914704/355263ec-16d9-4579-bad1-e765df2abbd6)


This is my setting, but it still has no effect

**Comment by simonguo** [comment]
You set the `dateRangePicker` ID and the pop-up layer of DateRangePicker are not in the same parent element, so the style will not take effect. I suggest you learn HTML, CSS, and how to debug through the browser first. 


This issue has nothing to do with rsuite, I will close this issue.

**Comment by Tian-YJ** [comment]
I am directly written in the line style, line to remove hover effect, I have tried many times, did not achieve, therefore, the unused code I cleared, so you see is my screenshot to you see, but you give the wrong writing, is still not effective, even before I have tried, are not effective, The property name you gave me I saw was debug from inside the browser, but I tried it didn't work





------------------ Original ------------------
From: Simon Guo ***@***.***&gt;
Date: Tue,May 7,2024 9:44 AM
To: rsuite/rsuite ***@***.***&gt;
Cc: Tian-YJ ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [rsuite/rsuite] Modifying DaterangePicker according to documentis invalid (Issue #3776)





 
You set the dateRangePicker ID and the pop-up layer of DateRangePicker are not in the same parent element, so the style will not take effect. I suggest you learn HTML, CSS, and how to debug through the browser first.
 
This issue has nothing to do with rsuite, I will close this issue.

**Comment by Tian-YJ** [comment]
Because I &nbsp;used the scss so that I should to write this





------------------ Original ------------------
From: Yajie Tian ***@***.***&gt;
Date: Tue,May 7,2024 1:20 PM
To: reply+AISAHUFSPDUTWRNSMY3NWZWEIVUH3EVBNHHIPAM2DQ ***@***.***&gt;, rsuite/rsuite ***@***.***&gt;
Cc: Author ***@***.***&gt;
Subject: Re: [rsuite/rsuite] Modifying DaterangePicker according to documentis invalid (Issue #3776)





I am directly written in the line style, line to remove hover effect, I have tried many times, did not achieve, therefore, the unused code I cleared, so you see is my screenshot to you see, but you give the wrong writing, is still not effective, even before I have tried, are not effective, The property name you gave me I saw was debug from inside the browser, but I tried it didn't work





------------------ Original ------------------
From: Simon Guo ***@***.***&gt;
Date: Tue,May 7,2024 9:44 AM
To: rsuite/rsuite ***@***.***&gt;
Cc: Tian-YJ ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [rsuite/rsuite] Modifying DaterangePicker according to documentis invalid (Issue #3776)





 
You set the dateRangePicker ID and the pop-up layer of DateRangePicker are not in the same parent element, so the style will not take effect. I suggest you learn HTML, CSS, and how to debug through the browser first.
 
This issue has nothing to do with rsuite, I will close this issue.

**Comment by Tian-YJ** [comment]
And because I did not write inline or css selectors, I chose to use is selectors to try, you can try, I have tried alone, has not been effective, so I want to see if zoom to try





------------------ Original ------------------
From: Simon Guo ***@***.***&gt;
Date: Tue,May 7,2024 9:44 AM
To: rsuite/rsuite ***@***.***&gt;
Cc: Tian-YJ ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [rsuite/rsuite] Modifying DaterangePicker according to documentis invalid (Issue #3776)





 
You set the dateRangePicker ID and the pop-up layer of DateRangePicker are not in the same parent element, so the style will not take effect. I suggest you learn HTML, CSS, and how to debug through the browser first.
 
This issue has nothing to do with rsuite, I will close this issue.
