### ISSUE TITLE
Icon bug. All icon is square

### ISSUE THREAD

**Issue by mmlatale** [rsuite/rsuite#3778]
### What version of rsuite are you using?

4.8.4

### What version of React are you using?

17.0.1

### What browser are you using?

all browser

### Describe the Bug

all icon from rsuite library is square
<img width="962" alt="Screenshot 2567-05-02 at 08 40 10" src="https://github.com/rsuite/rsuite/assets/34055469/edc52e4c-9458-4d1f-a029-7567c6ea48f4">

### Expected Behavior

need rsuite fix your library icon

**Comment by simonguo** [comment]
The CDN of the font file that the icon depends on is not accessible. If you are using it, please switch to the local path of the icon.
> https://github.com/rsuite/rsuite/blob/v4/docs/pages/guide/themes/en-US/index.md#how-to-configure-font-files-locally

**Comment by mmlatale** [comment]
Thank you for reply.

Now my issue is fixed.
