### ISSUE TITLE
Sidebar 组件在firefox中不能缩放

### ISSUE THREAD

**Issue by zpbc007** [rsuite/rsuite#378]
### Bug, feature request, or proposal:
bug

### What is the expected behavior?
组件在firefox中可以正常缩放

### What is the current behavior?
侧边栏组件在firefox中只能缩放到侧边栏内容的宽度。

### 原因
flex-basis属性在firefox上会根据元素child的宽度来进行计算[flexbugs](https://github.com/philipwalton/flexbugs/issues/41)

在缩小状态下可以添加min-width属性或将flex设为none

**Comment by zpbc007** [comment]
![1548299016227](https://user-images.githubusercontent.com/20379810/51651649-beb50c80-1fc7-11e9-8029-06f0fde2650d.jpg)

**Comment by hiyangguo** [comment]
@zpbc007 我认为这是一个浏览器的实现上的 bug 。处理方式有待商榷。
