### ISSUE TITLE
Cant hide format when clicking on the input - DatePicker 

### ISSUE THREAD

**Issue by IceCubexZ** [rsuite/rsuite#3795]
### What version of rsuite are you using?

5.58.0

### What version of React are you using?

18.0.24

### What version of TypeScript are you using (if any)?

5.1.6

### What browser are you using?

Chrome

### Describe the Bug

This is on version (5.37.0)
![image](https://github.com/rsuite/rsuite/assets/33515941/17e3900d-a1ae-4cbb-aa15-bdd7fcba4715)

This is on version (5.58.0)
![image](https://github.com/rsuite/rsuite/assets/33515941/c118c70c-acea-41a8-995c-54cc0ac0a37e)

Idk what changed but i want to hide the format when clicking on the input . My whole app is in hebrew and i want to keep it hebrew only . 

### Expected Behavior

I dont want to see the format on the input when clicking on it

**Comment by simonguo** [comment]
Hi @IceCubexZ .

 Are you using `renderValue` to customize rendering? I think it should be the same issue as #3794. I will try to fix it as soon as possible.

**Comment by simonguo** [comment]
Fixed in [v5.61.0](https://github.com/rsuite/rsuite/releases/tag/v5.61.0).
