### ISSUE TITLE
Error messages with the Timeline component

### ISSUE THREAD

**Issue by instituto-allamo** [rsuite/rsuite#3799]
### What version of rsuite are you using?

5.60.2

### What version of React are you using?

18.2.0

### What version of TypeScript are you using (if any)?

5.3.3

### What browser are you using?

Chrome

### Describe the Bug

Having bugs with Timeline component and React.
I have just copy paste the example on docs, changed nothing.

![error1](https://github.com/rsuite/rsuite/assets/151032429/c220ac4e-04d8-4bf7-8680-2fd42d52da70)

![error2](https://github.com/rsuite/rsuite/assets/151032429/58777ffc-8eba-41d8-aaa5-f51fd24edb33)

**Comment by simonguo** [comment]
https://stackblitz.com/edit/react-jczr8p?file=index.js
Please fork this example to reproduce your issue.
