### ISSUE TITLE
Placeholder grid or table issue, when is active, doesn't apply the animated effect as it used to.

### ISSUE THREAD

**Issue by JuanCaCode** [rsuite/rsuite#3802]
### What version of rsuite are you using?

lastest

### What version of React are you using?

18.0.0

### What browser are you using?

Chrome

### Describe the Bug

The placeholder in grid or table one used to be animated while active property  was true. as you can see in the Graph one. 

now, even if it has the active property, it doesn't work.

![image](https://github.com/rsuite/rsuite/assets/118025146/7127097a-b26d-4f0a-99e2-86a90cef0f59)

### To Reproduce
in the documentation page
[here](https://rsuitejs.com/components/placeholder/)

**Comment by simonguo** [comment]
Fixed in [v5.61.0](https://github.com/rsuite/rsuite/releases/tag/v5.61.0).
