### ISSUE TITLE
Set day of week to start

### ISSUE THREAD

**Issue by vendramini** [rsuite/rsuite#3812]
### What problem does this feature solve?
Set which day of week should be the first one. Our customers need to set which day of week their business start calculating to pay their employees. Example: my business work from Tuesday to Tuesday. It's a very specific use-case but it does exist. Currently we are using `dayjs + @mui/x-date-pickers/DateCalendar` which works well, but I would like to change to rsuite - for other reasons. 

As `@mui/x-date-pickers/DateCalendar` works with dayjs, I just have to do this `dayjs.updateLocale('en', { weekStart: 2 });` and it changes the calendar's starting week.

### What does the proposed API look like?
`weekStart={0 | 1 | 2 | 3 | 4 | 5 | 6}` maybe on `<CustomProvider/>`?

**Comment by simonguo** [comment]
Hi @vendramini 
Can you provide an example that I can refer to? For example, a demo on codesandbox.

**Comment by vendramini** [comment]
Hey @simonguo 
https://codesandbox.io/p/sandbox/set-week-start-75hj2y just change `weekStart` value.

Thanks :)

**Comment by simonguo** [comment]
Support `weekStart`  in [v5.62.0](https://github.com/rsuite/rsuite/releases/tag/v5.62.0).

https://rsuitejs.com/components/calendar/#custom-week

**Comment by vendramini** [comment]
Thank you so much <3
