### ISSUE TITLE
'Form' cannot be used as a JSX component. 

### ISSUE THREAD

**Issue by narenjoriona** [rsuite/rsuite#3822]
### What version of rsuite are you using?

5.62.0

### What version of React are you using?

18.2.0

### What version of TypeScript are you using (if any)?

5.4.2

### What browser are you using?

Chrome

### Describe the Bug

![image](https://github.com/rsuite/rsuite/assets/147404925/39533e04-da19-4011-9c01-9c9123073b5f)
![image](https://github.com/rsuite/rsuite/assets/147404925/cad207c9-9efa-41d2-923e-658b7c9faf55)
After upgrade **5.61 to 5.62** getting compile error

**Comment by simonguo** [comment]
Fixed in 5.62.1
