### ISSUE TITLE
Some manual date inputs are not registered properly on the DateRangePicker

### ISSUE THREAD

**Issue by AweVic** [rsuite/rsuite#3828]
### What version of rsuite are you using?

5.62.1

### What version of React are you using?

The version you are running on https://rsuitejs.com/components/date-range-picker/

### Describe the Bug

1. Start with this setup:
![1](https://github.com/rsuite/rsuite/assets/171241531/8cc5ba58-1505-4b78-a634-19b4bb30dabe)

2. Click on the day "01":
![2](https://github.com/rsuite/rsuite/assets/171241531/418c930f-a9c8-4930-9a69-152fc6fb4192)

3. Type "04" on the keyboard

Expected result: the adjusted day should now say "04" and nothing else should be changed

Actual result: the day becomes "10" and the year becomes "0004", as pictured:
![3](https://github.com/rsuite/rsuite/assets/171241531/2f5ce528-ebcf-456c-b4d5-154378901dae)

**Comment by simonguo** [comment]
Fixed in https://github.com/rsuite/rsuite/pull/3832

## Preview
https://rsuite-nextjs-git-fix-dateinput-rsuite.vercel.app/components/date-range-picker/

## Local Install Instructions

```bash
# yarn 1
yarn add https://pkg.csb.dev/rsuite/rsuite/commit/090a4567/rsuite
# yarn 2, 3
yarn add rsuite@https://pkg.csb.dev/rsuite/rsuite/commit/090a4567/rsuite/_pkg.tgz
# npm
npm i https://pkg.csb.dev/rsuite/rsuite/commit/090a4567/rsuite
```
