### ISSUE TITLE
Modal overflow is only working on "full" size, in other sizes overflow is not working

### ISSUE THREAD

**Issue by NilabjaDas** [rsuite/rsuite#3830]
### What version of rsuite are you using?

5.64.0

### What version of React are you using?

18.2.0

### What browser are you using?

Chrome

### Describe the Bug

Modal overflow is only working on "full" size, in other sizes overflow is not working.
```
 <Modal
        open={modalOpen2}
        onClose={onCloseModal2}
        size= {"md"}
        backdrop={true}
        overflow = {true}
      >
<Modal.Header>.................</Modal.Header>
<Modal.Body>..........................</Modal.Body> // This section should scroll if, overflow set to true. However its not
<Modal.Footer>....................</Modal.Footer>
 </Modal>
```
This wasn't the case earlier. I was using older version 5.35.1 of Rsuite.

### Expected Behavior

The Modal.Body should scroll inside the Modal as per documentation using overflow = true, in all sizes ie 'xs' | 'sm' | 'md' | lg' | 'full' | number | string. Whereas overflow is only working in 'full' size that too as its by default.

**Comment by NilabjaDas** [comment]
`<iframe src="https://codesandbox.io/embed/5j52m9?view=editor+%2B+preview&module=%2Fsrc%2FApp.js"
     style="width:100%; height: 500px; border:0; border-radius: 4px; overflow:hidden;"
     title="friendly-noether-5j52m9"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>`

**Comment by NilabjaDas** [comment]
Hi, very sorry I was busy in other projects. I have found the issue with the latest version of RSUITE, ie on usage of Modal over Drawer creates the issue. I have made a dummy replica for you to see.
Please, click on "Open Drawer" then, click on "Open Modal" to see the problem i was describing about. As requested here is the codesandbox link. 
Thanks

[https://codesandbox.io/p/sandbox/friendly-noether-5j52m9?file=%2Fsrc%2FApp.js%3A23%2C11](url)

**Comment by simonguo** [comment]
> Hi, very sorry I was busy in other projects. I have found the issue with the latest version of RSUITE, ie on usage of Modal over Drawer creates the issue. I have made a dummy replica for you to see. Please, click on "Open Drawer" then, click on "Open Modal" to see the problem i was describing about. As requested here is the codesandbox link. Thanks
> 
> [https://codesandbox.io/p/sandbox/friendly-noether-5j52m9?file=%2Fsrc%2FApp.js%3A23%2C11](url)

You need to define Modal outside Drawer, not inside it.

```diff
<div className="App">
  <div>
    <button onClick={() => handleDrawer(true)}>Open Drawer</button>
  </div>
  <Drawer
    open={showDrawer}
    size={"full"}
    onClose={() => handleDrawer(false)}
  >
    <Drawer.Header>
      <Drawer.Title>Drawer Title</Drawer.Title>
    </Drawer.Header>
    <Drawer.Body>
-     <ModalComp />
+     <button onClick={() => handleModal(true)}>Open Modal</button>
      <Placeholder.Paragraph />
    </Drawer.Body>
  </Drawer>
+ <ModalComp open={showModal}  />
</div>
```

**Comment by NilabjaDas** [comment]
Hi, thanks for your reply. As far as I understood is that Modal inside a Drawer wont work with _overflow_ .
However, the solution you gave serves me no purpose. Its a complex project where there are many layers over the drawer. Hence defining modal outside drawer is not an option, as Modal is defined in nested children of Drawer. It was working fine with earlier version of RSUITE, where Drawer was having size = "full" but shown as calc(100% - 60px).
If you are not able to fix the issue right now, I understand that. Please fix that in the upcoming versions thanks.
