### ISSUE TITLE
rsuite package depends on rsuite package

### ISSUE THREAD

**Issue by shalugin** [rsuite/rsuite#3842]
### What version of rsuite are you using?

5.64.1

### What version of React are you using?

-

### What version of TypeScript are you using (if any)?

-

### What browser are you using?

-

### Describe the Bug

The rsuite package depends on the rsuite package

<img width="1273" alt="image" src="https://github.com/rsuite/rsuite/assets/1784377/81be5551-8e85-46a5-9866-5dbcceeb37a7">

**Comment by simonguo** [comment]
Fixed in v5.64.2
