### ISSUE TITLE
Re-add toggleComponentClass function for DatePicker & DateRangePicker

### ISSUE THREAD

**Issue by rickhellenthal** [rsuite/rsuite#3850]
In version 4.* of rsuite the DateRangePicker and DateRangePicker had the function `toggleComponentClass` available to render a custom toggle component. In version 5.* there isn´t any function like this available. We'd like to see this re-added if possible. Also I'm curious as to why this was removed?

Thanks!

**Comment by simonguo** [comment]
Hi

DateRangePicker supports keyboard input in v5, rendering an Input element. Changing the Input element may cause the component to be unusable. If you just want to customize the root element of the component, you can use the `as` prop.

```tsx
<DateRangePicker as="div" />
```

**Comment by rickhellenthal** [comment]
Thanks!
