### ISSUE TITLE
Bug selectpicker when used in drawer

### ISSUE THREAD

**Issue by yayakyogi** [rsuite/rsuite#3853]
### What version of rsuite are you using?

5.64.2

### What version of React are you using?

18.3.1

### Describe the Bug

select picker menu always floating when scrolling content in drawer like this
<img width="611" alt="Screenshot 2024-06-25 at 9 14 21 AM" src="https://github.com/rsuite/rsuite/assets/57065482/e6497596-ac0f-4f0a-ba3f-dc6b871373c3">

### Expected Behavior

how to fixed it?
https://stackblitz.com/edit/react-jwxir5?file=index.js

**Comment by simonguo** [comment]
Please refer to this issue: https://github.com/rsuite/rsuite/issues/1498#issuecomment-778614506

**Comment by yayakyogi** [comment]
is still error

**Comment by yayakyogi** [comment]
is realy like this?
`<div src={containerRef}>
            <SelectPicker
              data={[{ label: 'a', value: 'a' }]}
              container={() => containerRef.current}
            />
          </div>`

**Comment by simonguo** [comment]
> is realy like this? `<div src={containerRef}> <SelectPicker data={[{ label: 'a', value: 'a' }]} container={() => containerRef.current} /> </div>`

- Typo, it's `ref` instead of `src`.
- The container should be relatively positioned.

```tsx
<div ref={containerRef} style={{ position: 'relative' }}>
  <SelectPicker
    container={() => containerRef.current}
  />
</div>
```
Also, you can use Drawer.Body as the container of SelectPicker without adding an additional div.

```jsx
<Drawer.Body ref={containerRef}>
  <SelectPicker container={() => containerRef.current} />
</Drawer.Body>
```

**Comment by yayakyogi** [comment]
finally solved, thanks bro
