### ISSUE TITLE
Allow to disable snapping of calender months in DateRangePicker

### ISSUE THREAD

**Issue by rickhellenthal** [rsuite/rsuite#3855]
### What problem does this feature solve?
Currently in the `DateRangePicker` when you select the start date in one calendar both the calendars snap to the month of the selected date and the next month. We would like the option to disable this behavior and the calendars have the ability to stay where they are when a date is selected. Similar to the behavior in v4 of rsuite.

For example:
- It is June now. The user navigates to December in the right calendar. The left calendar is untouched and stays in June.
- User selects a start date, for example 12 December
- The left calendar now snaps to December and the right calendar snaps to January

### What does the proposed API look like?
Possibility to pass a prop (`adaptiveCalendars?: boolean;` or `calendarSnapping?: boolean;` for example) to the `DateRangePicker`. If this is set to false the calendar no longer snaps a different position. Similar to the bahavior of rsuite v4.

**Comment by simonguo** [comment]
Hi @rickhellenthal 

According to your suggestion, I added a `calendarSnapping` property. You try it to see if it meets the needs of your application.
https://rsuite-nextjs-git-feat-date-range-picker-calendar-97001f-rsuite.vercel.app/components/date-range-picker/
