### ISSUE TITLE
Wrong spacing in Stack, HStack and VStack

### ISSUE THREAD

**Issue by ChristianCaracach-velaONE** [rsuite/rsuite#3885]
### What version of rsuite are you using?

5.65.0

### What version of React are you using?

18.3.1

### What browser are you using?

Firefox

### Describe the Bug

When I use Stacks, the spacing between elements its being created using "margin".
![imagen](https://github.com/user-attachments/assets/d236b038-5947-4687-a4f3-e4ae3e4e124a)
This is ok, but it also creates some margin for the incorrect axis (e.g using a HStack it adds marginBottom to elements. It doesn't make sense).
Keep in mind that I've always use alignItems: stretch in my components.
On the other hand, I've tested it in Chrome, and it works different. There, the spacing is created using "gap". So, it looks good.
![imagen](https://github.com/user-attachments/assets/73eaaf40-844a-40c1-b255-cd2ad70ecc0a)
Could this be a problem with the browser?

**Comment by simonguo** [comment]
Hi @ChristianCaracach-velaONE 

Added a judgment on whether the browser supports `flexbox-gap` in Stack. If not supported, it will be degraded to use `margin` to handle the spacing between elements. And `margin-bottom` is to solve the situation of multiple rows of elements.
> https://caniuse.com/flexbox-gap

**Comment by ChristianCaracach-velaONE** [comment]
Thanks for the answer @simonguo ! I'm using latest version of Firefox so, it shouldn't have a problem. 
But the problem still there. Do you know if there is a quick way to override it? I mean, a faster way than going stack-by-stack and manually removing the unnecessary margin.

Thanks!

**Comment by simonguo** [comment]
What is the operating system and Firefox browser version you are currently using?

**Comment by ChristianCaracach-velaONE** [comment]
Linux Mint 21.3
Firefox 128.0

**Comment by simonguo** [comment]
Can you use CSS flexbox-gap in your Firefox browser? If it works, then there is a problem with the judgment of flexbox-gap support in the browser in rsuite.

**Comment by ChristianCaracach-velaONE** [comment]
Yes, I can.
Here I added 5px
![imagen](https://github.com/user-attachments/assets/d902e5ca-51ab-4a38-8df8-c7a1126264ad)

Here I removed it
![imagen](https://github.com/user-attachments/assets/d16929e7-d7c4-4195-bbde-eb46dbc3eb11)

**Comment by simonguo** [comment]
https://rsuite-nextjs-git-fix-stack-gap-rsuite.vercel.app/components/stack/
Can you try this version to see if it works?

**Comment by ChristianCaracach-velaONE** [comment]
Yes, it works. You can notice the gap there.
![image](https://github.com/user-attachments/assets/3651916e-27fb-4a36-90f8-a0073cd5d640)
