### ISSUE TITLE
suggestion copy paste feature in DatePicker

### ISSUE THREAD

**Issue by choichoijin** [rsuite/rsuite#3887]
### What problem does this feature solve?

Hi I'm using DatePicker Component and I suggest copy/paste feature in this component.
I'd like to paste the value of the date picker to others.
But it seems current pickers doesn't offer copy and paste.
Since we need to fill pretty much of date pickers in my service, please let me know if there is a possible solution already.

### What does the proposed API look like?

no proposed code yet

**Comment by simonguo** [comment]
Hi @choichoijin  

It looks like the keyboard event is blocked, I will check it later, thank you for your feedback. It will be fixed as soon as possible.

**Comment by simonguo** [comment]
Try to copy on this DatePicker https://rsuite-nextjs-git-fix-usekeyboardinputevent-rsuite.vercel.app/components/date-picker/

**Comment by choichoijin** [comment]
@simonguo 
Thank you for fast fix!
Copy works well, but paste doesn't work. Could you check this as well?

**Comment by simonguo** [comment]
> but paste into the datepicker doesn't work. (picker to picker) 

I added the handling of the `onPaste` event, you try again.

**Comment by choichoijin** [comment]
works well :+1: I appreciate it

**Comment by choichoijin** [comment]
@simonguo Hi I was wondering when this PR will be merged and which version will have this feature available.
(Thanks again for fixing it quickly!)

**Comment by simonguo** [comment]
`rsuite` is updated and released every Friday
