### ISSUE TITLE
CheckTree defaultValue prop not populating tree

### ISSUE THREAD

**Issue by Gsoetan** [rsuite/rsuite#3905]
### What version of rsuite are you using?

5.68.0

### What version of React are you using?

^17.0.0

### What browser are you using?

FireFox

### Describe the Bug

I was trying to test out using the checktree with default checked values, but it would seem the the 'defaultValue' prop isn't being read. When a list is entered manually or through a variable nothing is populated when the tree renders.

(below is from the code sandbox provided on the checkTree component with my own addition)
```
import React from 'react';
import ReactDOM from 'react-dom';
import './styles.css';


import { CheckTree } from 'rsuite';

const data = [
  {
    label: 'Node 1',
    value: '1',
    children: [
      {
        label: 'Node 1-1',
        value: '1-1'
      },
      {
        label: 'Node 1-2',
        value: '1-2'
      }
    ]
  },
  {
    label: 'Node 2',
    value: '2',
    children: [
      {
        label: 'Node 2-1',
        value: '2-1',
        children: [
          {
            label: 'Node 2-1-1',
            value: '2-1-1'
          },
          {
            label: 'Node 2-1-2',
            value: '2-1-2'
          }
        ]
      },
      {
        label: 'Node 2-2',
        value: '2-2'
      }
    ]
  }
];

const App = () => (
  <CheckTree data={data} defaultValue={['2-2']} defaultExpandAll />
);

ReactDOM.render(<App />, document.getElementById('root'));
```

### Expected Behavior

I was expecting the items in the defaultValue list to set items in the tree to checked

### To Reproduce

Provide a list to the defaultValue prop
https://codesandbox.io/s/wonderful-snow-k7558c

**Comment by simonguo** [comment]
Fixed in v5.68.1
