### ISSUE TITLE
Two or more useMediaQuery calls using the same pattern, only the first one is updated

### ISSUE THREAD

**Issue by vendramini** [rsuite/rsuite#3908]
### What version of rsuite are you using?

"rsuite": "5.68.1"

### What version of React are you using?

"react": "18.2.0",

### What version of TypeScript are you using (if any)?

"typescript": "4.4.4"

### What browser are you using?

Chrome

### Describe the Bug

```typescript
const [a] = useMediaQuery("(min-width: 768px)");
const [b] = useMediaQuery("(min-width: 768px)");
const [c] = useMediaQuery("(min-width: 768px)");
```

### Expected Behavior

a, b and c should get updates. Only a is.

### To Reproduce

https://codesandbox.io/p/sandbox/rsuite-usemediaquery-breakpoint-th6qtd

**Comment by simonguo** [comment]
Fixed in [v5.69.0](https://github.com/rsuite/rsuite/releases/tag/v5.69.0)
