### ISSUE TITLE
onSelect callback not being triggered after clicking on "Today" button

### ISSUE THREAD

**Issue by AlfredoCode** [rsuite/rsuite#3914]
### What version of rsuite are you using?

5.68.0

### What version of React are you using?

18.3.1

### What browser are you using?

Chrome

### Describe the Bug

I am using Calendar component. When clicking on 'Today' button, the onSelect callback is not being triggered.

so lets say the date is focused on 15th of August with some tasks, when I click on 'Today' button and it is currently 6th of August, the onSelect callback is not called. Please Fix asap

### Expected Behavior

When clicking on 'Today' button, the onSelect callback should be triggered same as when user clicks on any other date manually.

### To Reproduce

1) Create compact bordered Calendar with any onSelect callback, in my example it is 'showDayInfo' that simply console.logs anything.
 ```
 <Calendar
  onSelect={showDayInfo}
  compact
  bordered
  renderCell={renderCell}
/>
```
2) Create some tasks for 15th of August and other one for whatever today date is.
3) Click on 15th of August
4) Click on 'Today' button
5) Bug is now reproduced, the onSelect callback is not triggered.

**Comment by simonguo** [comment]
If you want to listen to all events that trigger a change in the date, you should use `onChange`.

**Comment by AlfredoCode** [comment]
Thank you. Is there a reason to have two different callbacks `onSelect` and `onChange`?

**Comment by simonguo** [comment]
> Is there a reason to have two different callbacks `onSelect` and `onChange`?

The purpose is to keep consistent with DatePicker and DateRangePicker, onSelect is a callback that listens for selecting a date on the calendar panel.
