### ISSUE TITLE
TagPicker issue with 100% size 

### ISSUE THREAD

**Issue by azam693** [rsuite/rsuite#3923]
### What version of rsuite are you using?

5.69.0

### What version of React are you using?

18.3.1

### What version of TypeScript are you using (if any)?

4.9.5

### What browser are you using?

Chrome

### Describe the Bug

I created TagPicker component with next parameters
```
<TagPicker
            style={{ width: "100%" }}
            creatable={true}
            cleanable={false}
            data={items}
            value={values}
            labelKey="label"
            valueKey="value"
            onSearch={searchItems}
            onCreate={createItem}
            renderMenu={renderItems}
            onChange={changeItems}
        />
```
When I try to put a cursor (focus) on TagPicker I get an error "ResizeObserver loop completed with undelivered notifications"
<img width="628" alt="1" src="https://github.com/user-attachments/assets/4f17a6cf-ba43-43cd-aa18-cc2688342855">

This error happens when I have css style "width: "100%". If the size will be a constant number like "width: "100px" everything will be Ok.

But I need a responsive layout and dynamic sized input.

### Expected Behavior

The error shouldn't appear when I focus TagPicker.

### To Reproduce

Write "style={{ width: "100%" }}" or tailwind className "w-full".

**Comment by azam693** [comment]
Seems that the problem with calculating of menu items. The problem disappear when I put addition property like "menuStyle={{ width: "100%" }}". The main problem how to properly calculate it.

**Comment by simonguo** [comment]
Hi @azam693  
Thank you for your feedback. You can try setting `menuAutoWidth` to `false` to see if it can temporarily solve your problem. We will find the cause and fix it as soon as possible.

**Comment by azam693** [comment]
Hello @simonguo 
The `menuAutoWidth` setting  also helps to fix the bug. But the size of the menu starts to adjust by content that doesn't fit to me. I'm using `menuStyle={{ width: "300px" }}` as a temporary solution.

Anyway thank you for response!)

**Comment by simonguo** [comment]
I can't reproduce the problem using `style={{ width: "100%" }}`, can you reproduce the problem using Stackblitz or Codesandbox?

**Comment by azam693** [comment]
Hello @simonguo 
I dug deeper to the problem and found that it's a really specific issue. I tried to reproduce the problem separately from my project, but it didn't work out. 
So, I will study the problem again tomorrow. If I find nothing I will close the issue.

Thank you for your effort I really appreciate it.)
