### ISSUE TITLE
MultiCascader bug in localization

### ISSUE THREAD

**Issue by Bartlomiej-Stec** [rsuite/rsuite#3925]
### What version of rsuite are you using?

5.69.0

### What browser are you using?

Chrome

### Describe the Bug

MultiCascader locale is not working as expected. Not all strings are translated (in this case only placeholder is translated). Same input for CheckTreePicker or SelectPicker is working correctly.
`
<MultiCascader locale={{
    noResultsText: 'Brak wyników',
    searchPlaceholder: 'Szukaj',
    placeholder: 'Domyślnie wszystkie'}}
    data={data}
    block
/>
`

**Comment by simonguo** [comment]
Fixed in v5.70.0
