### ISSUE TITLE
The search bar of the TreePicker isn't focused once a character key is pressed

### ISSUE THREAD

**Issue by abourges-yseop** [rsuite/rsuite#3926]
### What version of rsuite are you using?

5.69.0

### What version of React are you using?

17.0.2

### What browser are you using?

Chrome 127.0.6533.99

### Describe the Bug

When we use the `TreePicker` with the search feature, once the treePicker is opened and we press a character key, it seems that the focus isn't performed on the search bar.

You can test it on the basic example provided here : https://rsuitejs.com/components/tree-picker/#basic

It doesn't happen on the `CheckTreePicker` component though.

From what I've tested, it seems that the `searchInput` isn't passed to the `searchInputRef` props of the `TreeView` in the TreePicker component, but it is done in the `CheckTreePicker`.

My understanding is based on your explanation about the components' accessibility : https://rsuitejs.com/guide/accessibility/, feel free to tell me if I miss something !

I'd love to use this accessible component :smile:

### Expected Behavior

When the `TreePicker` is opened, it would be great to focus on the search bar when we press a character key and get to see this character in the input.

### To Reproduce

- Open the `TreePicker` (not the `CheckTreePicker`)
- Press a character key
- The search bar isn't focused and the text isn't written in the input.

Have a good day !

**Comment by simonguo** [comment]
Fixed in v5.70.0
