### ISSUE TITLE
error using form component

### ISSUE THREAD

**Issue by coderwithattitude** [rsuite/rsuite#395]
### Bug, feature request, or proposal:
when i try to render the form i keep getting the below error, please find my code below

  ```
render() {
    return (
      <div>
        <Panel header={
          <div>
              <span style= {{ display: 'inline-block', marginRight: '30px'}}>
                  <h1>Payroll</h1>
              </span>
              <Button appearance="primary" className="tight-border spread-button bold-font" color="green" placement="left" style={{ verticalAlign: '6px', fontSize: '12px' }} onClick={this.handleShowModal}>
                  PAY EMPLOYEES
              </Button>
          </div>}
        >
          
          <Modal show={this.state.show} onHide={this.handleCloseModal} backdrop={'static'}>
            <Header>
              <Title>Add Employee</Title>
            </Header>
            <Body>
              <Form fluid>
                <FormGroup>
                  <ControlLabel>First Name</ControlLabel>
                  <FormControl name="firstname" />
                  <HelpBlock>Required</HelpBlock>
                </FormGroup>
                <FormGroup>
                  <ControlLabel>Last Name</ControlLabel>
                  <FormControl name="lastname" />
                  <HelpBlock>Required</HelpBlock>
                </FormGroup>
                <FormGroup>
                  <ControlLabel>Email</ControlLabel>
                  <FormControl name="email" type="email" />
                  <HelpBlock>Required</HelpBlock>
                </FormGroup>
                <FormGroup>
                  <ControlLabel>Password</ControlLabel>
                  <FormControl name="password" type="password" />
                </FormGroup>
                <FormGroup>
                  <ControlLabel>City</ControlLabel>
                  <FormControl name="city" />
                </FormGroup>
                <FormGroup>
                  <ControlLabel>Street</ControlLabel>
                  <FormControl name="street" />
                </FormGroup>
              </Form>
            </Body>
            <Footer>
              <Button onClick={this.handleCloseModal} appearance="primary">
                Ok
            </Button>
              <Button onClick={this.handleCloseModal} appearance="subtle">
                Cancel
            </Button>
            </Footer>
          </Modal>

         
        </Panel>
        <DrawerView show={this.state.showDrawer} onClose={this.handleCloseDrawer} />
      </div>
    );
  }
}
```

`

### What is the current behavior?

FormControl.js:129 Uncaught Error: 
        <FormControl> must be inside a component decorated with <Form>.
        And need to update React to 16.6.0 +.

**Comment by simonguo** [comment]
React 16.3 starts supporting the new context API, which is a problem if the React used in your project is greater than 16.3 and less than 16.6.

Because the contextType is only supported in the new API after react 16.6.

In `rsuite` it is determined whether the new Context API is supported. If supported, the `contextType` attribute is used. If not supported, the old Context API will still be used.

You can try to upgrade the version of react and react-dom.

[React 16.3](https://github.com/facebook/react/blob/master/CHANGELOG.md#1630-march-29-2018)
[React 16.6](https://github.com/facebook/react/blob/master/CHANGELOG.md#1660-october-23-2018)

**Comment by coderwithattitude** [comment]
> React 16.3 starts supporting the new context API, which is a problem if the React used in your project is greater than 16.3 and less than 16.6.
> 
> Because the contextType is only supported in the new API after react 16.6.
> 
> In `rsuite` it is determined whether the new Context API is supported. If supported, the `contextType` attribute is used. If not supported, the old Context API will still be used.
> 
> You can try to upgrade the version of react and react-dom.
> 
> [React 16.3](https://github.com/facebook/react/blob/master/CHANGELOG.md#1630-march-29-2018)
> [React 16.6](https://github.com/facebook/react/blob/master/CHANGELOG.md#1660-october-23-2018)

Thanks alot! i updated react-dom and problem solved
