### ISSUE TITLE
TimePicker and TimeRangePicker

### ISSUE THREAD

**Issue by giacomoaugello1** [rsuite/rsuite#3959]
**Feature Request: Time Input Components**

I would like to request the addition of a few time input components: one for selecting a single time and another for selecting a time range.

As a reference, these could be similar to the MUI TimePicker: [MUI TimePicker](https://mui.com/x/react-date-pickers/time-picker/) and the (yet-to-be-implemented) MUI TimeRangePicker: [MUI TimeRangePicker](https://mui.com/x/react-date-pickers/time-range-picker/).

In my opinion, RSuite is far superior to MUI, and I would love to see these features implemented. I noticed that the ability to select a time is already partially available in the `DatePicker` and `DateRangePicker` components, so it seems like this functionality is halfway there.

It would also be great to have options to choose between 12-hour and 24-hour formats, as well as to set the minimum time step (e.g., 5, 15, or 30 minutes).

Thank you for considering this request!

**Comment by simonguo** [comment]
Hi, you can switch between 12-hour and 24-hour formats by `showMeridian`. Hide the minutes and seconds you don't need to display with `hideMinutes` and `hideSeconds`.

```tsx
<DatePicker
  format="HH:mm:ss"
  showMeridian
  hideMinutes={minute => minute % 15 !== 0}
  hideSeconds={second => second % 30 !== 0}
  ranges={[]}
/>
```

**Comment by giacomoaugello1** [comment]
Hi! the `DatePicker` works perfectly! It would be possible to have the same functionality on `DateRangePicker` too ( hideMinutes, hideSeconds, HideHours)?

**Comment by simonguo** [comment]
DateRangePicker can consider adding this feature later

**Comment by simonguo** [comment]
> Hi! the `DatePicker` works perfectly! It would be possible to have the same functionality on `DateRangePicker` too ( hideMinutes, hideSeconds, HideHours)?

Support in rsuite@5.71.0
