### ISSUE TITLE
Unable to Generate Multiple Column Groups Dynamically

### ISSUE THREAD

**Issue by wangbo201308** [rsuite/rsuite#396]
### Bug, feature request, or proposal:
 This is a bug related to the Table component, which is that it cannot generate multiple column groups dynamically.  

### What is the expected behavior?
The expected behavior is that it can generate multiple column groups  dynamically.

### What is the current behavior?
According to the current syntax,  the table component can only generate a table with one column group or a a table with multiple column groups which are fixed and cannot be generated dynamically.
As is shown in the appendix below, part there is expected to be passed to the table component when we want to realize a column group, which means that we should generate many part there if we expect to get multiple column groups. However,  part one and  multiple part two generated by a loop function can not be returned as a result of a loop function according to JSX syntax unless they are wrapped by Fragment or something like that, which is invalid according to the current syntax.
![_20190215143912](https://user-images.githubusercontent.com/29032393/52840253-a736f280-3133-11e9-9b00-f34950e210fa.png)
![_20190214114758](https://user-images.githubusercontent.com/29032393/52840979-e8c89d00-3135-11e9-8a98-106c9dcfe900.png)

### What are the steps to reproduce?
Just copy the following code or try to generate a Multiple column groups table Dynamically, which means you should a loop function.

```
import React from 'react';
import { Table } from 'rsuite';
import 'rsuite/styles/index.less';
import './table.less';
const { Column, HeaderCell, Cell } = Table;

let fakeLargeData = [];
for (let i = 100000; i > 0; i--) {
  fakeLargeData.push({
    id: 100000 - i,
    First: {
      Name: 'test'
    },
    'Last Name': 'Last Name',
    'Third Name': 'Third Name',
    City: '深圳',
    Street: '西乡',
    'Company Name': 'Skieer'
  });
}
const list = ['Last Name', 'Third Name', 'City', 'Street', 'Company Name'];
const fakeList = [1, 2, 3];
class LargeTable extends React.Component {
  render() {
    return (
      <div>
        <Table
          virtualized
          width={1000}
          height={400}
          headerHeight={48}
          rowHeight={24}
          data={fakeLargeData}
          bordered
          cellBordered
        >
          <Column minWidth={150} flexGrow={1} align="left" fixed>
            <HeaderCell>商品名称</HeaderCell>
            <Cell dataKey="id" height={24} />
          </Column>
          {fakeList.map((num, firstIndex) => {
            const fragment =
                <Column key={firstIndex} minWidth={150 * 6} flexGrow={1} align="center" colSpan={6}>
                  <HeaderCell className="header-cell-group">
                    <div className="header-cell-group-title">Name</div>
                    <div className="header-cell-group-subtitle">
                      <span style={{ minWidth: '150px'}}>
                        First Name
                      </span>
                      <span style={{ minWidth: '150px'}}>
                        Last Name
                      </span>
                      <span style={{ minWidth: '150px'}}>
                        Third Name
                      </span>
                      <span style={{ minWidth: '150px'}}>City</span>
                      <span style={{ minWidth: '150px'}}>Street</span>
                      <span style={{ minWidth: '150px'}}>
                        Company Name
                      </span>
                    </div>
                  </HeaderCell>
                  <Cell dataKey="First.Name">
                    <div className="test">First Name</div>
                  </Cell>
                </Column>;
                {list.map((item, index) => {
                  return (
                    <Column key={index} minWidth={150} flexGrow={1} align="center">
                      <HeaderCell />
                      <Cell dataKey={item} />
                    </Column>
                  );
                })}
            return fragment;
          })}
        </Table>
      </div>
    );
  }
}
```

**Comment by simonguo** [comment]
@wangbo201308  If you can't describe your problem well, you can put the code into codesandbox.

https://codesandbox.io/s/5vq6zo2z5l

**Comment by wangbo201308** [comment]
> @wangbo201308 If you can't describe your problem well, you can put the code into codesandbox.
> 
> https://codesandbox.io/s/5vq6zo2z5l

Thanks. You can also refer to the chinese version.[https://www.cnblogs.com/guoxiaoming/p/7471652.html#4179318](url)

**Comment by simonguo** [comment]
Is this an example you want?

![image](https://user-images.githubusercontent.com/1203827/52843882-524ca980-313e-11e9-9992-622866d5a2bd.png)

Code : https://codesandbox.io/s/m3n45vv8vx

**Comment by wangbo201308** [comment]
> Is this an example you want?
> 
> ![image](https://user-images.githubusercontent.com/1203827/52843882-524ca980-313e-11e9-9992-622866d5a2bd.png)
> 
> Code : https://codesandbox.io/s/m3n45vv8vx

Thanks a lot ! This is exactly what I want, and maybe I should red the api in detail.
