### ISSUE TITLE
 the table does not fit the flexgrow

### ISSUE THREAD

**Issue by eliaschester** [rsuite/rsuite#397]
### Bug, feature request, or proposal:

I create a container that contains 3 components. The second component contains a table. this tables does not fit with the flexgrow property

### What is the current behavior?

the table does not fit the flexgrow

### What are the steps to reproduce?

![image](https://user-images.githubusercontent.com/6012814/52862011-e0129f80-3112-11e9-8b71-fd7116d4ed0c.png)

![image](https://user-images.githubusercontent.com/6012814/52862033-edc82500-3112-11e9-84c0-6d206126416a.png)

There is a way to refresh the table component? because if I change the size of the browser, the table fit with the rigth with. look

![image](https://user-images.githubusercontent.com/6012814/52862108-223be100-3113-11e9-82bd-71196329679e.png)

**Comment by simonguo** [comment]
I can't reproduce your problem. Could you reproduce the problem through `codesandbox` ? 

[![Edit Table 列宽不渲染问题测试](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/w73pwj0ox5)

**Comment by cao2358** [comment]
我也遇到同样的问题，使用flexGrow列之后，不能自动适应列宽，展示的样式如图下面会有一个不能拖动的滚动条，但是如果将页面的宽度做个简单调整就会正常，比如width改成99% 或者将浏览器全屏一下就会好

**Comment by LukaszGrela** [comment]
The table does not resize, needs extra kick by resizing window (or toggling the sidebar) here is the sandbox:

https://codesandbox.io/s/table-liekuanbuxuanranwenticeshi-forked-5epyj?file=/src/index.js

Is there a way to force redraw of the table (so it calculates the size correctly)?

**Comment by frei-it** [comment]
Same Problem here - Flexgrow columns do not fill width of full Table, but stay at a width of 100px after initial render.
Rezising window fixes issue, but only if done manually.

**Comment by alexvrv** [comment]
Why tf is this closed if the problem isn't fixed? :/

**Comment by likbes-cf** [comment]
still not fixed

**Comment by simonguo** [comment]
The Tabs component is often used to control the display and hide of elements through CSS. When the Table is hidden, the real value cannot be obtained when calculating the width of the table, which causes the width calculation of the `flexGrow` column to be incorrect. When switching from hidden to display, because it is controlled by CSS, it will not cause the component to be re-rendered. To solve this problem, you can add a judgment in the Tab to re-render the table every time it is displayed.

### Before: 

```tsx
const App = () => {
  const [key, setKey] = React.useState('1');
  return (
    <Tabs activeKey={key} onSelect={setKey}>
      <Tabs.Tab eventKey="1" title="Tab 1">
        <CustomTableA />}
      </Tabs.Tab>
      <Tabs.Tab eventKey="2" title="Tab 2">
        <CustomTableB />}
      </Tabs.Tab>
    </Tabs>
  );
};
```

### After

```tsx
const App = () => {
  const [key, setKey] = React.useState('1');
  return (
    <Tabs activeKey={key} onSelect={setKey}>
      <Tabs.Tab eventKey="1" title="Tab 1">
        {key === '1' && <CustomTableA />}
      </Tabs.Tab>
      <Tabs.Tab eventKey="2" title="Tab 2">
        {key === '2' && <CustomTableB />}
      </Tabs.Tab>
    </Tabs>
  );
};
```

**Comment by simonguo** [comment]
Fixed in https://github.com/rsuite/rsuite-table/pull/489
