### ISSUE TITLE
Need two clicks to focus InputPicker inside InlineEdit

### ISSUE THREAD

**Issue by Hedz0r** [rsuite/rsuite#3986]
### What version of rsuite are you using?

5.67

### What version of React are you using?

18

### What version of TypeScript are you using (if any)?

5.0.2

### What browser are you using?

Firefox

### Describe the Bug

1. Use `InputPicker` inside `InlineEdit`
2. Try opening the component and search for a value
3. You need a second click to focus the InputPicker and be able to search

This doesn't seem to be intented because all the InputPicker components allow to search directly upon clicking.

### Expected Behavior

Open the component and be able to search in one click. Would be amazing if this could be fixed!

### To Reproduce

You can check your own example
https://codesandbox.io/p/sandbox/phk8pl

**Comment by simonguo** [comment]
Fixed in v5.72.0

**Comment by hedzerkoolstra** [comment]
Thanks!
