### ISSUE TITLE
Hi, 新版本React出现了兼容性问题

### ISSUE THREAD

**Issue by Bytesu** [rsuite/rsuite#4]
![image](https://cloud.githubusercontent.com/assets/8148277/21170897/5585e67c-c203-11e6-9f85-5dcbd85c6188.png)

**Comment by Bytesu** [comment]
![image](https://cloud.githubusercontent.com/assets/8148277/21170937/a5873e5a-c203-11e6-89a5-fb83bd694eb5.png)

**Comment by Bytesu** [comment]
非常喜欢rsuite，支持能够继续维护下去哈

**Comment by simonguo** [comment]
当前兼容 0.14.*  版本，    15.* 版本以后的版本，后续会考虑更新

**Comment by simonguo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [rsuite 升级 react 版本 15.*](https://trello.com/c/mb7aJ8Ko/1-rsuite-%E5%8D%87%E7%BA%A7-react-%E7%89%88%E6%9C%AC-15)
