### ISSUE TITLE
DateRangePicker : selected date display in the calendar pop up, comes incorrect like this: MM/dd/yyyy HH:mm ~ MM/dd/yyyy HH:mm

### ISSUE THREAD

**Issue by arwaHakim** [rsuite/rsuite#4038]
### What version of rsuite are you using?

5.55.0

### What version of React are you using?

18

### What browser are you using?

safari

### Describe the Bug

In the DateRangePicker component:
The selected date which is shown in the top left corner of the calendar  pop up comes as date format like this in my case: MM/dd/yyyy HH:mm ~ MM/dd/yyyy HH:mm

### Expected Behavior

it should show the date which is there in the input filed. ex: 11/04/2024 20:08 ~ 11/04/2024 21:08
<img width="551" alt="Screenshot 2024-11-04 at 9 19 43 PM" src="https://github.com/user-attachments/assets/5385ab55-17c9-45ee-838c-f3d3c0e20f74">

### To Reproduce

1. Set any date in calendar input field ,either manually or by selecting from calendar.
2. click on the date input
3. calendar pop up will open
4. just click on any date just once (do not select start date and end date both, just select start date)
5. click outside the popup
6. popup will close
7. click on the date input again
8. The selected date which is shown in the top left corner of the  pop up comes as date format like this in my case: MM/dd/yyyy HH:mm ~ MM/dd/yyyy HH:mm

**Comment by simonguo** [comment]
Fixed in  v5.74.2

**Comment by arwaHakim** [comment]
Hi, will this fix be released in the next release! . By when can I expect
this
Thanks
Arwa
