### ISSUE TITLE
rsuite-table wordWrap not working

### ISSUE THREAD

**Issue by ChampionRoy** [rsuite/rsuite#404]
When wordWrap property used, the height of row cell do not change.
![image](https://user-images.githubusercontent.com/20150620/53319080-71042a80-390c-11e9-9327-09513aa720fc.png)
the css selector "rs-table-row-expanded" set height 46px with 10px padding, but nothing changed if workWrap is set. 
reproduce environment: chrome 72, rsuite 3.3 , and using isTree property.

**Comment by simonguo** [comment]
@ChampionRoy   
Upgrade rsuite to 3.7.7 and try it out.

[![Edit rsuite-table-tree-word-wrap](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/olmk2qwy96?fontsize=14)
