### ISSUE TITLE
Rsuite.css Source Map Error with Vite - Failed to Load index.css.map

### ISSUE THREAD

**Issue by Miderson99** [rsuite/rsuite#4040]
### What version of rsuite are you using?

5.70.0

### What version of React are you using?

18.2.0

### What browser are you using?

Edge

### Describe the Bug

![Captura de tela 2024-11-06 140507](https://github.com/user-attachments/assets/f06927d2-ffce-4aef-bf13-a9293cf8760d)

➜ press h + enter to show help
13:59:58 [vite] Failed to load source map for C:/Users/ENG-02/Desktop/blueFleet/BLUECHIP-BLUE-FLEET/SOFTWARE/FRONTEND/blue-fleet/node_modules/rsuite/dist/rsuite.css.
Error: An error occurred while trying to read the map file at index.css.map
Error: ENOENT: no such file or directory, open 'C:\Users\ENG-02\Desktop\blueFleet\BLUECHIP-BLUE-FLEET\SOFTWARE\FRONTEND\blue-fleet\node_modules\rsuite\dist\index.css.map'
    at async open (node:internal/fs/promises:638:25)
    at async Object.readFile (node:internal/fs/promises:1251:14)
    at async extractSourcemapFromFile (file:///C:/Users/ENG-02/Desktop/blueFleet/BLUECHIP-BLUE-FLEET/SOFTWARE/FRONTEND/blue-fleet/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:21001:53)
    at async loadAndTransform (file:///C:/Users/ENG-02/Desktop/blueFleet/BLUECHIP-BLUE-FLEET/SOFTWARE/FRONTEND/blue-fleet/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:51892:27)

    
 A warning about the missing index.css.map file in rsuite appears in the console on every development build. The application still functions correctly, but this warning is distracting and potentially impacts development. Is someone facing something like that?

### Expected Behavior

No warnings related to missing source maps should appear if the project dependencies are properly configured.

### To Reproduce

Run the project using Vite in development mode.
The warning appears in the console, indicating that the source map file index.css.map is missing in the rsuite package directory.

**Comment by simonguo** [comment]
Use rsuite.min.css instead of rsuite.css, a rsuite.min.css.map file is generated for rsuite.min.css in rsuite.

```diff
- import 'rsuite/dist/rsuite.css';
+ import 'rsuite/dist/rsuite.min.css';
```

**Comment by Miderson99** [comment]
Worked. Thanks very much for the help 👍

**Comment by simonguo** [comment]
Upgrade to v5.74.2 and you can use `rsuite.css`
