### ISSUE TITLE
Table locale not working

### ISSUE THREAD

**Issue by ruijff** [rsuite/rsuite#4042]
### What version of rsuite are you using?

5.74.1

### What version of React are you using?

^18.0.0

### What version of TypeScript are you using (if any)?

~5.6.2

### What browser are you using?

Chrome

### Describe the Bug

[https://codesandbox.io/p/sandbox/empty-wildflower-hp5f5n](https://codesandbox.io/p/sandbox/empty-wildflower-hp5f5n)

In the link above you can clearly see that I'm giving the table a locale to it to overwrite the empty message but the table completely ignores it and uses the en default. 

### Expected Behavior

It should overwrite the value of empty message with the given value in locale.

### To Reproduce

[https://codesandbox.io/p/sandbox/empty-wildflower-hp5f5n](https://codesandbox.io/p/sandbox/empty-wildflower-hp5f5n)

Here is an example on Code Sandbox.

But I have tried a fully empty project with nothing but vite, typescript and rsuite and still does not work.

**Comment by simonguo** [comment]
Fixed in https://github.com/rsuite/rsuite/pull/4037
