### ISSUE TITLE
Panel Component - Expanding Panel triggers Submit Event

### ISSUE THREAD

**Issue by Joshusus** [rsuite/rsuite#4043]
### What version of rsuite are you using?

5.74.1

### What version of React are you using?

18.3.1

### What version of TypeScript are you using (if any)?

4.9.5

### What browser are you using?

Chrome

### Describe the Bug

I have a set of Panels within a Form (we're using it to break up the data capture):

![image](https://github.com/user-attachments/assets/07961d17-0c22-41e8-b409-ec9cfd310f28)

Whenever I expand a panel, the `onSubmitForm` event is triggered! After a little investigation, it seems to be because the buttons rendered for the Panel headers has not got a type attribute, and so is defaulting to a **submit** button.

I don't think this would be the case to support some other behaviour, and buttons should always have a type defined to my knowledge anyway - so I think the fix is as simple as adding one. I've given this a manual test & that seems to work just fine :) 

![image](https://github.com/user-attachments/assets/c91ac3c3-21b8-47ce-9c94-a99680daf675)

Much appreciated!

### Expected Behavior

Expanding or closing a Panel should not trigger the onSubmit event.

### To Reproduce

Put Panels inside of a form. Monitor the onSubmit form event. Open/close a panel.

**Comment by Joshusus** [comment]
Here's my suggested fix, done in AccordionButton.tsx
![image](https://github.com/user-attachments/assets/3069aa40-1753-49e2-8af1-30b82d59429c)

**Comment by simonguo** [comment]
Fixed in v5.74.2
