### ISSUE TITLE
Table 页码发生变化时，Table Content 高度没有更新

### ISSUE THREAD

**Issue by superman66** [rsuite/rsuite#417]
### Bug, feature request, or proposal:

Bug

### What is the expected behavior?
当Table使用分页时，切换页码后，页面正常显示。

### What is the current behavior?
滚动Table数据到底部，然后切换页码（比如从30切换到10时），Table 内容区域高度未跟着变化。

### What are the steps to reproduce?

> Please fork this example, reproduce the problem you are issue.
> https://codesandbox.io/s/5vq6zo2z5l

**Comment by simonguo** [comment]
`rsuite-table@3.5.1`
