### ISSUE TITLE
Search bar styling missing when using modular-import

### ISSUE THREAD

**Issue by emattias** [rsuite/rsuite#438]
When using `MultiCascader` without the `checkbox.less` file the search results looks broken when setup to use [modular import](https://github.com/rsuite/examples/tree/master/modular-import).

When I add `import 'rsuite/lib/styles/checkbox'` manually the styling looks right again.

Maybe checkbox.less should be added here? 👇🏻 

https://github.com/rsuite/rsuite/blob/32bdaff81735c18734dbd4f8cf57316fae51da14/scripts/generate-styles.js#L42

**Comment by simonguo** [comment]
cc @hiyangguo

**Comment by hiyangguo** [comment]
@emattias We will fix it in next version. Thank you.

**Comment by simonguo** [comment]
@emattias  Fixed in `rsuite@3.8.3`
