### ISSUE TITLE
Add viewport overflowing prevention for floating elements (dropdown, tooltips, modals, etc)

### ISSUE THREAD

**Issue by emattias** [rsuite/rsuite#442]
Right now floating elements can grow outside of browser viewport window so that the floating element is cut off. 

I suggest that components with floating elements (eg. `MultiCascader`, `Tooltip`, etc) are built to prevent overflowing to happen.

The `material-ui` has a page demonstrating how they have solved this (they use [Popper.js](https://github.com/FezVrasta/popper.js)): https://material-ui.com/utils/popper/#scroll-playground

**Comment by simonguo** [comment]
thank you so much for your suggestion.

We will improve on the problem of element overflow, we may add a method on the component `< OverlayTrigger >` to update the placement.

**Comment by simonguo** [comment]
@emattias   Is it what you expected?

![yzw5n-hvnrl](https://user-images.githubusercontent.com/1203827/56191437-efed2800-605e-11e9-8917-776c5f6312cf.gif)

**Comment by emattias** [comment]
Yup, that solves my problem! 👍🏻
