### ISSUE TITLE
FormControl代理CheckPicker，改变data后onChange传来的val不对

### ISSUE THREAD

**Issue by begoat** [rsuite/rsuite#457]
### Bug, feature request, or proposal:
rsuite版本3.8.3
不知道是bug还是用法不对
### What are the steps to reproduce?

1. checkPicker勾选一些选项（这时候数据源是data1）
2. 查看控制台 CheckPicker onChange回掉中会看到打印的checkPicker中传过来当前内部的value
3. 点击按钮 改变 checkPicker数据源，然后重新勾选一些值
4. 查看控制台，代码中已经在点击按钮切换数据源的时候清空了当前checkPicker的value，但是在新的数据源渲染的列表勾选选项 又会出现旧数据源下的勾选的数据。

https://codesandbox.io/s/ko8lpo9o4v

**Comment by simonguo** [comment]
FormControl 与 Form 组合使用时候，对 value 与 onChange 受控的管理，建议放在 Form 上统一处理。  

https://codesandbox.io/s/j12xom3x3

**Comment by begoat** [comment]
好的，谢谢解答
