### ISSUE TITLE
Changing the background color using rowClassName has no effect

### ISSUE THREAD

**Issue by arjuna-chala** [rsuite/rsuite#461]
### Bug, feature request, or proposal:

Bug

### What is the expected behavior?

 <Table
                        height={400}
                        data={this.state.data}
                        onRowClick={data => {
                            console.log(data);
                        }}
                        showHeader={true}
                        rowClassName={(rowData) => 'karya-table-row'}
                    >

### What is the current behavior?

It shows the default color (white).

### What are the steps to reproduce?

CSS: 
.karya-table-row {
  background-color: red;
}

**Comment by arjuna-chala** [comment]
somehow the original message was cut. the code is:

 <Table
                        height={400}
                        data={this.state.data}
                        onRowClick={data => {
                            console.log(data);
                        }}
                        showHeader={true}
                        rowClassName={(rowData) => 'karya-table-row'}
                    >

**Comment by simonguo** [comment]
The style of the `Cell` should be defined in CSS
```css
.karya-table-row, .karya-table-row .rs-table-cell {
    background: red;
}
```

**Comment by arjuna-chala** [comment]
That worked. Thank you!

**Comment by akshaynarisetti** [comment]
Hey @simonguo I am also having the same problem I am using it like this

**CSS** 
```
.karyatablerow, .karyatablerow .rs-table-cell {
    background: red;
}
```

jsx:-
```
import style from "./file.css"

{ console.log(data); }} showHeader={true} rowClassName={(rowData) => return style.karyatablerow} >
```

**Comment by simonguo** [comment]
@akshaynarisetti  
Could you reproduce your problem with [codesandbox](https://codesandbox.io/s/rsuite-template-5vq6zo2z5l)?

**Comment by akshaynarisetti** [comment]
Hey @simonguo here’s the link to the sandbox Environment [codesandbox](https://codesandbox.io/s/musing-bartik-7fy3z5?file=/index.js)

**Comment by simonguo** [comment]
@akshaynarisetti  
The `rowClassName` property is to add a custom className for the table row. Its type can only be a string or a function that returns a string.

```tsx
rowClassName={(row) => {
  if (row?.id === 1) {
    return 'colorChange';
  }
}}
```
