### ISSUE TITLE
usage modularize with typescripts

### ISSUE THREAD

**Issue by fas3r** [rsuite/rsuite#474]
### Bug, feature request, or proposal:

Hello, 

I'm new in react world and typescripts, I tried to implement "Use modularized rsuite" as described [here](https://rsuitejs.com/en/guide/usage) in the bottom of the page. 

I used react-create-app to start, then installed the rsuite and the babel-preset-rsuite with npm. 

When I reproduce the example :
```
import React from 'react';
import ReactDOM from 'react-dom';
import Button from 'rsuite/lib/Button';

// import default style
import 'rsuite/styles/less/index.less'; // or 'rsuite/dist/styles/rsuite.min.css'

function App() {
  return <Button>Hello World</Button>;
}

ReactDOM.render(<App />, document.getElementById('root'));
```

I'm getting the following error : 

```
Could not find a declaration file for module 'rsuite/lib/Button'. '..../client/node_modules/rsuite/lib/Button.js
' implicitly has an 'any' type.
  Try `npm install @types/rsuite` if it exists or add a new declaration (.d.ts) file containing `declare module 'rsuite/lib/Button';`  TS7016

    1 |
    2 | import * as React from 'react';
  > 3 | import Button from 'rsuite/lib/Button';
      |                    ^
    4 |
    5 | // import default style
    6 | import 'rsuite/styles/less/index.less';
```

I saw the note at the bottom of the page mentioning :  `Note: If you use webpack Tree Shaking in your project, you cannot use it.` Maybe that's the issue ? 

I also searched for the "@types/rsuite" packages but no look. What is curious is that I see the `types` folder in `node_modules/rsuite/`.

Did I missed something ? 

Thanks

**Comment by simonguo** [comment]
If you use `babel-preset-rsuite` , you can still write this:

```js
import { Button } from 'rsuite';
```

**Comment by simonguo** [comment]
@fas3r  `npm install  rsuite@3.8.5`
