### ISSUE TITLE
Get name of form component on onChange handler

### ISSUE THREAD

**Issue by dvriv** [rsuite/rsuite#48]
### Bug, feature request, or proposal:

Question

### What is the expected behavior?

Generally when use native elements the handler function gets the name passed on **_'event'_**. This doesn't happen on RSuite form components, I get the value directly,  so what would be the best way to do it? Example how I do it with native html elements: (This is for multiple form elements so I don't have to use a lot of different functions)

```js
  handleInputChange(event) {
    const name = event.target.name; 
    const value = event.target.value
    this.setState({name: value});
  }

   <input
   name="input1"
   type="checkbox"
   onChange={this.handleInputChange} />

   <input
   name="input2"
   type="checkbox"
   onChange={this.handleInputChange} />
```
Thanks

**Comment by simonguo** [comment]
Should be rewritten as :

```js
this.setState({
  [name]: value
});
```

If you want to use the native component in the Rsuite form, refer to:   https://rsuitejs.com/en/components/form#Third-Party%20Libraries

**Comment by dvriv** [comment]
@simonguo true my mistake, then there is no way to get event.target.name with the rsuite form components?

**Comment by simonguo** [comment]
In the rsuite form components, the second parameter of the `onChange` is `event`.
```js
<Input
  name="username"
  onChange={(value, event)=>{
    console.log(event.target.name); // username
  }}
/>;
```

**Comment by dvriv** [comment]
That work, thank you @simonguo

**Comment by dvriv** [comment]
Seems like it works for Inputs but not for RadioGroup even if the documentation says it should work.

```js
<RadioGroup
   name="modo"
   value={this.state.modoValue}
   onChange={(value, checked, event) => {
   console.log(value, checked, event);
  }}
>
   <Radio value="pasivo">Pasivo</Radio>
   <Radio value="ajuste">Ajuste de Pasivo</Radio>
</RadioGroup>
```
this shows `pasivo true undefined` on console

**Comment by simonguo** [comment]
Sorry, here is a bug, I fix it right away. You can deal with this temporarily:
```js
 handleChange(name, value) {
    this.setState({
      [name]: value
    });
    console.log(name, value);
  }
  render() {
    return (
      <RadioGroup
        value={this.state.radioList}
        onChange={value => {
          this.handleChange('radioList', value);
        }}
      >
        <Radio value="A">Item A</Radio>
        <Radio value="B">Item B</Radio>
        <Radio value="C">Item C</Radio>
      </RadioGroup>
    );
  }
```

I also recommend that you use `Schema.Model` and `<Form>`  combinations to manage your form data structure.
https://rsuitejs.com/en/components/form#Form%20Data%20Check

**Comment by cetRide** [comment]
Hey you can try this.....it is working for me:
formHandler = (value, event) => {
    this.setState({ [event.target.name]: event.target.value });
  };
 submit = (event) => {
    event.preventDefault();
  };

//form
 <Input name="username" onChange={this.formHandler} />
<Input
              placeholder="Password"
              name="password"
              type="password"
              onChange={this.formHandler}
            />
<Button type="submit" onClick={this.submit} appearance="primary">
              Login
            </Button>
