### ISSUE TITLE
Icon on FormControl

### ISSUE THREAD

**Issue by keraf** [rsuite/rsuite#481]
### Bug, feature request, or proposal:
I am currently trying to build a form with icons inside the inputs. Using FormGroup and FormControl, I have not found a way to make it work. I have tried using Addon like in the Input example but was unsuccessful with that attempt.

Are icons in FormControl supported? Or is there another way to make it work similarly to Input?

Cheers!

**Comment by keraf** [comment]
Finally found out how to do it. Pasting it here for future reference:
```
<FormGroup>
    <FormControl accepter={InputGroup} errorMessage={formError.email}>
        <InputGroup inside>
            <Input
                type="email"
                name="email"
                placeholder="E-mail address"
                disabled={isLoading}
                onChange={this.onChange}
            />
            <InputGroup.Addon>
                <Icon name="envelope" />
            </InputGroup.Addon>
        </InputGroup>
    </FormControl>
</FormGroup>
```

**Comment by simonguo** [comment]
One of the solutions: 
```
<InputGroup>
    <FormControl accepter={Input} />
    <InputGroup.Addon>
        <Icon icon="user" />
    </InputGroup.Addon>
</InputGroup>
```

**Comment by DovahBrownies** [comment]
@simonguo 
This doesn't work when properly a `ControlLabel` or a `HelpBlock` is added...

![image](https://user-images.githubusercontent.com/35106956/80573949-99ece780-8a09-11ea-9ffe-5cf9090bc6bb.png)
```
      <InputGroup>
        <FormControl {...props} />
        <InputGroup.Addon>
          <Icon icon='star' />
        </InputGroup.Addon>
      </InputGroup>
```

![image](https://user-images.githubusercontent.com/35106956/80574110-e6d0be00-8a09-11ea-8777-5a13ff876f5c.png)
```
      <InputGroup>
        <ControlLabel>LABEL</ControlLabel>
        <FormControl {...props} />
        <InputGroup.Addon>
          <Icon icon='star' />
        </InputGroup.Addon>
      </InputGroup>
```

Any advice?
