### ISSUE TITLE
Table data 无法动态赋值

### ISSUE THREAD

**Issue by lnstock** [rsuite/rsuite#485]
### Bug, feature request, or proposal:
Table 的 data，只能在一开始就设置，如果在componentDidMount里，读取服务端的数据后再用 setState 是无法刷新的

### What are the steps to reproduce?
    state = {
        data: []
    }
    componentDidMount() {
        this.setState({
            data: [{ id: 1, name: 'abc' }]
        })
    }

    render() {
        return (
            <Table data={this.state.data}>
                <Table.Column width={70} align="center" fixed>
                    <Table.HeaderCell>Id</Table.HeaderCell>
                    <Table.Cell dataKey="id" />
                </Table.Column>

                <Table.Column width={200} fixed>
                    <Table.HeaderCell>Name</Table.HeaderCell>
                    <Table.Cell dataKey="name" />
                </Table.Column>
            </Table>
        )
    }

**Comment by simonguo** [comment]
https://codesandbox.io/s/rsuite-table-init-61nm4    通过你提供的代码，我无法重现你的问题。

**Comment by lnstock** [comment]
找到问题了，我用的 react-scripts 是低版本的 1.0.17，而且 react 也是16版的。升级以后就好了。。
