### ISSUE TITLE
按钮禁用并设置 `[trigger="click"]` 时无法显示 `<Toolltip/>`

### ISSUE THREAD

**Issue by hiyangguo** [rsuite/rsuite#497]
### Bug, feature request, or proposal:
Bug

### What is the expected behavior?
按钮禁用并设置 `[trigger="click"]` 时无法显示 `<Toolltip/>`

### What is the current behavior?
与 `[trigger="hover"]` 时保持一致

### What are the steps to reproduce?

https://codesandbox.io/s/rsuite-hello-world-30-uvnyz

浏览器信息：Chrome  版本 74.0.3729.131（正式版本） （64 位）

**Comment by simonguo** [comment]
禁用后的按钮，不拥有事件操作，hover 也不行。
