### ISSUE TITLE
Panel 组件样式新增 overflow:hidden，导致页面显示不正常。

### ISSUE THREAD

**Issue by superman66** [rsuite/rsuite#500]
### Bug, feature request, or proposal:
Bug
### What is the expected behavior?
页面超出宽度后，依然能正确显示。

### What is the current behavior?

在该提交中：https://github.com/rsuite/rsuite/pull/439
`.rs-panel` 新增加了 `overflow:hidden` 属性，导致在使用 Picker 组件时页面超出 Panel 部分被隐藏。

**Comment by hiyangguo** [comment]
@superman66 这里的 `overflow:hidden` 是为了处理 `border-radius` 的问题。 详见 #445
