### ISSUE TITLE
table在移动端里面，表头不超过一屏还是会左右滑动10px

### ISSUE THREAD

**Issue by ps2qwert** [rsuite/rsuite#509]
### Bug, feature request, or proposal:
bug

### What is the expected behavior?
在移动端里面，表头很少可以一屏撑满的时候，不能左右滑动

### What is the current behavior?
在表头内容很少一屏能展示下的情况还是会左右滑动10px，体验不好
在 源码中发现var SCROLLBAR_WIDHT = 10;我写成0就好了，希望可以开放出来api

### What are the steps to reproduce?
使用Table组件在移动端打开
> Please fork this example, reproduce the problem you are issue.
> https://codesandbox.io/s/5vq6zo2z5l

**Comment by simonguo** [comment]
@ps2qwert  在移动端你说的这个问题，我们在最近的版本中考虑进去。
当然，也欢迎你给我们提 PR https://github.com/rsuite/rsuite-table
