### ISSUE TITLE
Table scroll problem

### ISSUE THREAD

**Issue by bear-c** [rsuite/rsuite#510]
### Bug:
I want to do unlimited scrolling loading.There are some problems.When I scroll down and start loading the data.The data is loaded.But the scroll bar is still at the bottom

### What is the expected behavior?

How can I get the scrollbar to return itself to the correct position, such as in the middle？

### What is the current behavior?

he scroll bar is always at the bottom

### What are the steps to reproduce?
https://codesandbox.io/s/priceless-swanson-xqoxv?fontsize=14

**Comment by simonguo** [comment]
```js
onScroll = (x, y) => {
    const { data } = this.state;
    let contextHeight = data.length * 46;
    let top = Math.abs(y);
    if (contextHeight - top - TableHeight < 200) {
      this.setState({ data: dataSource(data.length + 100) });
    }
};
```

Should be able to meet your feature.

https://codesandbox.io/s/rsuite-table-scroll-demo-4m55u

**Comment by bear-c** [comment]
@simonguo  Your code implementation is similar to mine。
I need the scroll bar to return to the specified position instead of always at the bottom
As you can imagine, when I scroll to the bottom, after loading the data.The scroll bar should then recalculate the height.Because the table component is not a native scroll bar.So it's always at the bottom

**Comment by simonguo** [comment]
This issue has been fixed, fixed version: v3.5.6

```
npm i rsuite-table@latest
```
Example:
https://codesandbox.io/s/rsuite-table-scroll-demo-f7ijm

**Comment by Reggino** [comment]
This issue has re-appeared since v3.9.4 .

**Comment by Reggino** [comment]
If found the fix, you can setc ```shouldUpdateScroll``` to ```false``` on the Table-component, but this information is missing in the general rsuitejs docs.
