### ISSUE TITLE
Disabling hover effect for table

### ISSUE THREAD

**Issue by ronnie152147** [rsuite/rsuite#512]
How do I disable the hover effect when mouse point on table row? 

I have tried to override with CSS but it did not take effect

Thanks

**Comment by simonguo** [comment]
```js
<Table hover={false} >
```

**Comment by ronnie152147** [comment]
I don't see it in the doc page for this props though. Thank you for your quick response

**Comment by simonguo** [comment]
Sorry, we will update the documentation.
