### ISSUE TITLE
Dropdown problem

### ISSUE THREAD

**Issue by Aleione** [rsuite/rsuite#518]
Hi, i have a problem with Dropdown component
this is my code (copied by rsuite docs default example):

[new 1.txt](https://github.com/rsuite/rsuite/files/3388997/new.1.txt)

this is my fontend result:

![image](https://user-images.githubusercontent.com/51761861/61174195-5372ed00-a59d-11e9-8d4d-eff62dc7cc8f.png)

according to docs, i should obtain default filed, that can open below other fields.

Why this?

**Comment by simonguo** [comment]
import 'rsuite/styles/less/index.less'; // or 'rsuite/dist/styles/rsuite.min.css'

**Comment by Aleione** [comment]
Now it is working. Thanks a lot. But at the beginning there was an arrow  to slide dropdown, after browser cleaning there is this rectangle:
![image](https://user-images.githubusercontent.com/51761861/61381718-c507af80-a8ab-11e9-811f-d1ee735847f9.png)

i try reinstall rsuite and arrow returns, but after a new browser clenaing arrow disappered and reinstalling rsuite doesnt' change nothing this time.

How should i do to restore arrow?

Thanks

**Comment by simonguo** [comment]
Check if your icon font file is loaded?
