### ISSUE TITLE
很多表单和input组件比如下拉组件 在ipad 的 360浏览器中(其他没测)，选择要素后没有自动关闭，需要点击其他的 select 才会关闭当前的

### ISSUE THREAD

**Issue by X-neuron** [rsuite/rsuite#519]
### What are the steps to reproduce?

> Please fork this example, reproduce the problem you are issue.
> https://codesandbox.io/s/5vq6zo2z5l

**Comment by simonguo** [comment]
@X-neuron  目前 rsuite 主要服务器桌面浏览器，移动端浏览器还没有计划适配。
