### ISSUE TITLE
Dropdown in Table not visible

### ISSUE THREAD

**Issue by peguerosdc** [rsuite/rsuite#522]
### Bug, feature request, or proposal:
Bug

### What is the expected behavior?
I have a Dropdown that is going to be opened when clicking on a cell with a defined width inside a Table and I expect to see the Dropdown to be shown "on top" of the Table displaying its content.

### What is the current behavior?
The Dropdown is being rendered "inside" the Cell of the Table, so it is not visible (see the element inside the cell):
<img width="1277" alt="droptable" src="https://user-images.githubusercontent.com/7889726/61602621-eea03e00-abff-11e9-8323-1f73f133522d.png">

### What are the steps to reproduce?
Create a Table and add a Dropdown to be displayed when clicking on a cell.
```js
<Table>
    {/*Some other columns*/}
    <Column width={40}>
        <HeaderCell/>
        <Cell>
            {rowData =>
                <Dropdown placement="leftTop"
                    renderTitle={ () => <IconButton appearance="link" icon={<Icon icon="ellipsis-v" />} size="sm" /> }>
                    <Dropdown.Item>Option 1</Dropdown.Item>
                    <Dropdown.Item>Option 2</Dropdown.Item>
                </Dropdown>
            }
        </Cell>
    </Column>
</Table>
```
### Please fork this example, reproduce the problem you are issue.
[Sandbox Example](https://codesandbox.io/s/rsuite-template-wz5nl)

**Comment by simonguo** [comment]
The cells of the table are height-limited and `overflow:hidden` is set, so using the dropdown menu directly will hide inside the cell.

Can be solved by combining `<Popover>` and `<Dropdown.Menu>`

https://github.com/rsuite/rsuite.github.io/blob/master/src/components/table/custom-cell.md

![image](https://user-images.githubusercontent.com/1203827/61603462-378fdb00-ac70-11e9-86c4-639856cb9aa9.png)

**Comment by peguerosdc** [comment]
Wow! Going through that example was such a journey! Thanks!

I have updated [my CodeSandbox link](https://codesandbox.io/s/rsuite-template-wz5nl) to include your solution in case someone finds it useful. I encapsulated all that `<Whisper>` stuff inside a component called `<PopoverDropdownMenu>` which only receives the `<Dropdown.Items>` to be displayed in the menu. Some important notes:

- I am calling `event.stopPropagation()` when clicking on a menu item because I had set the property `Table.onRowClick` and when I select an item of the menu, I don't want the `<Table>` to think I am **also** clicking on that Row.
- I got rid of storing the Table's `bodyRef` because that was causing the `<Dropdown>` to sometimes not being shown in the first or last cell as it was rendered inside the `<Table>` and it was chopped by its boundaries.

Still, I was planning to encapsulate it even more as my goal was to provide the cell to be shown to my `<Table>` depending on my use-case and I included everything inside another component called `CustomCellWithDropdown` which was going to handle the actions on the Menu (see my CodeSandbox implementation) and that didn't work. The cell is not displayed because it is rendered with width=0px.

Anyway, thank you very much for your support! To be honest, I think the implementation with the `<Popover>`+`<Whisper>` is too hacky and I prefer to take another approach to design my UI to avoid using it as I don't want to maintain that code in the future. I am closing this issue and I would suggest to flag this implementation as a possible enhancement in the future to make the use of a Dropdown+Table less painful 😊

**Comment by iggyZiggy** [comment]
I'm going down the same rabbit hole as @peguerosdc 
I also followed the example for custom cell and implemented the hacky and painful solution as Carlos suggested (thanks!) but i still can't get rid off these errors:

```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of OverlayTrigger which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
    in button (created by Button)
    in Button (created by defaultProps(Button))
    in defaultProps(Button) (created by withStyleProps(defaultProps(Button)))
    in withStyleProps(defaultProps(Button)) (created by IconButton)
    in IconButton (created by defaultProps(IconButton))
``` 

it pops up for: OverlayTrigger (button), Transition (popover) when using popover with dropdown menu

Considering the example in documentation is a bit old (not using hooks), can you update that example or at least suggest how to get rid of this error/warning?

Thanks

**Comment by simonguo** [comment]
@iggyZiggy 
Refer to a solution to a similar issue. https://github.com/rsuite/rsuite/issues/952.

And we have fixed it in the V5 version to be released. https://github.com/rsuite/rsuite/issues/1165
