### ISSUE TITLE
按照官网如何使用来

### ISSUE THREAD

**Issue by LuciferWZX** [rsuite/rsuite#524]
### Bug, feature request, or proposal:
按照官方文档来使用会报
./node_modules/rsuite/lib/DropdownMenu.js
Module not found: Can't resolve '@babel/runtime/helpers/objectWithoutPropertiesLoose' in '/Users/wuzhixin/Desktop/my/rsuiteWeb/node_modules/rsuite/lib'
yarn add @label/runtime也没有用

### What are the steps to reproduce?

> Please fork this example, reproduce the problem you are issue.
> https://codesandbox.io/s/5vq6zo2z5l

**Comment by simonguo** [comment]
重复的问题 ： https://github.com/rsuite/rsuite/issues/454
