### ISSUE TITLE
Dropdown 设置 toggleComponentClass={Button}，点击时背景色错误

### ISSUE THREAD

**Issue by superman66** [rsuite/rsuite#525]
### Bug, feature request, or proposal:

Bug

### What is the expected behavior?

点击时，表现出正常Button的点击效果

### What is the current behavior?

···

<Dropdown toggleComponentClass={Button} appearance="primary" title="title"/>
···
Dropdown 设置了 toggleComponentClass和 appearance ，点击时，缺少背景色 。

如截图：
![image](https://user-images.githubusercontent.com/12592949/61700234-f7635200-ad6e-11e9-8053-4cae556566ce.png)

![image](https://user-images.githubusercontent.com/12592949/61700089-b0755c80-ad6e-11e9-8c9b-3ff75f538d65.png)

### What are the steps to reproduce?

> Please fork this example, reproduce the problem you are issue.
> https://codesandbox.io/s/5vq6zo2z5l

**Comment by simonguo** [comment]
![image](https://user-images.githubusercontent.com/1203827/63340823-7b165b80-c37a-11e9-9e17-cfdcc6073292.png)
cc @hiyangguo
