### ISSUE TITLE
Shift click to select/de-select multiple rows in rsuite table

### ISSUE THREAD

**Issue by ronnie152147** [rsuite/rsuite#537]
I am trying to implement shift-click features to select / de-select multiple rows but I couldn't get the event from onRowClick.

Is there any other way to do that and if so, any sample for it?

**Comment by simonguo** [comment]
Added the `event` parameter to `onRowClick`. Will be released later
```diff
- onRowClick: (rowData: RowData) => void;
+ onRowClick: (rowData: RowData, event: React.SyntheticEvent<any>) => void;
```
https://github.com/rsuite/rsuite-table/pull/89/files#diff-a9710bc15e6ac188260e9a3a279689a9L904

**Comment by bennihoss** [comment]
I just needed this event, too, what a coincidence that you just implemented it 5 hours ago. Thanks ;)
