### ISSUE TITLE
global component's className prefix, rs- Bug

### ISSUE THREAD

**Issue by Temkit** [rsuite/rsuite#539]
### Bug, feature request, or proposal:

Bug

### What is the expected behavior?

Global component's className prefix change with no bug

### What is the current behavior?

as you can find in the repo,[Github](https://github.com/Temkit/rsuitejs-nextjs-example) i added in static/theme/custom-theme.less

> @ns: yet-;

and in next.config.js

> config.plugins.push(
>         new webpack.DefinePlugin({
>           __RSUITE_CLASSNAME_PREFIX__: JSON.stringify("yet-")
>         })
>       );

The global component's className prefix has changed and some of component are working good, but i have some ugly style with console error : 

> index.js:1 Warning: Prop `className` did not match. Server: "rs-navbar-header" Client: "yet-navbar-header"

I have also in other projects : 

> index.js:1 Warning: Prop `className` did not match. Server: "rs-icon rs-icon-building" Client: "yet-icon yet-icon-building"

the prefix has changed and everything else is well styled with no problem

<img width="1280" alt="Capture d’écran 2019-08-04 à 18 18 53" src="https://user-images.githubusercontent.com/13275723/62427021-8021ac80-b6e4-11e9-9824-5f4ef6546550.png">
<img width="1280" alt="Capture d’écran 2019-08-04 à 18 18 10" src="https://user-images.githubusercontent.com/13275723/62427022-8021ac80-b6e4-11e9-8b5b-ae6581164ca2.png">
 

### What are the steps to reproduce?

here is the repo that reproduces the BUG 
[Github](https://github.com/Temkit/rsuitejs-nextjs-example)

**Comment by simonguo** [comment]
Add the following code to server.js : 
``` diff
const app = next({ dev });
const handle = app.getRequestHandler();

+ global.__RSUITE_CLASSNAME_PREFIX__ = "yet-";

```

**Comment by Temkit** [comment]
worked !  thanks.
