### ISSUE TITLE
Bug Report: Slider does not update its value, under Accordion PanelGroup

### ISSUE THREAD

**Issue by praisethemoon** [rsuite/rsuite#541]
Hello, I really love this library so far! I migrated my project from antd to rsuite and no regrets so far. I came a cross a bug however, here is the description:

### Bug, feature request, or proposal:
Bug report

### What is the expected behavior?
Slider's state would update to the actual selected value

### What is the current behavior?
Slider value jumps to max, and never changes again. `onClick` Event triggers successfully, with the max value as given argument.

### What are the steps to reproduce?

- Create PanelGroup, `accordion` on,
- Add panels, with sliders in them
- RIP sliders. Their value moves directly to `max` and never changes

Redo the same process, with `accordion` off, sliders works fine 🎩 

Forked example: [https://codesandbox.io/s/rsuite-template-zjzfk](https://codesandbox.io/s/rsuite-template-zjzfk)

**Comment by simonguo** [comment]
The cause of this problem is that the Panel does not correctly calculate the relative position of the component when it is closed.
The temporary way to solve this problem is to update `Slider` after the animation of the Panel is finished.

We will fix it later.

```diff
function App() {
+ const sliderRef = React.createRef();
+ const handleEntered=()=>{
+    sliderRef.current.updateBar();
+ }
  return (
    <div className="App">
      <PanelGroup accordion >
-       <Panel header="NANI?" key={1} id={1} >
-         <Slider min={0} max={100} defaultValue={50}/>
+       <Panel header="NANI?" key={1} id={1} onEntered={handleEntered}>
+         <Slider min={0} max={100} defaultValue={50} ref={sliderRef}/>
        </Panel>
      </PanelGroup>
    </div>
  );
}
```
Example : https://codesandbox.io/s/rsuite-template-37yts
