### ISSUE TITLE
Form Elements OnBlur & OnFocus

### ISSUE THREAD

**Issue by bennihoss** [rsuite/rsuite#559]
### Bug/feature request
I want to combine your UI-Framework with React Final Form, but i have issues to get the right meta data like  "touched" for the form elements, because most of the form elements doesn't implement onBlur & onFocus.
I found a similar issue, where i saw, that Input implements them, but on the other form elements they are not properly implemented.

### What is the expected behavior?
onBlur & onFocus should work properly on all form elements, like on Input.

### What is the current behavior?
InputNumber only triggers onFocus, other form elements doenst trigger any of that event.

### What are the steps to reproduce?
I didn't include all Form Elements, but i think it should be clear, which problem i mean.
https://codesandbox.io/embed/rsuite-input-events-myx61

**Comment by simonguo** [comment]
This issue will be fixed in the rsuite v4 release.
