### ISSUE TITLE
Rsuite fade CSS crashes with Bootstrap 4

### ISSUE THREAD

**Issue by ronnie152147** [rsuite/rsuite#582]
In Rsuite it uses .fade/fade in to trigger show/hide picker.

However in Bootstrap 4, it uses .fade .show/.fade:not(.show) for fade effect.

Is there any chance that rsuite component can avoid using the same className? Or any workaround on this?

**Comment by j-gurda** [comment]
Hello,

the rather ugly but working workaround from me in my use case (just want to use some components having other components styled with Bootstrap 4) is to copy only relevant classes from `rsuite/dist/styles/rsuite-default.css` to some custom CSS file. Then I don't need to import the whole `rsuite-default.css` that actually breaks Bootstrap 4 modal in my project.

**Comment by Saud-AlBallaa** [comment]
Thank you Mr. Simongou, any idea how much will take to solve this, because I almost finish my project and I really need the component
