### ISSUE TITLE
How to use React-Router with Nav components

### ISSUE THREAD

**Issue by dvriv** [rsuite/rsuite#60]
### Bug, feature request, or proposal:
Question

I am trying to create a Nav, what would be to best way to use the `<Link>` component from react-router or how to implement react-router navigation links?

I tried making `<Nav.Item>` a child of `<Link>` but doesn't work.
Making `<Link>` a child of `<Nav.Item>` does work but the link is smaller and you shouldn't nest anchor elements

 Not sure if is correct for me to ask those questions here, if is wrong please tell me. Thanks

**Comment by simonguo** [comment]
@dvriv 

The `<Nav.Item>` has a `componentClass` attribute, which is set to `Link`.
Then you can use all the props of `Link` in `<Nav.Item>`.

```html
<Nav.Item componentClass={Link} to="/home">Home</Nav.Item>
```

**Comment by dvriv** [comment]
Ohh that works perfect! Thank you

**Comment by sabarasaba** [comment]
@simonguo could it be that this doesnt work with react-router 4 ? 

```
<Sidenav.Body>
  <Nav>
    <Nav.Item componentClass={Link} to="/">Home</Nav.Item>
    <Nav.Item componentClass={Link} to="/users">Users</Nav.Item>
  </Nav>
</Sidenav.Body>
```

**Comment by bschrenk** [comment]
Just in case anyone finds this looks like **componentClass** was renamed to **as** in a newer version of rsuite.

So it should look like the below in new versions.

[Rsuite V5 vs V4 rename ComponentClass](https://rsuitejs.com/guide/v5-features/#rename-the-code-component-class-code-property-of-all-components-to-code-as-code
)

```
<Sidenav.Body>
  <Nav>
    <Nav.Item as={Link} to="/">Home</Nav.Item>
    <Nav.Item as={Link} to="/users">Users</Nav.Item>
  </Nav>
</Sidenav.Body>
```
