### ISSUE TITLE
CORS problems when fetching icons from CDN

### ISSUE THREAD

**Issue by Ericnr** [rsuite/rsuite#600]
I am blocked by CORS when trying to render icons. [imgur link](https://imgur.com/a/O09tONe). I just downloaded the lib, so I might be missing something.

**Comment by simonguo** [comment]
You try to use local fonts

### How to configure font files locally?

The icon font files used in React Suite are deployed in [jsDelivr CDN](http://cdn.jsdelivr.net/npm/rsuite-icon-font@3.0.0/fonts/),
If you want to deploy locally, you need to modify the path to the icon font:

```less
@icon-font-path: './fonts';
```

In addition, you will also need to configure `url-loader` in webpack to load icon font files, webpack 4 configuration example:

```js
{
  test: /\.(woff|woff2|eot|ttf|svg)($|\?)/,
  use: [
    {
      loader: 'url-loader',
      options: {
        limit: 1,
        size: 16,
        hash: 'sha512',
        digest: 'hex',
        name: '[hash].[ext]',
        publicPath: '/'
      }
    }
  ]
}
```
https://rsuitejs.com/en/guide/themes#How%20to%20configure%20font%20files%20locally?

**Comment by Ericnr** [comment]
Well I don't think it'd be interesting to eject from CRA just for this, so that's too bad. Still very strange I'm getting CORS issues from a CDN

**Comment by hiyangguo** [comment]
@Ericnr  I'm so sorry for this problem at the first. You can see :
![image](https://user-images.githubusercontent.com/15609339/64579815-c12d7080-d3b6-11e9-9d35-8ed2ef57e447.png)
This request already set the `access-control-allow-origin: *` , so it  should loaded font file successful. 
This error info is very strange , can you provide a example on [codesandbox](https://codesandbox.io/s/k9v972q3lr) for us? 
Thank you very much.

**Comment by Ericnr** [comment]
Welp, it is working now and I didn't change anything so it is all good!
