### ISSUE TITLE
[feature request] add <ColorPicker> to # Data Entry

### ISSUE THREAD

**Issue by cXiaof** [rsuite/rsuite#602]
### feature request: \<ColorPicker\>

We hope to add a color selector (uncontrolled/controlled) to Data Entry, which like the color bock in tool: palette. Click on the color block to pop up a small window to select the color.

I know that it can be implemented with third-party components such as react-color, but if it is used in Form components, there will be more trouble, synchronization / controlled uncontrolled / style unification, need to be resolved.

So if the palette has been implemented in the tool, is it convenient to make the extraction part of the palette into <ColorPicker\> as one of the Data Entry components, which is more convenient to use with other components.

Thank you

希望加一个颜色选择器(非受控/受控)到Data Entry里，可以如工具:调色板中的色块那样显示颜色，点击色块弹出一个小窗可以选择颜色。

我知道这个功能可以用第三方组件如react-color来实现，但是如果是用在Form组件里会有更多的像值的同步/受控非受控/样式的统一等问题需要考虑。

所以如果在工具中已经实现了调色板的功能的话，不知道是不是方便把调色板的功能抽取部分做成\<ColorPicker\>作为Data Entry组件中的一种，来更便捷得和其他组件一起使用。

谢谢

**Comment by simonguo** [comment]
ColorPicker  我更推荐用 rsuite 的 [extensions](https://rsuitejs.com/en/extensions) 方式去做。如果你对此感兴趣的，不妨通过 rsuite 的 UI 封装一个 react-color 组件，我们将收纳到 extensions 中。

例如 [MultiDatePicker](https://github.com/rsuite/multi-date-picker) 就是通过 DatePicker 封装的组件。预览地址：https://rsuite.github.io/multi-date-picker/
