### ISSUE TITLE
How do I load another component directly  into the nav item (tab) ?

### ISSUE THREAD

**Issue by sh4msi** [rsuite/rsuite#604]
Hello
How do I load another component directly  into the nav item (tab) ?
Please write an example that I can run

i use : rsuite 4.0.0

**Comment by simonguo** [comment]
I am not very clear about your needs, can this component solve your problem?

https://rsuite.github.io/responsive-nav/

**Comment by sh4msi** [comment]
I want to load the component that,  when I click on the Nav Item

Like this (but it doesn't work)
`<Nav.Item  children={<MyComponent/>}  eventKey="general">General</Nav.Item>`

**Comment by simonguo** [comment]
```jsx
const TabContent = ({ activeKey }) => {
  if (activeKey === 'general') {
    return <GeneralComponent />;
  }

  if (activeKey === 'about') {
    return <AboutComponent />;
  }
};

function render() {
  const [activeKey, setActiveKey] = React.useState();
  return (
    <div>
      <Nav
        appearance="tabs"
        onSelect={eventKey => {
          setActiveKey(eventKey);
        }}
      >
        <Nav.Item eventKey="general">General</Nav.Item>
        <Nav.Item eventKey="about">about</Nav.Item>
      </Nav>
      <TabContent activeKey={activeKey} />
    </div>
  );
}
```

**Comment by sh4msi** [comment]
Thanks for solving my problem

What exactly does the children(prop)  do?
Can't render it with this other component?
Could you give me an example?

**Comment by simonguo** [comment]
In your example, `General` is children.  I suggest you learn about `React`.
```
<Nav.Item children={<MyComponent/>} eventKey="general">General</Nav.Item>
```

**Comment by SevenOutman** [comment]
@sh4msi Learn more about `props.children` in React on its [official documentation site](https://reactjs.org/docs/jsx-in-depth.html#children-in-jsx).

**Comment by sh4msi** [comment]
> In your example, `General` is children. I suggest you learn about `React`.
> 
> ```
> <Nav.Item children={<MyComponent/>} eventKey="general">General</Nav.Item>
> ```

:)
I mean the children property
`children *  ---  React.Node --- The contents of the component`
 Well I used it but didn't get the result so I wanted to write an example

**Comment by SevenOutman** [comment]
@sh4msi
```
<Nav.Item>
  <MyComponent />
</Nav.Item>
```

Unlike other props, children is assigned this way instead of passing through the opening jsx tag.
