### ISSUE TITLE
How can I include the dark theme css file?

### ISSUE THREAD

**Issue by sickdyd** [rsuite/rsuite#607]
### Bug, feature request, or proposal:

I am working on a project made with `create-react-app`. I installed rsuite with `npm install rsuite`.

I'm following the documentation: https://rsuitejs.com/en/guide/themes

I would like to use the dark theme in my project, but I can't find the following file:

`@import '~rsuite/dist/styles/rsuite-dark.css';`

The file I'm currently including is: import 'rsuite/dist/styles/rsuite.min.css';

### What is the expected behavior?

I'd like to know how to include the dark theme css file.

### What is the current behavior?

I can't find the dark theme css file.

### What are the steps to reproduce?

> Please fork this example, reproduce the problem you are issue.
> https://codesandbox.io/s/5vq6zo2z5l

In the sandbox it seems to work fine.

**Comment by simonguo** [comment]
I can't reproduce the problem you said, you can refer to this example:

https://github.com/rsuite/examples/blob/master/create-react-app/src/App.js#L10

**Comment by sickdyd** [comment]
The dark style file is not present in node_modules/rsuite/dist/styles/ and I'm not sure why.

All I have is this:
![shot](https://user-images.githubusercontent.com/45290018/64668711-8fd9a100-d499-11e9-819e-9ae5af129f83.png)

**Comment by simonguo** [comment]
Which version of rsuite do you use?

**Comment by sickdyd** [comment]
"rsuite": "^3.8.8"

**Comment by simonguo** [comment]
Upgrade rsuite to 4.0.0

**Comment by sickdyd** [comment]
Thank you, that fixed the issue. Out of curiosity, when was the version 4.0.0 released? I started using rsuite just a few weeks ago, so I didn't realize there would have been an update already.

**Comment by simonguo** [comment]
https://github.com/rsuite/rsuite/releases/tag/4.0.0
https://medium.com/rsuite/react-suite-4-0-release-b702f70ff38b
