### ISSUE TITLE
when I change the height of the big data table tree frequently,The table can't remember scroll bar position

### ISSUE THREAD

**Issue by menglyf** [rsuite/rsuite#618]
### Bug, feature request, or proposal:
1.当表格高度200的时候，把纵向滚动条移动到最下方，然后点击按钮改变表格高度，此时滚动条会回到最顶部。
2.改变表格高度前，横向滚动条移动到最右边，点击按钮改变表格高度，此时滚动条回到最左边

### What is the expected behavior?
滚动条位置不变

### What are the steps to reproduce?

> Please fork this example, reproduce the problem you are issue.
> https://codesandbox.io/s/rsuite-hello-world-30-wcy8m

**Comment by simonguo** [comment]
- 问题1 产生的原因是 scrollTop 的超出了滚动范围所有被重置。
- 问题2 产生的原因是 Table 做了一次 resize 导致 横向滚动条重置。

问题 2 可以解决，问题 1 需要再想想。

**Comment by menglyf** [comment]
@simonguo 麻烦问下是否可以提供一下问题2目前的解决方案。

**Comment by simonguo** [comment]
@menglyf 你不需要做什么，我需要改进一下代码，到时候你更新一下版本号。

**Comment by menglyf** [comment]
@simonguo 多谢！请问有组件交流群吗？加入群沟通方便些

**Comment by simonguo** [comment]
https://github.com/rsuite/rsuite/blob/master/README_zh.md#%E6%94%AF%E6%8C%81-react-suite

**Comment by simonguo** [comment]
已修复
```
npm i rsuite@latest
```
