### ISSUE TITLE
表格合并单元格，无法自定义render内容

### ISSUE THREAD

**Issue by zhangyoof** [rsuite/rsuite#619]
### Bug, feature request, or proposal:
表格合并单元格，无法自定义render内容

### What is the expected behavior?
可以自定义

### What are the steps to reproduce?
firstName和lastName合并，lastName自定义render无法显示

> Please fork this example, reproduce the problem you are issue.
> https://codesandbox.io/s/rsuite-hello-world-30-l0ttq

**Comment by simonguo** [comment]
你写的代码中有两个问题：

1.span 不应该有 value 属性
2.单元格 colSpan 合并的规则是通过 `dataKey` 绑定的值来判断。

```diff
- <Cell>{rowData => <span value={rowData.lastName} />}</Cell>
+ <Cell dataKey="lastName">{rowData => <span>{rowData.lastName}</span>}</Cell>
```

**Comment by menglyf** [comment]
@simonguo 之前这里render的是input标签，改了标签以后忘记改属性。

> 当 lastName 对应列的值为 null 或者 undefined 的时候，则会被 firstName 列合并
我们想要的是：合并的两列分别去渲染两个input，但是当lastName为null/undefined的时候，只会渲染一个单元格。附带连接中打印了id，可以看到，lastName为null/undefined没有打印
