### ISSUE TITLE
Dropdown bug under IE11

### ISSUE THREAD

**Issue by 13120926828** [rsuite/rsuite#620]
### Bug, feature request, or proposal:
1. The dropdown component under IE when click Menu Item and then it appears."Unable to find node on an unmounted component".
2. I hope when i right click the dropdown panel will disappear.

Thank you.

### What is the expected behavior?
resolve these bugs.

### What are the steps to reproduce?

> Please fork this example, reproduce the problem you are issue.
> https://codesandbox.io/s/5vq6zo2z5l

**Comment by simonguo** [comment]
Fixed in the latest version
```
npm i rsuite@latest
```
