### ISSUE TITLE
访问官网有时会莫名奇妙地报404

### ISSUE THREAD

**Issue by Xezzon** [rsuite/rsuite#623]
### Bug, feature request, or proposal:
Bug

### What is the current behavior?
锚点跳转有时候会404，直接从地址栏访问基本都是404。但是两者的404还不太一样。直接访问得到的404如下图：![Snipaste_2019-09-20_08-25-35.png](https://i.loli.net/2019/09/20/QeA7WgpZ5Kh36qP.png)

### What are the steps to reproduce?

> Please fork this example, reproduce the problem you are issue.
> https://codesandbox.io/s/5vq6zo2z5l

**Comment by simonguo** [comment]
不好意思，为了提高国内的访问速度，昨天把国内访问都解析到了 gitee pages 的服务器，但他们服务在支持 SPA的时候有个bug，他们今天会解决。

**Comment by simonguo** [comment]
已修复
