### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by Xezzon** [rsuite/rsuite#624]
### Bug, feature request, or proposal:
Feature

### What is the expected behavior?
- Timeline的双列与横向
- 提供Table的Filter和Searcher接口
- Carousel（轮播）、Card（卡片。Antd或者Material那种，做人物简介很好用）

### What are the steps to reproduce?

> Please fork this example, reproduce the problem you are issue.
> https://codesandbox.io/s/5vq6zo2z5l

**Comment by simonguo** [comment]
- Timeline 新特性 和 Card， @hiyangguo  需要和设计师 @LeightonYao 讨论一下，设计上以及组件化必要性。
- Table 数据的过滤是通过对 data 操作，去驱动渲染，为了组件的灵活性，这个需要你自己去通过rsuite 提供的组件去组合实现。 参考设计如下：
![image](https://user-images.githubusercontent.com/1203827/65293529-1d01b180-db8e-11e9-897e-7daba0a69b52.png)
- Carousel 在计划中。
