### ISSUE TITLE
table出现空白

### ISSUE THREAD

**Issue by menglyf** [rsuite/rsuite#629]
### Bug, feature request, or proposal:
bug

### What is the expected behavior?
正常显示

### What is the current behavior?
先把纵向滚动条向下滚动一点，此时点击按钮将表格高度变高，会出现空白
**此bug出现在rsuite-table@3.5.7,此版本(3.5.7)修复了issue618,3.5.6版本不会出现**

### What are the steps to reproduce?

> Please fork this example, reproduce the problem you are issue.
> https://codesandbox.io/s/rsuite-scroll-bar-8cwgt

**Comment by zhangjiany2929** [comment]
你好，我也在表格滚动中遇到了类似的问题，我的问题在这个环境下也能够复现：
https://codesandbox.io/s/rsuite-scroll-bar-8cwgt
具体步骤如下：
1.数据加载完成后，向下滚动找到address-1节点
2.收起address-1节点

### What is the expected behavior?
滚动条位置保持不变

### What is the current behavior?
滚动条会回到页面顶端

**Comment by simonguo** [comment]
@menglyf  问题已经修复，待发布。

@zhangjiany2929  你描述的这个问题产生的原因是，点击收起树节点的时候，你当前滚动条手柄的位置已经超出了表格纵向滚动的最大值，所以产生了一次滚动条重置。

有一种解决办法就是让滚动条重置在最底部。

**Comment by zhangjiany2929** [comment]
@simonguo 相比重置在顶部，可能把滚动条重置在底部比较符合一般用户的习惯，因为这样离之前列表位置最接近。我看了下antd里面的表格也是这样处理的。我们能否也这样处理？

**Comment by simonguo** [comment]
@zhangjiany2929 可以

**Comment by zhangjiany2929** [comment]
@simonguo 请问这个是我自己可以处理呢，还是只需等待rsuite下一个版本发布？

**Comment by simonguo** [comment]
等下一个版本，这两天就会发布
