### ISSUE TITLE
<Tree> 建议 支持拖拽功能

### ISSUE THREAD

**Issue by Link-Kou** [rsuite/rsuite#630]
<Tree> 建议 支持拖拽功能

**Comment by simonguo** [comment]
@superman66  通过 react-dnd 添加一个示例。 可以做到 [extensions](https://rsuitejs.com/en/extensions)

**Comment by Link-Kou** [comment]
@superman66  @simonguo  等了好些日子了。能否给个示列，辛苦辛苦了

**Comment by superman66** [comment]
@Link-Kou 已经开发好了，等待UI给出设计稿，调整样式后就可以了。
预计下周会发布。

**Comment by Link-Kou** [comment]
@superman66   期待发布。 辛苦大佬开发，这里给您上香膜拜

**Comment by Link-Kou** [comment]
@superman66  大神什么时候发布！等到花儿都谢了...........
