### ISSUE TITLE
rsuite issue 模板提供的地址代码有误

### ISSUE THREAD

**Issue by hiyangguo** [rsuite/rsuite#639]
### Bug, feature request, or proposal:

![image](https://user-images.githubusercontent.com/15609339/65588742-9f3d0c00-dfba-11e9-92b6-e359537c32e1.png)

地址为：https://codesandbox.io/s/5vq6zo2z5l

### What are the steps to reproduce?

> Please fork this example, reproduce the problem you are issue.
> https://codesandbox.io/s/5vq6zo2z5l

**Comment by simonguo** [comment]
已修复
