### ISSUE TITLE
Cascader 设置受控后仍然可以切换 value

### ISSUE THREAD

**Issue by hiyangguo** [rsuite/rsuite#640]
### Bug, feature request, or proposal:
Cascader 设置受控后仍然可以切换 value

### What is the expected behavior?
设置 value 后，value 没改变，`<ToggleButton>` 的值应该始终不变

### What is the current behavior?
设置 value 后，value 没改变，点击`item`  后，`<ToggleButton>` 的值变成了点击的`item` 的值

### What are the steps to reproduce?

https://codesandbox.io/s/rsuite-template-2nlv7

**Comment by simonguo** [comment]
你示例中提供的：
```
<Cascader data={data} style={{ width: 224 }} value={["1"]} />;
```
Cascader 是应用于单选，value 的值不应该是数组。 

还是说你的问题和示例不匹配？

**Comment by hiyangguo** [comment]
示例有误应该为 
```
<Cascader data={data} style={{ width: 224 }} value={"1"} />;
```
