### ISSUE TITLE
建议 ： <Tree> 对DataItemType类型添加一个Expanded属性

### ISSUE THREAD

**Issue by Link-Kou** [rsuite/rsuite#642]
场景：

<Tree> 动态添加的子节点，默认是非展开的。
接管expandItemValues 属性需要实现比较复杂的展开控制。

建议：
添加Expanded属性后，可以在动态添加子节点的时候就可以轻松控制是否展开

**Comment by simonguo** [comment]
同时存在 expandItemValues 和 expanded 的时候会带来跟大的复杂度。

expandItemValues 是平衡后相对较方便的解决方案，如果在受控的情况下，你要操作节点展开，通过expanded 的方式会频繁操作 data 对象。
