### ISSUE TITLE
Modal 与 Tabel 配合，表格列Fixed后拖异常

### ISSUE THREAD

**Issue by Link-Kou** [rsuite/rsuite#649]
![image](https://uploads.codesandbox.io/uploads/user/54d06f4d-17b5-465c-83df-cb94c7484cde/-bzn-2019-09-26_16-54-35%20(1).gif)

代码:
https://codesandbox.io/s/cocky-liskov-kb60c?fontsize=14

**Comment by simonguo** [comment]
无法复现
