### ISSUE TITLE
Datepicker format issue

### ISSUE THREAD

**Issue by rajeshyogeshwar** [rsuite/rsuite#654]
### Bug, feature request, or proposal:
DatePicker component allows configuration of the date format. I keyed in **DD-MM-YYYY** as the desired format. The date post selection does appear in the provided format. But the header section still shows date in default format.

### What is the expected behavior?
The header section should respect the provided format option.

### What is the current behavior?
The header section of DatePicker component is not displaying the date as per the format.

### What are the steps to reproduce?
Define a component in form like below
```
<FormControl
 block={true}
 name="startDate"
 accepter={DatePicker}
 format="DD-MM-YYYY"
 limitEndYear={0}
 oneTap={true}
 placeholder="eg. 18-09-1991"/>
```

![screenshot-localhost_3000-2019 09 29-11_05_35](https://user-images.githubusercontent.com/7311146/65829676-64421d80-e2c5-11e9-868f-024956d7dffb.png)

**Comment by simonguo** [comment]
The reason why the `format` parameter cannot be directly formatted in the Header is because the user can pass `YYYY-MM-DD HH:ss:mm`.

Additional prop may be required if the header needs to be customizable.

**Comment by rajeshyogeshwar** [comment]
Is there any plan for adding such a prop? In my opinion it will add consistency to the component. Also, if we can set a lower boundary for year eg. 1900 so that the component can be limited to it would be a brilliant addition. Let me know your thoughts on it.

**Comment by simonguo** [comment]
We will plan to improve this feature.
What do you think if I put this feature in an international configuration?

**Comment by rajeshyogeshwar** [comment]
If my understanding goes correct about the internalisation configuration if you put it will setup the format as per the locale. In most of the cases it will be a desired behaviour. 
But, if there is a requirement where in someone has to format the date which doesn't match with provided locale then the developer will be stuck. Hence, I think you can look at utilising the `format` prop for the same and match the header format to specified prop. It will require minimal configuration from a developer. 
In addition to this, your idea about international configuration is very valid and you should still make that as an enhancement.

**Comment by rajeshyogeshwar** [comment]
Should I be expecting this enhancement to go in 4.0.3?

**Comment by simonguo** [comment]
Yes. I plan to solve this problem also in version 4.0.3.

**Comment by simonguo** [comment]
@rajeshyogeshwar 
https://github.com/rsuite/rsuite/pull/668 Did this PR solve your problem?

**Comment by rajeshyogeshwar** [comment]
It does solve my issue. Thanks a lot.

**Comment by rajeshyogeshwar** [comment]
@simonguo One other thing that was missed is the format in the tooltip. I think that needs to be taken care of as well.

![Screenshot from 2019-10-18 18-01-03](https://user-images.githubusercontent.com/7311146/67094537-af1ec900-f1d1-11e9-8b05-7924ce2a5d7d.png)
