### ISSUE TITLE
Slider doesn't work well on mobile

### ISSUE THREAD

**Issue by pegasus1982** [rsuite/rsuite#657]
Slider is working well on desktop browser.
However, when I try to test it on mobile browser, it don't work quite well.

Pressing any position on slider bar is working,
But when I try to drag and slide handle, it doesn't move as my touch event.

I hope this will be solved.

**Comment by simonguo** [comment]
Sorry, all of rsuite's current components are primarily for desktop browsers. Not recommended for use on mobile browsers.
