### ISSUE TITLE
Tooltip on disabled Buttons

### ISSUE THREAD

**Issue by bennihoss** [rsuite/rsuite#658]
###  feature request / bug:
Don't know if that is on purpose, but if you put a tooltip around a disabled button, the tooltip don't appear.

### What is the expected behavior?
On disabled buttons, it would be nice to show, why the button is disabled, so a tooltip would be nice on them.

### What is the current behavior?
No tooltip on disabled buttons, enabled buttons are no problem.

### What are the steps to reproduce?
https://codesandbox.io/embed/rsuite-template-8qpes

**Comment by simonguo** [comment]
Disabled buttons will not have a response event and are intentionally designed.

**Comment by hiyangguo** [comment]
![image](https://user-images.githubusercontent.com/15609339/66545646-bdd00500-eb6d-11e9-8ae7-ac07418ad306.png)
I saw this implementation on github . Maybe you can consider this suggestion.

**Comment by simonguo** [comment]
Elements with the disabled attribute aren’t interactive, meaning users cannot hover or click them to trigger a popover (or tooltip). As a workaround, you’ll want to trigger the overlay from a wrapper <div> or <span> and override the pointer-events on the disabled element.

```jsx
<Whisper
  trigger="click"
  speaker={<Tooltip id="tooltip-disabled">Tooltip!</Tooltip>}
>
  <span className="d-inline-block">
    <Button disabled style={{ pointerEvents: "none" }}>
      Disabled button
    </Button>
  </span>
</Whisper>
```

**Comment by dan-dr** [comment]
the workaround mentioned isn't working...
