### ISSUE TITLE
Feature request: <IntlProvider> auto detects locale when used with react-intl

### ISSUE THREAD

**Issue by SevenOutman** [rsuite/rsuite#66]
### Feature request: `<IntlProvider>` auto detects `locale` when used with `react-intl`

RSuite's `<IntlProvider>` should automatically detect locale when `locale` is not set and `react-intl`'s `<IntlProvider>` is one of its parents.

#### Example
```jsx
import { IntlProvider } from 'react-intl';
import { IntlProvider as RsIntlProvider } from 'rsuite';

const App = ({ children }) => (
  <IntlProvider locale=“zh-CN”>
    <RsIntlProvider>
      {children}
    </RsIntlProvider>
  </IntlProvider>
);
```
In the example code above, `<RsIntlProvider>` does not explicitly receive a `locale` prop. It should know that the current locale used by upper-scope `react-intl` is `'zh-CN'`, thus invoke `rsuite/lib/IntlProvider/locales/zh_CN` as its `locale` value.

#### How are locale string values mapped to RSuite's locale packs?
[BCP 47](http://www.ietf.org/rfc/bcp/bcp47.txt) language tag should work. [As explained in MDN](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/language), `navigator.language` API uses BCP 47, so it can be regarded as standard in browser scenarios. Besides, `react-intl` is also using `navigator.language` [in its docs](https://github.com/yahoo/react-intl/wiki#formatting-data), so it's probably using BCP 47 as well.

**Comment by simonguo** [comment]
However, this requires that all language configuration files be included by default. Caused the file to be too large.

**Comment by SevenOutman** [comment]
closed due to inactivity
