### ISSUE TITLE
open on <DropDown>

### ISSUE THREAD

**Issue by konsumer** [rsuite/rsuite#661]
### Bug, feature request, or proposal:

The `open` prop on `DropDown` doesn't seem to work.

### What is the expected behavior?

I expect that `open` would allow me to force a dropdown to be open. Alternatively, if `Nav` let me me open the menu with `activekey`, I could work around it, but that doesn't seem to work either.

### What is the current behavior?

I am creating a tree-like menu with sections, and I can derive the state of the menu from the current path. Even though `active` works, `open` does not.

### What are the steps to reproduce?
I have a system like this:

```jsx
<Nav>
  {Object.keys(categories).map((cat, c) => {
    const k = activeNavKey(currentPath, cat)
    return (
      <Dropdown open={k} active={k} key={c} eventKey={cat} title={categories[cat]}>
        {Object.keys(pages[cat]).map((page, p) => <Dropdown.Item eventKey={page} key={p} href={`/${page}`}>{pages[cat][page].title}</Dropdown.Item>)}
      </Dropdown>
    )
  })}
</Nav>
```
* `pages` is a big object with all my pages, categorized by menu
* `activeNavKey` returns boolean, based on which category is `open`
* `active` is working, but not `open`

[Here](https://codesandbox.io/s/rsuite-template-u6bj1) is my example, using hookrouter & your doc-categories. If you refresh the page with something selected, you can see that it doesn't `open` the menu, but it does make it `active`.

On a fresh-page-load, it should look like this:

![Screenshot from 2019-10-05 15-49-44](https://user-images.githubusercontent.com/83857/66261745-e0d27180-e787-11e9-861d-534dec499097.png)

but instead it looks like this:

![Screenshot from 2019-10-05 15-49-32](https://user-images.githubusercontent.com/83857/66261750-f778c880-e787-11e9-8f95-302b6af04ee9.png)

**Comment by simonguo** [comment]
`Sidenav` supports expanding nodes with `defaultOpenKeys` and `openKeys` properties.

```jsx
<Sidenav appearance="inverse" expanded defaultOpenKeys={['general','navigation']}>
    <Sidenav.Body>
        <FancyMenu />
    </Sidenav.Body>
</Sidenav>
```

**Comment by konsumer** [comment]
That's perfect! Thanks @simonguo. I made a [new sandbox](https://codesandbox.io/embed/rsuite-template-ckb5d) to illustrate for others.
