### ISSUE TITLE
[V4.1]: Enhance Timeline 

### ISSUE THREAD

**Issue by simonguo** [rsuite/rsuite#662]
## Timeline supports formatting time.
![image](https://user-images.githubusercontent.com/1203827/66361139-3e490700-e9b0-11e9-82e5-07c4c27148c2.png)

## Add an alignment to Timeline.
![image](https://user-images.githubusercontent.com/1203827/66361150-44d77e80-e9b0-11e9-9b0e-c2471913d756.png)

**Comment by hiyangguo** [comment]
Resolved #624
