### ISSUE TITLE
Seems like Table Pagination `displayLength` didn't work

### ISSUE THREAD

**Issue by lucky0604** [rsuite/rsuite#669]
### Bug, feature request, or proposal:
Bug

### What is the expected behavior?
```javascript
<Table height={420} data={data} loading={loading}>
          <Column width={50} align="center" fixed>
            <HeaderCell>Id</HeaderCell>
            <Cell dataKey="id" />
          </Column>

          <Column width={100} fixed>
            <HeaderCell>First Name</HeaderCell>
            <Cell dataKey="firstName" />
          </Column>

          <Column width={100}>
            <HeaderCell>Last Name</HeaderCell>
            <Cell dataKey="lastName" />
          </Column>
        </Table>

        <TablePagination
          lengthMenu={[
            {
              value: 10,
              label: 10
            },
            {
              value: 20,
              label: 20
            }
          ]}
          activePage={page}
          displayLength={displayLength}
          total={fakeData.length}
        />
```
should be `10 lines` each page

### What is the current behavior?
all lines in one page, but `activePage` and page numbers are right.
![image](https://user-images.githubusercontent.com/8739018/66450408-f945d300-ea8a-11e9-9545-65188498ab97.png)
 

### What are the steps to reproduce?
https://codesandbox.io/s/rsuite-template-lrlch
> the request api was in the local dev env, I don't know how to reproduce so just post the code, sorry.

**Comment by simonguo** [comment]
`displayLength` only works on `Pagination`.
`If ​​you want to display a few lines of data in Table`, you need to filter the value of `data`.

**Comment by lucky0604** [comment]
yep, you are right.
Ma mistake, I don't understand the meaning of  `getData` so I missed it.
Thanks very much.
