### ISSUE TITLE
SelectPicker 搜索无结果

### ISSUE THREAD

**Issue by hiyangguo** [rsuite/rsuite#670]
### Bug, feature request, or proposal:
Bug

### What is the expected behavior?
当 `data` 的 `label` 使用 `react-intl` 的 `<FormattedMessage>` 组件时，使用内置的搜索框进行 item 的过滤，可以获得正确的结果。

### What is the current behavior?
无法获得正确的结果。

![QQ20191009-143809-HD](https://user-images.githubusercontent.com/15609339/66457254-8c3e3780-eaa2-11e9-9ce9-0f8864e3a70f.gif)

### What are the steps to reproduce?
https://codesandbox.io/s/rsuite-template-m07qu
点击 Toggle 在输入框中 输入 **管理员**。

**Comment by simonguo** [comment]
搜索时候，React.ReactNode 转 string , 是通过递归遍历 children ，然后 string 检索。
而在遍历 `<FormattedMessage>` 的 children 的时候，找不到对应需要检索的预期值 。

你有什么建议？

**Comment by hiyangguo** [comment]
@simonguo 查了一下 `<FormattedMessage>` 确实没办法获取到 text。实际使用的时候暂时是直接去语言包把文字读出来放进去做 `label` 的。

**Comment by hiyangguo** [comment]
可以使用 `injectIntl` 获取 text 这样就可以搜索了。

https://github.com/formatjs/react-intl/issues/1051#issuecomment-338314671
