### ISSUE TITLE
import only needed lodash modules

### ISSUE THREAD

**Issue by iwan-uschka** [rsuite/rsuite#672]
### Bug, feature request, or proposal:
Proposal

### What is the expected behavior?
Instead of importing lodash completely it would be the better approach to import only needed lodash modules and using lodash-es instead of lodash. Like:

```
import _get from 'lodash-es/get';

...
if (_get(item, 'type.displayName') === 'Sidebar') {
...
```

This way the final bundle size could be decreased dramatically.

### What is the current behavior?
Lodash is imported completely like:

```
import _ from 'lodash';

...
if (_.get(item, 'type.displayName') === 'Sidebar') {
...
```

Right now lodash takes 115KB which is quite a lot :)

<img width="579" alt="lodash" src="https://user-images.githubusercontent.com/2256579/66481663-aa576800-eaa1-11e9-9402-cddcfe15b372.png">

**Comment by simonguo** [comment]
Thank you very much for your reminder, this is an oversight on our latest version.

I will use the babel plugin `babel-plugin-lodash` to solve this problem.
The compiled code will look like this:

![image](https://user-images.githubusercontent.com/1203827/66533282-fad3d180-eb44-11e9-9fec-96ad9aa1d8e1.png)

**Comment by iwan-uschka** [comment]
Awesome! Thanks for working on this great library.
