### ISSUE TITLE
How can I restrict uploads 

### ISSUE THREAD

**Issue by sh4msi** [rsuite/rsuite#673]
hi

How can I restrict uploads (upload user's avatar)
The user only uploads one photo and when the second photo is uploaded, the first photo is deleted

**Comment by simonguo** [comment]
You can disable the upload button by the number of files in `fileList`.
```jsx
function App() {
  const [fileList, setFileList] = React.useState([]);
  return (
    <div className="app">
      <Uploader
        listType="picture"
        action="//jsonplaceholder.typicode.com/posts/"
        disabled={fileList.length > 0}
        onChange={setFileList}
      >
        <button>
          <Icon icon="camera-retro" size="lg" />
        </button>
      </Uploader>
    </div>
  );
}
```
Then add a hidden style to the disabled button.
```css
.app .rs-uploader-trigger-disabled {
  display: none;
}
```

Complete example:
https://codesandbox.io/s/rsuite-template-qe0sl
