### ISSUE TITLE
InputPicker 样式有异常

### ISSUE THREAD

**Issue by Link-Kou** [rsuite/rsuite#679]
创建自定义表格列

代码
![image](https://user-images.githubusercontent.com/22113151/66621693-a9484700-ec17-11e9-94b5-b95d228cb04f.png)

展示结果
![image](https://user-images.githubusercontent.com/22113151/66621755-d563c800-ec17-11e9-97c1-753ca8cc6706.png)

个人 解决方式

我调整了一下 加了如下样式就正常了

![image](https://user-images.githubusercontent.com/22113151/66621851-25db2580-ec18-11e9-97bd-a233c8d44f2e.png)

**Comment by hiyangguo** [comment]
@Link-Kou 我按照你提供的代码写了个例子 https://codesandbox.io/s/rsuite-template-ly4cm 没有发现这个问题。麻烦 fork 例子复现一下。

**Comment by hiyangguo** [comment]
@Link-Kou 我按照你提供的代码写了个例子 https://codesandbox.io/s/rsuite-template-ly4cm 没有发现这个问题。麻烦 fork 例子复现一下。 
 
![image](https://user-images.githubusercontent.com/15609339/66629047-29c87100-ec33-11e9-86fa-607514269308.png)

**Comment by Link-Kou** [comment]
@hiyangguo   看完你的案例，我以为可能是我私人的Css的问题引起的，我重新弄了一个新的项目，但是奇怪的是我依旧有问题，我把版本调整到我本地使用的版本一致，你的案例中就是没有异常，而我的就有

版本
 "rsuite": "4.0.1"

目前 我自己加了这句话，先这样子解决先。

.rs-picker-input:not(.rs-picker-disabled) .rs-picker-toggle {
  left: 0;
}

**Comment by simonguo** [comment]
找到引起 CSS 冲突的代码
