### ISSUE TITLE
Popover控件与Data Entry分组内的控件z-index，遮挡问题

### ISSUE THREAD

**Issue by Link-Kou** [rsuite/rsuite#684]
Popover控件与Data Entry分组内的框架一起玩的时候Popover的z-index很高对 Data Entry分组内 有下拉弹出框的框架会有遮挡问题

![image](https://user-images.githubusercontent.com/22113151/66746781-58ee1500-eeb5-11e9-8d92-0db64e9e1726.png)

还有就是焦点失去的控制问题。

**Comment by simonguo** [comment]
这里不能直接通过 z-index 解决，另外有一种场景：在 Picker 的选项被 hover 的时候再展示 Popover ，这个时候是 Picker 中显示 Popover，而且这种场景相对使用较多。

那针对你的这个需求，可以通过给 Picker 设置 container 进行处理，让展开的菜单渲染到 Popover 内部。
```jsx
const popoverRef = React.createRef();
const instance = (
  <Popover title="Title" visible>
    <p>This is a defalut Popover </p>
    <p>Content</p>
    <div ref={popoverRef} />
    <SelectPicker data={[]} container={() => popoverRef.current} />
  </Popover>
);
ReactDOM.render(instance);
```
