### ISSUE TITLE
rsuite表格使用问题，本地开发和调试没问题，打包后表格自带样式失效，

### ISSUE THREAD

**Issue by ZhangMingZhao1** [rsuite/rsuite#688]
### Bug, feature request, or proposal:

![image](https://user-images.githubusercontent.com/29058747/66972170-5a425c00-f0c6-11e9-9ad0-647fb65bb58f.png)

代码：
`
import Table from 'rsuite/lib/Table';
import 'rsuite/lib/Table/styles'
`
直接按照这种按需引入的，本地是正常显示的
### What are the steps to reproduce?

> Please fork this example, reproduce the problem you are issue.
> https://codesandbox.io/s/5vq6zo2z5l

**Comment by simonguo** [comment]
你检查一下你的 development 环境与 production 环境配置有什么不同？
