### ISSUE TITLE
Input Picker clean state after changing data

### ISSUE THREAD

**Issue by iwan-uschka** [rsuite/rsuite#692]
### Proposal:

Shouldn't the `InputPicker` clean it's state if `data` changes?

After changing `data` the currently selected value isn't shown but internally cached. After switching back to the old `data` the previously selected item is shown again.

This way the current state is not shown properly to the user. Let me explain why:

In my scenario an `InputPicker` is used within a `Form` (via `acceptor`) and some validation rules have been defined:

```
inputPickerValue: Schema.Types.NumberType().isRequired(
  'This field is required.',
)
```

The rule `isRequired` doesn't apply in the case of `data` being changed => "This field is required" doesn't show up.

I tried updating the `value` (controlled) but it didn't help out.

Right now I fire a click event manually on the clean toggle before updating the `data`. Not elegant :)

Any ideas how to solve this or should the component be updated/fixed?

**Comment by simonguo** [comment]
You can call the `check` method of `<Form>` after the data is updated.

```jsx
class MyForm extends React.Component {
  constructor() {
    this.formRef = React.createRef();
  }
  componentDidUpdate(prevProps) {
    if (prevProps.data !== this.props.data) {
      this.formRef.current.check();
    }
  }
  render() {
    return (
      <Form ref={this.formRef} formValue={this.props.data}>
        <FormControl accepter={InputPicker} />
      </Form>
    );
  }
}
```

In addition, Form provides a set of methods to trigger form data validation and clear error messages.


```js
check: (callback?: (formError: E) => void) => boolean;
checkAsync: () => Promise<any>;
checkForField: (
    fieldName: keyof T,
    callback?: (checkResult: CheckResult<errorMsg>) => void
  ) => boolean;
checkForFieldAsync: (fieldName: keyof T) => Promise<CheckResult>;
cleanErrors(callback: () => void) => void
cleanErrorForFiled: (fieldName: keyof E, callback?: () => void) => void;

```

**Comment by iwan-uschka** [comment]
Thank you for your response. I already check the `Form` before submitting it like shown in the [docs](https://rsuitejs.com/en/components/form#Validations).

Please have a look at this [codesandbox](https://codesandbox.io/s/musing-curran-o0j2m). You can see 2 `InputPicker`. The data set of the second on depends on the selected item of the first one. So please do the following:

1. check first `InputPicker` 2 => empty data set
2. click on submit => validation errors appear which is correct
3. select an item from first `InputPicker` => first validation error disappears which is correct
4. select an item from second `InputPicker` => second validation error disappears which is correct
5. clean first `InputPicker` selection => only first validation error appears which isn't correct
6. click on submit => nothing changes
7. reselect the same item from first `InputPicker` => previously selected item from second `InputPicker` gets reselected automatically

I would like to reach this goal:
5. clean first `InputPicker` selection => both validation errors appear because the second `InputPicker` shows no selection
7. reselect the same item from first `InputPicker` => no item from second `InputPicker` gets selected automatically

It would be cool if can really clean up the state of an `InputPicker` if it's data set has been changed.

**Comment by simonguo** [comment]
First you need to clear the second value when you clear the first value.
```js
if (value.first === null) {
   value.second = null;
}
```
Then add a `useEffect` to determine if the value of the form has changed. If you change it, you need to handle the custom logic.
```js
React.useEffect(() => {
  if (rsFormValue.first === null) {
    rsFormReference.current.checkForField("second");
  }
}, [rsFormValue]);
```
Complete example:  https://codesandbox.io/s/eager-boyd-p1xd8

**Comment by iwan-uschka** [comment]
Thanks again for looking into it. Your solution doesn't fully work. Please select a value from the first picker, select from the second one, clear first => error messages are shown. Now select the same first value again and you'll see the previously selected second value is selected automatically again but the error message for the second picker is still active. I don't expect the second value to be selected automatically again.

The error message handling would need a fix as well and then it's not a simple workaround or solution anymore but a dirty hack. What do you think?

**Comment by simonguo** [comment]
The cause of this problem is that Form is not controlled, Form has no value attribute, and should be modified to formValue.
```diff
<RsForm
    ref={rsFormReference}
    model={rsFormModel}
-   value={rsFormValue}
+   formValue={rsFormValue}
```
Complete example: https://codesandbox.io/s/nifty-thunder-29hx9

**Comment by iwan-uschka** [comment]
In my project code `formValue` is used instead of `value` anyway so i will give it a try. Thanks.

**Comment by iwan-uschka** [comment]
This works. Thanks!

Can you explain why automatic value deletion (like described in my opening comment) wouldn't be a good thing to integrate? I can't think of a scenario where this wouldn't be the expected behaviour. Just curious :)

**Comment by simonguo** [comment]
1. From the perspective of one-way data flow, it is to modify `props` and then render the view, without modifying the props` of another component directly because of a component's `props` modification.
2. If there is some kind of data association between the component and the component, `Form` is not known.
3. If I need to design an association, I tend to do it by customizing `FormControl`. Encapsulate two `InputPicker`s into a `FormControl` , internal data cascading and description of error messages can be customized. This is the flexibility of the component.

**Comment by iwan-uschka** [comment]
Thanks again for taking the time.

I don't know if I can fully agree with you here because I think any component should take care of it's state integrity by itself. From my point of view it's bad to enable the `InputPicker` to have a value which isn't part of it's `data` source.
**BUT**: that's only my way of thinking about it. Probably it's good/better to be able to control the `value` next to `data` via `props` manually like you demonstrated it in https://codesandbox.io/s/nifty-thunder-29hx9 and implemented it in rsuite generally. Surely someone else is lucky about this very behaviour :)

Keep up the good work!
