### ISSUE TITLE
CheckTreePicker - Disabled Element Checked When Parent Checked

### ISSUE THREAD

**Issue by wmulhern** [rsuite/rsuite#698]
## Version

react@16.11.0
rsuite@4.0.4

### What is the expected behavior?

If a value is in the disabledItemValues array, when the parent of that element is selected (checked), the disabled element stays unchecked. 

### What is the current behavior?

For values in the disabledItemValues array, when the parent of that element is selected/deselected, the disabled element has the same behavior as the parent element. If the parent element is selected, the disabled element displays as checked and is added to the values array

### What are the steps to reproduce?

Go to your documentation on CheckTreePickers (https://rsuitejs.com/en/components/check-tree-picker), in the "Disabled" section, click the the "Disabled Option" dropdown, and select the "China" element. The "Beijing" element, which is disabled, is also selected.

### Any additional comments? (optional)

This might not be an issue at all.... this may be a deliberate design choice, but I assumed if an element is disabled if cannot be selected at all. If this is a deliberate design choice, perhaps there should be a feature where a disabled option cannot be selected at all.

**Comment by simonguo** [comment]
Make the specified option unselectable by setting the `uncheckableItemValues` property on `CheckTreePicker`.
