### ISSUE TITLE
Style lost after packaging with webpack4

### ISSUE THREAD

**Issue by Zousdie** [rsuite/rsuite#700]
## Version

React 16.11.0
rsuite 4.0.4

### What is the expected behavior?
The component's less style file is normally packaged.

### What is the current behavior?
Component styles that are loaded on demand are lost after packaging.

### What are the steps to reproduce?
1. Import and use `MultiCascader`
```
import { MultiCascader } from 'rsuite';
```
2. Package this project with webpack4

### Any additional comments? (optional)
The side effects of the project are misconfigured, causing the webpack tree-shaking to remove the less-loaded on-demand files.

Current sideEffects configuration：
```json
"sideEffects": [
    "lib/**/style/*"
  ]
```

Correct sideEffects configuration：
```
"sideEffects": [
    "lib/**/style/*",
    "*.less",
    "*.css",
  ]
```

**Comment by blueyestar** [comment]
Same issue here. I found a workround.
Using ```require``` instead of ```import``` to explicitly load the style sheet can pass around this issue.

**Comment by simonguo** [comment]
@Zousdie How did you import the style file?
