### ISSUE TITLE
望：InputPicker 控件 defaultValue值支持并非data中的也能显示

### ISSUE THREAD

**Issue by Link-Kou** [rsuite/rsuite#702]
InputPicker 控件 如果 defaultValue值并非data中的，控件是不会展示值。 

场景中:

商品分类或者标签之类的，比如过去存在A库标签，而现在没有了。按照现有控件的情况InputPicker直接就显示了空，而目前针对此情况只能采用placeholder来解决。希望改进一下。添加一个选项支持。defaultValue可以显示。而非必须data中存在

补充场景说明：

商品标签是固定值：A库、B库等。由运营预先创建。商品创建的时候必须从InputPicker中选择一个。而运营是可以将B库标签删除的。导致的结果就是，商品重新被编辑的时候InputPicker控件就显示为空，而非B库值。

@simonguo

**Comment by simonguo** [comment]
解决方法：判断 data 是否存在值，再更新 data。
