### ISSUE TITLE
Style lost in production build

### ISSUE THREAD

**Issue by Shayan20** [rsuite/rsuite#704]
Version
React 16.11.0
rsuite 4.0.4

What is the expected behavior?
The component's less style file is normally packaged.

What is the current behavior?
Component styles that are loaded on demand are lost after packaging.

What are the steps to reproduce?
Import any component from rsuit and than run cmd "npm run build" and than run cmd "npm start".
When you reload the page in localhost:3000 the styles are lost in nextjs

**Comment by simonguo** [comment]
How did you import the style file?

**Comment by simonguo** [comment]
Duplicate open issue https://github.com/rsuite/rsuite/issues/700

**Comment by Shayan20** [comment]
> How did you import the style file?

I am import hte components like this: 
import { Nav, Dropdown, Navbar } from "rsuite";
import "rsuite/lib/styles/index.less";

next.config.js
const withCSS = require("@zeit/next-css");
const withLess = require("@zeit/next-less");
const path = require("path");
const withImages = require("next-images");

module.exports = withImages(
  withCSS(
    withLess({
      webpack: {
        resolve: {
          alias: {
            rsuite: path.resolve(__dirname, "../rsuite")
          }
        }
      },
      lessLoaderOptions: {
        javascriptEnabled: true
      }
    })
  )
);

**Comment by cddumanov** [comment]
For all of you who have experienced this problem, please upgrade your rsuite version to the latest!
