### ISSUE TITLE
Nav.Item with NextJS Link as componentClass throws error

### ISSUE THREAD

**Issue by Kombustor** [rsuite/rsuite#711]
## Version
"react": "^16.11.0"
"rsuite": "^4.0.5"
"next": "^9.1.2

### What is the expected behavior?
The navigation item turns into a client-routed link according to the [basic NextJS example](https://nextjs.org/docs#basic-example).

### What is the current behavior?
Error thrown:

`Error: React.Children.only expected to receive a single React element child.`

### What are the steps to reproduce?
```
...
import Link from 'next/link'
import { Nav } from 'rsuite';
...
<Nav>
    <Nav.Item componentClass={Link} href="/">Home</Nav.Item>
    <Nav.Item componentClass={Link} href="/page2">Page2</Nav.Item>
</Nav>
```
My guess is that because the Nav.Item component has multiple child components (https://github.com/rsuite/rsuite/blob/master/src/Nav/NavItem.tsx#L92) NextJS Link can't add the href attribute to a specific one. But that's also not the intention. The href attribute should be added to the component itself.

But when wrapping the component into a Link like this:
```
<Link href="/">
    <Nav.Item>Home</Nav.Item>
</Link>
```
nothing happens at all because the top-level element is not the `a`nchor, but a `<li role="presentation" class="rs-nav-item">`, so NextJS can't add the href attribute here aswell.

### Any additional comments? (optional)

How to avoid this bug? How to handle NextJS links in rsuite navigations? By just adding a href attribute to Nav.Item we are skipping client-side routing and the page just loads to the new one.

**Comment by simonguo** [comment]
Thank you very much for discovering this problem. Since the child element of Next.js' Link must be an `a` element, there is a conflict when the rsuite navigation related components are combined.
To solve this problem, we added a `renderItem` property to the Item.

```js

import Link from 'next/link'
import { Nav } from 'rsuite';

<Nav>
  <Nav.Item
    renderItem={item => {
      return <Link href="/">{item}</Link>;
    }}
  >
    Home
  </Nav.Item>
  <Nav.Item
    renderItem={item => {
      return <Link href="/page2">{item}</Link>;
    }}
    href="/page2"
  >
    Page2
  </Nav.Item>
</Nav>
```
https://github.com/rsuite/rsuite/pull/713

**Comment by simonguo** [comment]
Recommended usage

```tsx
import Link from "next/link";

const MyLink = React.forwardRef((props, ref) => {
  const { as, href, ...rest } = props;
  return (
    <Link href={href} as={as}>
      <a ref={ref} {...rest} />
    </Link>
  );
});

function App() {
  return (
    <Nav>
      <Nav.Item componentClass={MyLink}>link</Nav.Item>
    </Nav>
  );
}
```

**Comment by adventurini** [comment]
How do you pass MyLink the href props?

**Comment by simonguo** [comment]
@adventurini 
```jsx
<Nav.Item componentClass={MyLink} href="/link" >link</Nav.Item>
```

**Comment by konsumer** [comment]
I get this error:

```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

with this:

```js
import React from 'react'
import {
  Dropdown,
  Nav,
  Button,
  Breadcrumb
} from 'rsuite'
import Link from 'next/link'

const NavLink = React.forwardRef((props, ref) => {
  const { as, href, ...rest } = props
  return (
    <Link href={href} as={as}>
      <a ref={ref} {...rest} />
    </Link>
  )
})

export const LinkNav = props => <Nav.Item componentClass={NavLink} {...props} />
export const LinkDrop = props => <Dropdown.Item componentClass={NavLink} {...props} />
export const LinkButton = props => <Button componentClass={NavLink} {...props} />
export const LinkBread = props => <Breadcrumb.Item componentClass={NavLink} {...props} />
```

example usage:

```jsx
<LinkNav href='/'>Home</LinkNav>
```

```
"rsuite": "^5.0.0"
"react": "17.0.2"
"next": "11.1.2"
```

Am I doing it wrong?

**Comment by konsumer** [comment]
It seems to work ok [here](https://codesandbox.io/s/white-fire-1iqhw?file=/src/App.js), so maybe it is something else.

**Comment by konsumer** [comment]
I even tried with

```jsx
export const LinkNav = props => <Nav.Item {...props} />
```

and it throws the same error in my app, so I'm really not sure. Does this stuff not work with nextjs, currently?

**Comment by konsumer** [comment]
I made a basic tester app [here](https://github.com/konsumer/rsuite-next-example) and it's also working fine, so I think it must be something else. I will keep playing with it.

**Comment by simonguo** [comment]
@konsumer  Use `as` instead of `componentClass`, in rsuite v5. 

```tsx
<Nav.Item as={NavLink} {...props} />
```

[New Features v5 and Migration from v4 ](https://rsuitejs.com/guide/v5-features/)

**Comment by konsumer** [comment]
I discovered this! I updated the demo and it's still working great. I will copy an approximation of that into my app. Thanks!

**Comment by konsumer** [comment]
For others finding this from Google:

```jsx
import React from 'react'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { Button, Nav, Dropdown, Breadcrumb } from 'rsuite'
import 'rsuite/styles/index.less'

export const NavLink = React.forwardRef((props, ref) => {
  const { as, href, ...rest } = props
  return (
    <Link href={href} as={as}>
      <a ref={ref} {...rest} />
    </Link>
  )
})

// track active
export function wrap (Component) {
  return props => {
    const router = useRouter()
    return <Component active={props.href === router.pathname} as={NavLink} {...props} />
  }
}

export const LinkNav = wrap(Nav.Item)
export const LinkDrop = wrap(Dropdown.Item)
export const LinkButton = wrap(Button)
export const LinkBread = wrap(Breadcrumb.Item)
```

Makes some nice active-tracking next links, and you can use it without active, like this:

```jsx
<Navbar.Brand href='/' as={NavLink}>RSUITE Site</Navbar.Brand>
```
