### ISSUE TITLE
Dropdown controlled state

### ISSUE THREAD

**Issue by bennihoss** [rsuite/rsuite#714]
### What problem does this feature solve?
Currently the Dropdown is controlled by the user interaction ("click", "hover",...), but it's not possible to set the open-state by an variable as known in other cases.
Currently my problem is, that a click on a dropdown-item triggers a modal dialog and the popup of the dropdown remains open until the user clicks on something. 
This seems a little bit odd, and there is no simple and clean solution to fix it, i could reimplement the dropdown or simulate the click or something, but i think a controlled open-state would be a general improvement.

![image](https://user-images.githubusercontent.com/26083510/68295620-0e664f80-0093-11ea-8a99-5c91e754b4ab.png)

### What does the proposed API look like?

An open-property for Dropdown, which can be controlled by the outer component and events, same as in Modal etc.

```html

                <Dropdown
                    open={this.state.open}
                    title="Click here"
                >
                       ....items
                </Dropdown>
```

**Comment by simonguo** [comment]
Dropdown supports controlled open
```js
const App = () => {
  const [open, setOpen] = React.useState(false);
  return (
    <Dropdown title="Default" open={open} onClose={setOpen} onOpen={setOpen}>
      <Dropdown.Item>A</Dropdown.Item>
      <Dropdown.Item>B</Dropdown.Item>
    </Dropdown>
  );
};
```

**Comment by bennihoss** [comment]
oh then i'm sorry, in the documentation the open-property is missing, because of that i didn't tried it:
https://rsuitejs.com/en/components/dropdown#%3CDropdown%3E

tank you very much ;)
