### ISSUE TITLE
RTL Support | Tooltip Placement Problem

### ISSUE THREAD

**Issue by Anas-Abdelhadi** [rsuite/rsuite#728]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `16.11` |
| `rsuite` | `4.1.1` |

### What is the expected behavior?
The placement of the tooltip in **RTL** pages should be a reflection of the **LTR** pages.

### What is the current behavior?
The placement of the **tooltip does NOT** change when switching between **RTL** and **LTR**

### What are the steps to reproduce?
create a **tooltip** with default placement or set it to **Left**. switch to **RTL**. the **tooltip** still appears on the **left**.

**Comment by hiyangguo** [comment]
@Anas-Abdelhadi This isn't a bug. We defined the `left` ,`top` ,`right` ,`bottom` is  indicating the location of the display . And `start` , `end` is logical way. So `left` is mean left however direction is RTL or LTR.

You can use it like this:
```
<Whisper
    trigger="click"
    placement={document.querySelector('html').dir === 'rtl' ? 'right' : 'left'}
    speaker={
      <Tooltip>
        This is a ToolTip for simple text hints. It can replace the title
        property
      </Tooltip>
    }
  >
    <Button appearance="subtle">{placement}</Button>
  </Whisper>
```

**Comment by hiyangguo** [comment]
@simonguo I think this design is a little troublingly when use . Maybe we can change it ?

**Comment by hiyangguo** [comment]
Refrence #727

**Comment by Anas-Abdelhadi** [comment]
@hiyangguo It's true that a developer can modify it however he likes. but talking about a **framework**, the process of applying a RTL direction to the application should be achieved **automatically** without having to worry/ or retouching the components all over the application. 
The component should be smart enough and automatically reflect its UI/behaviour without any extra work or necessary intervention from the developer.

Please refer to the discussion **[here #727 ](https://github.com/rsuite/rsuite/issues/727)** on the same topic.

**Comment by hiyangguo** [comment]
@Anas-Abdelhadi Maybe you are right , we will think about this . Thank you very much.
