### ISSUE TITLE
RTL Support | Table Problem

### ISSUE THREAD

**Issue by Anas-Abdelhadi** [rsuite/rsuite#729]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `16.11` |
| `rsuite` | `4.1.1` |

### What is the expected behavior?
The **Table** should be flipped appropriately in **RTL** cases. 

### What is the current behavior?
The **Table** layout in both **RTL** and **LTR** is exactly the same. **RTL** is not applied

### What are the steps to reproduce?
create a **table** and switch to **RTL**.

**Comment by simonguo** [comment]
Resolved: https://github.com/rsuite/rsuite-table/pull/108
