### ISSUE TITLE
TS 描述错误

### ISSUE THREAD

**Issue by Link-Kou** [rsuite/rsuite#740]
"rsuite": "4.1.1"

1.
< Input />  onChange  描述返回 
string | string[]

2.
 < FormControl name="categoryId"  accepter={DateRangePicker} />  
 defaultCalendarValue ts 提示必须参数

**Comment by simonguo** [comment]
什么组件？

**Comment by Link-Kou** [comment]
@simonguo  忘记加空格了

**Comment by simonguo** [comment]
@Link-Kou   你去学习一下 markdown 吧。代码可以通过 ` 符合格式化，参考如下：

![image](https://user-images.githubusercontent.com/1203827/69294807-28cd2b00-0c46-11ea-9978-3f6f886e8bda.png)


```jsx
<Input /> 
<FormControl name="categoryId" accepter={DateRangePicker} />
```
