### ISSUE TITLE
DateRangePicker 有禁用日期时在 Safari 浏览器打开面板时卡顿

### ISSUE THREAD

**Issue by hiyangguo** [rsuite/rsuite#765]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `16.8.6` |
| `rsuite` | `4.1.1` |

### What is the current behavior?
在 Safari 浏览器中打开 https://rsuitejs.com/components/date-range-picker#禁用
点击

![image](https://user-images.githubusercontent.com/15609339/70017932-8014b900-15bf-11ea-9254-64cf7aaf94f8.png)

页面会卡顿

**Comment by hiyangguo** [comment]
```
<DateRangePicker disabledDate={combine(allowedMaxDays(100), afterToday())} />
```
在件选择打开年份切换面板时，打开速度很慢

**Comment by simonguo** [comment]
#768 的解决方案，就是把渲染最慢的逻辑从打开日历面板后置处理，迁移到切换月份的时候去做复杂的校验。 所以会导致，打开 Picker 的速度会变快了，但是在切换月份的时候还是会很慢。

暂时没有其他好的解决方案。
