### ISSUE TITLE
单独引入tabe组件使用，打包发布后，tabel显示混乱（开启 了virtualized），本地开没有问题

### ISSUE THREAD

**Issue by Xutaotaotao** [rsuite/rsuite#772]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `16.7.0` |
| `rsuite` | `4.1.2` |

### What is the expected behavior?

单独引入tabe组件使用，打包发布后应该正常显示。
### What is the current behavior?
单独引入tabe组件使用，打包发布后，tabel显示混乱（开启 了virtualized），本地开发没有问题。
引入table代替antd本身的table解决大数据table问题。

```
import React from 'react';
import Table from 'rsuite/lib/Table';
import Checkbox from 'rsuite/lib/Checkbox';
import { Pagination,Empty,Spin,Icon,Tree,Button, message } from 'antd';
import config from 'config';
import httpFetch from 'share/httpFetch';
import 'rsuite/lib/Table/styles';
import 'rsuite/lib/Checkbox/styles';
```

**Comment by simonguo** [comment]
@Xutaotaotao  检查一下你的 development 与 production 环境之间有什么差别？

**Comment by Xutaotaotao** [comment]
解决了，但是并不是按照文档的按需加载的方式引入组件，尝试了引入index.less文件。怀疑是打包的时候没有将样式文件打进去引起的。
```
import React from 'react';
import {Table,Checkbox} from 'rsuite';
import { Pagination,Empty,Spin,Icon,Tree,Button, message } from 'antd';
import config from 'config';
import httpFetch from 'share/httpFetch';
import 'rsuite/lib/styles/index.less';
```

**Comment by Xutaotaotao** [comment]
感觉开启了virtualized，列表滑动还是不够流畅，不够解决了antd大数据列表的问题，不会使整个系统卡顿。列表页字段500条一页，每行大概50个字段的数据量。后面准备再尝试一下react-virtualized

**Comment by simonguo** [comment]
@Xutaotaotao  你打包是用的 webpack 吗？ 什么版本？

关于 50 列会导致滚动卡的问题，应该和这个是同一个问题： https://github.com/rsuite/rsuite-table/issues/113#issuecomment-562450137

**Comment by simonguo** [comment]
@Xutaotaotao 
关于样式按需加载调整为以下试一下：
```diff
- import 'rsuite/lib/Table/styles';
- import 'rsuite/lib/Checkbox/styles';
+ import 'rsuite/lib/Table/styles/index.less';
+ import 'rsuite/lib/Checkbox/styles/index.less';
```

**Comment by Xutaotaotao** [comment]
打包是用的umi自带的build，umi版本为2.4.4

样式按需加载调整后可以正常打包使用。
```
import 'rsuite/lib/Table/styles/index.less';
import 'rsuite/lib/Checkbox/styles/index.less';
```

但是关于 50 列会导致滚动卡的问题，加了`rowKey="id"`依然没有改善，高度是固定的。因为所有的columns都是动态渲染并且可配置的，暂时还不知道怎么优化。不知道作者是否还有有其他方式优化。

![image.png](https://upload-images.jianshu.io/upload_images/8108267-db78427715934e97.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
