### ISSUE TITLE
Drawer Gap Bug

### ISSUE THREAD

**Issue by Anas-Abdelhadi** [rsuite/rsuite#777]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `16.7.0` |
| `rsuite` | `4.1.2` |

### What is the expected behavior?

When switching between different drawers (one on the right, the other on the left) No gaps should appear.

### What is the current behavior?
 When closing a right drawer, then immediately opening a left one, there will be a visible gap

![image_2019_12_09T09_05_10_630Z](https://user-images.githubusercontent.com/44828864/70422304-2eaf7280-1a74-11ea-81b0-fdf306a92250.png)

### What are the steps to reproduce?
Use the drawer example in the docs with multiple drawers.

**Comment by hiyangguo** [comment]
@Anas-Abdelhadi Hi, I can't repeat this bug . Can you provide detail info for this? Thank you very much.

**Comment by MohammadYounes** [comment]
@hiyangguo 
![drawer](https://user-images.githubusercontent.com/4712046/71327222-889d4700-250e-11ea-8f2d-2112a455b4ac.gif)

**Comment by hiyangguo** [comment]
@MohammadYounes 
![QQ20191225-103612-HD](https://user-images.githubusercontent.com/15609339/71429617-813e8f00-2702-11ea-9338-07786010248c.gif)

I can't repeat this bug already.Can you provide your browser info?

**Comment by MohammadYounes** [comment]
@hiyangguo Chrome Version 79.0.3945.88 (Official Build) (64-bit) / Windows 10

**Comment by hiyangguo** [comment]
@MohammadYounes Thank you very much.

@simonguo I repeat this issue in   Windows Chrome. 
![image](https://user-images.githubusercontent.com/15609339/71443878-7870ac00-2748-11ea-8af8-246338823c2f.png)
Maybe you can fix it.
