### ISSUE TITLE
Table 控件单元格添加上下合并需要

### ISSUE THREAD

**Issue by Link-Kou** [rsuite/rsuite#798]
我经常制作的都是ToB的一些系统。

我看官方的单元格合并是左右合并的。这种情况经常发生在多表头下。

日常情况下不同列数据之间。几乎不会有需要合并的情况（我做的都是ToB的,目前接手项目没有一个项目要求左右合并单元格）

**而同列上下数据合并的情况。反而是最需要的。**

**Comment by simonguo** [comment]
你描述的这个需求是合并行，目前支持的功能是合并列。

针对这个需求，遇到一些困难，希望能听到你具体的想法

- API 怎么设计？
- 怎么兼容 Expanded 和 Tree ？
- 怎么兼容 virtualized ？
- 怎么兼容 wordWrap ？
- 怎么兼容 setRowHeight ？
- 怎么兼容自定义列内容 ？
- 分页怎么处理 ？

如果你有合理的方案，欢迎提 PR , 或者进一步讨论。

**Comment by Link-Kou** [comment]
回答@simonguo  的问题，我必须加上一些场景，也就是说，要兼容支持的场景有什么，我是搞ToB企业的软件居多。我总结一下我们实际业务特点

- 1.表格展示数据单页不会超过100条
- 2.数据极少翻看超过10页以上
- 3.搜索查询数据占据主导地位
- 4.数据基本上都是最新数据居多
- 5.统计几乎不以表格展示，都是图表展示。涉及到特殊化统计，都是导出进行Excel处理占主流地位

---
表格应用场景实在是太多了。我建议添加单元格合并，只能基于我的场景去说明
---

给出我个人建议

- API 怎么设计？
   为表格做出不同模式,isTree 已经一个案例，剩下的就是如何确定要合并的问题了。我建议可以添加一个函数字段用来让用户自己判断是否要合并。

- 怎么兼容 Expanded 和 Tree ？
    单元格的合要求兼容Expanded和Tree模式，目前来说是不需要，本身的条件就不允许

- 怎么兼容 virtualized ？
   virtualized确实是一个麻烦点，无法回答，我只能针对我的场景加以说明：这个问题核心还是什么场景下需要大规模数据展示。而Web表格可以提供给你比起导出或者SQL更加方便功能？因为我碰到的场景都是导出Excel处理的。因为他们玩Excel函数实在是溜的一批。而且方便高效同时能够保存。而且有部分人会SQL哦！我们会弄一个只读库让他们尽情玩弄。

- 怎么兼容 wordWrap ？
   这个回答不了，因为跟具体的实现有关系了，官方的表格是以div的方式弄的，如果要搞合并，就需要对两个处于不同的div进行处理。

- 怎么兼容 setRowHeight ？
    这个回答不了，因为跟具体的实现有关系了。理由同上

- 怎么兼容自定义列内容 ？
   理论上来说列合并也是存在此问题的。

- 分页怎么处理 ？
  合并行只是针对当前页。不会存在跨页合并的问题。
