### ISSUE TITLE
建议文档组件，可收起，太占空间，不利于查看组件详细文档

### ISSUE THREAD

**Issue by liuxiaojiu** [rsuite/rsuite#8]
![image](https://user-images.githubusercontent.com/15249267/39224846-cfc3e3e4-487b-11e8-807a-b38ff5a46124.png)

**Comment by simonguo** [comment]
@liuxiaojiu  感谢反馈，我们会最近的文档更新中解决这个问题！

**Comment by simonguo** [comment]
@liuxiaojiu  你反馈的菜单收缩功能已支持
