### ISSUE TITLE
建议添加一个 Toast 控件

### ISSUE THREAD

**Issue by blueyestar** [rsuite/rsuite#801]
场景：
用以在mobile 下的 信息展示。

问题：
现有的 alert 控件在mobile 下并不友好

**Comment by XYUU** [comment]
我认为优化alert的再mobile下的体验更合适，而不是再开一个组件。

**Comment by simonguo** [comment]
@blueyestar 我并不推荐你在移动端的产品中使用 rsuite，rsuite 目前主要支持桌面端中后台产品最佳，在移动端我们并没有进行过完整性的设计和测试。移动端目前我更推荐你使用 https://github.com/mui-org/material-ui。

rsuite 后续如果有移动端适配的计划，再通知你。

**Comment by blueyestar** [comment]
@simonguo  好的， 谢谢你的建议
