### ISSUE TITLE
List 与 Modal 组合 设置拖动有层级问题

### ISSUE THREAD

**Issue by Link-Kou** [rsuite/rsuite#809]
![image](https://user-images.githubusercontent.com/22113151/71663858-c6616180-2d91-11ea-81f3-493061f8c568.png)

**Comment by hiyangguo** [comment]
https://codesandbox.io/s/magical-gagarin-yrgno

@Link-Kou 你可以在样式中添加下面的代码，用以临时解决这个问题。
```
.rs-modal-open .rs-list-item-helper {
  z-index: 1149;
}
```
