### ISSUE TITLE
React Suite fails `script-src` content security policy (CSP) due to `unsafe-eval` violation

### ISSUE THREAD

**Issue by lukepur** [rsuite/rsuite#819]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `16.8.4` |
| `rsuite` | `4.2.0` |

### What is the expected behavior?
React Suite adheres to `script-src` CSP without requiring `unsafe-eval`

### What is the current behavior?
React Suite violates `script-src` CSP due to the use of `new Function("return this;")`

### What are the steps to reproduce?
1. Build a project that includes an React Suite component (e.g. Popover)
2. Serve the project with the CSP header `Content-Security-Policy="script-src 'self' cdn.jsdelivr.net;"` (alternatively, the source `index.html` can include the meta tag `<meta http-equiv="Content-Security-Policy" content="script-src 'self' cdn.jsdelivr.net;">`)
3. Watch the world burn. Also, the project won't load due to a CSP violation (in Chrome at least)

### Any additional comments? (optional)
The culprit appears to be the `prefix` util which uses the `global = new Function("return this;")()` pattern to ensure the correct global scope is accessed, regardless of execution environment when checking for a custom CSS prefix.

It looks like this was introduced in the [migration from flow to typescript](https://github.com/rsuite/rsuite/blob/1ff9584e8627b9e85c8c96789646e45ff1852ffb/src/utils/prefix.ts). It would be interesting to know why the global scope coercion needed to be employed, as the previous version of the file didn't contain it (supposedly relying upon webpack's `definePlugin` up until this point).

Finally, thanks for creating the great set of cohesive components that is React Suite and sharing it with the world 💯

**Comment by simonguo** [comment]
Thank you for telling us this.

I recalled that it was supposed to solve the problem of server rendering.
