### ISSUE TITLE
Controlling Radio Component's Input via the "checked" prop generates a warning from React

### ISSUE THREAD

**Issue by dgaitsgo** [rsuite/rsuite#82]
One should be able to deselect a Radio component that has been selected. But this doesn't seem possible at the moment. If you click on a checked Radio, the Radio remains checked. The Component has a "checked" prop which when I toggled based on user input, gives the following warning:

> A component is changing an uncontrolled input of type radio to be controlled...

Even an example as rudimentary as this should throw a warning.
`<Radio checked={data.ui.selected} />`

**Comment by simonguo** [comment]
Does the 'data.ui.selected' you define change from undefined to boolean?

**Comment by dgaitsgo** [comment]
@simonguo Excuse the late response as I'm not receiving notifications from some reason. I only looked back to log a new issue :) The value should never be `undefined` but I will double check that assumption and make a full working example of the issue.

**Comment by dgaitsgo** [comment]
Okay, I can't faithfully reproduce this issue. Even when I explicitly set it to `undefined`, it works. Sorry for the distraction.
