### ISSUE TITLE
Release the source .sketch file?

### ISSUE THREAD

**Issue by rnarrkus** [rsuite/rsuite#820]
### What problem does this feature solve?

It's really helpful to have the [spec guides](https://rsuitejs.com/design/default) available (which I assume is exported from [sketch-measure](https://github.com/utom/sketch-measure)), but it would be even better to have the source file available for mocking up designs. Especially when trying to choose a framework to start with before any front-end implementation. Are there any plans to release this?

Thanks for the awesome library!

**Comment by zdzarsky** [comment]
It's key missing feature for me, our designer has to redraw all the components and it's pretty annoying!

**Comment by dhushyanth-s** [comment]
This is a must, considering the popularity of react suite (and also the usefulness of the project for designers)

**Comment by vltansky** [comment]
Would be really useful to have the source file.
@simonguo

**Comment by simonguo** [comment]
rsuite v5 provides design-related resources.
https://next.rsuitejs.com/resources/design/
