### ISSUE TITLE
Rsuite with some css-in-js library

### ISSUE THREAD

**Issue by afoures** [rsuite/rsuite#824]
Hi,

I want to use Rsuite with some css-in-js library (styled-components), is there a way of theming both with the same theme ?
And have you thought about going to replace less with some css-in-js library ?

Thanks

**Comment by hiyangguo** [comment]
@afoures Sorry ,we don't support use css-in-js to custom theme now. 
But you can still use dist css file in you project ,then use css-in-js to custom you component styles.
```
import 'rsuite/dist/styles/rsuite-default.css';
```
We maybe provide the solution for css-in-js , thank you very much,

**Comment by rajatpundir** [comment]
We definitely need ability to integrate styled-components with rsuite.

**Comment by simonguo** [comment]
For the time being, you can refer to the solution in the example.
https://github.com/rsuite/rsuite/tree/master/examples/with-styled-components
