### ISSUE TITLE
Some css classes interfere with other projects

### ISSUE THREAD

**Issue by iSplasher** [rsuite/rsuite#825]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `16.12.0` |
| `rsuite` | `4.2.0` |

### What is the current behavior?

Hello, thanks for this fantastic library.
Some classes have generic names like `.hidden`, which interfere with other projects such as tailwindcss. The markup for `.hidden` is
```
.hidden {
    display: none !important;
}
```
So it's not even possible to override it.

### What is the expected behavior?

It would be great if every class names were prefixed with `rs-` just like most classes.
`.hidden` -> `.@{ns}hidden`

### What are the steps to reproduce?

Try and use media queries with the `.hidden` class:

```
@media only screen and (max-width: 600px) {
  .hidden {
    display: block;
  }
}
```

It won't work.

**Comment by iSplasher** [comment]
Another benefit is when you use `postcss-purgecss`.
You can easily whitelist rsuite rules with `/^rs-/`.

**Comment by hiyangguo** [comment]
The same with #582

**Comment by SevenOutman** [comment]
Closing due to duplication.
