### ISSUE TITLE
babel-preset-rsuite not work

### ISSUE THREAD

**Issue by empty916** [rsuite/rsuite#826]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `16.10.1` |
| `rsuite` | `4.2.0` |
| `@babel/cli` | `7.5.5` |
| `webpack` | `4.39.0` |
| `babel-preset-rsuite` | `4.0.0` |

### What is the expected behavior?

期望是组件按需加载

### What is the current behavior?

使用babel-preset-rsuite时，组件并没有按需加载
```javascript
// .babelrc.js
presets: [
  ["rsuite", { "style": true }],
  [
    '@babel/preset-env',
    {
      modules: false,
    },
  ],
  '@babel/preset-react',
  '@babel/preset-typescript',
],

// index.js
import { Input, Button } from 'rsuite'; // 不起作用

```
在使用手动引入时

```javascript

// index.jsx
import Input from 'rsuite/lib/Input';
import 'rsuite/lib/Input/styles';
import Button from 'rsuite/lib/Button';
import 'rsuite/lib/Button/styles';
// 有效
```

**以上是使用webpack打包，使用webpack-bundle-analyzer插件分析得出的结果**

**Comment by hiyangguo** [comment]
@empty916 能提供一下你的 `package.json` 和 `webpack.config`么？感谢。

**Comment by empty916** [comment]
@hiyangguo 可以，麻烦给个联系方式

**Comment by hiyangguo** [comment]
@empty916 https://gitter.im/rsuite/rsuite

**Comment by empty916** [comment]
因为babel-preset-rsuite与@babel/plugin-transform-modules-commonjs插件冲突，去除@babel/plugin-transform-modules-commonjs配置即可
