### ISSUE TITLE
Responsive Problem

### ISSUE THREAD

**Issue by xXAvoraXx** [rsuite/rsuite#835]
### What problem does this feature solve?
Hello, I would like to use your rsuit UI kit but we have a some problem. The main problem is ui responsive for mobile and small devices. When I use sidebar or other components, I will expecting hide menu on mobile or other small devices. But that on devices not good seem or not hiding. The other problem is sidebar height, I tried do sidebar like yours on rsuit.com, however I could'nt becouse of sidebar does not follow across the page. I think you must should add layout template includes with sidebar,navbar and container on your documents. That would be more helpful to us.

**Comment by hiyangguo** [comment]
Thank you for you advice , we will consider this problem , and added a example for this latter.
