### ISSUE TITLE
`SelectPicker`,`DateRangePicker` 等 Picker 相关组件 `size` 属性无效，为什么？

### ISSUE THREAD

**Issue by petsgre** [rsuite/rsuite#837]
在最新的版本4.2.1

我在线上版本也测试了也发现这个问题

![image](https://user-images.githubusercontent.com/22208613/73652629-4d239a00-46c2-11ea-822f-3e51592d8b87.png)

**Comment by hiyangguo** [comment]
@petsgre Picker 的 size 属性应与 `toggleComponentClass={Button}` 结合使用
```
import { Button,SelectPicker } from "rsuite";

<SelectPicker toggleComponentClass={Button}  size="xs"/>
```
详见[文档](https://rsuitejs.com/components/select-picker#%E5%B0%BA%E5%AF%B8)

**Comment by petsgre** [comment]
toggleComponentClass 有效，谢谢
@hiyangguo
