### ISSUE TITLE
Table ExpandedRowKeys - ExpandAll Performance Issue

### ISSUE THREAD

**Issue by JoToe** [rsuite/rsuite#839]
### Versions
react 16.12.0
react-dom 16.12.0
rsuite 4.2.1
### What is the expected behavior?
Having a big tree in the Table and expand all rows, The performance should be fine during scrolling or resizing columns. When the expand all time could take some time, but the behaviour afterwards should be the same as before, or in using a flat Table with the same amount of data.

### What is the current behavior?
Using the Table as a tree and expanding all rows at once when having a big structure like over 10k objects is taking too much time. Additionally the Table ist working slower afterwards using resize columns or scrolling. When I switch to a flat Table with the same amount of data the performance is very good.

### What are the steps to reproduce?
Unfortunatelly I cannot provide a big structure in codesandbox because it is limited to provide big json files.
In this example I have only a small structure which needs to be exchanged. To see the mentioned behaviour. So please exchange the treeData.js file content with the attached data.
[treeData.zip](https://github.com/rsuite/rsuite/files/4158494/treeData.zip)

Then you can click on the "Expand All" Button and see that the UI is freezing because when you move the mouse, the cursor will still be the hand cursor. And you cannot click anywhere else.
After it has been done you can try to resize columns or scroll and will see that the performance is bad. 
The sample code is showing the same behaviour as in my local app but I do not know why the sample is not showing the expanded rows correct. But the problem behaviour is reproduceable anyhow.

https://codesandbox.io/s/rsuite-table-test-expandedrowkeys-performance-mr8dc

**Comment by ambiyu** [comment]
Here is the codesandbox example with fixed expanding/collapsing and a large data set. I removed a bit of data but still enough to demonstrate the bad performance.
[https://codesandbox.io/s/rsuite-table-test-expandedrowkeys-performance-oy5s9](https://codesandbox.io/s/rsuite-table-test-expandedrowkeys-performance-oy5s9)

The main issue is that scrolling and expanding/collapsing rows when there are a lot of expanded rows (large expandedRowKeys array) is very laggy. This occurs even when the rows are not actually rendered, so there is probably some inefficient code going through the entire array each time.

Expand all rows and then collapsing the rows like this and you will see that the performance not good with only 8 rows:
[https://i.imgur.com/eKm41Pr.png](https://i.imgur.com/eKm41Pr.png)

The tree table I'm working on has ~3000-4000 rows total and the performance is still bad.

**Comment by simonguo** [comment]
@JoToe  @ambiyu 

The performance bottleneck is mainly here.
https://github.com/rsuite/rsuite-table/blob/master/src/Table.js#L1202-L1258

In order to get the expanded or closed state of a node, every render will traverse all the data.
I need to think about how to improve the design here. If you have any suggestions, please give us a PR.

**Comment by hero9** [comment]
@simonguo Did you have time to improve this performance bottleneck?

**Comment by simonguo** [comment]
Hi all ,  fixed in https://github.com/rsuite/rsuite-table/pull/266
