### ISSUE TITLE
Separate concepts of "valid date" and "shown dates"

### ISSUE THREAD

**Issue by thelazydogsback** [rsuite/rsuite#850]
It appears that the hideXXX fns not only determines what is shown in the UI, but also serve double-duty in what is considered a *valid* date. So if I have hideMinutes={m => m % 15 != 0} and the user edits a date that is initialized to 12:17, then OK will be disabled because it is not considered a valid date.

However, just because I don't want to user to *choose* 12:17 as a time in the UI (she should choose only "rounded" to 15 mins) that does not mean that the more specific 12:17 is *invalid* if the date happened to already be set from somewhere else.

It may be useful to separate the concepts of validity from the granularity of what shown in the UI.
For example, to be backward compatible you could still link valid dates to the hideXXX functions by default, but let the user also add a validDate:(date)=>boolean callback that let's the user choose what dates are valid -- e.g., when the "OK" button should be enabled, in which case that fn will be used for validity, and hideXXX will only be used to decide what is shown in the UI.

**Comment by simonguo** [comment]
@thelazydogsback 
https://github.com/rsuite/rsuite/pull/852 Removed rule to disable time with hideXXX fns.
If you need to disable the time you need to use the `disabledDate?: (date?: Date) => boolean;` property.
