### ISSUE TITLE
Unable to import "rsuite/lib/DateRangePicker/styles"

### ISSUE THREAD

**Issue by Sri-Linga** [rsuite/rsuite#857]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `16.11.0` |
| `rsuite` | `4.2.0` |

### What is the expected behavior?

should be able to import corresponding component CSS like @import "rsuite/lib/DateRangePicker/styles" instead of @import "rsuite/dist/styles/rsuite-default.css"

### What is the current behavior?
<img width="625" alt="Screen Shot 2020-02-18 at 9 36 18 AM" src="https://user-images.githubusercontent.com/52572973/74745614-28870080-5232-11ea-8735-332dc8241a9e.png">

Failed to find 'rsuite/lib/DateRangePicker/styles'

**Comment by simonguo** [comment]
@Sri-Linga 
Can you provide more detailed information, such as the version used, your development environment, and screenshots of errors?

**Comment by Sri-Linga** [comment]
@simonguo I've updated the description above with all details, Thank you!!

**Comment by hiyangguo** [comment]
@Sri-Linga We don't provide the component css file now , can you use less file ?

**Comment by Sri-Linga** [comment]
@hiyangguo thanks for your answer, I'm not sure what less file you're referring to. but my problem with using "rsuite/dist/styles/rsuite-default.css" is it's overriding all my project styles like links and font families, I have to write CSS again to override them,
a:active,
a:focus,
a:hover {
  text-decoration: none !important;
  color: inherit !important;
}

**Comment by hiyangguo** [comment]
@Sri-Linga Yes we will overwrite the default styles now , because we want provide a unify ui on difference os and devices. And you can see detail info on the [Supported HTML Elements - rsuite](https://rsuitejs.com/en/guide/html-elements)

**Comment by Sri-Linga** [comment]
@hiyangguo The thing is it's not just overriding only datepicker styles but also the entire project styles, could you please let me know when you have separate datepicker styles file that I can use?
Thank you!!

**Comment by hiyangguo** [comment]
@Sri-Linga I'm sorry , you can't do it now. We will add this feature a little latter.

**Comment by hiyangguo** [comment]
@Sri-Linga I'm sorry , you can't do it now. We will add this feature a little latter.

**Comment by thellimist** [comment]
have the same issue

**Comment by wellingtonnascimento** [comment]
I have the same problem, is there already a solution?

**Comment by SevenOutman** [comment]
> I have the same problem, is there already a solution?

Which version of `rsuite` are you using?

**Comment by wellingtonnascimento** [comment]
i am using a 4.10.2 version, i want to use only the DateRangePicker component, when i import css from lib, it breaks my css

**Comment by SevenOutman** [comment]
> i am using a 4.10.2 version, i want to use only the DateRangePicker component, when i import css from lib, it breaks my css

There's no compiled CSS for each component individually but Less files. Have you already setup Less compiler/loaders correctly?

**Comment by wellingtonnascimento** [comment]
Import css less into component that use date picker and overwrite all my global css

**Comment by SevenOutman** [comment]
> Import css less into component that use date picker and overwrite all my global css

RSuite has some global style resets that may overwrite yours. You can set Less variable `@reset-import: false;` to disable them.

**Comment by wellingtonnascimento** [comment]
where do i find this file to add this information @reset-import: false ?

**Comment by SevenOutman** [comment]
> where do i find this file to add this information @reset-import: false ? 

You can create another Less file where you import rsuite Less and set the variable.

**Comment by wellingtonnascimento** [comment]
@SevenOutman  I'm importing the rsuite-default.css file, in case I have to change it to .less? and create another .less file and add the variable @reset-import: false

![Captura de tela de 2021-08-21 16-17-30](https://user-images.githubusercontent.com/27688166/130332700-6249e173-e5ce-4c98-a0d0-83a4baf2918e.png)

**Comment by SevenOutman** [comment]
> I'm importing the rsuite-default.css file.

You may put your own styles after rsuite styles so that rsuite doesn't overwrite yours.

**Comment by CitizenAERG** [comment]
I'm sorry to Comment on this closed issue, but I would love to use this component into our project, but currently, the fact that it forces you to chose between setting up less in your project, or getting your whole css overwritten is a nightmare.

**Comment by SevenOutman** [comment]
> Why not just adopt regular CSS module imports ?

Hi @CitizenAERG, we chose Less in order to get the ability to customize rsuite styles at the compiling phase.
