### ISSUE TITLE
Tree Table could provide possibility to get the expanded buttons on a different column than the first one

### ISSUE THREAD

**Issue by JoToe** [rsuite/rsuite#861]
### What problem does this feature solve?
When having a tree table with a column of checkboxes on the first column. I do not want to have the expand buttons on the first row. So with defining the index of the column where to put the expand buttons I can customize it by myself.

### What does the proposed API look like?
With defining the expandable ColumnIndex via TableProps I can change the column.

```
<Table data={data} isTree={true} expandableColumnIndex={1} />
```

**Comment by simonguo** [comment]
```tsx
<Table isTree>
  <Column width={100}>
    <HeaderCell>ID</HeaderCell>
    <Cell dataKey="id" />
  </Column>
  <Column width={100}>
    <HeaderCell>Name</HeaderCell>
    <Cell dataKey="name" treeCell />
  </Column>
</Table>
```
@JoToe  Wouldn't it be better to design a `treeCell` property on` Cell`?

**Comment by JoToe** [comment]
@simonguo sounds ok for me, then you can say the cell that it should "show" the tree structure. But you can also define multiple cells with the treecell property. When this does not make any problems, I am fine with this implementation. Thanks.
