### ISSUE TITLE
Panel组件嵌套Icon问题

### ISSUE THREAD

**Issue by yingzk** [rsuite/rsuite#869]
panel (collapsible)嵌套panel，则子panel会带上父级的右上角icon
![image](https://user-images.githubusercontent.com/23278599/75319116-f8c99f80-58a6-11ea-8708-4f5069e39aac.png)

**Comment by yingzk** [comment]
复现：[](https://codesandbox.io/embed/xenodochial-pare-ghqrm?fontsize=14&hidenavigation=1&theme=dark)

**Comment by simonguo** [comment]
@hiyangguo 推荐修复方案
```diff
- .rs-panel-collapsible .rs-panel-heading:before {
+ .rs-panel-collapsible > .rs-panel-heading:before {
```

**Comment by yingzk** [comment]
多谢~

**Comment by simonguo** [comment]
@yingzk 这确实是组件内存在的 bug ，会在近期 `rsuite@4.3.1` 版本中修复， 在未修复前我先把该 issue reopen 。
