### ISSUE TITLE
deprecated React.createFactory used in withLocale

### ISSUE THREAD

**Issue by iwan-uschka** [rsuite/rsuite#871]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `16.13.0` |
| `rsuite` | `4.2.1` |

### What is the expected behavior?

No depreacation warning.

### What is the current behavior?

```
Warning: React.createFactory() is deprecated and will be removed in a future major release. Consider using JSX or use React.createElement() directly instead.
```

### Any additional comments? (optional)

See https://github.com/rsuite/rsuite/blob/master/src/IntlProvider/withLocale.tsx#L15

Not urgent at all :)

**Comment by simonguo** [comment]
@iwan-uschka 
Has been fixed. Please wait for the recent new release.
https://github.com/rsuite/rsuite/pull/862/files#diff-8a0a4c241091f4a18a1ad2b46d830ce8L32

**Comment by iwan-uschka** [comment]
Seems to work. Thx!
