### ISSUE TITLE
css 和 组件对应不上

### ISSUE THREAD

**Issue by yangkaihello** [rsuite/rsuite#877]
css 和 组件对应不上

**Comment by hiyangguo** [comment]
@yangkaihello 请提供更详细的说明。你可以在[这里](https://codesandbox.io/s/5vq6zo2z5l)复现你遇到的问题。

**Comment by yangkaihello** [comment]
https://codesandbox.io/s/practical-platform-2cc2y?from-embed

**Comment by hiyangguo** [comment]
@yangkaihello 
1. 文档有遗漏。这个 logo 我们没有提供标准的组件。你需要自己去写样式。
```
.navbar-brand {
  padding: 18px 20px;
  display: inline-block;
}
```
2. 使用本地字体，请参考[官网文档 - 如何在本地配置字体文件？](https://rsuitejs.com/guide/themes#%E5%A6%82%E4%BD%95%E5%9C%A8%E6%9C%AC%E5%9C%B0%E9%85%8D%E7%BD%AE%E5%AD%97%E4%BD%93%E6%96%87%E4%BB%B6%EF%BC%9F)

3.  嵌套问题应该使用 `componentClass` ,例如：
```
import{Link} from 'react-router-dom';

 <Nav.Item icon={<Icon icon="cog" />}  componentClass={Link}>Settings</Nav.Item>
```
详见[官网文档 - 与 Router 中的 Link 组合](https://rsuitejs.com/components/nav#%E4%B8%8E%20Router%20%E4%B8%AD%E7%9A%84%20Link%20%E7%BB%84%E5%90%88)
