### ISSUE TITLE
Steps component has a weird look

### ISSUE THREAD

**Issue by afoures** [rsuite/rsuite#884]
### Versions
| package  | version |
| -------- | ------- |
| `react`  | `16.12.0` |
| `rsuite` | `4.2.1` |

### What is the expected behavior?

No blank space.

### What is the current behavior?

There is a weird blank space before the `Step.Item` title.

### What are the steps to reproduce?

I just used `Steps` component as stated in the documentation.

https://codesandbox.io/s/long-dew-o55fz

<img width="561" alt="Screenshot 2020-03-02 at 13 43 02" src="https://user-images.githubusercontent.com/25182179/75678259-846b7380-5c8d-11ea-88cc-fe42d992eaba.png">

**Comment by ninjaoxygen** [comment]
Remove text-align: center; from the styles.css

**Comment by simonguo** [comment]
![image](https://user-images.githubusercontent.com/1203827/75857088-920d2e80-5e30-11ea-954d-031ef2986ae5.png)
