### ISSUE TITLE
希望能给出只兼容到chrome49的原因

### ISSUE THREAD

**Issue by linningmii** [rsuite/rsuite#9]
看到你们能兼容到firefox45，但是chrome却只能兼容到49，希望能说明一下原因

对于gov项目，很多时候chrome44是标配，chrome只能到49的话我想很多时候在选型的时候就不会考虑到了

**Comment by simonguo** [comment]
cc @hiyangguo

**Comment by hiyangguo** [comment]
@linningmii 首先，
非常感谢您提出的宝贵意见。
浏览器兼容性这部分，我们团队是经过激烈的斗争所决定的。我们官方文档所列出的[浏览器兼容列表][官方文档]是我们完整测试过的，对一些问题做过兼容或降级处理（如 IE 10 不支持某些 api）的最低浏览器版本列表。
另外 [chrome 44][chrome 44] 浏览器。我们刚刚下载安装跑了一下。基本是没有什么问题的。但由于我们团队的资源问题，并没有做出完整详细的测试，如果在使用中发现问题，欢迎社区同学在这方面给我们提交[issue][issue]。并热烈欢迎给我们提交 pr。


[chrome 44]:http://t.cn/RLuSJQY
[官方文档]:https://rsuitejs.com/guide/introduction#%E6%B5%8F%E8%A7%88%E5%99%A8%E6%94%AF%E6%8C%81
[issue]:https://github.com/rsuite/rsuite/issues/new
