### ISSUE TITLE
fix some specific column (at least the first) in the table for larges horizontal scroll tables

### ISSUE THREAD

**Issue by cocodrino** [rsuite/rsuite#900]
Hi good day, I've got currently a big horizontal table with a lot of columns, the first column store the user names, I wish that when I scroll horizontally in my table, the column "name" will be fixed as first column, so in every moment I can see what is the person associate to x data in some column

thank you so much...

**Comment by simonguo** [comment]
`<Column>` support `fixed` property.

```jsx
<Column fixed>
```

**Comment by cocodrino** [comment]
damn, thank you so much @simonguo , I've tried this and works perfect...I though that fixed means something different here.
