### ISSUE TITLE
Focus on input programmatically

### ISSUE THREAD

**Issue by ortigozamatias** [rsuite/rsuite#926]
| `react`  | `16.12.0` |
| `rsuite` | `4.3.2` |

### What is the expected behavior?
The input should be focused after mounting a form.

### What is the current behavior?
Error saying that `focus` is not a method.

### What are the steps to reproduce?
Only trying to focus the input when the component mounts. I've also tried to pass the `ref` to the `FormControl` without setting the `accepter` props.
I saw that the focus works well when there is no `Form` around using `inputRef` prop. However, when trying to pass this to the `FormControl` the error appears.

https://codesandbox.io/s/rough-bush-i74ue

**Comment by simonguo** [comment]
@ortigozamatias  The input element can be obtained via `inputRef`.
https://codesandbox.io/s/vigorous-knuth-r3e8p

**Comment by ortigozamatias** [comment]
It works. Thanks!
