### ISSUE TITLE
Modal close button is not showing after build

### ISSUE THREAD

**Issue by gobinda168** [rsuite/rsuite#960]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `X.Y.Z` |
| `rsuite` | `X.Y.Z` |

### What is the expected behavior?

In Modal header, close button icon is not showing after build but it was visible is localhost

**Comment by simonguo** [comment]
Check if the HTML DOM element exists? If it exists, check if the font file corresponding to iconfont is loaded?

**Comment by gobinda168** [comment]
here is the screenshot of my build application
[image: image.png]

you can see that icons are missing.

**Comment by gobinda168** [comment]
![image](https://user-images.githubusercontent.com/18115891/79411811-6ea5d980-7fc1-11ea-923d-7172a11ac19e.png)

icons get disappeared after the build.

**Comment by simonguo** [comment]
You can try to deploy the font file locally.
https://rsuitejs.com/en/guide/themes

### How to configure font files locally?

The icon font files used in rsuite are deployed in [jsDelivr CDN](http://cdn.jsdelivr.net/npm/rsuite-icon-font@3.0.0/fonts/),
If you want to deploy locally, you need to modify the path to the icon font:

```less
@icon-font-path: './fonts';
```

In addition, you will also need to configure `url-loader` in webpack to load icon font files, webpack 4 configuration example:

```js
{
  test: /\.(woff|woff2|eot|ttf|svg)($|\?)/,
  use: [
    {
      loader: 'url-loader',
      options: {
        limit: 1,
        size: 16,
        hash: 'sha512',
        digest: 'hex',
        name: '[hash].[ext]',
        publicPath: '/'
      }
    }
  ]
}
```

**Comment by SevenOutman** [comment]
Hi @gobinda168, I'm closing this issue as it seems to have been resolved. Feel free to re-open if it's actually not.
