### ISSUE TITLE
tabel组件，点击编辑变成编辑状态，tabel内的滚动条就自动滚动到顶部

### ISSUE THREAD

**Issue by zhaoyang141414** [rsuite/rsuite#964]
tabel组件，点击编辑变成编辑状态，tabel内的滚动条就自动滚动到顶部

**Comment by simonguo** [comment]
能否通过 https://codesandbox.io/ 复现一下你描述的问题

**Comment by zhaoyang141414** [comment]
> 能否通过 https://codesandbox.io/ 复现一下你描述的问题

你好  http://rsuite.github.io/rsuite-table/   这上面的案例  Editabel那一个，你把滚动条拖到底部，在点击edit，滚动条就回到顶部了。我这边也是这样的问题

**Comment by simonguo** [comment]
清楚了，问题确定后，近期我们会进行修复。

**Comment by zhaoyang141414** [comment]
> 清楚了，问题确定后，近期我们会进行修复。

好的

**Comment by simonguo** [comment]
### 问题产生的原因
为了避免 data 更新后，滚动条的位置不对，让 table 存在白屏的问题，所有在每次 data 更新后自动让滚动条位置重置为 0 。

### 修复方案
新增一个 onDataUpdated 回调函数，会在数据更新后触发，在回调函数的第2个参数提供了一个操作滚动条的方法，由 Table 使用的开发工程师自己决定是否需要重置滚动条位置。
```jsx
<Table
  onDataUpdated={(_nextData, scrollTo) => {
    scrollTo({ y: 0, x: 0 });
  }}
>
```
### 什么时候可以使用？

计划在 rsuite@4.4.0 版本发布修复（约在4月25日前）
