### ISSUE TITLE
Electron下打包后icon font显示方框

### ISSUE THREAD

**Issue by ljz2012008** [rsuite/rsuite#967]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `^16.13.1` |
| `rsuite` | `^4.3.3` |
| `Electron` | `^8.2.3` |

### What is the expected behavior?
显示正常

### What is the current behavior?
Electron下dev模式icon font显示正常，打包后不正常显示方框
<img width="148" alt="Screen Shot 2020-04-17 at 3 10 33 PM" src="https://user-images.githubusercontent.com/6338583/79542240-d7727c00-80bd-11ea-9c4f-d0ae362bad5f.png">
![11091587106688_ pic_hd](https://user-images.githubusercontent.com/6338583/79542247-da6d6c80-80bd-11ea-8410-066687fff0c0.jpg)

**Comment by hiyangguo** [comment]
这个你应该要处理一下你打包的规则。使用cdn 的话。访问地址的scheme应该是 `https` 你现在用的是 `file`。
如果你需要使用本地字体的话，需要设置
```
@icon-font-path: './fonts';
```
并处理好 webpack 相关的loader 。你可以参考我们的[指南](https://rsuitejs.com/guide/themes/#%E5%A6%82%E4%BD%95%E5%9C%A8%E6%9C%AC%E5%9C%B0%E9%85%8D%E7%BD%AE%E5%AD%97%E4%BD%93%E6%96%87%E4%BB%B6%EF%BC%9F)

**Comment by hiyangguo** [comment]
你也可以试试
```
@icon-font-path: 'https://cdn.jsdelivr.net/npm/rsuite/dist/styles/fonts';
```

**Comment by simonguo** [comment]
在 rsuite v5 中改为 svg icon ，解决了该问题。

```
npm i rsuite@next
```
