### ISSUE TITLE
tabel组件为isTree时，无法排序

### ISSUE THREAD

**Issue by zhaoyang141414** [rsuite/rsuite#968]
### What problem does this feature solve?
当tabe为isTree属性时，排序功能点击不生效。建议支持tabel为isTree时，也能支持排序功能

**Comment by simonguo** [comment]
isTree 和 排序是两个不冲突的功能，排序功能是需要你点击标题后去更新 data 通过受控的方式实现排序功能。如果你想表达的不是这个问题，你可以提供一个 [codesandbox]( https://codesandbox.io/s/5vq6zo2z5l) 示例，说明一下你的问题吗？

**Comment by simonguo** [comment]
长时间未得到反馈的问题
