### ISSUE TITLE
Sidenav 属性 expanded 为false情况下，能提供二级菜单显示隐藏回调

### ISSUE THREAD

**Issue by Link-Kou** [rsuite/rsuite#970]
场景：

![2020-04-17_23-32-40 (1)](https://user-images.githubusercontent.com/22113151/79586688-0d3a5380-8104-11ea-904a-65aa69d0e439.gif)

由于expanded模式下，菜单过多超出去后，overflow对二级以下菜单有影响。

**Comment by simonguo** [comment]
Sidenav  下的 Dropdown 有一个`onClose` 的回调方法，是你需要的吗？

**Comment by Link-Kou** [comment]
@simonguo  我试了一下，如果菜单真的多到一定程度。现在的缩小菜单的情况下，二级菜单渲染的dom要改一下，不能渲染到里面, 否者实现overflow的相关效果，实在是搞不定。

![image](https://user-images.githubusercontent.com/22113151/79742849-0bf06d00-8336-11ea-9e1c-f587c6636abf.png)

![image](https://user-images.githubusercontent.com/22113151/79742861-127ee480-8336-11ea-9753-5a9ba3e62d55.png)

**Comment by simonguo** [comment]
如果你们的业务决定了一级菜单非常很多，而且不能改设计的情况下，二级菜单我建议就不要直接用 Dropdown 了，用 Popover + DropdownMenu 实现。

https://rsuitejs.com/components/dropdown#%E4%B8%8E%20Popover%20%E7%BB%84%E5%90%88%E4%BD%BF%E7%94%A8
![image](https://user-images.githubusercontent.com/1203827/79743527-4eff1000-8337-11ea-8139-5caa9839b8c8.png)

**Comment by Link-Kou** [comment]
我在尝试一下其他的方案。修改起来难度不小
