### ISSUE TITLE
Schema 校验的问题

### ISSUE THREAD

**Issue by Link-Kou** [rsuite/rsuite#974]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `16.10.2` |
| `rsuite` | `4.3.4` |

ts描述里面，没有第三个参数

![image](https://user-images.githubusercontent.com/22113151/79726566-95477580-831d-11ea-8e02-330607d3534b.png)

InputNumber输入 「-」 号的时候的提示！没有办法接管

![image](https://user-images.githubusercontent.com/22113151/79726573-98426600-831d-11ea-9f5d-909d99ae61f3.png)

**Comment by simonguo** [comment]
- TS 声明已修复: https://github.com/rsuite/schema-typed/commit/04a65c96de031e7036ff2690282e89d29b505c9b
- 类型验证的错误 errorMessage, 可以定义类型的时候传递参数
```ts
NumberType(errorMessage: string)
```
