### ISSUE TITLE
FormControl   InputNumber  触发不了 onChange

### ISSUE THREAD

**Issue by Link-Kou** [rsuite/rsuite#975]
### Versions

| package  | version |
| -------- | ------- |
| `rsuite` | `4.3.4` |

<FormControl name="weight" accepter={InputNumber}/>

触发不了 onChange

**Comment by simonguo** [comment]
请 fork 这个例子，复现你的问题。
https://codesandbox.io/s/5vq6zo2z5l

**Comment by Link-Kou** [comment]
https://codesandbox.io/s/wonderful-smoke-1izc2

@simonguo   

例子中数组初始化给的是 undefined ,造成无法传递参数的问题

**Comment by Link-Kou** [comment]
@simonguo  
测试了下 
1、初始化传递字符串，输出的即是 文本类型的 
2、如果传递是 数值类型的 ，输出的即是 数值类型的 

这里就有点小坑后端了。这里就有一个数值转换的问题。
这个控件怎么去处理有点小意思哦！一看就是老江湖。
