### ISSUE TITLE
Calender DateRangePicker not open

### ISSUE THREAD

**Issue by Gustavoohrq** [rsuite/rsuite#996]
### Versions

| package  | version |
| -------- | ------- |
| `react`  | `16.12.0` |
| `rsuite` | `4.3.4` |

### What is the expected behavior?

OPEN THE CALENDAR

### What is the current behavior?
The date pick ranger calendar is not opening

### What are the steps to reproduce?

https://i.imgur.com/kBnBPmy.gifv

### Any additional comments? (optional)
No.

**Comment by simonguo** [comment]
@Gustavoohrq 
Please fork this example, reproduce the problem you are issue.
https://codesandbox.io/s/5vq6zo2z5l

**Comment by BATTLEROYALXS** [comment]
Hello same problem in production here, the fade effect is at opacity 0 need none or 1 any solution ?
